### ISSUE TITLE
Add support for per-query metrics in Hibernate statistics

### ISSUE THREAD

**Issue by jfougere** [micrometer-metrics/micrometer#1006]
Current implementation of **HibernateMetrics** exposed counters & also time gauges for max execution queries, however no tags are provided in order to know about which query those metrics are related.

I believe this could be very useful and could be done using current Hibernate **Statistics** class implementation.

For example the TimeGauge **hibernate.query.executions.max** could be tag with a **query** tag and the value could be provided by `Statistics.getQueryExecutionMaxTimeQueryString()`.

Also the other counter metrics could be retrieved by query using:

- `Statistics.getQueries()`
- `Statistics.getQueryStatistics(String query)`

What do u think ?

**Comment by jkschneider** [comment]
Sounds great. A PR would be welcome!

**Comment by chrisatrotter** [comment]
Could you provide an example of how to use the per-query metric support in Hibernate statistics? I've tried to find out how to have this functionality work with Spring boot through the spring-actuator to expose hibernate statistics with per-query metrics. I've had little success until i found this great change! 🙌

**Comment by shakuzen** [comment]
Note that Hibernate metrics have moved to the Hibernate project, in the [hibernate-micrometer](https://github.com/hibernate/hibernate-orm/tree/main/hibernate-micrometer) module.

You need to enable statistics for Hibernate by setting the `hibernate.generate_statistics` configuration to `true`, which can be done with Spring Boot application properties like `spring.jpa.properties.hibernate.generate_statistics=true`. See the [Spring Boot documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator.metrics.supported.hibernate). You will need to provide an instance of `HibernateQueryMetrics` as a bean or bind it yourself, since Spring Boot does not currently auto-configure it. You can do that in a `@Configuration` class, for example, like the following:

```java
@Bean
MeterBinder hibernateQueryMetrics(EntityManagerFactory entityManager) {
    return new HibernateQueryMetrics(entityManager.unwrap(SessionFactoryImplementor.class), "mySess", Tags.empty());
}
```
