### ISSUE TITLE
Gather CPU usage per thread

### ISSUE THREAD

**Issue by stepio** [micrometer-metrics/micrometer#1024]
Hello,

First of all, thank you very much for this great project!

I got a task to implement/configure monitoring for CPU usage per thread. After short digging into stackoverflow I found the similar question here:
https://stackoverflow.com/questions/755899/monitor-cpu-usage-per-thread-in-java

In my opinion something similar could be introduced here as well:
https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmThreadMetrics.java
The code could be the following (not tested):
```java
    @Override
    public void bindTo(MeterRegistry registry) {
...
        if (threadBean.isThreadCpuTimeSupported() && threadBean.isThreadCpuTimeEnabled()) {
            Arrays.stream(threadBean.getThreadInfo(threadBean.getAllThreadIds()))
                .filter(Objects::nonNull)
                .forEach(info -> {
                    Gauge.builder("jvm.threads.cpu", threadBean, (bean) -> getThreadCPUTime(bean, info))
                        .tags(Tags.concat(tags, "threadName", info.getThreadName()))
                        .description("The current CPU usage per thread")
                        .baseUnit("nanoseconds")
                        .register(registry);
                });
        }
...
    }

    static long getThreadCPUTime(ThreadMXBean threadBean, ThreadInfo info) {
        long time = threadBean.getThreadCpuTime(info.getThreadId());
        return time == -1 /* thread of the specified ID is not alive or does not exist */ ? 0 : time;
    }
```

The question is... Have you thought about such a feature already? Do you see any disadvantages of such tracking? Performance impact, for example.

As an obvious problem it's possible that some of the threads could be missed by this code - if they're created after the initialization is done (outside of the pools, for example). But I don't see a clear solution to improve this.

**Comment by mweirauch** [comment]
Yeah, thought about it already.
The thing is, with twhat you sketche out, who is calculating a "human consumable" usage (e.g. percentage)?
IIRC you need to take the process runtime into the equation to calculate how much time has passed in general to see how much of the time (percentage) your process threads contributed to the CPU usage.
This might be possible with some math-capable monitoring systems like prometheus but might not work for other backends which need pre-aggregated metrics.
So the question would be, should micrometer do the pre-calculation of a "usage" before exposition.

Or do you already have a solution for server side calculation of such a "human consumable" usage?
(Or perhaps I am totally missing something :))

**Comment by stepio** [comment]
I though about just tracking the time (raw metric) so that it can be processed within monitoring system.

In our case we export data to `Grafana` through `StatsD` so I thought about forming a pie chart from this data:
https://grafana.com/plugins/grafana-piechart-panel/installation

**Comment by mweirauch** [comment]
Unrelated of how one exports this (as a raw cpu time or pre-calculated cpu usage), I think we need another solution to the registration. The draft you showed only registers the threads which are running during the meter binding. It won't register any later threads which are spun up and down during the runtime of the process.

We could be using a `MultiGauge` to ease registration if one ships CPU usage. (And a non existant `MultiCounter` for shipping CPU time, because the values are increasing only.)
Nevertheless we'd need some periodic "notify" which tells us to look up and register/deregister the current set of threads and their CPU time/usage. (Perhaps some `TransientMeter` which registers/deregisters other `Meters` on value retrieval?)

Somebody an idea regarding periodic meter registration/deregistration and the necessity - or not - for a `MultiCounter`?
