### ISSUE TITLE
Gauge of String type

### ISSUE THREAD

**Issue by mrniko** [micrometer-metrics/micrometer#1033]
Hi!

Dropwizard metrics libs provides the ability to create Gauge of String type. This feature is quite useful if you have metrics describing follow:

status of server: offline / online.
server address: 172.02.41.23:9012
...

Is it possible to have such capability in micrometer?

**Comment by jkschneider** [comment]
We can look at it, but I'm not sure how portable this concept is to various monitoring systems.

**Comment by mweirauch** [comment]
In a dimensional metric system you could/should encode this as a tag: `server.info{status="[online,offline"], ip="172.02.41.23", port="9012"} = 1`.

Might be also used to transport build/software versions: `app.info{version="1.2.0", branch="master"} = 1`

**Comment by dnault** [comment]
@mweirauch With a backends that require hierarchical name mapping, doesn't putting the String in a tag just creates multiple keys?

**Comment by mweirauch** [comment]
@dnault yes it would. But it's the same for a dimensional system.
Take for example the follow Prometheus-style metric from an old Grafana installation:
`grafana_info{version="4.6.1"} 1`
Whenever the version changes, it's another metric series and the old one will phase out (or not depending on your retention policy). Same goes for the hierarchical naming approach.

The main challenge though - besides afformentioned "issues" - really is how these String-values should be collected/stored, because currently every `Meter` is holding a double-based value.
