### ISSUE TITLE
Change `TimedAspect` implementation to AOP Alliance instead of AspectJ

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#1048]
See comments on https://github.com/micrometer-metrics/micrometer/issues/361

> Is there a reason why AspectJ was used instead of AOP Alliance? Both are supported by Spring, but only AOP Alliance is by Guice. Spring Transactions uses AOP Alliance (TransactionInterceptor), making it easy to leverage in Guice w/o Spring IoC.

> I also think should use AOP Alliance by default. AspectJ could be a additional option.

**Comment by gavlyukovskiy** [comment]
I've created a pull request https://github.com/micrometer-metrics/micrometer/pull/500 that uses AOP Alliance, but also uses Spring to bind the interceptor and in the interceptor itself to lookup annotations from the class hierarchy instead of just concrete instance class. I'm not familiar with Guice, but it looks like custom Guice code is needed to bind `MethodInterceptor` onto annotated classes/methods. 

I think we could duplicate logic to lookup annotation from the hierarchy (to allow usage on spring data repositories and other interfaces for which implementation is created at runtime) and create two bind classes - one for Spring and another one for Guice.

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2018 We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.

**Comment by BeytullahC** [comment]
> There was no interest in the issue since 2018 We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.

One day, someone walked in, sunglasses on, and closed a valid issue—just because too much time had passed... :)

**Comment by jonatan-ivanov** [comment]
@BeytullahC I'm not sure this is the best way to encourage maintainers to re-open the issue.
