### ISSUE TITLE
Support Datadog distributions via DogStatsD

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#1056]
https://docs.datadoghq.com/developers/metrics/distributions/

**Comment by shakuzen** [comment]
The page has a note at the top:

> This feature is in beta. Contact Datadog support to enable distribution metrics for your account.

I suppose we could still implement it as an incubating feature.

**Comment by shakuzen** [comment]
#1859 is open to add support for Datadog distributions via DogStatsD. There's still no documented API to send distributions via the HTTP API. I'm not sure it is a good match anyways, since we would have to decide how to buffer/send the per event distribution data separate from the rest of the metrics for the DatadogMeterRegistry.

**Comment by bxacsq** [comment]
Is there any update about this feature? Current our services send metrics to Datadog, and the lack of the datadog distribution support in micrometer makes it inconvenient to get the latency stats of the online services.

**Comment by vsingal-p** [comment]
Is there any update on this? Distributions would lower the cost of custom metrics. It's very important for many teams

**Comment by shakuzen** [comment]
Support has been merged for this with `DistributionSummary` type meters in #2745 and `Timer` type meters in #2775. If the summary is configured with the `percentileHistogram` enabled, the metric will be published to dogstatsd as a distribution type metric. This will be available in the upcoming 1.8.0-M3 milestone release. Please try it out and let us know if there is any feedback.
