### ISSUE TITLE
Possible inconsistence between timer metrics for Executor and ExecutorService

### ISSUE THREAD

**Issue by fragonib** [micrometer-metrics/micrometer#1080]
Hi!

The latest version of Micrometer (1.1.1) supports per-execution timer metrics. However, Is micrometer registering different metrics, related to task timming, for different type of executors?

* **java.util.concurrent.Executor:** both timer metrics `executor.execution` and `executor.idle`
* **java.util.concurrent.ExecutorService:** just timer metric `executor` 

If so, what's the reason behind this?

# Involved code:

**io.micrometer.core.instrument.internal.TimedExecutor**
```java
public class TimedExecutor implements Executor {
    private final MeterRegistry registry;
    private final Executor delegate;
    private final Timer executionTimer;
    private final Timer idleTimer;

    public TimedExecutor(MeterRegistry registry, Executor delegate, String executorName, Iterable<Tag> tags) {
        this.registry = registry;
        this.delegate = delegate;
        this.executionTimer = registry.timer("executor.execution", Tags.concat(tags, "name", executorName));
        this.idleTimer = registry.timer("executor.idle", Tags.concat(tags, "name", executorName));
    }
``` 

**io.micrometer.core.instrument.internal.TimedExecutorService**
```java
public class TimedExecutorService implements ExecutorService {
    private final ExecutorService delegate;
    private final Timer timer;

    public TimedExecutorService(MeterRegistry registry, ExecutorService delegate, String executorServiceName, Iterable<Tag> tags) {
        this.delegate = delegate;
        this.timer = registry.timer("executor", Tags.concat(tags ,"name", executorServiceName));
    }
```

**Comment by fragonib** [comment]
Hi, Is this difference by design? What are the reasons behind that different behaviour?

Thank you.

**Comment by mweirauch** [comment]
If I am not totally mistaken it's missing the idle timings. (Apart from the differing metric name for the execution timer: `executor.executions` vs `executor`. Unfortunately.)
So all `Callable`s and `Runnable`s would need to be wrapped again to get the "idle" timings for the scheduled/submitted tasks. Is that what is your question about or are you just irritated about the different metric names?

**Comment by fragonib** [comment]
I'm just concerned by both:

- Same timer metric concept, but with different metric name on both executors: `Executor` and `ExecutorService`.
- Support for task timming in `ScheduledExecutorService` as showed on https://github.com/micrometer-metrics/micrometer/issues/1021 for specific methods of this executor .

Is there any plan to address both?

**Comment by maddenj-ie** [comment]
Is this addressed by #775 ?

**Comment by fragonib** [comment]
Reviewing pull request (didn't run any test yet) I think it is. 

Thank you for your contribution.

I'm interested on it. According micrometer roadmap, when could we get this one?

**Comment by perlun** [comment]
@shakuzen and others: this is addressed by #775, which has been pending for a long time.

Could we get that PR reviewed? If the change suggested there feels too agressive, I might be able to submit a PR that only changes `executor` -> `executor.execution`, so we at least fix the inconsistency. We can then try to fix the `executor.idle` metric in due time.

/cc @slovdahl

**Comment by shakuzen** [comment]
Idle timing was added with #1608. The remaining inconsistency is the naming of the task execution timer across the timed executors. Current state is:

* `TimedExecutor`: `executor.execution` and `executor.idle`
* `TimedExecutorService`: `executor` and `executor.idle`
* `TimedScheduledExecutorService` (just added in 1.3): `executor` and `executor.idle`

The naming inconsistency is unfortunate, but we can't just change the name because this will be a breaking change for users. We could do nothing until 2.0 and unify then. Or we could add a timer called `executor.execution` for the `TimedExecutorService` and `TimedScheduledExecutorService` while keeping the existing `executor` so both names are available, even though they should be measuring the same thing. Then remove the `executor` one in Micrometer 2.0.

**Comment by marcingrzejszczak** [comment]
Is there anything else we should be doing here, or can we close this?

**Comment by shakuzen** [comment]
There's been no change as far as I know so the inconsistency mentioned in my previous comment remains to this day. We don't have great options for correcting the issue without duplication and an eventual breaking change. Since we have no current plans for a new major version, I'm not sure when we would be able to make the breaking change and remove the duplication. On a case by case basis, a `MeterFilter` could be configured by users to align the naming. It hasn't been brought up lately as a concern (as far as I know) so perhaps users are working around the inconsistency.
