### ISSUE TITLE
Include / Exclude Timer submetrics

### ISSUE THREAD

**Issue by bisoldi** [micrometer-metrics/micrometer#1103]
I'm using the Timer meter in my project and would like to disable / exclude `.sum` and `.max` and in some cases even `.count`.  I'm using the Cloudwatch Registry, though I could see the same use-case for any monitoring system.  Finally, I didn't want to have to refactor my code to use the FunctionTimer which has only `.avg` and `.count` (and yes, I see the irony in suggesting a code-change so I don't have to change my code).

Also, the point at which these Metrics are created appears to be post-MeterRegistryCustomizer, and don't see any way to exclude them.

Anyways, I was wondering what people would think about building in a way to exclude a specified list of those submetrics.  One thought I had was to add a Timer.builder method that would specify which sub-metrics to include possibly using an enum to be explicit (defaulting to ALL so as not to break existing code) and then in the specified Registry (in my case CloudWatchMeterRegistry) check for ALL or the specific enum before each metrics.add(...) call.  Or, it could be a bit more fluent and the metricDatum(...) method could return an Optional<MetricDatum> and then in the metricData method, call .ifPresent() on the optional and add it to the Stream.

Thoughts?

**Comment by jkschneider** [comment]
The issue with surfacing something in `Timer.builder` is not all registries ship the same statistics for timers. For example, some monitoring systems like a precomputed average, others do not.

* If you exclude `.sum`, `.max`, and `.count` what is left? 
* If you just exclude `.sum` and `.max` leaving `.count`, it sounds like you really want a counter and not a timer (although in general we say don't count things you can time since you may discover later you want the timings).

Can you be more specific about the use cases?

**Comment by shakuzen** [comment]
@bisoldi I'm checking back on this to see if you could provide the feedback @jkschneider requested in the previous comment.

**Comment by bisoldi** [comment]
@shakuzen @jkschneider 

Sorry for the delay.  After some refactoring, I am using Timer to keep track of 2 different times.  

The first is the time it takes to run a process, which takes anywhere from < 1 second to 60 seconds and occurs frequently.

The above process includes processing log records and pushing them out to Kinesis and so the second Timer tracks the amount of time each record is delayed before it is successfully pushed out to Kinesis.

So, with the above 2 use cases, sum and count don't really matter much.  I could use .max but without an idea of the frequency of the .max, that's not much use to me either.  Right now, I'm primarily using .avg.

I guess I could use a Counter...?  It just seemed like Timer is natively meant for counting time. 

Would you recommend Counter instead?

**Comment by shakuzen** [comment]
Average is computed as `sum / count`, so those would need to be kept internally, even if not published. As Jon mentioned, depending on the registry used, pre-computed averages won't be provided at all, deferring instead to your backend to compute the average for a time range (even across dimensions) on demand.

Is the goal just to reduce the cost of time series in CloudWatch?

Without the `count` you won't be able to correlate the timing information to any change in rate (e.g. is it slow because it is processing more than it can handle quickly or another cause?)

**Comment by bisoldi** [comment]
@shakuzen Yeah, my intent was really just to reduce not only cost but also clutter in CW.  It sounds like it's probably not worth it.  Thanks for indulging it though!
