### ISSUE TITLE
Replace dependency locking mechanism with explicit version definition

### ISSUE THREAD

**Issue by OleksiiBondar** [micrometer-metrics/micrometer#1105]
Few impacted PRs and related comments to the topic:
https://github.com/micrometer-metrics/micrometer/pull/1100#issuecomment-450462726
https://github.com/micrometer-metrics/micrometer/pull/1102 - failed with dependency looking
https://github.com/micrometer-metrics/micrometer/pull/1098 - failed with dependency looking
https://github.com/micrometer-metrics/micrometer/pull/1072 - also failed on quality check stage

**Comment by OleksiiBondar** [comment]
@jkschneider 

>can be addressed by simply removing locks from master and keeping them on the release branches

Yes, it will definitely help a lot with continuous failures with locking against master.

>It's tedious and error prone.

Can't agree about error-proneness. To me, having `latest.release` which can bring new major version seems more error prone than updating versions once in a while. 
One thing is to have version specified as `1.2.+`, but with `latest.release` build process becomes to some degree a lottery.

Clearly understand your concerns in terms of maintanance overhead and I'm with you. How about some trade-off between maintanance and controlled environment? Maybe having atleast fixed major version is suffice? From what I can see, we already have some dependency defined like this:

https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/build.gradle#L22
https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/build.gradle#L34
https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/build.gradle#L40-L41

**Comment by jkschneider** [comment]
I think we already have made this decision on limiting to major versions where it matters most like for dropwizard and tomcat and logback like you mentioned. And those decisions haven't been made based on what would work for Micrometer. We could easily upgrade to dropwizard 5, tomcat 9, etc. We keep those pinned to major versions largely for compatibility with major web frameworks.

> To me, having latest.release which can bring new major version seems more error prone than updating versions once in a while.

To me this is the kind of error we _want_ on the master branch. In other words, bring the pain forward and address upstream breakages on the master branch as they happen rather than stop once every few months, look up each and every dependency to see if it has a newer major, upgrade each one, fix problems. There is definitely no right answer here, but as a maintainer I really just want to spend as little time on the build as I can and more time working on features.

**Comment by OleksiiBondar** [comment]
Ok, sound like as a part of this issue it comes down to doing just this 

> can be addressed by simply removing locks from master and keeping them on the release branches

Right?

**Comment by jkschneider** [comment]
Yep, and fixing up a few odds and ends where latest dependencies are bad for some reason (see note on Hystrix on latest head). Done with 5f5c70c6.
