### ISSUE TITLE
Prometheus: Use default CollectorRegistry

### ISSUE THREAD

**Issue by TYsewyn** [micrometer-metrics/micrometer#111]
Is it possible to return `CollectorRegistry.defaultRegistry` in `PrometheusMetricsConfiguration` by default instead of `new CollectorRegistry(true)`?
Using the default registry, all other metrics that are created by 1 of the many modules Prometheus offers (eg. simpleclient_hotspot, simpleclient_servlet, simpleclient_spring_web,...) are also picked up and shown when you scrape the Prometheus actuator endpoint.

**Comment by jkschneider** [comment]
It's easy enough to use the `defaultRegistry` if you'd like by specifying:

```
@Bean 
CollectorRegistry collectorRegistry() {
   return CollectorRegistry.defaultRegistry;
}
```

I think it best to stay away from this as a default, because the static state that accompany it can be nasty for test parallelism. Furthermore, I'd like us to be in a state where there should be no reason for you to need a `simpleclient_servlet`, `simpleclient_hotspot`, etc because we have already provided binders out of the box that do the same things. Don't be shy about pointing out the gaps!

**Comment by TYsewyn** [comment]
Thanks for the quick answer! I didn't check all the binders before, but like you said, there shouldn't be a reason for us to use those dependencies anymore. Thanks for pointing that out!

**Comment by huanzhang** [comment]
@jkschneider I want to use simpleclient_jetty's metrics, but I don't know how to add it to Prometheus actuator endpoint.

**Comment by checketts** [comment]
@huanzhang Adding in a bean that uses the default registry (as Jon's show above) is sufficient to make it appear on the actuator endpoint.

Perhaps a stack overflow question would be a good option if you are running into specific hurdles?
