### ISSUE TITLE
Include HTTP Metrics exposition into springboot 1.5 legacy dependency

### ISSUE THREAD

**Issue by fabMrc** [micrometer-metrics/micrometer#1113]
Hi

With springboot 2 and Actuator all metrics are browseable in HTTP and exposed in Json Format.
Why do not choose to do the same things for springboot 1.5.x. Actuator in this legacy version does not embedded anything about this but it is easy to take the 2.x code and adapt it for 1.5.

thanks

**Comment by jkschneider** [comment]
@fabMrc The reason is Spring Boot 1.5.x has a different `/metrics` actuator endpoint based on the hierarchical scheme that has been removed in Spring Boot 2 to make way for the new one. The actuator endpoint really should just be a diagnostic tool anyway, as the individual registries expose metrics to their respective monitoring systems in specific ways. The thought was that you should be moving forward to Spring Boot 2 anyway, so the legacy support helps get metrics out of your old app with a sacrifice here and there (like this endpoint).
