### ISSUE TITLE
Effective method of monitoring multiple instances

### ISSUE THREAD

**Issue by sameer-chebbi** [micrometer-metrics/micrometer#1163]
Given - 
I set up a Gauge in my microservice. I have to reset it every midnight to measure an event. The event being total number of update calls that are being to made to my mongoDB. Gauge name (with tags) is - 
updates.<tag:service-name>.<tag:db-name>

Question - 
Once I deploy multiple instances of my service, how will the graphite reporting be affected. Since obviously more than one meter with the same name will be tried to register. 
What could be the value of updates.service-name.db-name be? How should I name my tags so that I can collect data from all instances irrespective of how many are created/destroyed?

My own efforts-
Initially, I started with naming my gauge like updates.service-name.db-name. 
When I observed that the gauge count did not match the actual number of data inserted, I figured this might be due to multiple instances.
So I renamed the gauge to - updates.servicename.eureka-instance-id.db-name and on grafana, I used sumSeries to get the total count - updates.service-name.*.db-name.
a - the total never matched so i guess I was using the wrong query.
b - with every service deploy and restart, there is a new eureka-instance-id. This leads to just too many tags.
c - (I don't think this relates to micrometer) After a while, I could see all the different gauges eventually settling down to one common value. Leading to the wrong summed up value. It could be since we are consuming data from kafka and kafka is sending the same message across different consumers.

**Comment by jonatan-ivanov** [comment]
> I have to reset it every midnight to measure an event. The event being total number of update calls that are being to made to my mongoDB.

I don't think you should reset such a metric, also you should use a `Counter` for this instead of a `Gauge`.

>How should I name my tags so that I can collect data from all instances...

You should add some sort of an instance identifier to your apps, e.g.: hostname+port, hostname+pid, container ID, pod name, etc. see the docs: https://micrometer.io/docs/concepts#_common_tags
Once you have this, you can aggregate (I assume `sum`) these time series and you can get the total number of calls across all instances.

>a - the total never matched so i guess I was using the wrong query.

You should check how to to this in graphite, check if you see all of the time series from all of the instances first.

>b - with every service deploy and restart, there is a new eureka-instance-id. This leads to just too many tags.

Yes, you will might have an issue like this depending on how you identify your instances, check my comment above for other ideas. One real hacky solution that comes to my mind is using the index of the instance in the list of instances in eureka (I'm not sure what troubles will this bring in).

>c - (I don't think this relates to micrometer) After a while, I could see all the different gauges eventually settling down to one common value. Leading to the wrong summed up value. It could be since we are consuming data from kafka and kafka is sending the same message across different consumers.

I'm not sure what does this mean but as I mentioned above, you should not use a `Gauge` for this.
