### ISSUE TITLE
How to create a multi-value tag metric gauge?

### ISSUE THREAD

**Issue by icemagno** [micrometer-metrics/micrometer#1170]
Sorry for this guys. I know it's not a really issue but I can't find help anywhere.

Can someone give a help here?

https://stackoverflow.com/questions/54242374/how-to-create-a-multi-value-tag-metric-gauge/

Thank you.

**Comment by checketts** [comment]
The answer already provided on the stack overflow question is accurate: there isn't support for multivalue tags. 

If you take Prometheus for example, it can only express one value of each tag like so: 

`my_metric{method="post"} 123`

You can't repeat the `method` key. 

Of you have 2 separate metrics that can be expressed by overlapping tags you could create a separate gauge with the dupicated tag, however I would recommend against that since often tags are intended to express parts of a whole and the duplicate tags would inflate the overall count if you were to have queries that didn't take your duplicated metrics into account.

**Comment by shakuzen** [comment]
I'm not clear on the use case. Maybe it would be easier to chat about this on our Slack channel. If you want to record the same metric value for multiple tag key-value combinations, you could record the same value for each combination, but again, I don't understand the use case for this.
