### ISSUE TITLE
[Help] How to dynamic disable/enable meters already registered or root meterRegistry

### ISSUE THREAD

**Issue by lubinson** [micrometer-metrics/micrometer#1197]
Hi Expertise,

Can already registered meters or the root meterRegistry (injected by Spring) been disable/enable (maybe many times) at running time dynamically?

I have reached the meter filter feature, I thought it was I need. But this filter is to applied on new meters to be added to meterRegistry, not to filter on behavior of registered meters. 

Different levels of control is more desired, e.g. disable/enable some meters or disable/enable all of them by a convenient way.  

Thanks in advance.

**Comment by izeye** [comment]
It sounds like `MeterFilter` should work here. Am I missing something?

**Comment by shakuzen** [comment]
I agree with @izeye. If you're using Spring Boot, then you can just update the application's configuration properties to control which meters are enable/disabled. See [this part of the documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#_per_meter_properties). Does that work for you @lubinson?

**Comment by jkschneider** [comment]
Meter filters are only evaluated once at initial meter registration time currently, and I think @lubinson
is asking for them to be applied "more frequently". We know we can't evaluate them at registration time every time because:

1. Performance would suffer.
2. What about meters held in fields or other state?
3. Gauges are infrequently re-registered so special case of (2).

I think the best we could do would be for the registry to periodically schedule a re-evaluation of filters, but I can't comprehend at this point all the implications for field-level meter references and the like. Tough feature, but a killer one if it can be done.

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2019. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
