### ISSUE TITLE
Support for DLQs

### ISSUE THREAD

**Issue by eloo** [micrometer-metrics/micrometer#121]
Hi,
i've just figured out that it seems that the DLQ (Dead letter queues) are not being instrumented by the SpingIntegrationMetrics.
Would it be possible to support DLQs too?

Thanks

**Comment by jkschneider** [comment]
@garyrussel Did you manage to instrument these in your work on Spring Integration metrics?

**Comment by garyrussell** [comment]
DLQs are not `MessageChannels` they are an entity in the broker (RabbitMQ, Kafka etc).

Since 1.3, each binding gets a dedicated errorChannel which is created by SCSt, not Spring Integration.

When a `@StreamListener` throws an exception, an `ErrorMessage` is sent to the error channel.

The binder subscribes a message handler to that channel; the handler can writes failed messages to a DLQ (if the binding is so configured).

Since SCSt creates the error channel (not SI), we will need to change the abstract binder to configure the error channels with micrometer metrics; it's a pretty straightforward change.

I will discuss with @olegz tomorrow, but we should be able to get it into the SCSt 2.0 release candidate.

**Comment by garyrussell** [comment]
After further thought; I think we can do something in SI for __any__ dynamically registered integration components.

**Comment by garyrussell** [comment]
[SI Pull request](https://github.com/spring-projects/spring-integration/pull/2362) - it should be in SI 5.0.2 which will be released right after the Micrometer GA.
