### ISSUE TITLE
Expose buffered property for StatsdConfig

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#1375]
This was added in #1046 and it needs to be made available from the Spring `ConfigurationProperties` class `StatsdProperties` and `StatsdPropertiesConfigAdapter` in our spring legacy module, and also in Spring Boot.

**Comment by mickaeltr** [comment]
Hello @shakuzen,
I was hoping to use `buffered = false` on a Spring Boot application, in order to workaround https://github.com/micrometer-metrics/micrometer/issues/1882
By any chance, do you know why it has still not been added to [Spring Boot](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/export/statsd/StatsdProperties.java)?
Thank you

**Comment by izeye** [comment]
@mickaeltr It seems to have been missed somehow. I created https://github.com/spring-projects/spring-boot/pull/30898 to try to resolve it.

**Comment by shakuzen** [comment]
> I was hoping to use `buffered = false` on a Spring Boot application, in order to workaround #1882

#1882 isn't directly related to the statsd registry because the statsd registry isn't a step meter registry. So I'm doubtful the `buffered` property will help if you're seeing that issue. It may be worth opening a separate issue with details and a sample project that reproduces the issue.

**Comment by mickaeltr** [comment]
Hello @shakuzen, that worked! We have cronjobs that run Spring Boot applications, then exit. Metrics in those cronjobs were never published. Running them with `--management.metrics.export.statsd.buffered=false` fixes it. Maybe [the issue](https://github.com/micrometer-metrics/micrometer/issues/1882) I was referring to is different… Anyway, thanks again 🙌
