### ISSUE TITLE
Add support for Cassandra database

### ISSUE THREAD

**Issue by fkoehler** [micrometer-metrics/micrometer#1397]
It would be helpful to have a Metric binder which, something similar to the KafkaConsumerMetrics binder. Maybe we can fetch the metrics via JMX from Cassandra?

**Comment by shakuzen** [comment]
See also #1359. It would be nice if the Cassandra driver supported more extensible ways of recording metrics, or natively supported Micrometer itself. Have any users requested this to the maintainers of the Cassandra driver? We're moving away from the JMX way of retrieving metrics for the Kafka client because doing it via JMX can be pretty messy.

**Comment by LeifW** [comment]
The Cassandra docs mention Micrometer as one of the supported outputs for the metrics collected by the driver: https://docs.datastax.com/en/developer/java-driver/4.11/manual/core/metrics/

**Comment by shakuzen** [comment]
Thanks for the link to the docs, @LeifW. Indeed Cassandra has updated their driver to support more metrics libraries than Dropwizard since 4.8.0, per ticket [JAVA-2808](https://datastax-oss.atlassian.net/browse/JAVA-2808). I don't think there is anything more to do in Micrometer, since the instrumentation is provided by the driver.
