### ISSUE TITLE
Exception thrown from gauge stops scheduled task

### ISSUE THREAD

**Issue by engineal** [micrometer-metrics/micrometer#1444]
I am using micrometer with the CloudWatchMeterRegistry. I have registered a gauge like so:

`registry.gauge("my_repository.count", Tags.empty(), myRepository, MyRepository::count);`

The CloudWatchMeterRegistry, being a child of the PushMeterRegistry, schedules the publish task at a fixed rate. However, if `MyRepository::count` throws an exception, metrics stop being published until the application is restarted.

I have followed the exception and it appears to make it into the `CloudWatchMeterRegistry.publish()` function, which contains a try...finally block without a catch. Once the exception makes it to the scheduled executor service, it will no longer schedule the publish method anymore.

While I could make sure every gauge has a try...catch block, it would be cleaner if a catch block could be added to the `CloudWatchMeterRegistry.publish()` function.

**Comment by izeye** [comment]
@engineal [Any `Throwable` from `PushMeterRegistry.publish()` should be caught in `PushMeterRegistry.publishSafely()`](https://github.com/micrometer-metrics/micrometer/blob/bbd4113990061f09d8a97696be38d5ebbbd912c0/micrometer-core/src/main/java/io/micrometer/core/instrument/push/PushMeterRegistry.java#L43-L52) since #1228, so 1.1.4+ should be okay. Which version of Micromter are you using?

**Comment by engineal** [comment]
Thanks for your comment, I am using 1.1.3. I will test 1.1.4 to verify that my bug is fixed there.

**Comment by shakuzen** [comment]
@engineal if with the logging of the exception you've found an issue in Micrometer code, please let us know and we'll try to get it fixed.
