### ISSUE TITLE
statsd counter and timer are not pollable but gauges are

### ISSUE THREAD

**Issue by codeperfector** [micrometer-metrics/micrometer#1451]
I'm using version 1.1.4 of micrometer-statsd-registry in a spring boot app and sending metrics to telegraf version 1.9.2 running locally.
When I create a statsd gauge I see gauge metrics being reported to telegraf periodically. However when I create a counter using Counter.builder(...).register(...) or StatsdMeterRegistry.counter(...) I never see any metrics reported. Ditto for timers.
I looked into the source and I see that StatsdMeterRegistry has a field called "pollableMeters". When I create gauges, the size of pollableMeters increases by 1 but when I create and register counters or timers then it never increases.
As an experiment I tried to create a counter using Meter.builder(..).register(..) and that worked. 
It seems like there is a bug with the way counters and timers are implemented in StatsdMeterRegistry. I believe that StatsdMeterRegistry.newCounter should add the counter that it creates to pollableMeters and the same with timers or anything else that's related.

```
        // this works and the values reported for "pipestream.counter" show up in telegraf logs
        Meter.builder("pipestream.counter", Meter.Type.COUNTER,
                Collections.singletonList(new Measurement(test::doubleValue, Statistic.COUNT))).register(meterRegistry);
        // this doesn't send any metrics to telegraf for "pipestream.counter"
        counter = Counter.builder("pipestream.counter").register(meterRegistry);
```
I can see that the StatsdMeterRegistry behaves this way as far back as pull request #143
https://github.com/micrometer-metrics/micrometer/pull/143/files

**Comment by shakuzen** [comment]
Counter increments are published immediately when they happen.

https://github.com/micrometer-metrics/micrometer/blob/fb956dd319dc9e1cf9fd1f72d58a4a321bf7b313/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdCounter.java#L40-L46

Counters don't need to be polled because they only change when an increment is made. Same for Timers. Gauges, however, may not have any specific value until read, so they are periodically polled.
So counter increments should be reported. If they are not showing up in Telegraf that may be another issue.

**Comment by tom-mi** [comment]
The problem with this approach is that counters that are infrequently (or never) incremented never appear in the monitoring (we are using Datadog and push metrics via dogstatsd). This is problematic for meters like error counters, which we would like to define alerts & graphs on error counters, but we never see any data until actual errors happen.
Is there a workaround for that, like sending a zero increment on startup or similar?
(in our case, this would also be relevant for non-custom metrics that come with spring boot, like log events by log level)

**Comment by brahtala-leovegas** [comment]
I have the same problem, I use counters for alerts, and if value is 0 long enough, that counter is not visible in Datadog.
It looks like I should move to gauges.

**Comment by shakuzen** [comment]
> Is there a workaround for that, like sending a zero increment on startup or similar?

Not that I can think of. It is a (in my opinion, reasonable) optimization to not send values for meters that do not have values. Incrementing by zero won't work because values of zero or less will be ignored by the current implementation.
https://github.com/micrometer-metrics/micrometer/blob/373ea7bf1e391f6321f4b475e80214b5355b274b/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdCounter.java#L41-L42

> The problem with this approach is that counters that are infrequently (or never) incremented never appear in the monitoring (we are using Datadog and push metrics via dogstatsd). This is problematic for meters like error counters: We would like to define alerts & graphs on error counters, but we never see any data until actual errors happen.

I see how this can be unexpected and confusing, but it's not really a problem for the alert, is it? When there aren't increments to the error counter, the alert won't fire, and when there are, it will.

If a counter is never incremented, it doesn't exist yet in that instance. Think about a counter metric for an HTTP endpoint that tags HTTP status code - we wouldn't want to make a counter for every possible status code and publish zero values for them. Most of these will probably never happen and so there is no need to have a time series for them.

**Comment by codeperfector** [comment]
Thanks for the explanation! It clears out my confusion about how counters are incremented. The issue with not reporting zero values might be another separate question. I however think that it should be fine if zero values are not pushed out to the reporting system.
