### ISSUE TITLE
Custom implementation of MeterRegistry

### ISSUE THREAD

**Issue by favetelinguis** [micrometer-metrics/micrometer#1493]
We would like to send metrics to cloudwatch. Using the provided cloudwatch solutions makes to many assumptions about how your project is setup, for example you need to depend on cloud AWS which then makes even more assumptions. We would like to write a more lightweight implementation which just get a CloudWatchAsyncClient injected and makes no other assumptions about our project. 

However im not sure how. Is there any example on how to make a custom implementation insted of having to depend on the available metrics registry? 

So far I have done some experimenting with the following:
```
public interface CloudWatchConfig extends StepRegistryConfig {
    int MAX_BATCH_SIZE = 20;

    @Override
    default String prefix() {
        return "cloudwatch";
    }

    default String namespace() {
        String v = get(prefix() + ".namespace");
        if (v == null)
            throw new MissingRequiredConfigurationException("namespace must be set to report metrics to CloudWatch");
        return v;
    }

    @Override
    default int batchSize() {
        String v = get(prefix() + ".batchSize");
        if (v == null) {
            return MAX_BATCH_SIZE;
        }
        int vInt = Integer.parseInt(v);
        if (vInt > MAX_BATCH_SIZE)
            throw new InvalidConfigurationException("batchSize must be <= " + MAX_BATCH_SIZE);

        return vInt;
    }
}
```
```
@Service
@Log
public class CloudWatchMeterRegistry extends StepMeterRegistry {

    public CloudWatchMeterRegistry(CloudWatchConfig config, Clock clock) {
        super(config, clock);
    }

    @Override
    protected void publish() {
        getMeters().stream().forEach(a -> {
            log.warning(a.getId().toString());
        });
    }

    @Override
    protected TimeUnit getBaseTimeUnit() {
        return TimeUnit.MILLISECONDS;
    }
}
```
```
@Configuration
public class MetricsPublisherConfig {
    @Bean
    public CloudWatchConfig cloudWatchConfig() {
        return new CloudWatchConfig() {
            // NOT SURE HOW THIS IS USED OR HOW TO IMPLEMENT THIS
            @Override
            public String get(String key) {
                return "testtest";
            }
        };
    }
}
```

However im not sure how to do the implementation of the `cloudWatchConfig` function and getting the error.

`Caused by: java.time.format.DateTimeParseException: Text cannot be parsed to a Duration`

Am I working in the right direction or how should such a thing be done?

**Comment by shakuzen** [comment]
You are working in the right direction. I think the issue is config methods that are trying to return a `Duration` are using your constant `testtest` value returned by the `get` method to parse a `Duration`. For example, look at the default `step()` implementation on `PushRegistryConfig`:

https://github.com/micrometer-metrics/micrometer/blob/6c657f93479b03835478153c33cde4122b7b7ac2/micrometer-core/src/main/java/io/micrometer/core/instrument/push/PushRegistryConfig.java#L33-L36

If you don't want any custom logic in the `get` method, have it always return `null` and then the default will be used. An example of this can be found in tests.

https://github.com/micrometer-metrics/micrometer/blob/42f4aef9ec9e6950744de7227231fadf383f13b6/implementations/micrometer-registry-cloudwatch2/src/test/java/io/micrometer/cloudwatch2/CloudWatchMeterRegistryTest.java#L45-L55

---

If you think the assumptions in the CloudWatch registry implementation are not generally reasonable, we can consider what we can do to make it work better for most users. If your situation is very specific, though, then making your own implementation may be best.
