### ISSUE TITLE
DataSourcePoolMetadataProvider

### ISSUE THREAD

**Issue by itsgauravsaxena** [micrometer-metrics/micrometer#1502]
I know it must have been discussed before but I am struggling to setup data source metrics in my application. Spring boot 2.0.3.Release with oracle database (local h2 DB). Any working  example would be a great help as I am in really last minutes.

**Comment by izeye** [comment]
@itsgauravsaxena If you're using an auto-configured data source, you don't need any additional configuration for it. Please see [this sample using H2/HikariCP](https://github.com/izeye/sample-micrometer-spring-boot/tree/jdbc).

**Comment by itsgauravsaxena** [comment]
I am not using auto configuration due to historical reasons.
My configuration bean rather looks like this

    @Bean
    DataSource dataSource() throws SQLException {

        OracleDataSource dataSource = new OracleDataSource();
        dataSource.setUser(username);
        dataSource.setPassword(password);
        dataSource.setURL(url);
        dataSource.setImplicitCachingEnabled(true);
        dataSource.setFastConnectionFailoverEnabled(true);
        return dataSource;
    }

**Comment by izeye** [comment]
@itsgauravsaxena Thanks for the additional info. Based on the bean definition you provided above, the `DataSource` won't be pooled with any data source pool library Spring Boot supports and the metrics you referred above are for the pooled data sources. So your bean definition for `DataSource` should be changed to be a pooled version if you want to see the metrics for the pooled data sources. This is [a sample demonstrating how to do it](https://github.com/izeye/sample-micrometer-spring-boot/tree/jdbc-custom-data-source). You might also want to check [the relevant section in the Spring Boot reference documentation](https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#howto-configure-a-datasource).

If you have an additional question, it'd be good to create a StackOverflow question  as it seems to be a Spring Boot question rather than Micrometer itself.

**Comment by itsgauravsaxena** [comment]
Thanks @izeye 
I just switched to pooled datasource but I dont see any change in behaviour.

` @Bean
public DataSource dataSource() throws SQLException {
            PoolDataSourceImpl dataSource = new PoolDataSourceImpl();
            dataSource.setConnectionFactoryClassName("oracle.jdbc.pool.OracleDataSource");`

Or should it be like this.
`@Bean
	public DataSource customDataSource() {
		return DataSourceBuilder.create().url("jdbc:h2:mem:mydb").build();
	}`
I will also make a stackoverflow question also in the meantime.
Thanks a lot 👍

**Comment by izeye** [comment]
@itsgauravsaxena Spring Boot provides out-of-the-box support only for the following three pooled data sources at the moment:

- `com.zaxxer.hikari.HikariDataSource`
- `org.apache.tomcat.jdbc.pool.DataSource`
- `org.apache.commons.dbcp2.BasicDataSource`

If you want to create the `DataSource` bean on your own, you need to create an instance from one of them. Or you can resort to the `DataSourceBuilder`.

If you create a question on Stack Overflow, feel free to add a link to the question here for anyone interested in it.
