### ISSUE TITLE
Datadog Registry implementation does not honor commonTags for WebFlux metrics

### ISSUE THREAD

**Issue by krmeda** [micrometer-metrics/micrometer#1512]
When common tags are configured as per [documentation](https://micrometer.io/docs/concepts#_common_tags), the datadog registry ignores the common tags. 

I verified common tags setup by using a secondary Prometheus registry where it is showing up correctly in `/actuator/prometheus` endpoint. 

Makes using the `name-tag` support of Datadog Registry a problem for already available metrics such as Spring Webflux metrics.

**Comment by shakuzen** [comment]
@krmeda I'm trying to find my Datadog credentials to try to reproduce this, but could you confirm you've tried with the latest versions and this is still an issue? Are you using the DatadogMeterRegistry or the StatsdMeterRegistry? Since you mention WebFlux, I assume you are using Spring Boot. In that case you should use [the Spring Boot configuration property](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#production-ready-metrics-common-tags) to set the common tags.

**Comment by krmeda** [comment]
I am using the `DatadogMeterRegistry`. I will check with the latest versions and also use the spring boot configuration property and reply back...
