### ISSUE TITLE
performance downgrade after enable "http.server.requests" metrics with micrometer-jersey2 

### ISSUE THREAD

**Issue by wangyf2010** [micrometer-metrics/micrometer#1522]
we're using spring-boot:2.1.1.RELEASE. After add below 2 dependencies to enable prometheus metrics for "http.server.requests". we saw there are performance downgrade:
micrometer-registry-prometheus:1.1.1 & micrometer-jersey2:1.1.1

LnP report shows:
cpu: enable "http.server.requests" - 34% vs diable "http.server.requests" - 25%.
GC overhead: 1% vs 0.7%
Latency: 69ms vs 40ms 

any ideas to improve its performance?

**Comment by mweirauch** [comment]
Hi @wangyf2010 thanks for reporting. I got some remarks and questions.
* First of all, instrumentation doesn't come for free. There's always an overhead.
* The only thing which comes to my mind (without checking the code again) is that we are collecting the resource class and method annotations on every request. We could introduce some caching, so that this overhead is only present once on the first requests to a particular resource/method. A further improvement could be scanning the available resources proactively. (IIRC there was such a possibility.)
* The increased CPU load could also stem from the `PauseDetector` which was still in effect until release `1.1.4` which did add a noticeable CPU usage on every timer registered. You could try setting the `NoPauseDetector` to see if it makes a difference.

One aspect I'd like to get more info about:
Which HTTP requests is the measured latency reporting? Only the API requests, or  over API and Actutor endpoint requests (including prometheus scapes to /actuator/prometheus)?
I am asking because the prometheus endpoint payload gets quite big - especially if timer histogram information is included as well - and this could of course add to the overall latency.

**Comment by wangyf2010** [comment]
Thanks @mweirauch for detail comments!

It is over actuator endpoints requests. we did LnP with histogram & without histogram. both of them have big CPU overhead. And we just did LnP on our business API, not ping /actuator/prometheus at all.
I have one question here: does micrometer have window to record http request metrics? if there are many requests come in, will record too many metrics, then have memory leak issue?  Or only polling "/actuator/prometheus", then that could reset metrics and start new round metrics recording?

For  NoPauseDetector, great to know it. could you let me know how to configure it? Then I can give a quick try with it.

**Comment by wangyf2010** [comment]
found logic to scan annotations per request: https://github.com/micrometer-metrics/micrometer/blob/6c657f93479b03835478153c33cde4122b7b7ac2/micrometer-jersey2/src/main/java/io/micrometer/jersey2/server/MetricsRequestEventListener.java#L76

**Comment by mweirauch** [comment]
> It is over actuator endpoints requests. we did LnP with histogram & without histogram. both of them have big CPU overhead. And we just did LnP on our business API, not ping /actuator/prometheus at all.
> I have one question here: does micrometer have window to record http request metrics? if there are many requests come in, will record too many metrics, then have memory leak issue? Or only polling "/actuator/prometheus", then that could reset metrics and start new round metrics recording?

The memory usage should be constant per unique (basically the same tags on `http.server.requests`) HTTP-request metric.  There should be no leak, just the regular memory usage per metric. Of course recording histogram data additionally has its memory overhead. There's a [memory footprint estimation](https://micrometer.io/docs/concepts#_memory_footprint_estimation) in the docs.

So if you don't serve hundred different URLs multiplied with a big variation of http return codes, exceptions and request methods, you should be fine. Except for instrumentation cost, the memory overhead should be constant no matter if you got 1 or 500rps. (Please somebody correct me if I am wrong here.)

> For NoPauseDetector, great to know it. could you let me know how to configure it? Then I can give a quick try with it.

IIRC you said in Slack that you got it figured.

> Is that also ok to upgrade to 1.1.4?

Sure, why not. Just make sure all micrometer dependencies are resolving to the same version in your project.

**Comment by wangyf2010** [comment]
I tried 1.1.4 and did lnp, no big improvement for performance.
If there isn't mem leak for per recording metrics. I'd prefer to analyze it by below 2 ways:
1. I want to improve annotation scanning part to see whether it helps. 
2. Understand there is cost for instrumentation, while per lnp looks like there are much more overhead for CPU. And there are more GC overhead, so I suppose there are memory problem (create too many objects if have more traffic.). I'll analyze heapdump too to see whether could find anything wrong. 

Thanks @mweirauch

**Comment by shakuzen** [comment]
Could you share more about how you are getting these numbers? What's the load you are putting on the application and what variety of requests are you sending?

>     1. I want to improve annotation scanning part to see whether it helps.

Please make an issue for this so we can track it separately. Thank you.

**Comment by shakuzen** [comment]
Closing for now due to lack of feedback. If we can get more information to look into this further, we can reopen later.
