### ISSUE TITLE
ProcessorMetrics.processCpuUsage

### ISSUE THREAD

**Issue by xiaobing395845388** [micrometer-metrics/micrometer#1534]
when springboot project run in a docker container of k8s clouder, processCpuUsage reports  current process CPU load / k8s host node, not current process CPU load/contianer

**Comment by checketts** [comment]
This is a JVM limitation.  Are you running with `-XX:+UnlockExperimentalVMOptions` or `-XX:+UseCGroupMemoryLimitForHeap` ?

Either way, this isn't something Micrometer can address itself.

More information here: https://dev.to/zac_siegel/java-and-docker---memory-and-cpu-limits-3h77

**Comment by shakuzen** [comment]
The automatic docker support added in Java 10 was backported to Java 8 update somewhat recently, so I would suggest trying to use the latest update of Java 8. That said, I don't know if it solves the process CPU usage issue or not. The current implementation in `ProcessorMetrics` depends on the result of the `OperatingSystemMXBean`'s method `getProcessCpuLoad`.  There's also #1274 to add/switch to OSHI as an implementation for getting these metrics. I'm not sure if it does better about process CPU usage in Kubernetes or not.

@xiaobing395845388 please share what version of Java you are using to run your application, so we can verify if the latest update version helps or not.

**Comment by xiaobing395845388** [comment]
1.8.0_201

**Comment by shakuzen** [comment]
@xiaobing395845388 thank you for responding quickly. That version should have the backport of the docker support things (which went in u191, I think).
How are your CPU limits configured for the container?

**Comment by xiaobing395845388** [comment]
configure  CPU  limit 6  cores   and  CPU request  2 cores

**Comment by pvorb** [comment]
I can tell that `OperatingSystemMXBean.getAvailableProcessors()` already respects CPU **limits** and returns the number of CPU cores according to this limit. If I set a limit of, say, 750m it will return 1. If I set a limit of 4, it will return 4. I have tested this with recent versions of OpenJDK 8 and 11.

I tried to evaluate numbers reported by `OperatingSystemMXBean.getProcessCpuLoad()` as well, but I'm not sure how to interpret these numbers. I compared Micrometer's `process.cpu.usage` against `docker stats` and `htop`. Values reported by `docker stats` and `htop` roughly match each other with `docker stats` having a small delay. `process.cpu.usage` seems to be a little less than the others. I tested on a VM with 4 cores. Where `docker stats` reports a CPU usage of 2.5 %, `process.cpu.usage` is around 0.001. So this might be caused by the 4 CPUs, which would have a maximum of 400% in `docker stats` and a maximum of 1.0 in `process.cpu.usage`. The Pod was running with a CPU limit of 750m and CPU requests of 200m.

I think this shows that `process.cpu.usage` doesn't account for the current CPU limit of the pod.

**Comment by xscript** [comment]
@shakuzen Any update on this issue?
Looks like `process.cpu.usage` still uses the host machine's cores instead of the container's CPU limit.
We are using Java8u252 and Java11u7.

**Comment by wuguanyu** [comment]
I already encounter this issue，systemCpuUsage is different from k8s pod cpu monitor

**Comment by xiaobing395845388** [comment]
@shakuzen  Any update on this issue?

**Comment by izeye** [comment]
[JDK-8228428](https://bugs.openjdk.java.net/browse/JDK-8228428) seems to have fixed `OperatingSystemMXBean.getSystemCpuLoad()` at Java 14. However, for `OperatingSystemMXBean.getProcessCpuLoad()`, [it has been mentioned there](https://bugs.openjdk.java.net/browse/JDK-8228428?focusedCommentId=14302960&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14302960), but it hasn't been changed for some reason. I'm not sure why as there's no explanation for it.

**Comment by leebake** [comment]
@izeye Is above mentioned related to my investigation?
I've plotted three graphs:

1. cpu usage given by querying (prom-operator):
`sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{container!="POD", container="services-gateway"}) by (pod, container)`

2. cpu system usage by querying:
`system_cpu_usage{job="services-gateway"}`

3. cpu process usage by querying:
`process_cpu_usage{job="services-gateway"}`

`kubectl top po services-gateway-56b9d8c985-6dtd2` shows me the given result (assume that there is no spikes in cpu usage):
<img width="604" alt="Zrzut ekranu 2020-12-7 o 15 30 38" src="https://user-images.githubusercontent.com/3183992/101363060-311ff480-38a1-11eb-9b8d-fdd2c2c5cd23.png">

Basing on the above I would assume that the `prom-operator` metric returns correct cpu usage. Why do both system and process cpu usage (from Micrometer) give me those weird values? 
![Zrzut ekranu 2020-12-7 o 15 26 12](https://user-images.githubusercontent.com/3183992/101362794-dd151000-38a0-11eb-9490-1cc57066caeb.png)
![Zrzut ekranu 2020-12-7 o 15 27 00](https://user-images.githubusercontent.com/3183992/101362776-d6869880-38a0-11eb-8551-48ccf5ccb7fc.png)

**Comment by marcingrzejszczak** [comment]
Is this still a problem with the latest versions and JDKs?
