### ISSUE TITLE
Build broken since Atlas version 0.93.0

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#1545]
Noticed by @mwl https://github.com/micrometer-metrics/micrometer/pull/1544#issuecomment-521543413

Since the `master` branch doesn't use dependency locks and the dependency is declared with `latest.release` as the version, we get the latest version of the `com.netflix.spectator:spectator-reg-atlas` dependency on each build. Since version `0.93.0` the tests are failing. They continue to fail with the latest version (at the time of opening this issue) `0.94.0`.

We can pin to an older version to fix the build temporarily, but we need to figure out the root cause of things starting to fail and perhaps report it to the maintainers of the dependency.

The last version the tests pass with is `0.92.2`

**Comment by brharrington** [comment]
There are two issues:

1. `AtlasMeterRegistryCompatibilityTest` can be fixed by updating the config. Spectator AtlasRegistry now supports multiple step sizes for on-demand streaming, but that is causing a problem with the consolidated value that is published for storage in the way the test is setup.
2. `AtlasMeterRegistryTest` is using reflection to call a private method that was renamed. What it was trying to do wouldn't have worked correctly anyway because the flush would happen without crossing the step boundary so the values wouldn't be ready to collect. I'll work on a change in Spectator so you can just call close. In the future it would probably be better to file an issue on Spectator rather than rely on private methods.

When there is an updated Spectator release with the changes for 2, I can send you a PR. It'll probably be a day or two.

**Comment by shakuzen** [comment]
Thank you for the support, @brharrington. We'll do a better job of checking with the Spectator/Atlas team in the future on these things.

**Comment by shakuzen** [comment]
>     1. `AtlasMeterRegistryCompatibilityTest` can be fixed by updating the config. Spectator AtlasRegistry now supports multiple step sizes for on-demand streaming, but that is causing a problem with the consolidated value that is published for storage in the way the test is setup.

@brharrington could you elaborate more on the change that should be made? I took a look but wasn't sure what to change in the test configuration.

**Comment by brharrington** [comment]
See #1550. It is basically making the `lwcStep` value used for on-demand streaming of the data match the publishing step.
