### ISSUE TITLE
monitor apps on k8s using prometheus pushgateway, but data from  destroyed pots not disappeared on grafana

### ISSUE THREAD

**Issue by woshiyjs123** [micrometer-metrics/micrometer#1557]
Sorry to disturb, i encountered a problem.
    our company's applications is running on k8s, using deployment. our applications is using spring cloud framework which integrated micrometer packages. i use prometheus pushgateway to collect metrics  because pod ip will change ofter pod rebuild everytime. 
    but i discovered that pods' data on grafana will not disappeared after pod is rebuilded . 
see, only 172.18.0.10 and 172.18.0.14 is alive, but the old pods is not disappeared.
![image](https://user-images.githubusercontent.com/6252630/63661669-29dcf080-c7ee-11e9-8a70-4b0bc25699bf.png)
only after i delete the group in pushgateway, the pod disappeared.
![image](https://user-images.githubusercontent.com/6252630/63661951-285ff800-c7ef-11e9-97e4-6a6c2a6d9e23.png)
but it's tedious to delete groups after software version update everytime.
is there some better way?

**Comment by checketts** [comment]
You really should move away from pushgateway and use Prometheus relabeling for this use case. 

Done do your metrics based off up, but instead switch to the pods label (typically a useful one declared in the deployment)

**Comment by woshiyjs123** [comment]
> You really should move away from pushgateway and use Prometheus relabeling for this use case.
> 
> Don't do your metrics based off ip, but instead switch to the pods label (typically a useful one declared in the deployment). You can use the pod ID to tell appart the instances instead of IP.

thank you very much, i will try it.

**Comment by woshiyjs123** [comment]
> You really should move away from pushgateway and use Prometheus relabeling for this use case.
> 
> Don't do your metrics based off ip, but instead switch to the pods label (typically a useful one declared in the deployment). You can use the pod ID to tell appart the instances instead of IP.

i think  about your idea a good while, but also can't got what i should do. 
prometheus relabeling only can be used to change the metrics, but can't solve my problem. i want to delete the prometheus data from destoryed pods.

**Comment by mweirauch** [comment]
Regarding the metrics of gone pods remaining in Pushgateway, you can set the shutdown-operation in your Spring-Boot application which shall be performed on application shutdown. You can set it with the following property: ` management.metrics.export.prometheus.pushgateway.shutdown-operation`; options are `none` (default), `delete` and `push`. You want `delete` in your case. Remember though, that there is no guarantee, that the pod is terminated orderly and thus it might be it can't send the delete operation to the Pushgateway and thus a stale entry will remain. (You can clean up stale entries in Pushgateways UI, likely via its API.)

Nevertheless as @checketts already pointed out, you should really switch your Prometheus scrape configuration to [kubernetes_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config) so that Prometheus can discover pods via the k8s api-server instead.

**Comment by woshiyjs123** [comment]
> Regarding the metrics of gone pods remaining in Pushgateway, you can set the shutdown-operation in your Spring-Boot application which shall be performed on application shutdown. You can set it with the following property: ` management.metrics.export.prometheus.pushgateway.shutdown-operation`; options are `none` (default), `delete` and `push`. You want `delete` in your case. Remember though, that there is no guarantee, that the pod is terminated orderly and thus it might be it can't send the delete operation to the Pushgateway and thus a stale entry will remain. (You can clean up stale entries in Pushgateways UI, likely via its API.)
> 
> Nevertheless as @checketts already pointed out, you should really switch your Prometheus scrape configuration to [kubernetes_sd_config](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kubernetes_sd_config) so that Prometheus can discover pods via the k8s api-server instead.

thank you, i got it.
