### ISSUE TITLE
http.server.requests : MAX property settled to 0

### ISSUE THREAD

**Issue by romilptl** [micrometer-metrics/micrometer#1587]
I am using Spring Boot 2.1.4 and added actuators and configured Spring Boot Admin which works fine. I am using `/metrics/http.server.requests` to get the details about endpoints. From that, we get MAX property which indicates the max time taken by the endpoint to be execute. As discussed here [here](https://stackoverflow.com/questions/57247185/spring-boot-actuator-max-property) is set back to 0 after an interval of **2 minutes.** 

Question:
**How can I prevent or change the time for MAX to be set back to 0?
Now, in metrics http.server.requests has been replaced by http.client.requests which does not show my requests in Spring Boot Admin, how can I use http.server.requests**

**Comment by checketts** [comment]
That StackOverflow question is confusing and doesn't seems to answer the question, but rather has some guesses involved. I also checked and the docs don't document this very clearly (that I could find).

MAX is intended to show the outlier and worst case measurement in a timeframe. Some other metrics libraries would display a MAX that was the highest the system had ever seen (since the JVM had been started). However that become less useful if the JVM is running for days and weeks since you wouldn't know how close to the MAX the code is hitting.

So in MicroMeter the MAX is a rolling MAX by window. If it shows 1 sec, then that mean the slowest measurement in that minute took 1 sec. And if it displays 0 then it means it had no measurements in that minute.

Regarding your question of `http.server.requests` and `http.client.requests` are 2 separate metrics. Server requests are requests that have be received. Client requests are how many requests have been made by your code using RestTemplate.

Since this isn't an actionable issue, let's move this discussion to Stack Overflow. feel free to post the link to further questions here.

**Comment by shakuzen** [comment]
> I also checked and the docs don't document this very clearly (that I could find).

@checketts Shall we open an issue to improve the docs?

**Comment by romilptl** [comment]
@shakuzen [DistributionStatisticConfig ](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/DistributionStatisticConfig.java)has `.expiry(Duration.ofMinutes(2))` which sets the measurements to 0 if there is no request has been made in between expiry time or rotate time. Do I am going in the right direction? 

If yes, How can I change the duration of expiry?

**Comment by izeye** [comment]
@shakuzen I created https://github.com/micrometer-metrics/micrometer-docs/pull/101 to improve the docs based on @checketts's comment.

**Comment by checketts** [comment]
Thanks @izeye!

**Comment by romilptl** [comment]
Thanks @izeye for updating the docs. We have to change `.expiry(Duration.ofMinutes(2))  ` in DistributionStatisticConfig class explicitly for a custom time window. Is it right? Is there any other way to change that time window?

**Comment by izeye** [comment]
@romilptl It seems so. If you change the value, it'll also affect other distribution statistics like percentiles as you can see its Javadoc.
