### ISSUE TITLE
@Timed get metric with `_total` or retrieve number of requests in a time interval

### ISSUE THREAD

**Issue by sbilello** [micrometer-metrics/micrometer#1615]
Hello!

By default `@Timed` is able to show the metric with `http_server_requests_sum` and `_count`. The latency is computed with `my_metric_sum/my_metric_count` but how can I get the `_total` [?](https://www.innoq.com/en/blog/prometheus-counters/) 
I would like to know if it is possible to use the above metrics to get the number of requests in a time interval.
If I use the `increase` function on `http_server_requests_count` I don't see a growing time series but it goes up and down like a gauge

**Comment by shakuzen** [comment]
This is largely a Prometheus question, so I'd defer you to [their documentation](https://prometheus.io/docs/prometheus/latest/querying/functions/#increase) and support. `increase` going up and down is expected, since it only tells you the increase each interval. `sum_over_time` (see [its documentation](https://prometheus.io/docs/prometheus/latest/querying/functions/#aggregation_over_time)) might be what you're looking for, but I would caution that you should not expect the total count to be exact. As an example of when the count in Prometheus may not have all increments, since Prometheus is pull-based, there could be increments between the last successful scrape and when an application shuts down, which would not be counted in the data in Prometheus.
