### ISSUE TITLE
The use of Gauge is not friendly

### ISSUE THREAD

**Issue by pangxljc** [micrometer-metrics/micrometer#1653]
Why does the method of Gauge.builder() not return an Object of Gauge, and then call Gauge's method to perform the indicator operation?
I think this is a more friendly way.Will you consider improving?

**Comment by checketts** [comment]
Can you please add a snippet of code demonstrating what you have in mind? Also please keep in mind we don't want to break current code usage.

**Comment by shakuzen** [comment]
@pangxljc as @checketts requested, could you provide sample code of what it looks like to do what you want now and with your proposed change? I'm not understanding the request right now.

**Comment by felipegasparini** [comment]
I think @pangxljc mentions the fact that currently the Gauge is "pull" based instead of "push" based. So one has to pass a lambda to it and hold the reference of the value so it is not garbage collected and your gauge stops working.

This is a different approach from how Prometheus client implements a gauge (https://github.com/prometheus/client_java#gauge). With Prometheus client you create a Gauge object, keep a reference to it and whenever you need, you update its value (that is why I call it push based, since value is pushed to the gauge).

The current implementation, IMO, covers all use cases, but for some use cases are way simpler with a push based Gauge, one example are scheduled tasks. Ex: 

```java
// having a Gauge that allows to set value
public class Job extends Thread{
    private final Gauge lastRunGauge = MeterRegistry.gauge("job.last_run");
    public void run(){
        while(true){
            // do something
            lastRunGauge.setValue(System.currentTimeMillis()); // or even better (no need to hold reference for gauge): MeterRegistry.gauge("job.last_run").setValue(System.currentTimeMillis());
            Thread.sleep(10_000);
        }
    }
}

// using current Gauge
public class Job extends Thread{
    // if one doesnt use atomic reference, the captured value in the lambda may be garbage collected and gauge will stop working
    private final AtomicReference<Long> lastRunTime = new AtomicReference<>(0);
    public Job(){
        MeterRegistry.registerGauge("job.last_run", (x)-> {
            lastRunTime.get();
        } )
    };
    public void run(){
        while(true){
            // do something
            lastRunTime.set(System.currentTimeMillis());
            Thread.sleep(10_000);
        }
    }
}

```

**Comment by shakuzen** [comment]
@felipegasparini thank you for the details.

> With Prometheus client you create a Gauge object, keep a reference to it and whenever you need, you update its value

Instead of keeping a reference to a Gauge object, you keep a reference to a backing atomic Number (e.g. `AtomicLong`), which doesn't seem to be more of a pain but I can see how it may be unfamiliar. If some object you already keep a reference to has a method to calculate what you want to gauge, you don't need to keep an extra reference at all, which seems better in that case, and not worse in the other case.

> ```java
> // or even better (no need to hold reference for gauge): MeterRegistry.gauge("job.last_run").setValue(System.currentTimeMillis());
> ```

Indeed this kind of one-liner isn't available now. It would probably be hard to add something like this, keep compatibility, and not make it even more confusing with the added overloaded `gauge` methods. I'm not opposed to reviewing suggested changes, though.

I know it was just an example, but in the case of timing task execution, it is something we already support and using that would be preferred over instrumenting each task implementation yourself. See [ExecutorServiceMetrics](https://github.com/micrometer-metrics/micrometer/blob/e6ff3c2fe9542608a33a62b10fdf1222cd60feae/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/ExecutorServiceMetrics.java). Not having to instrument yourself and getting the metrics you want is the best case scenario. Then you don't have to deal with maintaining references at all :)

**Comment by fdesu** [comment]
@shakuzen 
Thanks for the insight, though could you please explain what are the downsides of having `MeterRegistry#gauge` returning `Gauge` instead of the plain value?

I come across the usability mismatch after investing some time in using counters and timers which are pretty straightforward:
```java
meterRegistry.counter(...).increment(count); //in case of Counter
Timer.builder(name)
                //customization
                .register(meterRegistry)
                .record(duration); // in case of timers
```

When using Gauges though it is a bit of different thing, as you need to manage collection of mutable containers that record measurements.

**Comment by fdesu** [comment]
@shakuzen 
I was thinking about maybe it makes sense to introduce something like `RecordingGauge` with some kind of the `record(T)` method. I see similar pattern in `Counter` and `FunctionalCounter` as well as in `Timer` and `FunctionTimer`.

Maybe it makes sense to introduce such a type? `RecordingGauge` could possibly make use of `DefaultGauge` and could internally manage the mutable container.

**Comment by cosenmarco** [comment]
I'd like to add my point of view to the discussion.
I'm implementing right now a gauge backed by the result of some database query. The query looks like this:

```sql
SELECT count(m.id) as queueLength, m.retrycount, m.nodekey 
FROM whateverTable m 
GROUP BY m.nodekey, m.retrycount
```
The intention is to use nodekey and retrycount as tags so that I can monitor the queue size for all my nodes and get some insights on the retry counts.

Also I don't want to couple the database query operation to the gauges themselves as I want to be in control of how often the query is performed.

Also it wouldn't be practical with ca. 100 nodes and 8 possible retry counts to perform a query for every combination of tags. So it's not possible to perform the DB query within the `ToDoubleFunction` itself.

What I ended up doing was to keep a map where the keys are the combination of tags I want to use and the values are the `AtomicInteger`s which hold the values. Upon refresh I may get new values and some existing values may have disappeared, so I have to perform the following steps:
- update all counts which already existed
- set to 0 all counts which are not there anymore
- register new values to my map and to the registry as a new `Gauge`

This is awkward. I would expect that a `Gauge` backed by a strong reference would
let me fetch the referenced object (an `AtomicInteger` for example) and perform some update on it so I could write something like this without having to worry myself about holding references to the underlying information store:

``` java
 Map<ValuesMapKey, Integer> currentValues =makeDbQuery();
currentValues .forEach((key, value) -> {
   StrongGauge gauge = StrongGauge.builder("whatever_queue_length", 
         new AtomicInteger(0),   // Or better: a lambda like () -> new AtomicInteger(0) only executed when the gauge doesn't exist
         AtomicInteger::get)
      .tags(tagsFromKey(key))
      .register(meterRegistry);

   // getReference() or getStoredObject() or... whatever
   gauge.getReference().set(value);  // I don't need to worry about whether the gauges was in registry or not.
});
```

**Comment by jkschneider** [comment]
@cosenmarco Could you check out `MultiGauge` which was designed for the SQL-query-like problem?

![image](https://user-images.githubusercontent.com/1697736/81340938-acf15e80-907e-11ea-9f44-0fd4cfa90ece.png)

**Comment by cosenmarco** [comment]
@jkschneider will do. Seems quite interesting, thanks.

**Comment by joshiste** [comment]
@jkschneider ist there a way to provide a `Supplier<Iterable<Row<?>>>` to the MultiGauge? So that this supplier is called when collecting the metrics - so we don't need to actively call `register(Iterable<Row<?>> rows)` in a extra scheduled thread?

**Comment by agebhar1** [comment]
I had a quit similar use case for grouped database query result(s) described here https://github.com/micrometer-metrics/micrometer/issues/1653#issuecomment-597488635 by @cosenmarco I came up with the prototype of a `CachingMultiGauge` https://github.com/agebhar1/micrometer-caching. What did you think?

**Comment by abhi-jha** [comment]
Hey @jkschneider. What book is that snippet from?

**Comment by jonatan-ivanov** [comment]
@abhi-jha https://www.oreilly.com/library/view/sre-with-java/9781492073918/
