### ISSUE TITLE
Help Wanted : Issue with dynatrace meter registry initialization

### ISSUE THREAD

**Issue by aniketvsawant** [micrometer-metrics/micrometer#1654]
Hi Team, 

I have using spring boot 2 application, added `micrometer-dynatrace-registry` dependency and provided configuration in properties file as per the documentation with `management.metrics.export.dynatrace.enabled=true` but be default the MeterRegistry object is initializing with SimpleMeterRegistry.

Do we have any example of micrometer dynatrace with Spring boot 2.0 ?

Thanks.

**Comment by izeye** [comment]
@aniketvsawant Thanks for getting in touch, but it seems to be a Spring Boot question rather than Micrometer one. It'd be better to ask it on Stack Overflow or their Gitter. Having said that, I have [a Dynatrace integration sample](https://github.com/izeye/sample-micrometer-spring-boot/tree/dynatrace) which I created when I was looking at #1648. It seems to work except `system.load.average.1m` as described in #1648.

**Comment by aniketvsawant** [comment]
@izeye  Thanks for your quick response. It seems the issue is with spring boot version. I upgraded version from 2.0.2 to 2.2.0 and now everything is working as expected. I have gone through your sample and looks working as expected. Few more thing to do but one more question - Can we publish HTTPTracing information to Dynatrace ?

**Comment by izeye** [comment]
> It seems the issue is with spring boot version. I upgraded version from 2.0.2 to 2.2.0 and now everything is working as expected.

@aniketvsawant [Auto-configuration for Dynatrace has been added since Spring Boot 2.1.0](https://github.com/spring-projects/spring-boot/blob/d254c6271253c57383e351998ffdd97b2d385c99/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/metrics/export/dynatrace/DynatraceMetricsExportAutoConfiguration.java#L43).

> Can we publish HTTPTracing information to Dynatrace ?

I'm not sure what you mean by "HTTPTracing information".
