### ISSUE TITLE
Version 1.3.0 modifies characters of my metrics source

### ISSUE THREAD

**Issue by nyivan** [micrometer-metrics/micrometer#1664]
Hello,

I noticed that version upgrading to 1.3.0 of micrometer-core and micrometer-registry-wavefront caused micrometer to modify silently some characters of my metrics source. The examples of modified characters I found until now are '[' and ']'. Both these are being replaced by '-'. Is that expected? If so, why?

**Comment by izeye** [comment]
@nyivan Thanks for the report!

Micrometer 1.2.x is using `com.wavefront:wavefront-sdk-java` 1.6, but Micrometer 1.3.x is using `com.wavefront:wavefront-sdk-java` 1.13 which includes https://github.com/wavefrontHQ/wavefront-sdk-java/pull/95. Based on its description, it seems to be intentional.

/cc @hanwavefront

**Comment by shakuzen** [comment]
We anticipate some normalization/sanitization of names/values to match what different metrics backends allow for characters in those places. If you were able to publish your metrics to Wavefront before with those characters and use them with those characters in Wavefront before and not after, I would follow-up with the Wavefront team, as the sanitization is happening in their library, as pointed out by @izeye.
