### ISSUE TITLE
Upgrade to latest netty version

### ISSUE THREAD

**Issue by lplotni** [micrometer-metrics/micrometer#1741]
As micrometer-registry-statsd uses netty as shaded dependency there is no way to update it to newest version. The netty version included has following vulnerability:
https://nvd.nist.gov/vuln/detail/CVE-2019-16869

**Comment by checketts** [comment]
I don't think the shaded netty is handling requests so the CVE doesn't apply, right?

**Comment by lplotni** [comment]
I guess you're right, but it is still a bit annoying that it yields a high severity vulnerability while running e.g. the OWASP dependecy check.

**Comment by checketts** [comment]
I agree. And I would like it to get fixed. I just wanted to understand our exposure/urgency.

**Comment by shakuzen** [comment]
As @checketts pointed out, Netty usage in micrometer-registry-statsd does not do any HTTP handling, so this is a false positive in our case. It's in my backlog to fix #1591 but only from Micrometer 1.4. The reason for that is because the changes required will be substantial to allow us to upgrade the shaded version of reactor-netty while keeping the behavior we want.

I can appreciate the pain that having this false positive come up on reports can be, but unfortunately vulnerability checkers tend to lack the sophistication to consider usage of a dependency in determining applicability of vulnerabilities.

We will upgrade the shaded dependency once #1591 is fixed but do not have plans to backport that fix to maintenance releases due to the breadth of the change. We can leave this issue open in the meantime so others that run into this have the explanation here and can understand micrometer-registry-statsd is not actually affected by the CVE.

**Comment by stewi2** [comment]
Curious why netty needs to be shaded instead of being a regular transitive pom dependency? Because it gets really confusing when micrometer-statsd-registry is being embedded inside a shadow jar that depends on a different netty version. At least Gradle's dependency resolver is woefully unaware of the embedded netty version.

**Comment by shakuzen** [comment]
@stewi2 The build tool dependency resolver being unaware of the embedded netty version is the point of shading it. We are avoiding compatibility issues between what Micrometer's StatsD registry uses to publish metrics and what an app may or may not choose to use Netty, Reactor, and/or Reactor Netty for, including what version. For example, the version of reactor-netty used by our StatsD registry implementation may be sensitive to the version of netty used with it, but we don't want to pass along those restrictions to end users or troubleshoot what version of netty might be used at runtime - it would generally make upgrading and support more difficult than it needs to be.
