### ISSUE TITLE
file descriptors (Prometheus metric name)

### ISSUE THREAD

**Issue by danielmenezesbr** [micrometer-metrics/micrometer#175]
According to [Prometheus documentation](https://prometheus.io/docs/instrumenting/writing_clientlibs/#process-metrics), the metric name to collect file descriptors is `process_open_fds` and `process_max_fds`. Micrometer uses `process_fds_open` and `process_fds_max`

related to #170

**Comment by checketts** [comment]
The micrometer direction is intentional. There is a hierarchical naming that we are encouraging. Similar to how logging levels work. Someday (soon) I expect to have a `filter` I can set to disable metrics.

Something like:
```
metrics:
  process:
    cpu: enabled
    fds: disabled
```

The Prometheus metric name doesn't allow for this approach.

**Comment by jkschneider** [comment]
If we had [added base units](https://github.com/micrometer-metrics/micrometer/blob/716980cc7aa6a1f6941c799f86b19167fe7f67fc/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/system/FileDescriptorMetrics.java#L63) to the gauge, the Prometheus naming convention would be adding "fds" to the end anyway.

Since we should really have base units on any meter that conceptually has them in our out-of-the-box instrumentation, perhaps this forces us back to `process_open_fds` and `process_max_fds` like it is written in the Prom docs?

**Comment by jkschneider** [comment]
Fixed with 736fd95ca5a9fb9846699489877eb4021882b9df
