### ISSUE TITLE
Expose Hibernate statistics

### ISSUE THREAD

**Issue by snicoll** [micrometer-metrics/micrometer#180]
We had a [PR to expose Hibernate statistics](https://github.com/spring-projects/spring-boot/pull/3596) in Spring Boot but the move to micrometer made it irrelevant. Perhaps we would consider adding this to micrometer?

cc @mdeinum

**Comment by mdeinum** [comment]
I might have some time on my hands to migrate the original PR to work with micrometer. But I need some help getting started. @jkschneider could you give me some pointers?

**Comment by checketts** [comment]
Pointers:

* Have `HibernatePublicMetrics` implement `MeterBinder`
* Each of your `addMetrics` lines, instead of returning a result, will become a `Gauge` that return a single measurement.

For example:
```
addMetric(metrics, prefix + "sessions.open", stats.getSessionOpenCount());
```
Would be something like
```
Gauge.builder("hibernate.sessions.open", stats, stats -> stats.getSessionOpenCount())
  .tags("entityManagerFactory", emfName)
  .register(registry);
```
Check out the [GuavaCacheMetrics](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache/GuavaCacheMetrics.java) for comparison

**Comment by mdeinum** [comment]
Pull request created. I'm of course open to comments :). 

I had doubts about using a `Counter` or a `Gauge` and we also have some execution times in there should that be a `TimeGauge` or ... ?
