### ISSUE TITLE
ElasticMeterRegistry should allow indexType override

### ISSUE THREAD

**Issue by magaton** [micrometer-metrics/micrometer#1891]
Currently, for ES versions < 7, indexType is hardcoded in TYPE_PATH_BEFORE_VERSION_7 static variable.
It would be good to have a way to override the indexType, so it can be something other than 'doc'

**Comment by shakuzen** [comment]
As a note for future planning, once we no longer support Elasticsearch versions less than 7, we should remove this configuration option.

**Comment by shakuzen** [comment]
I think we made a mistake when we made this a method on `ElasticMeterRegistry` instead of a method in `ElasticConfig` and use that in `ElasticMeterRegistry`. I'd like to change that before releasing 1.4, so I am reopening this. In fact, we had a change for that already (#1328) that I missed when reviewing this issue and corresponding pull request.
