### ISSUE TITLE
Usage of `numThreads` parameter 

### ISSUE THREAD

**Issue by poznachowski** [micrometer-metrics/micrometer#1900]
What I see in `PushRegistryConfig` interface is a `numThreads` parameters (that defaults to 2):
https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/push/PushRegistryConfig.java#L50

However, it seems that it's not used at all (and never was - as far as I see):
https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/push/PushMeterRegistry.java#L67

The ScheduledExecutorService is using a single thread. You could you please clarify that?

I found it, while seeking the best approach to provide business metrics basing on SQL queries, that may take some time to execute. I hoped that I could use this parameter to parallelize retrieving Gauge values (SQL executions). I know that's out of scope (of the submitted issue), but could you provide any recommendations for my case? It seems that managing scheduled executor myself and create Gauges around calculated values is the best option.

**Comment by jkschneider** [comment]
It was a holdover originally from `AtlasConfig`, which is maintained in the Spectator project. Micrometer doesn't use this anywhere AFAIK.

Concerning parallelizing SQL queries... 

> It seems that managing scheduled executor myself and create Gauges around calculated values is the best option.

This is definitely the best option in your case. In general, Micrometer's view of gauges is that their values are updated precisely when the gauge value is retrieved (at metrics publishing). But since you may conclude that your SQL queries are expensive and should run less frequently than the metrics publishing interval, then updating an intermediate value tied to the gauge on an interval that you determine is a good idea. You're effectively trading off mean-time-to-resolution for query impact.
