### ISSUE TITLE
Why are counter's double value and not long (and latencies, etc. etc.)

### ISSUE THREAD

**Issue by deanorderly** [micrometer-metrics/micrometer#1925]
Typically, in finance, long is used and values are in pennies and in time, long is used.  Why doubles in the Counter?  Because of double and rounding, it's never exact on the processor and even JUnit makes you do this

Assert.assertEquals(1.0, counter.count(), 0.1);

they used to have Assert.assertEquals(1.0, counter.count()); but that's deprecated because it doesn't work much of the time.

I guess this is a request to have everything in long...even guages can be in long and someone could convert any thing they want by a multiplier to long if they need it(after all, double for the gauge is not exact either).

**Comment by checketts** [comment]
> Originally posted: https://stackoverflow.com/questions/58068832/why-is-a-counter-a-double-and-not-a-long

There are several reasons that counters are doubles instead of longs. As with any architecture it balances the tradeoffs.

# Maximum compatibility with underlying metrics libraries

Micrometer is a facade over other metrics frameworks and `double` is the most versatile option.

Prometheus for example uses a double for its counters and by sticking with the same type, it maximizes compatibility. 

As a further reason for why Prometheus uses `double`s is to treat all metrics the same internally, simplifying its architecture and optimizing its performance and memory utilization. Though that a different topic for discussion.

# Measuring partial changes

While most counter uses are incrementing single events. Counters are still a viable choice when measuring other things like bytes received, rows processed, etc. While none of these example are partial counts. It doesn't stop a user from coming up with a usecase where they want to measure partial counts. One example might be 'seconds spent processing', since partial seconds is very common with computing. Some systems measure whole units like milliseconds or nanoseconds instead, let's cover that next.

# Maximum precision

The double type gives more precision. While this might sound counter-intuitive, bear with me. Some durations that could be measured in a counter would be total time spent performing some task. Garbage collection, DB processing, etc.  Some of those events take nanoseconds. While I wouldn't recommend Micrometer as a replacement for a profiler, measuring small time units would cause confusion (see [Who Wants Seconds](https://www.robustperception.io/who-wants-seconds) where a Prometheus engineer explains this reasoning further)

If a registry were to standardize on nanoseconds for all measurements, those orders of magnitude that a `long` (9 quintillion in a long versus 9 quadrillion in a double) would use up the extra precision of the long anyways.

You'll note that Micrometer uses doubles to measure total duration in timers and the beauty of that metric is that is is actually a counter in its core (a monotonically incrementing number).

# A double is plenty large

I recall doing some rough math and if a counter is measuring single events, that means it could be measuring 10,000 events every second for over 20,000 years and not begin to lose precision. 

So there certainly are limitations that are good to be aware of, but given the expectations of needs of the system `double` is quite sufficient.

**Comment by deanorderly** [comment]
@checketts 

Hmm, I wanted to do 
			    .publishPercentiles(0.95, 1.0)
BUT 1.0 could end up being .999991 not 1 for max percentile.  This should also be integer or it actually will round and not get the max value that I want.  This actually could break due to rounding if enough requests go through it.  The above should be scale of 0...100 instead for best accuracy.
 
next, 1 by 1 these have been proved wrong by others(added below).  Here is the list I have seen previously and I remember a document at twitter on this regarding stats as well.

"Maximum compatibility with underlying metrics libraries" ->  This one I really don't understand at all. A long can be converted to a double much easier than the other way around(to be compatible with prometheus).  in fact, it doesn't work the other way due to rounding.  it is broken and reports the wrong value.  Sure, they may have had to provide a divisor like some int or something BUT that could be done in a filter easily enough for different underlying systems

"Measuring partial changes" -> This is just wrong since a long can measure partial changes...you just have to know the denominator.  The finance industry has proven this well with fractions of a dollar or even a penny AND they can't be off due to rounding!  So in finance, they count pennies or sometimes they may count even smaller but it's still a long so that it's exact and not rounded.

"Maximum precision" -> Both long and double are 8 bytes.  They are trying to say they can store MORE in a double that is 8 bytes than an 8 byte long.  I don't see how that is possible?  Actually a long has 'more' precision than a double.

"A double is plenty large" -> Ok, sure, and a long is larger.  

For reference, the 8 bytes used in java are https://www.quora.com/How-is-a-float-or-double-value-stored-in-memory-in-java

**Comment by deanorderly** [comment]
ps. I do realize that would be a HUGE change from where you are now btw.  It is just something that would be VERY VERY nice to figure out and slowly move to over time.  We represent all 'partial' stats as a long still sometimes, on a scale of 0 to 100 in a long as well.  

At the lower level of integration with a system that does doubles, one can provide a divisor to get into a double for 'all' timers and perhaps a divisor per other type of partial metric wanted(ie. very special case since many can represent a partial on a scale of 0 to 100,000 if they want in a long).  I would make the filters or something do something here so it's a configure once per 'type'...but that would also have max portability AND be accurate as well on top of that.

Anyways, this is just something to consider (long-term request).

**Comment by jkschneider** [comment]
> .publishPercentiles(0.95, 1.0)
BUT 1.0 could end up being .999991 not 1 for max percentile. This should also be integer or it actually will round and not get the max value that I want. This actually could break due to rounding if enough requests go through it. The above should be scale of 0...100 instead for best accuracy.

@deanorderly This is technically correct, but I struggle to buy into the harm. From the perspective of monitoring for availability, we're saying a chart could present an incorrect notion of the 100th percentile for a single maximum sample some high 9 value. In most cases, pre-computed percentiles aren't even really all that useful in the first place. And micrometer always ships a max for summaries and timers which is equivalent to the 100th percentile anyway.

Tradeoffs abound in libraries such as these. I take the support for partial increments (for units of measure that don't have integral bases like temperature) as more valuable than rounding risk?

**Comment by deanorderly** [comment]
"Tradeoffs abound in libraries such as these."  VERY TRUE.  

It is really just a side-thought of "man, it would be really nice instead of all testing having to do is the number between .9 and 1.1".

After all, Junit deprecated the equals(double, double) in favor of something that works 100% of the time with a (double, double, rangeValue)

Dean

**Comment by jkschneider** [comment]
Indeed, or AssertJ's mechanism:

```java
assertThat(c.count()).isEqualTo(2.0, offset(1e9))
```

I don't see how we can practically change this decision at this point, so I think I'll close this. Happy to consider further if any other ideas come up.

**Comment by deanorderly** [comment]
yup, that's fine.  yeah, this change would literally have to be a breaking release and too many people are using it already.
