### ISSUE TITLE
NewRelicClientProvider implementations not using NamingConvention configured via Builder

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#1958]
The configured `NamingConvention` from the Builder is not passed to the NewRelicClientProvider implementations, so the default `NewRelicNamingConvention` is always used.

**Comment by neiljpowell** [comment]
@shakuzen The implementations use the default just like the NewRelicMeterRegistry.  NamingConvention hasn't been exposed as a construction/builder option in previous versions, so the effect is the same.

**Comment by shakuzen** [comment]
> NamingConvention hasn't been exposed as a construction/builder option in previous versions, so the effect is the same.

I'm wondering whether exposing it at all was a mistake (see https://github.com/micrometer-metrics/micrometer/pull/1957#issuecomment-607058490) without a request from users to be able to customize it. We're ending up with multiple places to pass things which requires understanding about which will eventually be used. If we are exposing it, though, users would expect it to have the intended effect.

**Comment by neiljpowell** [comment]
Yep, understood. I was just pointing out that it's not actually a bug but I'm happy to help with the update to expose it now or for 1.5.  If I recall, there are other MeterRegistry implementations that also don't expose NamingConvention, which could be due to a strict preference of their target backends.  

Speaking of another possible oversight, it would be good to expose the underlying HttpUrlConnectionSender proxyHost and proxyPort options all the way to the NewRelicConfig.  It's needed for anyone using the API implementation in an environment without open Internet access.  We could do this and exposing NamingConvention for 1.5.

**Comment by shakuzen** [comment]
The `namingConvention` is already a method on the Builder from 1.4.0, which is what caused me to notice and open this issue https://github.com/micrometer-metrics/micrometer/commit/5d5617ded1975298f9ed9ea4972f07fe31a4c313#diff-d8e6a06ddbf45f53edb233b7b4729cfcR127-R130

**Comment by shakuzen** [comment]
Release notes should mention the removal of the constructor with NamingConvention from public API - it was a mistake this constructor was ever included in public API.
