### ISSUE TITLE
Provide an API to build a default WavefrontSender based on WavefrontConfig

### ISSUE THREAD

**Issue by snicoll** [micrometer-metrics/micrometer#1965]
`WavefrontMeterRegistry` can be built using a `WavefrontSender` or without one. If none is provided, a default instance is created based on the current configuration.

Spring Boot could use a public API for the latter as we'd like to expose a `WavefrontSender` bean and back off if the user has provided one.

This relates to #1964 as well as we'd like to make sure a direct API cal without an API token leads to a failure as it used to.

**Comment by snicoll** [comment]
One more though. `WavefrontDirectIngestionClient.Builder` has some interesting settings Spring Boot may want to expose as  configuration properties.

If that makes sense (i.e. the type of the default `WavefrontSender` is always going to be a  `WavefrontDirectIngestionClient`) then it would be nice if Micrometer would initialize a builder for us. 

If we don't have that guarantee, then let's stick with a method that return the interface.

**Comment by shakuzen** [comment]
> If that makes sense (i.e. the type of the default `WavefrontSender` is always going to be a `WavefrontDirectIngestionClient`) then it would be nice if Micrometer would initialize a builder for us.

I see there is a `WavefrontProxyClient`, but since recent versions of the Wavefront proxy can accept HTTP traffic, I'm not sure there is a reason to use that anymore. There's also a `WavefrontMultiClient` but I don't know how common its use is, and doesn't seem like something we need to provide a convenience API for. @panghy any insight on this?

**Comment by panghy** [comment]
The multi-client is mainly for sending data to multiple wavefront backends, we shouldn't configure that by default. As long as the user can supply their own WavefrontSender that'd be fine.

We are in the process of deprecating the proxy client since sending metrics on sockets is just not reliable and new proxies can accept HTTP traffic on the same port. The only thing is that to report to the proxy via HTTP, you wouldn't need an API token (and it would be http and not https).
