### ISSUE TITLE
Consider graduating Stackdriver integration from Incubating status

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#1991]
We [added support for Stackdriver in 1.1.0](https://github.com/micrometer-metrics/micrometer/issues/474), and we have [adjusted and fixed multiple issues for it](https://github.com/micrometer-metrics/micrometer/issues?q=label%3A%22registry%3A+stackdriver%22+). I am seeking feedback from users of the `StackdriverMeterRegistry` if they think it is at a level of stability and feature-completeless to warrant promotion from Incubating status. Please share your experience and thoughts either on the Micrometer Slack or as a comment on this issue. Thanks.

**Comment by jkschneider** [comment]
For a historical note: the main reason it was released initially as incubating is because Stackdriver didn't allow dimensional aggregation of "custom" metrics, i.e. anything that doesn't originate from the platform, i.e. anything coming from Micrometer.

It seemed like there was a need for some sort of API to declaratively specify what kinds of aggregations you would need _up front_ in the app. Maybe, for example, sum all `http.server.requests{uri="/foo", outcome=SERVER_ERROR}` regardless of the value of the `exception` tag. Separately sum all `http.server.requests{uri="/foo"}`. Then you could actually accomplish a Stackdriver rendering of error ratio for the "/foo" endpoint.

It's unfortunate in a way because it requires so much _a priori_ knowledge of how you'll want to later aggregate the data. And because this is being done on a per-instance level, there's still no way to get the cluster-wide error ratio for "/foo" unless you simply don't ship the instance id as a tag (or maybe as part of the declarative thing you have to specify to publish both time series with and without instance id).

**Comment by amohabir** [comment]
It seems stable enough for us in production, but there is one caveat since we're running multiple services on the same project. There is a maximum amount of 500 metric descriptors that you can create per project. The current implementation can be quite inefficient due to creating a metric descriptor per timer and percentile for example. So for example a timer with a configuration to send p50, p95, p99 and max will already cost you 4 metric descriptors. Multiply this with the amount of timers and services and it will add up. Would be much nice to add an option to send the percentile metrics based on a percentile tag for a single timer.  

See also: https://cloud.google.com/monitoring/quotas#custom_metrics_quotas

**Comment by shakuzen** [comment]
> So for example a timer with a configuration to send p50, p95, p99 and max will already cost you 4 metric descriptors.

Wouldn't it be better to enable percentile histogram and calculate the percentiles in Stackdriver from the distribution we send?

**Comment by amohabir** [comment]
From what I remember, the percentile histogram integration isn't working properly, since the input for the histogram expects bins, which aren't available in the Micrometer gauge object.

**Comment by shakuzen** [comment]
Please try with the latest version of Micrometer and open a new issue if it isn't working. When percentile histogram is enabled, we send a Distribution type to Stackdriver.
