### ISSUE TITLE
long shot feature request(nice to have)

### ISSUE THREAD

**Issue by deanorderly** [micrometer-metrics/micrometer#1995]
It would be SUPER nice if MeterRegistry implemented an interface.  interfaces make it much easier to swap in/out so it would be MUCH more like slf4j in that I could have my own implementation.

of course, then methods should return interfaces to Counter, etc. etc. so I can implement those as well.

anyways, long shot.

**Comment by shakuzen** [comment]
You can already make your own implementation of `MeterRegistry`, similar to any of the ones maintained by the Micrometer team. What are you not able to achieve by doing that?

**Comment by deanorderly** [comment]
@shakuzen it brings in a bunch of classes references by the class MeterRegistry causing performance degradation (less classes is better for startup in serverless).  There is a bunch of code in MeterRegistry AND in the classes it returns as well like Builders that would go unused.  typically you want biz logic interfaces so I can strip out all impl classes.

personally, I use a com.xxxxxxxx.api every time to create a clear api that can be implemented without dragging along my implementation classes (and when I can create a jar for that api....though not always as sometimes I stick the api packages in the same project which of course can be dangerous due to human mistakes).

**Comment by jkschneider** [comment]
Once upon a time `MeterRegistry` started as an interface. There were some reasons that it settled eventually as an abstract class, mainly because there are parts of the contract we need implementors to honor but don't want user facing (e.g. `protected` access), and parts of the contract that simply needed to be guaranteed without a ton of duplication (like the ordering of meter filter acceptance and transformation, locking, etc.).

At this point, in the 1.x line we can't make the abstract class `MeterRegistry` an interface because even if it were achievable it would break binary compatibility.

> it brings in a bunch of classes references by the class MeterRegistry causing performance degradation (less classes is better for startup in serverless)

The moment you bring in a concrete implementation, you bring in any classes (builders, etc.) that belong to it, so the only way we bring in _less_ classes is if one or more of the following happen...

1. Concrete implementations of `MeterRegistry` never have static inner builder classes, i.e. the builder is a top-level class distinct from the registry implementation. Your app only doesn't load the builder class if it doesn't use the builder.
2. Meter types never have static inner builder classes, but such builders must be distinct top-level classes, e.g. `CounterBuilder`? You only don't load these classes if _nowhere_ in the application stack is a meter builder used. Meter builders tradeoff instrumentation verbosity for detail (description text, base units, min/max expected values, etc.). Most low-level libraries like frameworks or client libraries will choose higher verbosity for better detail, as they should.

The only alternative solution to (1) is to expose public constructors for each registry implementation that take the range of all options the builder takes, and perhaps a combinatorial explosion of such constructors with defaults.

The only alternative solution to (2) is to expose overloads on the `MeterRegistry` "interface" to accept the full range of options the meter builder can take.

API design always involves tradeoffs.

* If we expose overloads to accept the full range of options meter builders can take, we allow low-level library authors to publish rich metrics at the expense of more method overloads being suggested by IDE completion for higher-level app developers.
* If we expose a range of constructors on each registry implementation, we _suggest_ to the end user that there is no builder, an API discoverability problem.
* The meter overloads on `MeterRegistry` suggests the lack of a meter-specific builder, another API discoverability problem.

Even if we did all of this, and up and down the stack everybody perfectly optimized for not using builders to limit the number of loaded classes, what will we have achieved? I think at most:

`total(registries) + total(meter types) = total(registries) + ~10` classes?

I don't find saving 10-12 loaded classes being worth the cost of all these API usability problems, serverless or not.

**Comment by jkschneider** [comment]
> MUCH more like slf4j

I think we should appreciate where SLF4J simply isn't the same thing. Loggers are stateless, single-type telemetry. Micrometer may strive to be like it in the sense that it is a facade, but the analogy will never be perfect.

**Comment by deanorderly** [comment]
it would have been a nice to have.  you can close it though.

**Comment by jkschneider** [comment]
> it would have been a nice to have

Agreed. I wanted it too. Just too many tradeoffs in the end.
