### ISSUE TITLE
dynamic set of Tags support (feature nice to have)

### ISSUE THREAD

**Issue by qyc-dd** [micrometer-metrics/micrometer#1996]
Wavefront does support different set of tags for the same metric.
I understand there is a limitation of prometheus that it doesn't allow different set of tags.
Is it possible that we can disable that validation controlled by a parameter?

It is not possible that for every metric we can well define all the tags before hand. And we're constantly changing the names of metrics all the time due to adding new tags.
This would be a great feature nice to have and for better control.

Thanks.

**Comment by jkschneider** [comment]
@qyc-dd Micrometer doesn't actually perform this validation, and does in fact allow for different tags for the same metric name.

For all out-of-the-box instrumentation we try to ensure consistent tags for maximum _portability_, and because we know Prometheus is popular. But the contract doesn't require it. My hope is that eventually Prometheus drops this requirement, though I'm not holding my breath.

**Comment by akibabu** [comment]
I'm not 100% sure this is the same question but.

@jkschneider Is it a requirement in Prometheus?
We are now running a patched version removing this piece of code and it seems to be working fine.
Both scraping the actuator endpoint and the Pushgateway client.

Inspired by this answer https://github.com/micrometer-metrics/micrometer/issues/877#issuecomment-651356213

But that answer creates a new Collector for each set of tags (and by that a Prometheus TYPE/HELP group) which works for the actuator but returns a 400 from the pushgateway. Instead we reuse the collector for a name and add let the original code add children.
