### ISSUE TITLE
Micrometer BOM missing jersey2 entry

### ISSUE THREAD

**Issue by dreis2211** [micrometer-metrics/micrometer#2012]
Hi,

I just found that the latest BOM snapshot under https://repo.spring.io/libs-snapshot/io/micrometer/micrometer-bom/1.5.0-SNAPSHOT/micrometer-bom-1.5.0-20200421.014352-46.pom is missing the entry for jersey2. I was wondering if that was on purpose?

Cheers,
Christoph

**Comment by shakuzen** [comment]
Sorry for the inconvenience. We're a bit blocked waiting for resolution of [MVNCENTRAL-5714](https://issues.sonatype.org/browse/MVNCENTRAL-5714), since our build fails to resolve a 2.x version of the jersey-server dependency. It seems @jkschneider removed micrometer-jersey2 from the build in https://github.com/micrometer-metrics/micrometer/commit/30f6f8ea787d33d181562f50a11fefe41f921a06#diff-88b7c47e47b8ee65263b6784b86fa0a7R4. We'll restore that once the Maven Central issue is resolved.

**Comment by dreis2211** [comment]
Thanks for the fast reply. I can't access the JIRA issue, unfortunately. Any indication if this is gonna be solved soon? This is breaking Spring-Boot builds for example, at the moment.

**Comment by shakuzen** [comment]
I've just committed a workaround (534ad04) that should get things back to how they were before (from a micrometer consumer perspective). I suspect the Central issue will take some time but not sure how much - could be hours, could be days.

**Comment by dreis2211** [comment]
Highly appreciated.
