### ISSUE TITLE
MeterRegistry.gauge not returning value reference of already existing Gauge 

### ISSUE THREAD

**Issue by dmaiman80** [micrometer-metrics/micrometer#2024]
When running the following code:

```java
public void testGauge(MeterRegistry meterRegistry) {
   // Creating the Gauge
   AtomicInteger value1 = meterRegistry.gauge("myTestGauge", new AtomicInteger(0));

   // Getting the same Gauge
   AtomicInteger value2 = meterRegistry.gauge("myTestGauge", new AtomicInteger(1));

   value1.set(2);
   value2.set(3);

   System.out.println(meterRegistry.get("myTestGauge").gauge().value());  
}
```

I get a value of 2 - when I would expect a value of 3.

It appears that the underlining code for meterRegistry.gauge checks to see if the Gauge already exists and if so uses that Gauge in the code internally. However, the method always returns the reference object you pass in - while not updating the Gauge's reference.
Wouldn't this be problematic when actually calling value2.set(3). Wouldn't that set not get monitored - as no Gauge is technically referencing it?

It would be nice to have a method where we present a value if the Gauge is not present. If the Gauge is present, it should just return back the reference object for the Gauge.

Thanks,
-Dave

**Comment by shakuzen** [comment]
> Wouldn't this be problematic when actually calling value2.set(3). Wouldn't that set not get monitored - as no Gauge is technically referencing it?

Correct, but why are you calling `value2.set(3)` instead of `value1.set(3)` when that's the one you initially registered the gauge with?

If a meter is already registered, registering it again will not change it. I can see how the behavior here is confusing but there's no point in registering the same gauge twice - use the first state object. This is a convenience method so that you can instantiate and assign the value object on the same line. What is the use case to do something like the example instead of just update via `value1`?

We could change it to behave the way you're expecting, but that would be a behavior change and the current behavior is mentioned in the JavaDoc for the method.

**Comment by pan3793** [comment]
I'm also confusing with such behaviors. Gauge in micrometer has significant difference comparing to dropwizard and prometheus.

Gauge in prometheus provides convenient `inc` and `dec` methods, and dropwizard has the similar stuff but named counter. Since counter in micrometer should keep monotonous, so I'm trying to use gauge to trace something which can up and down, and the my expected API is

- when create a user, `MetricsTool.gauge("user", "level", "3").inc(1)`
- when delete a user, `MetricsTool.gauge("user", "level", "3").dec(1)`

So far, I didn't find a easy approach to get such implementation.

Here is one approach that I have tried, but failed because the `Metrics.gauge` behavior mentioned by this issue.
```
  def dec(name: String, tags: String*)
         (value: Double = 1.0): Unit = metrics { ms =>
    ms.registry.gauge(name, Tags.of(tags: _*), new AtomicDouble).addAndGet(-value)
  }
```
Further, such implementation don't use strong reference so the ref `AtomicDouble` will disappeared after GC.

Would you like give me some advices? @shakuzen

**Comment by gdomo** [comment]
@shakuzen Consider following code:

```
AtomicInteger myGauge = meterRegistry.gauge("myGauge", new AtomicInteger(0));
myGauge.set(1);
```


Looks valid? Yes, absolutely typical usage. But with current behavior it could be non working due to previous  `.gauge("myTestGauge")` call.

Any workaround?

**Comment by shakuzen** [comment]
> But with current behavior it could be non working due to previous `.gauge("myTestGauge")` call.

@gdomo I'm not understanding the connection to such a call and the preceding sample code. If the meter name is different, they will be different meters. So there is no conflict with an existing meter of a different name.

**Comment by shakuzen** [comment]
> Further, such implementation doesn't use strong reference so the ref `AtomicDouble` will disappeared after GC.
> 
> Would you like give me some advices?

@pan3793 I would suggest checking [this section](https://micrometer.io/docs/concepts#_manually_incrementing_or_decrementing_a_gauge) in the reference documentation. If you have ideas on how we could improve the documentation so it is more understandable, please open an issue or pull request to the [micrometer-docs](https://github.com/micrometer-metrics/micrometer-docs/) repository.

There are many ways you could implement the kind of thing you're asking for and it depends on your code structure what makes the most sense. Here's a quick sketch of one way that might make sense:

```java
class LoginService {
    private final AtomicInteger loggedInUsers;

    LoginService(MeterRegistry meterRegistry) {
        this.loggedInUsers = meterRegistry.gauge("users.loggedIn", new AtomicInteger());
    }

    public void logIn(User user) {
        loggedInUsers.incrementAndGet();
        // do stuff
    }
    
    public void logOut(User user) {
        loggedInUsers.decrementAndGet();
        // do stuff
    }
}
```

**Comment by julianrschmidt** [comment]
Maybe we can provide a need to register more than once. We are using the gauge builder with an object reference and a function to be called on that object. The trouble we are having is that the object reference is itself subject to change due to context switches (in a Kafka streams application), that we do not control. We therefore have to update the reference to that object inside the gauge. Our workaround (see code below): Whenever there is a context switch, we search for the gauge in order to check whether it has already been registered, delete it if that's the case, and register the gauge again with the new reference. This works, but is a bit cumbersome. We would greatly appreciate it, if there was a way to simply reregister a gauge with a different object reference.

```
private <T> void registerGauge(String name, T obj, ToDoubleFunction<T> f, String description, Iterable<Tag> tags) {
        Gauge gauge = meterRegistry.find(name).gauge();
        if (gauge != null) {
            meterRegistry.remove(gauge);
        }

        Gauge.builder(name, obj, f)
                .description(description)
                .tags(tags)
                .register(meterRegistry);
    }
```

**Comment by jonatan-ivanov** [comment]
@julianrschmidt You can wrap your KafkaMetric or any other "state" object into an `AtomicReference` and pass that to your Gauge; this would enable you to replace the object that provides the value for you.

```
AtomicReference stateRef = new AtomicReference(new State());
Gauge
    .builder("test.gauge", stateRef, ref -> ref.get().getValue())
    .register(registry);
```

You can get your state object by `stateRef.get()` and replace it by `stateRef.set(new State())`.
Btw Micrometer does support KafkaMetrics (and Kafka removing the references is a pain), I recommend you to check it.

**Comment by lukass77** [comment]
> > Further, such implementation doesn't use strong reference so the ref `AtomicDouble` will disappeared after GC.
> > Would you like give me some advices?
> 
> @pan3793 I would suggest checking [this section](https://micrometer.io/docs/concepts#_manually_incrementing_or_decrementing_a_gauge) in the reference documentation. If you have ideas on how we could improve the documentation so it is more understandable, please open an issue or pull request to the [micrometer-docs](https://github.com/micrometer-metrics/micrometer-docs/) repository.
> 
> There are many ways you could implement the kind of thing you're asking for and it depends on your code structure what makes the most sense. Here's a quick sketch of one way that might make sense:
> 
> ```java
> class LoginService {
>     private final AtomicInteger loggedInUsers;
> 
>     LoginService(MeterRegistry meterRegistry) {
>         this.loggedInUsers = meterRegistry.gauge("users.loggedIn", new AtomicInteger());
>     }
> 
>     public void logIn(User user) {
>         loggedInUsers.incrementAndGet();
>         // do stuff
>     }
>     
>     public void logOut(User user) {
>         loggedInUsers.decrementAndGet();
>         // do stuff
>     }
> }
> ```

what need to do incase you also need to send tag which value tag is changing , this current api you can not set also tag value ..

**Comment by lukass77** [comment]
@jonatan-ivanov can you please provide more info on your exampole .. I want to try to implement this
not fully understand , which package is new State()  , and not understand 
`ref -> ref.get().getValue() ` , what is "ref" represent
Thanks!!

**Comment by ttddyy** [comment]
@lukass77 I believe `State` is your object that holds value to the gauge.
`ref -> ref.get().getValue()` is a lambda representing how to provide values to the gauge. `ref` is `stateRef` object passed from the second parameter in the method in this example.
So, it extracts the `State` from `AtomicReference`, then feeds the value to the gauge by calling `getValue()`.

**Comment by jonatan-ivanov** [comment]
Additionally, please check the docs, we have other examples there: https://micrometer.io/docs/concepts#_gauges

**Comment by matt1good** [comment]
This is terribly inconsistent.  You can call Timer() and get back the same timer you created earlier.  You can use the Guage.builder.register() and get back the same Guage stateObject you created earlier so why is this method different?
If you want to get technical, the javadoc is wrong. It claims "will keep a weak reference to the object" when, in fact, it doesn't maintain a reference to the new stateObject at all.
If you want to fix this in docs, yes, please explain in the javadoc this irrational behavior. "If the guage already exists, this method does nothing and returns the value object you sent in - not the one associated with the guage specified."

**Comment by jonatan-ivanov** [comment]
>[...] why is this method different?

Because `Gauge` is "async" while `Timer` is not. This means that you need to update the `Timer` but you can't update the `Gauge`, it gets updated indirectly.

>If you want to get technical, the javadoc is wrong. It claims "will keep a weak reference to the object" when, in fact, it doesn't maintain a reference to the passed in stateObject at all.

You might want to check again, the `Gauge` actually does that:
https://github.com/micrometer-metrics/micrometer/blob/9ea5bf196dea77a4276abf2db59855b6d1a59730/micrometer-core/src/main/java/io/micrometer/core/instrument/internal/DefaultGauge.java#L38

>If you want to fix this in docs [...]

We are always happy to improve our docs, though I'm not sure I understand what you want to say here. Are you interested filing a PR?

**Comment by shakuzen** [comment]
We're only storing a weak reference to the state object by default, so it wouldn't make sense for us to return the state object. If a strong reference to it is not held, the object will be subject to garbage collection. Our assumption is that you already have a reference to it if you want to update it.

**Comment by lukass77** [comment]
@shakuzen - can you please share what was the motivation to use week reference for gauge ?
what will heppen if implementation was working without week reference ..

regarding @jonatan-ivanov suggestion  , keeping a map in memory (key --> weakReference) by the application it self .. is as what I think shifting the responsibility from the framework micrometer to the application that use micrometer ..and from heap size point of view we are ending with the same heap size for the java process ..

why the framework can not hold this map of weak-referenc objects internaliy ..  , do you think it make sense the application will hold a map of gauge weak-reference object ? if I have 1000 combination on gauge object due to tag values which can be change 

the only way I saw to access the weak-reference is upon gauge creation .. 
can we get the weak-reference by api call from gauge ?
the only solution I see now is what suggested above .. find the current gauge remove it and create a new one ..
but is this the best solution ..?

can we have guauge with strong reference .. so on find we will have way to update the state object ?

**Comment by lukass77** [comment]
I also want to add that we discover that when we create guage like this 
`statsdMeterRegistry.gauge(statsdParams.getMetricFullName(), tags, lag);`
we have gaps (time interrval with no values) of reporting on the montoring server (datadog) 
when we create the same guage like this 
`Gauge.builder(statsdParams.getMetricFullName(), () -> lag).tags(tags).register(statsdMeterRegistry)`
metric values reported as expected to the monitor server (datadog)

There is an implementation diffents between the two method for creating gague .., can not tell if this by intention or not ..
and suggest to open a new issue on that ..

1. why from user prespective we need more the single way to create a meter , keep thing simple provide single way to do it 
2. if you chose to provide more the one way to build a metric object make sure that both object are working the same underhood .

**Comment by jonatan-ivanov** [comment]
>can you please share what was the motivation to use week reference for gauge ?

I think to not cause a memory leak. Micrometer should not prevent your objects from collection since it knows nothing about your objects or their lifecycle. The control over them must be in your hands not in Micrometer's.

>what will heppen if implementation was working without week reference ..

If Micrometer would use strong reference, it could cause memory leaks.

>I think shifting the responsibility from the framework micrometer to the application that use micrometer

Yes, that's the point, see my answer above: Micrometer should not prevent your objects from collection since it knows nothing about your objects or their lifecycle. The control over them must be in your hands not in Micrometer's.

>and from heap size point of view we are ending with the same heap size for the java process

If things can be collected but Micrometer prevents GC to collect them that can cause a memory leak which can mean significant GC overhead or out of memory errors.

>why the framework can not hold this map of weak-referenc objects internaliy

I hope I answered this above.

>do you think it make sense the application will hold a map of gauge weak-reference object ? if I have 1000 combination on gauge object due to tag values which can be change

I think I do. Also, please take a look at [`MultiGauge`](https://micrometer.io/docs/concepts#_multi_gauge), it might do what you need to register lots of gauges.

>the only way I saw to access the weak-reference is upon gauge creation ..
can we get the weak-reference by api call from gauge ?

I think the point of view is the opposite here. You have something (the state object) that you manage, control, and you know how to get. You pass it to Micrometer, why should it give back to you? You already have it I doubt it is only possible to fetch it at Gauge creation. A Gauge is not a "container" and also see above: you should not really interact with it. There are also scenarios where doing this would be quite weird: `Gauge.builder("test", () -> 1).register(registry);`

>the only solution I see now is what suggested above .. find the current gauge remove it and create a new one ..
but is this the best solution ..?

I think I might lost track of the context here. What is this solving and why would you re-register a gauge? (You can set the value of your state object and if you want to replace that, there is always `AtomicReference`.)

>can we have guauge with strong reference .. so on find we will have way to update the state object ?

Yes, you can use a `Gauge` with strong reference, you need to tell explicitly that you want this see its builder: `.strongReference(true)` but I'm not sure I understand the second part of this.

>There is an implementation diffents between the two method for creating gague .., can not tell if this by intention or not ..
and suggest to open a new issue on that ..

Please open a new issue for this with a minimal reproducer in Java (please double check that you are using the `Gauge` correctly and you have a strong reference to the `lag` variable).

>why from user prespective we need more the single way to create a meter , keep thing simple provide single way to do it

Those things are quite different: the first one uses a `Number` as the state object, the second one uses a `Supplier<Number>` (with no "real" state object). If you meant why we have `.register` and Builder too: register is just a shortcut for the most common/simple things (also, we can't remove it).

>if you chose to provide more than one way to build a metric object make sure that both object are working the same underhood .

They are different things (`Number` vs. `Supplier<Number>`) and they should work slightly differently. Though not as differently that they should cause issues to you if you use them properly so please create a new issue with a reproducer (please double check that you are using the `Gauge` correctly and you have a strong reference to the `lag` variable).

**Comment by jonatan-ivanov** [comment]
Here's a sample with the [`MultiGauge`](https://micrometer.io/docs/concepts#_multi_gauge) I mentioned above:
```java
SimpleMeterRegistry registry = new SimpleMeterRegistry();
MultiGauge gauge = MultiGauge.builder("test").register(registry);
gauge.register(List.of(Row.of(Tags.of("abc", "123"), 1)), true);
System.out.println(registry.getMetersAsString());
gauge.register(List.of(Row.of(Tags.of("abc", "123"), 2)), true);
System.out.println(registry.getMetersAsString());
```

**Comment by lukass77** [comment]
Thanks @jonatan-ivanov for the detail answers .. 
1 ) I will work on short smaple that will show our case , and if discover an issue I will open I new issue on that ..

2) can you please give more details on the diffrents between (Number vs. Supplier<Number>) - or is this can be read on java api ..for us working with Supplier<Number> works as expected .. but not sure I fully understand "with no "real" state object" .. we currenlty not holding all state objects in a dedicated map on application end ..

**Comment by jonatan-ivanov** [comment]
>can you please give more details on the diffrents between (Number vs. Supplier)

In order to create a `Gauge`, you usually need 3 things:
- A `name`
- A `stateObject`
- A `valueFunction` that converts `stateObject` to `double`

Here's an example:
```java
String string = ""; // reference must kept
...
Gauge.builder("test", string, String::length).register(registry);
```
Your `stateObject` can be a `Number`, but you don't necessarily want that number to be the value of the `Gauge`, let's say something like this:
```java
Number number = 0; // reference must kept
...
Gauge.builder("test", number, this::addOne).register(registry);
// or as a shortcut, this:
registry.gauge("test", number, this::addOne);
```
But if you want to use the number as the value, you would do something like this:
```java
Number number = 0; // reference must kept
...
Gauge.builder("test", number, Number::doubleValue).register(registry);
// or as a shortcut, this:
registry.gauge("test", number, Number::doubleValue);
```
This is a common scenario, so there is an even simpler shortcut:
```java
Number number = 0; // reference must kept
...
registry.gauge("test", number);
```
Please notice that in case of these examples we always used a `stateObject` and sometimes the `valueFunction` was user-provided, sometimes Micrometer provided it. It's important to mention that the `valueFunction` was there even if it was not visible. Micrometer does not necessary need a `stateObject`, but it needs a way to get a value. If that is your use case and you can get the value without a `stateObject`, Micrometer lets you register a `Gauge` if you provide how to get its value in the form of a `Supplier<Number>`, e.g.:
```java
Gauge.builder("test", System::currentTimeMillis).register(registry);
```
Please notice that providing a `stateObject`+`valueFunction` combo (`gauge("test", number)`) is different than providing the method to get the value (`Supplier<Number>`): in the second case, there is no `stateObject` that Micrometer should handle. This does not mean there is no state, it is just not visible to Micrometer, e.g.: `Gauge.builder("test", () -> giveMeTheValue()).register(registry);`. Because of these, all of the followings look the same to Micrometer:
```java
Gauge.builder("test", () -> giveMeTheValue()).register(registry);
Gauge.builder("test", System::currentTimeMillis).register(registry);
Gauge.builder("test", string::length).register(registry);
Gauge.builder("test", number::doubleValue).register(registry);
Gauge.builder("test", () -> number).register(registry);
Gauge.builder("test", () -> 0).register(registry);
```
Since there is no `stateObject` for Micrometer and since it keeps a (strong) reference to the method to get the value (as well as it did to the `valueFunction` previously), and since the method can keep a strong reference to the state object (what is a state object for you but for Micrometer it does not exists), doing this:
```java
Gauge.builder("test", () -> number).register(registry);
```
means `number` will not get garbage collected. This is also equivalent to this:
```java
Number number = 0;
...
Gauge.builder("test", this::giveMeTheValue).register(registry);
...
private double giveMeTheValue() {
    return number;
}
```
Where I think it is more visible why `number` will not get garbage collected.

I understand that this can be surprising and might not be the behavior you want but if you have any suggestions (must be non-breaking) for improvements, please let us know.

**Comment by shakuzen** [comment]
> @shakuzen - can you please share what was the motivation to use week reference for gauge ?
> what will heppen if implementation was working without week reference ..

To give a concrete example, you can look at some of our instrumentation. For example, in TomcatMetrics, we get session metrics from a Tomcat `Manager` object. Micrometer does not manage the lifecycle of this object; Tomcat does. It would be problematic if we kept a strong reference to this and prevented it from being garbage collected. This is the general pattern where there is some existing code providing the value you want to track as a gauge, and that code should not behave differently because you are instrumenting it with Micrometer.

https://github.com/micrometer-metrics/micrometer/blob/221191add27da846bd5a1a4fdda63a90f752d46d/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/tomcat/TomcatMetrics.java#L117-L120

**Comment by jonatan-ivanov** [comment]
>it makes no sense if we can't update the gauge by updating the reference object

That's how you can update a Gauge. :)
See the docs: https://micrometer.io/docs/concepts#_manually_incrementing_or_decrementing_a_gauge
```java
// maintain a reference to myGauge
AtomicInteger myGauge = registry.gauge("numberGauge", new AtomicInteger(0));

// ... elsewhere you can update the value it holds using the object reference
myGauge.set(27);
myGauge.set(11);
```

>because in a lot of real world cases, the tags of gauges are not determined in advance

Could you please give us an example?
Also, could you please check if `MultiGauge` can work in this case?
https://micrometer.io/docs/concepts#_multi_gauge

**Comment by frankjkelly** [comment]
Micrometer is wonderful and invaluable and it would be lovely if, when you try to reregister at least a WARN log message was emitted, at best a Runtime exception.
If you try to change an immutable number someone should tell the developer :-)
Thank you!

**Comment by jonatan-ivanov** [comment]
@frankjkelly Thank you for your kind words. :)

By re-registering you mean removing and registering a Gauge?
You should not do this (I would say almost ever), but if you want to and want to emit a `WARN` message, Micrometer provides you listeners for this, they are in the MeterRegistry:
- `onMeterAdded`
- `onMeterRemoved`

You can subscribe to these events and emit a log event.
We cannot really emit a `WARN` event in this case for every users since there are unfortunate scenarios when you need to do this due to the underlying clients we need to instrument, e.g.: Kafka completely throws out its metrics objects in some cases and recreates them (sometimes with different tags) so we must re-register meters all the time. :(

>If you try to change an immutable number someone should tell the developer :-)

Please notice that none of the `Number`s you should use with a Gauge (should be thread-safe) are immutable: `AtomicInteger`, `AtomicLong`, etc. See the example above. Having a state object though that is immutable is a completely valid scenario, in those cases, you can use an `AtomicReference`, e.g.:
```java
AtomicReference<String> myGauge = registry.gauge("numberGauge", new AtomicReference<>("a"), state -> state.get().length());
...
myGauge.set("ab");
myGauge.set("abc");
```

**Comment by lukass77** [comment]
@jonatan-ivanov  - 
1) what happen when the state object is removed by GC , on the application that use micrometer gauge ?  

on this example 
// maintain a reference to myGauge
AtomicInteger myGauge = registry.gauge("numberGauge", new AtomicInteger(0));

// ... elsewhere you can update the value it holds using the object reference
myGauge.set(27);
myGauge.set(11);

2) update on the state object , how gauge knows to take the new value from the state object is there pulling interval gauge check for a new value  ?

**Comment by lukass77** [comment]
what still confuse me is why we have 2 diffrent ways to create gauge ..
first way - 
AtomicInteger myGauge = registry.gauge("numberGauge", new AtomicInteger(0)); --> which return the state object

and a second way "using the builder pattern"
Gauge.builder("test", System::currentTimeMillis).register(registry) --> which return the Gauge itself but not the state object 

1. why we need both ways ? -- can we simplify this by having only single way to create guage , and a single way to update it value  ?
2. why the 2 ways return different types ?  one return the state object and the other return the gauge .

**Comment by jonatan-ivanov** [comment]
>what happen when the state object is removed by GC , on the application that use micrometer gauge ?

This should not happen since you keep a reference to the state, right? :)
If you don't and this will happen, `NaN` will be reported, you can try this out.

>update on the state object , how gauge knows to take the new value from the state object is there pulling interval gauge check for a new value ?

It depends on the registry. Whenever the `Gauge` is "pulled", it fetches the new value. For step registries this happens once per minute, for Prometheus, this happens every time you scrape.

>what still confuse me is why we have 2 diffrent ways to create gauge ..

We have two different ways to create every `Meter` not just `Gauge`.

>why we need both ways ? -- can we simplify this by having only single way to create guage , and a single way to update it value ?
why the 2 ways return different types ? one return the state object and the other return the gauge .

Creating a `Gauge` with a `Builder` is the way that ensures you can use all the features of a `Gauge` (description, unit, etc). The other way `registry.gauge(...)` is just a shortcut. Lots of users found it handy, please ignore it if you find it confusing. 

They return different types because:
- Returning the state is more convenient if you are using the shortcut, so that you can have a one-liner for registering the gauge and have the state.
- To be consistent to every other `register` methods, we return the instance which can be handy e.g. for testing, you can ignore it in other cases, see the docs:
>Generally the returned Gauge instance is not useful except in testing, as the gauge is already set up to track a value automatically upon registration.

>if some way is for test only put it under src/test directory as java standard project , so it will not be available to use for production runtime ... , and I would not put a "test" example on the official documentation ...

As the docs says it's mainly for testing purposes but I'm not sure I'm following what do you mean put it under `test`? The register method is necessary. You might not put a test example in the official docs but I would find it not a great user experience. Testing is important as well as the docs supporting you and showing you ways to test your code, you can find examples for this in a lot of other places in the Micrometer docs (or in other open source projects as well).

>can framework expose only single way to interact with gague for creationg and updating , and other api call to be private scope ?

I'm afraid no:
- It is actually used by users
- Every other `Meter` has these two ways (builder and shortcut)
- It would be a breaking change

**Comment by schnapster** [comment]
Every time I have to touch Micrometer Gauges, it's confusing and error-prone for me. Never had such a problem with other libs (dropwizard, prometheus). I'd love to recommend Micrometer to more people, but this thread does not give me hope that such developer experience issues will be improved :/
If it takes a breaking change, thats fine! I'm sure the next major version is coming eventually.

**Comment by jonatan-ivanov** [comment]
Somewhat connected to this PR, Micrometer now warns you if you try to do what is in the description of this issue (re-registering a `Gauge`): https://github.com/micrometer-metrics/micrometer/pull/5688. We also improved the docs around this.

**Comment by jonatan-ivanov** [comment]
>Every time I have to touch Micrometer Gauges, it's confusing and error-prone for me. Never had such a problem with other libs (dropwizard, prometheus). I'd love to recommend Micrometer to more people, but this thread does not give me hope that such developer experience issues will be improved :/

@schnapster It's hard to improve if you don't tell us what is confusing and error-prone for _you_. Could you please open a new issue? Do you have improvement ideas?

As for Dropwizard, this is how you create a Dropwizard Gauge (slightly modified official docs example):
```java
private final AtomicInteger state = new AtomicInteger();
// [...]

registry.register(name(GaugeDemo.class, "demo.gauge"), new Gauge<Integer>() {
    @Override
    public Integer getValue() {
        return state.intValue();
    }
});

// register with lambdas:
// registry.register(name(GaugeDemo.class, "demo.gauge"), (Gauge<Integer>) state::intValue);
state.set(100);
```

In Micrometer "reproducing" the above is:
```java
private final AtomicInteger state = new AtomicInteger();
// [...]

registry.gauge("demo.gauge", state, AtomicInteger::doubleValue);
state.set(100);
```
This might not be what you meant but the two seems pretty similar to me.

For Prometheus (slightly modified official docs example):
```java
private final Gauge temperature = Gauge.builder()
    .name("temperature_celsius")
    .help("current temperature")
    .labelNames("location")
    .unit(Unit.CELSIUS)
    .register();
// [...]

temperature.labelValues("Berlin").set(22.3);
```

In Micrometer "reproducing" the above is:
```java
private final AtomicReference<Double> temperature = new AtomicReference<>(0.0);
// [...]

Gauge.builder("temperature", temperature, AtomicReference::get)
    .description("current temperature")
    .tag("location", "Berlin")
    .baseUnit("celsius")
    .register(registry);
// [...]

temperature.set(22.3);
```
There is a difference in these examples though, it might not be apparent first, but Prometheus lets you set multiple values:
```java
temperature.labelValues("Berlin").set(22.3);
temperature.labelValues("London").set(12.3);
```
while the Micrometer example above does not, it only handles one value. For multiple values, the Micrometer example would be:
```java
private final MultiGauge temperature = MultiGauge.builder("temperature")
    .description("current temperature")
    .baseUnit("celsius")
    .register(registry);
// [...]

temperature.register(List.of(
    Row.of(Tags.of("location", "Berlin"), 22.3),
    Row.of(Tags.of("location", "London"), 12.3)
), true);
```

>If it takes a breaking change, thats fine! I'm sure the next major version is coming eventually.

Please feel free to share what ideas you have in mind in another issue.

**Comment by schnapster** [comment]
With Prometheus, I can simply do this:

```
@Component
class Metrics {
    val temperature = Gauge.builder()
        .name("temperature_celsius")
        .help("current temperature")
        .labelNames("location")
        .unit(Unit.CELSIUS)
        .register()
}

@Component
class TemperatureTaker(metrics: Metrics) {
    fun measure() {
        metrics.temperature.labelValues("Berlin").set(22.3)
    }
}
```

Multiple calls to `TemperatureTaker#measure` will be fine, the registry will return the already registered object. I could even access it from another class, for example I often like to access metrics in test code to verify they are being correctly handled by the business code. I don't need to keep track of the state object or worry about whether it has been already initialized or not, as the prometheus registry does that job for me.

In Micrometer however I cannot do that. Not only won't the registry return the already registered object (why is it called registry again then?), it also will not throw an exception into my face as it should for using its API wrongly - instead it silently returns an untracked state object, so coding errors will only be visible at some later point in prod or wherever.

I'm positive that you can come up with an API that is less error-prone, and introduce it within a minor release while deprecating the existing methods. Wouldn't even take a major release to deliver an improvement.

**Comment by jonatan-ivanov** [comment]
>With Prometheus, I can simply do this:

Let me rewrite your code to Java, also let me call out an issues with it: you are using the global static registry here, mixing that up with dependency injection is not a good idea, you can have initialization issues and testing will be hard. Let me fix that here (Micrometer also have a global so you can do the same what you did above but I cannot recommend it):
```java
// @Component
class Metrics {
    final Gauge temperature;

    Metrics(PrometheusRegistry registry) {
        this.temperature = Gauge.builder()
            .name("temperature_celsius")
            .help("current temperature")
            .labelNames("location")
            .unit(Unit.CELSIUS)
            .register(registry);
    }
}

// @Component
class TemperatureTaker {
    final Metrics metrics;

    TemperatureTaker(Metrics metrics) {
        this.metrics = metrics;
    }

    void measure() {
        metrics.temperature.labelValues("Berlin").set(22.3)
    }
}
```

With Micrometer, you can do this (not sure about you but to me it seems similar):
```java
// @Component
class Metrics {
    final AtomicReference<Double> temperature = new AtomicReference<>(0.0);

    Metrics(MeterRegistry registry) {
        Gauge.builder("temperature", temperature, AtomicReference::get)
            .description("current temperature")
            .tag("location", "Berlin")
            .baseUnit("celsius")
            .register(registry);
    }
}

// @Component
class TemperatureTaker {
    final Metrics metrics;

    TemperatureTaker(Metrics metrics) {
        this.metrics = metrics;
    }

    void measure() {
        metrics.temperature.set(22.3);
    }
}
```
You might also want to check out `MeterBinder` in Micrometer since the `Metrics` class above is exactly that (you can replace the ctor to a `bindTo` method and Boot will auto-register it for you, the whole thing can be one class if you want).
I would like to call out that this is the exact same code I wrote earlier (https://github.com/micrometer-metrics/micrometer/issues/2024#issuecomment-2831582776) but now it is in a class, this might not be what you meant but the two seems pretty similar to me.

Also, if you want to register many `Gauge`s, the `MultiGauge` example above would look like this:
```java
class Metrics {
    final MultiGauge temperature;

    Metrics(MeterRegistry registry) {
        this.temperature = MultiGauge.builder("temperature")
            .description("current temperature")
            .baseUnit("celsius")
            .register(registry);
    }
}

class TemperatureTaker {
    final Metrics metrics;

    TemperatureTaker(Metrics metrics) {
        this.metrics = metrics;
    }

    void measure() {
        metrics.temperature.register(List.of(
            Row.of(Tags.of("location", "Berlin"), 22.3),
            Row.of(Tags.of("location", "London"), 12.3)
        ), true);
    }
}
```
Still seems very similar.

>Multiple calls to TemperatureTaker#measure will be fine, the registry will return the already registered object. I could even access it from another class, for example I often like to access metrics in test code to verify they are being correctly handled by the business code. I don't need to keep track of the state object or worry about whether it has been already initialized or not, as the prometheus registry does that job for me.

Same for the Micrometer example. Btw I would like to emphasize again that for testing using the global static registry (or any globals) is a bad idea.

>In Micrometer however I cannot do that.

I think I just demonstrated above that you can.

>Not only won't the registry return the already registered object (why is it called registry again then?) [...]

It does not need to, look at the code above. Also, it is called a `MeterRegistry` it is for `Meter`s, you can reference your state objects on your own or you can use a `MultiGauge` to keep the record of the values for you. (Not having a storng reference to the state object is a feature here, if Micrometer would do that, that's a memory leak, a lot of users would be angry if Micrometer would do that.)

>[...] it also will not throw an exception into my face as it should for using its API wrongly - instead it silently returns an untracked state object, so coding errors will only be visible at some later point in prod or wherever.

Not throwing an exception is also a feature, a lot of our users would be very angry if Micrometer would do that. :) But it will warn you, see my comment above: https://github.com/micrometer-metrics/micrometer/issues/2024#issuecomment-2831581172

>I'm positive that you can come up with an API that is less error-prone, and introduce it within a minor release while deprecating the existing methods - wouldn't even take a major release to deliver an improvement.

I'm not sure the tone you use helps me to understand your concerns better and provide you a solution. What I already asked earlier could though: please share what ideas you have in mind to improve this in another issue.

I'm pretty sure my mind is spoiled because I cannot un-learn what I already know (hence my ask for you help) but if you really cannot or don't want to separate the state object from the `Gauge` registration, you can do this too: https://github.com/micrometer-metrics/micrometer/compare/main...jonatan-ivanov:micrometer:value-binder

**Comment by schnapster** [comment]
Please forgive my somewhat acerbic wording, it was not appropriate.
I was also not exact enough in my last post to say that it "In Micrometer however I cannot do that" - as you have shown that it is possible. My point however is that I find it unintuitive and error-prone to achieve that result. I am using Micrometer in some projects, and Prometheus Client in some others, and will for now not convert more projects over, and also cannot recommend the Micrometer API to other devs working in a relevant tech stack.

**Comment by jonatan-ivanov** [comment]
No problem. :)

>I was also not exact enough in my last post to say that it "In Micrometer however I cannot do that" - as you have shown that it is possible. My point however is that I find it unintuitive and error-prone to achieve that result. 

It's not just possible but to me the two seems very similar. I still don't understand what you find unintuitive and error-prone. Again, I'm pretty sure my mind is spoiled because I cannot un-learn what I already know, hence my repeated ask for you help. We would really appreciate an issue with your pain points _and a proposed solution_ to better understand where Micrometer is failing your expectations otherwise I'm not sure how I could help. I guess the `ValueBinder` above still would not work for you(?) but I'm not sure what would, explaining it would be a huge help. 

>I am using Micrometer in some projects, and Prometheus Client in some others, and will for now not convert more projects over, and also cannot recommend the Micrometer API to other devs working in a relevant tech stack.

This might be a misunderstanding but what I'm really interested in is your feedback about improving our APIs, docs, etc. Do you have improvement ideas?
