### ISSUE TITLE
Add onMeterRegistrationFailed listener configuration to MeterRegistry

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#2068]
This is mainly driven by the significant burden Prometheus' requirement places on everyone for the same metric name to have the same set of tags.

Previously, `PrometheusMeterRegistry` threw an `IllegalArgumentException`. Now, we'll _not_ throw an exception but instead silently continue, but inform any callbacks registered that this `Meter.Id` could not be registered.

In this way, the user can do whatever they'd like with these problems, including logging or propagating a hard failure if they choose.

See issues like https://github.com/micrometer-metrics/micrometer/issues/1253 for motivation.

**Comment by checketts** [comment]
The tag mismatch sometimes happens due to two different libraries creating the same meter name and not matching on tags; inetty and httpclient I believe hit this at one time.

Would a user be able to use a MeterFilter to clean up those tags if they got into that situation?

Sure, the best solution is to have the libraries not step on each other, but I just wanted to think through what options would be available to users when hitting this exception.

**Comment by jkschneider** [comment]
> Would a user be able to use a MeterFilter to clean up those tags if they got into that situation?

`MeterFilter` is already an option. Once you see the implementation, I think you'll see this listener is called as a last resort after filters have been applied and there's still a problem.

**Comment by jkschneider** [comment]
Also included here is a new method on `PrometheusMeterRegistry` called `throwExceptionOnRegistrationFailure()` which sets up such a listener that throws the same unchecked exception it did before. But now this behavior is _opt-in_.

**Comment by jkschneider** [comment]
cc / @izeye because I know you've been squashing all the tag problems lately (and many thanks for this)! Just want you to be aware of the different behavior.
