### ISSUE TITLE
Buffered statsd lines are not published on close

### ISSUE THREAD

**Issue by WillBrindle** [micrometer-metrics/micrometer#2141]
This may well be misunderstanding on my part but is there any way to ensure all counters are updated on close?
Here is a minimal example of the problem:
```
public static void main(String args[]) throws InterruptedException {
        StatsdConfig config = new StatsdConfig() {
            @Override
            public String get(String k) {
                return null;
            }
        };
        MeterRegistry registry = new StatsdMeterRegistry(config, Clock.SYSTEM);

        String METRIC = "test.metric";

        registry.counter(METRIC);
        registry.close();
}
```
If you spin up a simple udp server you'll see nothing is sent. This extends to if I add a sleep for a value more than `step()` , before or after closing. If I add a loop before closing where I increment the counter then sleep I start to get buffered messages across, but if not enough messages have been sent to clear the buffer by the last metrics are lost.

Setting buffered in my config to false resolves the problem but the natural behave feels like flushing should occur on close.

**Comment by mickaeltr** [comment]
Isn't it the same issue as https://github.com/micrometer-metrics/micrometer/issues/1882 ?

**Comment by jonatan-ivanov** [comment]
#1882 fixed this for `StepMeterRegistry` implementations while `StatsdMeterRegistry extends MeterRegistry`.

**Comment by jgrigg** [comment]
I'm still seeing this behaviour when running any of the aforementioned versions. i.e doing `nc -ul 8125` and running @WillBrindle's original example yields nothing. The test looks right though :/

**Comment by shakuzen** [comment]
@jgrigg could you open a new issue with the relevant details and refer to this issue? That will be better for tracking. Please try to reproduce the issue with a minimal sample.

**Comment by izeye** [comment]
I could reproduce @jgrigg's comment with `nc -ulp 8125` command and [this sample](https://github.com/izeye/hello-micrometer/blob/statsd/src/main/java/com/izeye/helloworld/micrometer/Main.java).

`counter.increment()` seems to have been lost due to a missing UDP connection. If I add a second of sleep before it, it seems to work.

I created https://github.com/micrometer-metrics/micrometer/pull/6371 to demonstrate the status quo.

The reason why it's okay in the `StatsdMeterRegistryPublishTest` is that the tests wait for a UDP connection to be available as follows:

https://github.com/micrometer-metrics/micrometer/blob/807d09855749a46e014a82de24004f1f9fd59bd5/implementations/micrometer-registry-statsd/src/test/java/io/micrometer/statsd/StatsdMeterRegistryPublishTest.java#L346
