### ISSUE TITLE
DropwizardMeterRegistry.newGauge shouldn't use WeakReference

### ISSUE THREAD

**Issue by mrniko** [micrometer-metrics/micrometer#2149]
DropwizardMeterRegistry.newGauge uses WeakReference this causes NaN value for some attributes.

**Comment by shakuzen** [comment]
That's expected behavior. See [this section of the documentation](https://micrometer.io/docs/concepts#_why_is_my_gauge_reporting_nan_or_disappearing):

> It is your responsibility to hold a strong reference to the state object that you are measuring with a Gauge. Micrometer is careful to not create strong references to objects that would otherwise be garbage collected. Once the object being gauged is de-referenced and is garbage collected, Micrometer will start reporting a NaN or nothing for a gauge, depending on the registry implementation.

Could you provide a more complete description of what you are doing or a sample demonstrating the issue you are facing?

**Comment by mrniko** [comment]
I use it like this:

// this value will be stored
DropwizardMeterRegistry.gauge("myGague", 10L);

// this value won't be because of WeakReference usage
DropwizardMeterRegistry.gauge("myGague", 100000L);

**Comment by mrniko** [comment]
I'm closing it since it's expected behaviour.

**Comment by shakuzen** [comment]
If the intent is to update the value of the gauge from `10` to `100000` and there isn't a function available to provide the current value, you could use a `Number` object to store the current value (and keep a reference to that object). Calling the `gauge` method (or any method to create/retrieve a meter) again will not update the meter because the meter created in the first invocation of the `gauge` method is returned.

Example from the documentation:

```java
// maintain a reference to myGauge
AtomicInteger myGauge = registry.gauge("numberGauge", new AtomicInteger(0));

// ... elsewhere you can update the value it holds using the object reference
myGauge.set(27);
myGauge.set(11);
```
