### ISSUE TITLE
GraphiteMeterRegistry reports 3 times on close()

### ISSUE THREAD

**Issue by markusheiden** [micrometer-metrics/micrometer#2156]
On close() the GraphiteMeterRegistry reports three times (instead of once like before) to graphite:
* reporter.report()
* stop() -> reporter.stop() -> GraphiteReport.stop() -> ScheduledReporter.stop() -> report()
* reporter.close() -> ScheduledReporter.close() -> ScheduledReporter.stop() -> report()

Technically this is no problem, just suboptimal.

**Comment by izeye** [comment]
It seems that https://github.com/dropwizard/metrics/issues/1461 causes the behavioral change since `metrics-core` 4.1.18.

**Comment by shakuzen** [comment]
Thanks for digging into this @izeye. That makes it a bit difficult to solve this since Micrometer users may be using the `metrics-core` dependency before or after 4.1.18. If we remove our explicit call to `report`, we risk not publishing one last time on close for those using earlier than 4.1.18. It does look like we can eliminate at least the call to `stop` since the `close` method's JavaDoc indicates it will stop the reporter. I'd like to make that change in maintenance branches so that with 4.1.18 and later it'll only be 2 publishes, which is a little better. In our next feature release, we can get rid of the explicit call to `report` with a release note that users should be on the latest patch release to retain the publish on close behavior.
