### ISSUE TITLE
Support per_unit parameter in Datadog

### ISSUE THREAD

**Issue by RobinsonZ** [micrometer-metrics/micrometer#2181]
DataDog expresses two-part "per" units such as bits per second, etc. by using two parameters in the metadata (`unit` and `per_unit`) as described [here](https://docs.datadoghq.com/api/v1/metrics/#edit-metric-metadata). Currently, at least as far as I could tell by looking at the code, Micrometer's DataDog integration does not support splitting the provided metric unit into these `unit` and `per_unit` elements. It would be useful to parse two-part units provided in some sort of standard format (perhaps splitting the unit in two based on a separator such as `/` or "per") and submit those to Datadog correctly.

**Comment by shakuzen** [comment]
Micrometer meters don't have a "per unit" because the interval at which metrics are reported depends on the configured step interval, which is configured for the registry, not on a meter basis. For out-of-the-box meter types, I think this only applies to Counter/Timer/DistributionSummary's `count` statistic, which would be per the configured `step` interval (`DatadogConfig#step`) - e.g. 112 occurrences per minute.

We don't currently do any scaling of the value reported, though. For the default step of 1 minute, it would be easy enough to set the per unit as `minute`. For other step intervals, we would need to scale the `count` value to a per unit of `minute` or `second`, probably.

Is the `count` statistic of the built-in meter types the only thing you had in mind or was there something else you were thinking could benefit from having the `per_unit` set?

Also, I noticed that the `per_unit` field isn't listed in the endpoint payload for [submitting metrics](https://docs.datadoghq.com/api/v1/metrics/#submit-metrics), but I'm wonder if it is available there also. It would be needed in case the descriptions are disabled in `DatadogConfig`, which causes no metadata to be sent.

**Comment by RobinsonZ** [comment]
> Is the count statistic of the built-in meter types the only thing you had in mind or was there something else you were thinking could benefit from having the per_unit set?

In my specific case, I was interested in reporting units that are inherently a rate. For example, I have a gauge (available bandwidth for a process) that is inherently reported in units of bits per second.

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2020. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
