### ISSUE TITLE
Do we have a plan to support kafka with micrometer-registry-elastic?

### ISSUE THREAD

**Issue by DanielYWoo** [micrometer-metrics/micrometer#2209]
When we have many data to push to ElasticSearch, it might get ElasticSearch overloaded, so do we have plan to add kafka between the application and ElasticSearch?

**Comment by DanielYWoo** [comment]
anybody has interests to discuss this?

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2020. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.

**Comment by shakuzen** [comment]
@DanielYWoo It's not such a common problem to have that metrics publishing overwhelms the backend because metrics are aggregate data that is not supposed to be high cardinality and does not need to be published so frequently (the default in Micrometer is once per minute). This means that the load on your metrics backend should not increase if there is more traffic to your monitored applications. The load will only depend on the average number of metrics per application instance, the number of application instances, and the publish frequency (what we call step interval).

That said, you can probably achieve what you want with some configuration code. Many registries in Micrometer use an `HttpSender` to publish metrics. While the name implies HTTP and that is what the implementations we provide do, you could provide your own implementation that instead writes metrics to Kafka and then configure your ElasticMeterRegistry to use that. On the builder there is a method to pass a custom `HttpSender` instance that it will use when publishing metrics.

**Comment by DanielYWoo** [comment]
Thanks @shakuzen  for the explanation. I understand that publishing is batched and infrequent. In my case, we do have some tags with high cardinality, and most importantly, we have too many pods publishing concurrently to the Elastic stack. 

Now it's not a problem for me anymore because we use pull mode instead of push mode. We switched the registry to a Prometheus registry, we now pull data from pods with DynaTrace, and there is no scalability issue anymore with pull mode. I think in very large clusters, push mode is not the best option due to the error handling, retry, and autoscaling peaks etc. But if for some reason you have to use push mode, I believe Kafka is needed. e.g., suppose we have autoscaling enabled in K8S, on Black Friday, thousands of new pods are scheduled in a few minutes, while the Elastic stack is a statefulset that cannot scale up quickly enough, we will run into trouble. Kafka can act as a buffer here. But anyway, since we have pull mode supported with the defacto industry metrics standard - Prometheus format, why not using it ;-)

**Comment by DanielYWoo** [comment]
@marcingrzejszczak  thanks and yes we can close it. There is no need to have Kafka here. In large autoscaling environments, we have other alternative solutions, like what I discussed with @shakuzen above.

**Comment by shakuzen** [comment]
It's always good for us to better understand the real world scenarios our users are facing, so thanks for the additional details, @DanielYWoo. While it could still be an issue with enough application instances, perhaps you may have been running into [this issue](https://github.com/micrometer-metrics/micrometer/issues/2818) we had for a while but eventually fixed so publishing time is properly distributed across application instances. Either way, I'm glad you were able to sort things out with Prometheus. If someone writes an implementation of `HttpSender` that writes metrics to Kafka, maybe they can share it here for anyone else interested in using it.

**Comment by DanielYWoo** [comment]
my great pleasure to share whatever I have. Thanks again.
