### ISSUE TITLE
@Timed in any Spring-managed bean not work when called in same bean

### ISSUE THREAD

**Issue by lmlsky** [micrometer-metrics/micrometer#2214]
1：`@Timed` in any Spring-managed bean not work 
 maven config   
```xml
 <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.1.4.RELEASE</version>
        <relativePath/>
    </parent>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
```
2：code
```java
@Configuration
@EnableAspectJAutoProxy
public class AutoTimingConfiguration {

    @Bean
    MeterRegistryCustomizer<MeterRegistry> configurer(@Value("${spring.application.name}") String applicationName) {
        return registry -> {
            registry.config().commonTags("application", applicationName);
        };
    }
    @Bean
    public TimedAspect timedAspect(MeterRegistry registry) {
        return new TimedAspect(registry);
    }

}
```
3：code
```java
    @Timed(value = "my_fly", percentiles = {0.95, 0.99})
    public String fly() {
        return "fly";
    }
```

**Comment by checketts** [comment]
Is the code calling the `fly()` method in the same bean? If so it won't use the proxy and will bypass the timing.

**Comment by lmlsky** [comment]
yes, in the same bean

**Comment by shakuzen** [comment]
As @checketts pointed out, this is how AOP works with Spring and is expected behavior. We mention this in the official [Micrometer documentation](https://micrometer.io/docs/concepts#_the_timed_annotation) - perhaps this could be improved if you saw this and were still confused.

> Micrometer’s Spring Boot configuration does not recognize `@Timed` on arbitrary methods.

See also the "Understanding AOP Proxies" section of the [Spring Framework documentation](https://docs.spring.io/spring/docs/5.2.8.RELEASE/spring-framework-reference/core.html#aop-understanding-aop-proxies). If you call the `fly` method from an auto-wired bean, then it will be proxied. Alternatively, you may be able to configure AspectJ differently to support proxying of direct method calls, but that's outside the scope of Micrometer. I'll close this issue as it is more about AspectJ than Micrometer.
