### ISSUE TITLE
Micrometer continues connection retry on Invalid Key

### ISSUE THREAD

**Issue by Sagar2366** [micrometer-metrics/micrometer#2230]
(Case : Someone in team accidently deleted Datadog API Key) 

In spring boot application, if Datadog api key is invalid then Micrometer tries to reconnect to Datadog for Infinite time.
Is there any way to handle exception by which after 4-5 retries I can exit application ?

**Comment by shakuzen** [comment]
The API key is used when publishing metrics, which happens on the configured step interval (1 minute by default for DatadogConfig). Metrics are not published immediately at startup and we do not make an attempt to verify if the key is a valid key at startup (beyond there being some key configured). I'm not sure we have a certain way to know a key is invalid other than getting a 403 HTTP response when publishing metrics or metadata.

Is it fair to summarize the issue as being it is hard to notice if an application is running with an invalid Datadog API key because there is no indication other than metrics are not available for that application in Datadog?

There is a balance to be had between verifying a valid configuration and ensuring that metrics failures do not affect the application. We can try to improve the situation but I think blocking startup to somehow validate the API key and exiting the application is probably too extreme.

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2020. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
