### ISSUE TITLE
How to keep the counter value unchanged when the application restarts？

### ISSUE THREAD

**Issue by 0lidaxiang** [micrometer-metrics/micrometer#2247]
My springboot application will restart every few days.I don't want the counter to restart from 0 after restarting. Is there any way to do it？Thanks

**Comment by shakuzen** [comment]
Relying on the absolute value of a counter is generally an anti-pattern. From the [Micrometer documentation on Counters](https://micrometer.io/docs/concepts#_counters):

> When building graphs and alerts off of counters, generally you should be most interested in measuring the rate at which some event is occurring over a given time interval. Consider a simple queue. Counters could be used to measure things like the rate at which items are being inserted and removed.
>
> It’s tempting at first to conceive of visualizing absolute counts rather than a rate, but the absolute count is usually both a function of the rapidity with which something is used **and** the longevity of the application instance under instrumentation. Building dashboards and alerts of the rate of a counter per some interval of time disregards the longevity of the app, letting you see aberrant behavior long after the app has started.

Given the above information, do you think it still makes sense to use the absolute value? If so, you could explain more about your use case, considering the above?

**Comment by 0lidaxiang** [comment]
Thanks @shakuzen . 

My application needs to count the number of visits for some URIs, but this application is restarted by colleagues every few days, so the counter metric will restart from 0. This makes me very distressed.

**Comment by shakuzen** [comment]
If longer-term storage and analysis is a goal, the meters should be published to a metrics backend. You can then execute queries and use functions on the time series data from across restarts there. Metric values in-memory are not for long-term, persistent use.

**Comment by fabioformosa** [comment]
Hi @0lidaxiang how did you solve your use case? I'm interested to.

**Comment by shakuzen** [comment]
@fabioformosa did you consider my previous two comments? I've responded on the topic, but if there's still some confusion, please elaborate so we can help.

**Comment by fabioformosa** [comment]
Sure, I read your comments. I was wondering about your point "_Metric values in-memory are not for long-term, persistent use_".
Let's suppose:

-  I have an order table in the database and I would like to keep a counter with the number of order, to see in Prometheus the rate of order creation over the last 30 days. 
- I invoke the counter.increment() every time an order is created
- I execute in Prometheus the function rate(order_counter[30d]) * (number of seconds in a month)

What happens if the app was restarted and so the counter reset? Can I resume to increment from zero when the app is up again or should I initialize the counter, running a query on the order table, to restore the total order counter again?

I read in the prometheus documentation of the [rate function](https://prometheus.io/docs/prometheus/latest/querying/functions/#rate)
```Breaks in monotonicity (such as counter resets due to target restarts) are automatically adjusted for.```

Is this adjustment valid even for long-term range time (30 days) ?

**Comment by shakuzen** [comment]
Yes, Prometheus should handle the resets, as it mentions.
