### ISSUE TITLE
Publishing of connection pool metrics (gauge)

### ISSUE THREAD

**Issue by gennadiy-dubina** [micrometer-metrics/micrometer#2267]
Hi everybody,

i have a question about **Gauge** metrics and connection pool metrics particularity.

To collect connection pool metrics everybody uses Gauge.
But Gauge is `a meter that only changes when it is observed`

It means we need to publish our metrics to server very often to get accurate data.
if app publishes metrics once a minute it means we will Gauge state once a minute and will miss system state during this minute.
So to get good accuracy of Gauge meter we need to publish metrics pretty often like each 3-5 sec.

Am i right? have i missed something?

Does it make sense to **DistributionSummary** for connection pool metrics to gather usage? to know that 90% of pool in use for some period of time?

Thanks,

**Comment by checketts** [comment]
You are correct that a gauge only reports when observed. I wouldn't recommend using a DistributionSummary for the general usecase, but if you have a need and want to create your own meter that is updated on a more frequent basis, that could be useful to you.

I recommend against this for most people because instead of a single value per tag, you get perhaps 10 more (depending on your config) so you need to balance the raw number of meters against how useful it is.

The second problem you'll want to address is HOW to record these counts. For example if you want to put those values in a DistributionSummary, you'll need to perhaps run a thread the checks every few seconds to report the current state. We wouldn't want Micrometer doing that by default.

**Comment by jkschneider** [comment]
@gennadiy-dubina DistributionSummary can also record histogram buckets, percentiles, SLO boundaries, etc.

This may seem strange given the name, but the best outcome for connection pool monitoring is probably `LongTaskTimer`. It records the number of active tasks and durations (active tasks / pool capacity is a saturation metric) along with max active duration, percentiles, histograms SLOs, etc.

I've been wondering whether connection pools and other "limited size resources that could get saturated" like this deserved their own meter type. And you're hinting at _yes_ I think... What `LongTaskTimer` lacks is a "max active tasks in some interval" metric.

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2020. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.

**Comment by robmoore-i** [comment]
I'm also interested in this, to track active connection counts.

**Comment by jonatan-ivanov** [comment]
@robmoore-i Your connection pool might already do this, e.g.: HikariCP does.
(If you are using Spring Boot, this should be already there for you.)

**Comment by robmoore-i** [comment]
👍 We use HikariCP and that works fine. In this case what I'm looking at is tracking the number of active connections our application makes to S3.
