### ISSUE TITLE
LogbackMetrics ignoreMetrics will ignore forever if exception is thrown in Runnable

### ISSUE THREAD

**Issue by tekener** [micrometer-metrics/micrometer#2270]
In case that the Runnables run() methods throws an exception the ThreadLocal `ignoreMetrics`  stays true forever.
 
LogbackMetrics.java
```   java
public static void ignoreMetrics(Runnable r) {
        ignoreMetrics.set(true);
        r.run();
        ignoreMetrics.remove();
}
```

**Comment by wuguanyu** [comment]
I want know, When should we need invoke LogbackMetrics ignoreMetrics

**Comment by shakuzen** [comment]
> When should we need invoke LogbackMetrics ignoreMetrics ?

See [the JavaDoc](https://www.javadoc.io/doc/io.micrometer/micrometer-core/latest/io/micrometer/core/instrument/binder/logging/LogbackMetrics.html). Copied below:

> Used by Counter.increment() implementations that may cause a logback logging event to occur. Attempting to instrument that implementation would cause a StackOverflowError.

Unless you are making a custom `Counter` implementation, I would not expect users to need to use it. Because the Logback metrics are counters, care needs to be taken when incrementing a counter if it may cause logging, since it could lead to infinite recursion of incrementing.
