### ISSUE TITLE
Common tags do not work in case composite repository is nested.

### ISSUE THREAD

**Issue by ksiczek** [micrometer-metrics/micrometer#2284]
Hello.

I am not sure if that does not work by design or maybe I am doing something wrong but please do consider the following scenario:
We have a composite registry (cr) that was configured to have some common tags (cr_ct) and that registry contains a PrometheusMeterRegistry. Moreover, the composite registry cr was added to _Metrics.globalRegistry_. The thing is that if we write metrics through _Metrics.globalRegistry_ then common tags are somehow being bypassed but if we do the same using registry _cr_ then tags are respected. In other words, if a composite registry is part of another composite registry then its common tags are not respected when metrics are written through the outer one. 

In fact, in our setup, we could skip the registry _cr_ or switch from using _Metrics.globalRegistry_ to _cr_ but it seemed interesting enough to have it reported.

Maven demo 
[common-tags-test.zip](https://github.com/micrometer-metrics/micrometer/files/5348433/common-tags-test.zip)

K

**Comment by SoMuchForSubtlety** [comment]
I have the same issue with spring boot 2.5.0

This is my workaround

```java
@Configuration
public class MeterConfiguration {
	@Autowired
	PrometheusMeterRegistry meterRegistry;

	@Bean
	MeterRegistry meterRegistry(PrometheusMeterRegistry registry) {
		return registry;
	}

	@PostConstruct
	public void initialize() {
		meterRegistry.config().commonTags(Arrays.asList(
				Tag.of("tag1", "value1"),
				Tag.of("tag2", "value2")
		));
	}
}
```

**Comment by istvan-nagy-intland** [comment]
This is still an issue.
I'm planning to use multiple registries and the obvious way to add common tags provisioned to each of them would be adding them to the Metrics.globalRegistry, but this doesn't work.
If I add them directly to eg. the PrometheusMeterRegistry, I can see them appear in Grafana.
Is this intentional behavior and needs some kind of extra configuration to work or a bug?

**Comment by shakuzen** [comment]
I took a look at this, and to clarify the issue is when you are registering meters to a composite but the MeterFilter configuration you want to be applied is on a composite registry between the composite for registering meters and the non-composite registry. This is intentional behavior, I believe. I think it would help if we take a step back and understand the background on the usage. In general, the global registry is a convenience for environments that do not have dependency injection available to inject a desired registry. If you want common tags (or other MeterFilter) to apply to all meters in all registries, you should configure that on the registry with which you will register meters and add all registries as descendants of that composite.. If you want common tags (or other MeterFilter) on a subset of registries, you should configure it on the composite registry for those registries and register meters to that composite registry. Is there a reason you can't do that, or is the current behavior just surprising and we should figure out how to improve documentation on that?
