### ISSUE TITLE
Micrometer support with kinesis registry

### ISSUE THREAD

**Issue by piyushkapoor89** [micrometer-metrics/micrometer#2290]
As part of this issue, we would want to know if there are any plans for Micrometer to have integration with Kinesis for exporting metrics similar to what we have for cloudwatch, datadog etc. 
Also in case there are no recent development planned for kinesis support, can we go ahead and add the support for Kinesis after development. Thanks !

**Comment by shakuzen** [comment]
I'm not sure I understand the request. Kinesis is not a metrics backend, as far as I understand, but it is a data pipeline. Do you mean instrument metrics for Kinesis clients, publish metrics to Kinesis as an intermediary instead of directly to metrics backends, or something else?

**Comment by piyushkapoor89** [comment]
Thanks for responding, yes my ask is to publish metrics to kinesis as an intermediary and thus control lies at our hand on where to channelize those metrics and introduce any transformation as part of the flow.

**Comment by checketts** [comment]
@piyushkapoor89 I don't know that Kinesis integration is widely requested (this is the first I've heard anyone wanting to use it).  So I don't know how useful it would be in Micrometer itself.

For yourself, you could implement a Kinesis registry by extending `PushMeterRegistry` and overriding the `publish` method and pushing to Kinesis that way.

**Comment by shakuzen** [comment]
In addition to what @checketts said, what format would we publish metrics in? In order to process them and send them to different backends, you're essentially doing half the work of Micrometer all over again on the side consuming the metrics from Kinesis.

To echo what @checketts said, we would need to see more interest and concrete use cases around this to add this in Micrometer, but you could certainly achieve something like this with a custom registry already.

**Comment by developer-g** [comment]
@checketts & @shakuzen As you rightly mentioned above that metrics exporter support is already available for most of the metrics backends but our ask is to have support for the data pipeline as well, so that it can support transformation/preprocessing, filtering, resiliency & data is forked(published) to multiple metrics backends through a single pipeline. 
Please share your thoughts?

**Comment by shakuzen** [comment]
What kind of processing on metrics are you planning? With the exception of StatsD, raw metrics data points aren't published, so I don't have a good idea of the kind of processing you would want to do. `MeterFilter` is the way to filter meters or tags in Micrometer. Note that you can already ship to multiple metrics backends by using multiple `MeterRegistry` implementations with a `CompositeMeterRegistry`.

**Comment by checketts** [comment]
Perhaps the usecase is publishing the raw meters to Kinesis without aggregation?

**Comment by developer-g** [comment]
Yes, we want to publish raw metrics to kinesis and let the data pipeline to do the rest.
I agree with you that we can achieve the same by extending PushMeterRegistry as well but that will add coupling of kinesis with the application code. When we have a framework of exporting metrics data to various backends through exporters, why not use the same flow and add support for data pipeline like kinesis?

**Comment by shakuzen** [comment]
I'm still trying to understand why publishing raw measurements to Kinesis to process them there and eventually store them in a metrics backend is better than publishing them to the backend directly in the first place (as is the standard behavior for Micrometer). In what format would we publish measurements to Kinesis, with what naming convention, with what base time unit? If you want to use a StatsD line format, you can use the line sink already like the [documentation shows an example for Kafka](https://micrometer.io/docs/registry/statsD#_using_apache_kafka_for_line_sink). I'm still very curious about the specific use case over direct-to-backend publishing. Publishing and processing raw measurements outside of the application requires more resources and is less efficient.
