### ISSUE TITLE
webflux uri showing host header

### ISSUE THREAD

**Issue by bijukunjummen** [micrometer-metrics/micrometer#231]
I am very likely missing something here. The uri in some of my apps metrics shows the hostname:

`http_server_requests_duration_seconds_count{exception="none",method="POST",status="200",uri="http://bk:8080/messages",} 300.0`

`http_server_requests_duration_seconds_count{exception="none",method="POST",status="200",uri="http://localhost:8080/messages",} 604.0`, 

Should it not be just the pure uri - 

`http_server_requests_duration_seconds_count{exception="none",method="POST",status="200",uri="/messages",} 604.0`, 

This is for a Spring Boot 2(2.0.0.M6) based webflux app

**Comment by jkschneider** [comment]
You are correct, and it should be just the path. We have plenty of work left to do on Webflux support. See also #199.

**Comment by jkschneider** [comment]
I think this is fixed in the latest version of Boot.

![image](https://user-images.githubusercontent.com/1697736/36054070-1e87c182-0dba-11e8-81bc-4ac40f0697e7.png)

Here is a sample project that results in the correct tag:

[boot2-webflux-micrometer.zip](https://github.com/micrometer-metrics/micrometer/files/1712687/boot2-webflux-micrometer.zip)
