### ISSUE TITLE
PrometheusNamingConvention duplicates "_seconds" suffix with default configuration for Timer metrics

### ISSUE THREAD

**Issue by Fetsivalen** [micrometer-metrics/micrometer#2320]
*Version*: Latest

By default in [PrometheusMeterRegistry](https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusMeterRegistry.java#L72) configured PrometheusNamingConvention with default constructor which configures "" value in `timerSuffix`.

And when the method `name` called for the Timer metric, it will append the `_seconds` suffix even when it is already present.
see: [this switch case](https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusNamingConvention.java#L69-L74)

At the same time, that implementation won't add _total suffix for counter metrics.
see:  [this switch case](https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusNamingConvention.java#L64-L67). 

Am I missing some intentional reason why it is happening in this way or it is a bug?

**Comment by shakuzen** [comment]
That code has not changed since 1.0, but it does look potentially off. The intention was to support an alternate naming convention for timers that used an additional suffix before `_seconds` (see `PrometheusDurationNamingConvention`). It doesn't look like we consider the case for the default of a blank `""` suffix and a meter name that already ends in `seconds`, which I believe is what this issue is reporting. I would say it is also best practice to not name Timers ending in `seconds` generally, anyways, though. We could still probably improve the logic and unit tests here.
/cc @checketts who added the `PrometheusDurationNamingConvention`.

**Comment by Fetsivalen** [comment]
Actually, my issue is not about the naming of the metrics itself.

I used PrometheusNamingConvention to generate dashboards from the source code and different users are able to provide metric names either from Prometheus endpoint, or the ones they pass to the meter registry.

Of course, I can resolve it inside my own code, but it seems to me that behavior in PrometheusNamingConvention is not consistent for the Timers and Counters.

I'd be happy to contribute this feature but the change seems like breaking change to me, and I wonder whether it will be welcomed, and what is the process of such changes.

**Comment by checketts** [comment]
I can't recall why it was implemented as is. The `blame` looks like I just reformatted the code. So that isn't very helpful.

It appears the current logic is intended to make the suffix `_duration_seconds` or just `_seconds`, feel free to add the missing case @shakuzen mentioned.

**Comment by Fetsivalen** [comment]
Hi @shakuzen  
are you going to merge this PR, or it isn't smth you'd like to have in micrometer and I should close this ticket?
