### ISSUE TITLE
Cache metrics are always 0 for Hazelcast

### ISSUE THREAD

**Issue by tmoreno** [micrometer-metrics/micrometer#2340]
Hi!

I'm using Spring Boot with Hazelcast as a cache.

When I try to get cache metrics like: cache.entries, cache.gets.latency, ... all of them are always 0

Do I have to configure any propierties in the yml file?

Thanks!

**Comment by priyankpande9** [comment]
I am also facing the same issue.

**Comment by shakuzen** [comment]
Have you seen the [corresponding Spring Boot documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator.metrics.supported.cache)?
Could either of you provide a minimal sample project that reproduces the issue you are seeing? That would help us investigate the issue.

**Comment by shakuzen** [comment]
Closing due to lack of feedback. We can reopen if we get a minimal sample project that reproduces the issue.

**Comment by danielt-ent** [comment]
Having the same issue. This SO comment seems to suggest that LocalMapStats are not meant to be used that way for clients:
 https://stackoverflow.com/a/44461250

Since most things just work on HazelcastInstances and those can be either clients or regular cluster members, it's not obvious what to expect.

So for configurations where the spring application isn't also a full cluster member, the stats will always be wrong. I'm not really sure what to do about this but maybe since I got here via google, maybe this will be useful to someone else.

**Comment by shakuzen** [comment]
@danielt-ent could you provide a minimal sample project that reproduces the issue that we can run? We have a [Hazelcast 2 sample](https://github.com/micrometer-metrics/micrometer/tree/main/samples/micrometer-samples-hazelcast) and [Hazelcast 3 sample](https://github.com/micrometer-metrics/micrometer/tree/main/samples/micrometer-samples-hazelcast3) that you can run and see cache metrics logged for them, but I know they don't cover all possible configurations of Hazelcast. If `HazelcastCacheMetrics` does not work with Hazelcast running in client mode, that would be something we should at least document.
