### ISSUE TITLE
TimedAspect creates a new timer each time?

### ISSUE THREAD

**Issue by skingsland** [micrometer-metrics/micrometer#2383]
I'm trying to use `TimedAspect` in my Spring Boot app, but I'm _occasionally_ seeing duplicate timers with the same name in my meter registry, in some cases. I think the reason might be because `TimedAspect` [calls](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/aop/TimedAspect.java#L105) [Timer#start](https://github.com/micrometer-metrics/micrometer/blob/07f2b628e4740309f45f237bd9258a121751d0f2/micrometer-core/src/main/java/io/micrometer/core/instrument/Timer.java#L56), which creates a new sample timer, instead of reusing one that already exists. Then when it stops the timer, it [registers](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/aop/TimedAspect.java#L137) the real timer with the registry.

Why doesn't it call `registry.timer(metricName)` instead, so it creates the timer up front? Is it because using a sample timer is necessary to support tags?

In my local testing, calling `registry.timer()` instead fixes the problem of having duplicate timers. Here's what the aspect I'm using looks like:
```
@Aspect
@Component
public class MyTimedAspect {
  private final MeterRegistry registry;

  MyTimedAspect(MeterRegistry registry) {
    this.registry = registry;
  }

  @Around("@annotation(io.micrometer.core.annotation.Timed)")
  public Object time(ProceedingJoinPoint joinPoint) throws Throwable {
    final Method method = ((MethodSignature) joinPoint.getSignature()).getMethod();
    final Timed timed = method.getAnnotation(Timed.class);
    final String metricName = timed.value();

    final Stopwatch callStart = Stopwatch.createStarted();
    final Object result = joinPoint.proceed();
    registry.timer(metricName).record(callStart.elapsed());

    return result;
  }
}
```

**Comment by marcingrzejszczak** [comment]
Is this still a problem with latest versions? Can you write a test that proves this?

**Comment by shakuzen** [comment]
> Why doesn't it call `registry.timer(metricName)` instead

That is a shortcut for when you don't have any tags on a Timer. We do have tags included with TimedAspect, and they depend on the outcome of the method being timed (whether it throws an exception). So we don't know the timer to which we want to record until after the PJP has completed. You will end up with Timers with the same name but different tag values depending on the outcome and method being timed. That is expected. For example, if your method timed with TimedAspect is called twice and one time it throws and exception and the other time it doesn't - you will have two timers because the value of the `exception` tag will be different.
