### ISSUE TITLE
Azure Registry: send metrics from long task timer as single MetricTelemetry

### ISSUE THREAD

**Issue by uvalashchuk** [micrometer-metrics/micrometer#2425]
Regular timer is sending metrics as one `MetricTelemetry` setting `timer.totalTime` to `value` and `timer.count` to `count`, but long task timer publisher sends two `MetricTelemetry` instances making it hard to aggregate average execution time in Azure Application Insights.

Is there a reason of sending two instances instead of one? Will it be changed in future releases to send metrics from long task timer as single entry?

Implementations from `io.micrometer.azuremonitor.AzureMonitorMeterRegistry`:
```
    private Stream<MetricTelemetry> trackLongTaskTimer(LongTaskTimer timer) {
        MetricTelemetry active = createMetricTelemetry(timer, "active");
        active.setValue(timer.activeTasks());

        MetricTelemetry duration = createMetricTelemetry(timer, "duration");
        duration.setValue(timer.duration(getBaseTimeUnit()));

        return Stream.of(active, duration);
    }

    private Stream<MetricTelemetry> trackTimer(Timer timer) {
        MetricTelemetry mt = createMetricTelemetry(timer, null);
        mt.setValue(timer.totalTime(getBaseTimeUnit()));
        mt.setCount(castCountToInt(timer.count()));
        mt.setMin(0.0); // TODO: when #457 is resolved, support min
        mt.setMax(timer.max(getBaseTimeUnit()));
        return Stream.of(mt);
    }
```

**Comment by shakuzen** [comment]
> Is there a reason of sending two instances instead of one?

Upon further thought, I believe there is. It is because LongTaskTimer values are gauge-like in nature. They are a snapshot of what is currently active (not finished), without any relation to what was previously active. So I think the current behavior is probably more correct.

If you have a Timer and a LongTaskTimer and in one step you record one measurement for the timer and you start one task for the LTT (without stopping it), then it will be reported as a count/active of one for each. If in the second step, you record another measurement for the timer and start a second task for the LTT (both tasks are still active throughout the step), then the timer will report 1 again for the count because it has had 1 recording in the step. The LTT would report 2 active tasks because there are currently two active tasks. So while there have only ever been two recordings and two tasks active, the (count) values are `1`, `1` for the Timer and `1`, `2` for the LTT. If you wanted to aggregate the count over the two steps for the Timer, you would sum them to get 2. However, doing this for LTT would not be meaningful. All you can know is how many tasks were active in that step - you can't know if it is the same task or a different task from the information in LTT alone. I believe this distinction is why LTT is reported differently than Timer.

@uvalashchuk Given the above, does the current way LTT values are reported make sense, or do you still think there is an issue we should address?
