### ISSUE TITLE
Memory Leak in micrometer version # 1.1.2

### ISSUE THREAD

**Issue by Shubhamjain2908** [micrometer-metrics/micrometer#2440]
We are using micrometer version **1.1.2** with Spring boot version **2.1.2** to get the metrics.
There seem to be some memory leak in the following version, We face with a high CPU & JVM utilisation for few of our AWS instances (usually the old one's). & when we inspect the heap, it was at max utilisation with more that 85% usage of micrometer class. 

PFA images  for more info.
![image](https://user-images.githubusercontent.com/33689620/107188857-703c0480-6a0e-11eb-8f26-5d4967e11473.png)

<img width="924" alt="Screenshot 2021-02-08 at 12 49 00 PM" src="https://user-images.githubusercontent.com/33689620/107188149-2999da80-6a0d-11eb-8c3f-669262228d8a.png">
<img width="929" alt="Screenshot 2021-02-08 at 12 49 36 PM" src="https://user-images.githubusercontent.com/33689620/107188179-374f6000-6a0d-11eb-8cdd-e310dd005b22.png">

Few open questions I had.
- How can we know which tag is leading to this high memory consumption?
- How can we fix it?
- How can we avoid such leaks in future?

**Comment by jonatan-ivanov** [comment]
Hi @Shubhamjain2908

Micrometer 1.1.2 is not supported anymore, could you please check if the latest version has the same issue?
You can find the supported versions and the support policy here: https://github.com/micrometer-metrics/micrometer#long-term-support-versions

**Comment by zlaval** [comment]
Hi, today i've faced with the same issue with version 1.2.x. I'm going to try the latest one.

**Comment by jonatan-ivanov** [comment]
@Shubhamjain2908 Good to hear. It seems the upgrade solved the issue so I'm closing this, please feel free to reopen if you encounter such a problem again.

**Comment by Shubhamjain2908** [comment]
Hi @jonatan-ivanov 

We tried to run our application with the updated version. It works well for 2-3 weeks. But then we face the same issue with High CPU utilisation.

<img width="1339" alt="Screenshot 2021-02-23 at 11 25 49 PM" src="https://user-images.githubusercontent.com/33689620/109161007-8ed72500-779c-11eb-8208-05af960cf65e.png">
<img width="1347" alt="Screenshot 2021-02-23 at 11 25 13 PM" src="https://user-images.githubusercontent.com/33689620/109161019-939bd900-779c-11eb-9d4b-4fc655134e8d.png">

<img width="1357" alt="Screenshot 2021-02-24 at 11 19 55 AM" src="https://user-images.githubusercontent.com/33689620/109160977-8383f980-779c-11eb-9e53-17830bd73ff3.png">

**Comment by jonatan-ivanov** [comment]
@Shubhamjain2908 I know nothing about this application so I'm just trying to guess here:
- You have and awful lot of major GCs that could be the cause of the high CPU usage
- It looks like your reactor queue is huge, could you please check what is in there from the heap-dump (other than GC logs)?
- What registry are you using? Is it happen to be StatsD?
- What happens if you set StatsD to use the TCP client `management.metrics.export.statsd.protocol=tcp`?
- Do you see something weird (e.g.: infinite reconnection loop) when you set the shaded netty log level to `DEBUG`: `logging.level.io.micrometer.shaded.reactor.netty=DEBUG`?

**Comment by Shubhamjain2908** [comment]
@jonatan-ivanov Thanks for the response. 
I'll look into the given points more closely. Will try to implement few of it on our Application & will provide the necessary details.

**Comment by shakuzen** [comment]
@Shubhamjain2908 were you able to get any more details on this with @jonatan-ivanov's suggestions? Do you know if the timing corresponds to any issue in the statsd daemon where metrics are being sent? It shouldn't cause this much of an issue anyways, but I'm just wondering in hopes we can get to the root cause. As @jonatan-ivanov said, the high CPU utilization corresponds with the jump in major GCs, so maybe figuring out the cause of those would shed some light. Micrometer GC metrics include the cause of the GC.
It doesn't look like there's increased traffic in your application at the time of the increased CPU usage, according to the charts you've provided. We would expect an increase in the metrics to send to statsd if the traffic increases but not otherwise. The only thing I can think of is metrics are stuck being retried to send, but then I would expect the memory to increase over that time and it looks relatively constant in your graphs.

**Comment by Shubhamjain2908** [comment]
Hey @shakuzen, 
We couldn't able to reproduce this issue. There is a possibility that the 2nd machine where we got an issue ( after version update) might be an old machine. 
Closing the issue for now, will keep you guys updated if the issue happens again.
