### ISSUE TITLE
Peek at time in Timer.Sample

### ISSUE THREAD

**Issue by bentatham** [micrometer-metrics/micrometer#2494]
I would like to be able to peek at the elapsed time of a Timer.Sample.

The purpose would be to be able to log the elapsed time from Sample, check for high time thresholds in the code, or similar reasons.

I suggest a method on Timer.Sample like `long elapsed(TimeUnit unit)` or `Duration elapsed()` (or both)

**Comment by shakuzen** [comment]
This is similar to what is already offered by [LongTaskTimer](https://micrometer.io/docs/concepts#_long_task_timers). If we did add this to the Timer Sample, we would want to be consistent with the method signature on the LongTaskTimer Sample. I'm curious to know more about the concrete uses of adding this. If information about active samples is generally useful, it could be a case for some combining of LTT and Timer so that information is available to the metrics backend. This has been brought up before, but I'm curious about your and others' use cases.

> log the elapsed time from Sample, check for high time thresholds in the code, or similar reasons.

Particularly, would you not want to do this as alerts on metrics in your metrics system?

**Comment by shakuzen** [comment]
I'm still interested in getting feedback on this to drive the evolution of Timer and LongTaskTimer looking forward to Micrometer 2.0 where we can make more substantial changes in this area.

**Comment by shakuzen** [comment]
Closing due to lack of feedback
