### ISSUE TITLE
Add facility to meter HTTP response codes

### ISSUE THREAD

**Issue by alex859** [micrometer-metrics/micrometer#251]
In Spring Boot 2 it would be useful to have not only time metrics for requests but also a meter for response statuses.

I am thinking at something like
```java
@GetMapping("/api/people")
@Timed
@HttpStatusMetered
public List<Person> listPeople() { ... }
```
with a new annotation and then some new methods in `WebMvcMetrics` to increment a counter, so people can get rates of `200` vs `500` for example. 

Same thing could be done on the client side

If you think this can be useful, I would be happy to contribute.

Thank you.

**Comment by checketts** [comment]
Rates are already available via the current instrumentation. For example with Prometheus the query to get the 1 minute rate would be: `sum(rate(http_server_requests_duration_seconds_count[1m])) by (status)`

Other backends might not support that calculation. What backend do you have in mind? Perhaps we could ensure that backend's registry makes it easier to track rates.

**Comment by alex859** [comment]
That is true, but we still need to create different metrics per response status.
My understanding is that currently only one will be sent to the backend, while it would be nice be able to send, for example:
```
metric_prefix.listPeople // a timer for all requests which we can then do count on
metric_prefix.listPeople.200 // a timer or maybe just a counter for 200 response code
metric_prefix.listPeople.500 // a timer or maybe just a counter for 500 response code
...
```

Is this currently achievable?

(P.S. we are using Graphite as backend)

Thank you

**Comment by jkschneider** [comment]
We already record response as a tag in our `MetricsFilter`. For a hierarchical backend like graphite, that will come out like:

```
http.server.requests.response.200
http.server.requests.response.500
```

Timers are always composed at a minimum of a count and a time. In the case of Graphite, since we are passing instrumentation through Dropwizard, you'll also get a 1, 5, 15 minute rate, absolute max, etc.

If you wanted to reason about latency or throughput for all requests, you can glob over this expression, like:

```
http.server.requests.response.*
```

There are other tags, so the hierarchical name will be longer than this, but hopefully this gives you an idea of what's going on.
