### ISSUE TITLE
issue with nested @Timed 

### ISSUE THREAD

**Issue by blnprasad** [micrometer-metrics/micrometer#2526]
I'm observing that if two methods say A & B annotated with @Timed and  A invokes B then  only timing of A is being reported but not B. is this expected? how do i get timing information for both A&B in these cases?

**Comment by checketts** [comment]
Since `@Timed` creates an AOP proxy for the timing, you would have to inject the proxy into the class itself and call `B` on the injected proxy instead of within the class. (I'm not aware how you would do that).

The simpler way that would work and not require proxy gymnastics would be to not use the annotation and instead  wrap the contents of the methods in the timer with a `record` callback.
