### ISSUE TITLE
Rename Mongo tags provider interfaces to align with existing tags providers

### ISSUE THREAD

**Issue by wilkinsona** [micrometer-metrics/micrometer#2541]
1.7 is introducing two new tags provider interfaces for Mongo:

- `MongoMetricsCommandTagsProvider`
- `MongoMetricsConnectionPoolTagsProvider`

The use of `Metrics` in the name doesn't seem to be consistent with the existing `…TagsProvider` interfaces:

- `JerseyTagsProvider`
- `JerseyClientTagsProvider`
- `HttpServletRequestTagsProvider`

I wonder if they should be renamed to `MongoCommandTagsProvider` and `MongoConnectionPoolTagsProvider` respectively?

**Comment by bono007** [comment]
I will submit a proposal w/ the name changes.

**Comment by shakuzen** [comment]
I don't have a strong opinion one way or the other. I will say the reason they ended up that way is fairly logical, though. They are the tags provider used by the respective listeners by the same name but with `Listener` at the end instead of `TagsProvider`. And those listener names probably make sense because e.g. `MongoCommandListener` wouldn't really be specific for something that implements the `CommandListener` interface of the Mongo library. I do agree that Metrics and TagsProvider is a bit redundant, though. So yes, let's align them before the RC release.
