### ISSUE TITLE
Some metrics named unintuitively 

### ISSUE THREAD

**Issue by max-rocket-internet** [micrometer-metrics/micrometer#2544]
Hi!
Some of the metric names are a bit confusing if you're already familiar prometheus.

For example the name of `http_server_requests_seconds_count` would imply that it is a count of seconds in relation to HTTP server requests. But it's simply a count of HTTP requests, the `seconds` part is irrelevant I think? Even popular [some blog posts](https://tomgregory.com/monitoring-a-spring-boot-application-part-2-prometheus/) are mentioning the confusing name:

> http_server_requests_seconds_count is a metric to hold the count of HTTP requests (don’t worry about the fact that the name contains the word seconds)

According to [the convention](https://prometheus.io/docs/practices/naming/), I think a better name would be `http_server_requests_total`

Similarly, I think `http_server_requests_seconds_xxx` should be renamed to `http_server_request_duration_seconds_xxx`, there's many examples of this naming, including in prometheus itself 🙂

**Comment by shakuzen** [comment]
There's a `PrometheusDurationNamingConvention` if you want `duration` in your timer metric names. Seconds are obviously a duration, so I think it's just longer metric names and makes the name even more different than other monitoring systems, but we provide the option to configure that if you want.

> According to [the convention](https://prometheus.io/docs/practices/naming/), I think a better name would be `http_server_requests_total`

Timers are a [Histogram](https://prometheus.io/docs/concepts/metric_types/#histogram) or [Summary](https://prometheus.io/docs/concepts/metric_types/#summary) type in Prometheus (depending on DistributionStatisticConfig), which are defined to have a `_sum` and `_count` time series. So if we used `_total` instead, we wouldn't be following the model. `_total` is for standalone Counter types. Internally the `_sum` and `_count` time series are counter types, but the naming is different since they're part of a Summary or Histogram.

> For example the name of `http_server_requests_seconds_count` would imply that it is a count of seconds in relation to HTTP server requests. But it's simply a count of HTTP requests, the `seconds` part is irrelevant I think?

I don't disagree, but we're simply following the model that Prometheus defines as described above. Prometheus doesn't have metadata for Units, hence why they end up in the metric name, and the base name should be consistent for a metric family. [OpenMetrics](https://openmetrics.io) adds support for Unit metadata but still requires the unit be part of the metric name, which I find unfortunate, but I suppose was done for compatibility with the Prometheus format.

Ultimately, I don't think there's anything to change in Micrometer, in light of the above explanation. `PrometheusDurationNamingConvention` is available while not the default. If we changed it to be the default, it would break existing Micrometer users that have built dashboards, queries, alerts around the current default names. We could perhaps revisit the decision of default for Micrometer 2.0, but I would like to see more feedback on the benefits of doing so.
