### ISSUE TITLE
Add TomcatPublicMetrics equivalent for MicroMeter

### ISSUE THREAD

**Issue by checketts** [micrometer-metrics/micrometer#257]
This was uncovered via #256

**Comment by wilkinsona** [comment]
I think this may need to go in Boot (at least for Boot 2.0) as getting hold of the embedded Tomcat instance requires use Boot classes. If Micrometer did that, we’d have a circular dependency between the projects.

**Comment by checketts** [comment]
The Binder will exist in micrometer. The autoconfig would exist in boot. I'll create one autoconfig in the spring-legacy module and each out to @wilkinsona or @jkschneider for the Boot 2 one.

**Comment by jkschneider** [comment]
Your intuition is spot on @checketts.

**Comment by wilkinsona** [comment]
Micrometer, a dependency of Boot, shouldn't know about the embedded containers that Boot supports. If it does, we have a conceptual cycle between projects. This issue is proposing Tomcat-specific metrics, but we may also want to provide metrics for Jetty and Undertow. That would broaden Micrometer's knowledge of containers that Boot supports which feels wrong to me.

#260 also illustrates a further problem with this approach. It's building against Tomcat 9.0.1, but Boot's using 8.5.x (8.5.23 at the moment). Having to keep Boot and Micrometer's Tomcat versions in sync further reinforces the cycle.

I think we should consider all of this functionality going in Boot.

**Comment by checketts** [comment]
Tomcat isn't the first usecase. Notice Jetty metrics also exist in Micrometer (https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/JettyStatisticsMetrics.java) and are used by non-SpringBoot enabled apps. (I'm not sure if SpringBoot 2 is leveraging that yet, I'm a bit behind on that adoption)

Eventually, as Micrometer grows in acceptance I would love to see the instrumentation added to the individual projects (as Hikari did)

I downgraded the Tomcat dep version. The `Manager` class that the metrics derive from is a stable interface that isn't changing. 

I'm not opposed to leaving the Tomcat binder out of Micrometer. But if we can provide support for metrics that are decoupled from SpringBoot I want to encourage that, especially if it improves MicroMeter adoption.

**Comment by jkschneider** [comment]
I agree with @checketts. I understand the theoretical problem with dependency divergence between Micrometer core and Boot, but think we just need to examine it on a case-by-case basis. Micrometer has non-Spring users [Armeria](https://github.com/line/armeria), Ratpack, etc. that may benefit from general-purpose binders.

If the only part of the Tomcat API that we are interacting has not changed across major releases, I don't think there is a problem.

Suppose in some future event we are forced to diverge from Boot across one or more major releases of Tomcat that involves a breaking change in `Manager`. At that time, it will be simple enough to add a `TomcatMetricsX` (where `X` is the version) to Boot and we'll be on our way.
