### ISSUE TITLE
Custom MeterRegistry for MicrometerMetricsPublisher without using Graphite ,...

### ISSUE THREAD

**Issue by kAgotsi** [micrometer-metrics/micrometer#2621]
Hello,

I would like to use Hystrix metricsPublisher to get the metrics in my project and save it on database, but I don't want to go through Graphite,....
How can I do it?
Based on the documentation, to save the hystrix metrics you use :
`HystrixPlugins.getInstance().registerMetricsPublisher(HystrixServoMetricsPublisher.getInstance());`

So with your library, to register the metrics, I will do: 

`HystrixPlugins.getInstance().registerMetricsPublisher(MicrometerMetricsPublisher(MeterRegistry registry, HystrixMetricsPublisher metricsPublisher)
`
So how to do it?
Thanks

**Comment by jonatan-ivanov** [comment]
I'm not sure, I got your question. After you set-up the Micrometer integration with Hystrix, you can send metrics to any registry that is supported by Micrometer: https://micrometer.io/docs

You don't need a custom registry if your metrics backend is supported by Micrometer.

**Comment by kAgotsi** [comment]
> I'm not sure, I got your question. After you set-up the Micrometer integration with Hystrix, you can send metrics to any registry that is supported by Micrometer: https://micrometer.io/docs
> 
> You don't need a custom registry if your metrics backend is supported by Micrometer.

Thank you for your feedback, I would like to retrieve the hystrix metrics and save it in an internal database linked to my project without going through a registry such as Graphana, Promotheus.
So I saw in your code you have created a  custom Publisher for hystrix (MicrometerMetricsPublisher) which allows you to get the metrics.
So how can I get the hystrix metrics from MicrometerMetricsPublisher and save it in my database with Java code without using registry (Graphana,...)

**Comment by jonatan-ivanov** [comment]
I see, thanks for the explanations, and also, for editing the description so that the next reader will have a better understanding.

As you mentioned in your original description, you can create a [custom `MeterRegistry`](https://micrometer.io/docs/guide/customMeterRegistry), please see the docs. You can also take a look at the currently supported meter registries: https://github.com/micrometer-metrics/micrometer/tree/main/implementations based on these, you can implement your own solution.
