### ISSUE TITLE
Support extra tags for each gRPC call

### ISSUE THREAD

**Issue by ivansenic** [micrometer-metrics/micrometer#2622]
Currently the tags in the gRPC `MetricCollectingServerInterceptor` are fixed to `service, method, methodType & statusCode`. 

It would be great if there would be a support for a custom tags that depend on the `ServerCall` and `Metadata` as well, not only the method being invoked. This way the user would have freedom to add extra tags with values that depend on the caller.

**Comment by jonatan-ivanov** [comment]
We have this functionality for other instrumentations, [search](https://github.com/micrometer-metrics/micrometer/find/main) for classes that contains TagsProvider in their names, e.g.: [`MongoCommandTagsProvider`](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoCommandTagsProvider.java) and [`DefaultMongoCommandTagsProvider`](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/DefaultMongoCommandTagsProvider.java) (see: [usage in `MongoMetricsCommandListener`](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/mongodb/MongoMetricsCommandListener.java)).


I think if there is enough interest in it, we can do something similar. Would you be up to creating a PR for it?

**Comment by jonatan-ivanov** [comment]
@ivansenic Would the components in my previous comment help?
Do you have any proposal?

**Comment by ivansenic** [comment]
@jonatan-ivanov Creating the tag provider interface and default implementation is easy. I am more interested in how can this be plugged in the current implementation.

I would say that [metricsFor](https://github.com/micrometer-metrics/micrometer/blob/c3cf9f674fb07f7300b1c9bb7c6da746897b8a86/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/AbstractMetricCollectingInterceptor.java#L163) would be a good place to do this, change the signature of the `metricsFor` and pass `call` and `requestHeaders`. In the concrete impl then I can pipe to the tag provider for creating the tags and default tag provider would simulate current behavior. But this would break the `new..` protected methods of the [AbstractMetricCollectingInterceptor](https://github.com/micrometer-metrics/micrometer/blob/c3cf9f674fb07f7300b1c9bb7c6da746897b8a86/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/grpc/AbstractMetricCollectingInterceptor.java#L43), meaning that this would become a breaking change for anybody that extended it with it's own impl. If this is fine, I have no problem in doing so.

**Comment by ivansenic** [comment]
@jonatan-ivanov Any chance you can respond to the above comment? Or anybody else from the core team?

**Comment by jonatan-ivanov** [comment]
@ivansenic That would break the `public` `preregisterService` and `preregisterMethod` methods too, right?
I'm not sure why those are needed or why the `protected` methods are `protected` in that class.

What I'm thinking about to keep the changes backward compatible is adding an overloaded `metricsFor` method (what you mentioned) and calling it depending on the presence of the tag provider. I did not try out so I don't know if it could work.


@ST-DDT do you happen to know the background of the preregister and the protected methods?

**Comment by ST-DDT** [comment]
Do you have an example for the tags that you would like to add?

The preregister methods are optional. I added them because in our applications some methods are called very rarely and I needed a way to identify them easily.

As for the protected calls. They are just a way for me to reuse code across the server and client implementation. They are based on the greatest common data avaiable for both server and client.
Adding a TagProvider would render the entire abstract base class useless. Please note that you will need separate TagProvider interfaces for both server and client. ~Maybe its possible to use the same interface if we trash most of the current client implementation and potentially some of the semantics.~ 

I'm not against this change if it is worth it, but it may come at the price of increased complexity. Depending on the requirements, the client side may work entirely different from the server side.
Especially the client side may be affected by the increase of complexity. Please ensure that it is still possible to cancel (and count) client calls, that have not been `ClientCall#start`ed due to executor constraints.

Please consult the grpc javadocs, regarding the limitations of the scope/thread safety of the related beans.

**Comment by oehme** [comment]
For me, the main thing that's missing from the default tags is the target address of the channel. I have an app with multiple channels that use the same service interface, connected to different hosts. If I use the same interceptor for each channel (e.g. [like Micronaut does](https://github.com/micronaut-projects/micronaut-grpc/blob/7f16e0377ad26794430040a1d695bc00e424e598/grpc-client-runtime/src/main/java/io/micronaut/grpc/channels/GrpcChannelBuilderFactory.java#L74)), then all the metrics end up indistinguishable. I've worked around this by adding a different interceptor to each channel and using the counterCustomizer/timerCustumizer to add the channel tag. It would be great if that just worked out of the box though, especially when future Micronaut versions [add this as a global interceptor](https://github.com/micronaut-projects/micronaut-grpc/issues/80).

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2021. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
