### ISSUE TITLE
Need Clarity on Global Registry

### ISSUE THREAD

**Issue by LethiferousMoose** [micrometer-metrics/micrometer#2634]
My team is adopting Micrometer for use with Elastic and during my testing I ran into something that confuses me.

I am using Spring Boot's autoconfigure for metrics something like the following:

**application.yaml**
```yaml
management:
  metrics:
    export:
      simple:
        enabled: true
        step: 30s
        mode: STEP
```

When I was testing/unit testing I had tried the following in an area where Spring is not available to auto-wire the `MeterRegistry`:
```java
Metrics.gauge("TestName", this, TestClass:getValue)
```

When I read this out, it never invoked the mapped method, I also noticed that the created Gauge has no children, so `CompositeGauge#value()` returns `0.0D`.
```java
@Override
public double value() {
    return firstChild().value();
}
```

Now if I do the following:
```java
Metrics.addRegistry(new SimpleMeterRegistry());
Metrics.gauge("TestName", this, TestClass:getValue)
```

It works as expected and the gauge reads out the value of the mapped function.

So now for my question, does Spring Boot need to be fully up, running, and configured before I can use the static `Metrics` methods? At the moment I see some of my meters propagating to the `SimpleMeterRegistry` created from the application properties, but the number is less than half, and the rest all reside only in the global one. Which leads me to believe there are race conditions in play here, where our application is prepping stuff at the same time Spring is setting up, and only some of them are properly getting configured within Micrometer.

**Comment by jonatan-ivanov** [comment]
Let me answer these one-by-one:
- [`SimpleMeterRegistry`](https://micrometer.io/docs/concepts#_registry) doesn’t export the data anywhere, you should use [`ElasticMeterRegistry`](https://micrometer.io/docs/registry/elastic) for elastic, [Spring Boot will auto-configure both](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator.metrics) for you in a [`CompositeMeterRegistry`](https://micrometer.io/docs/concepts#_composite_registries)
- `Metrics.gauge` will use the [Global registry](https://micrometer.io/docs/concepts#_global_registry). Since Spring Boot will auto-configure registries for you, by using the Global registry instead of injecting the one that Spring Boot creates for you, you just introduced a split-brain problem.

>Does Spring Boot need to be fully up, running, and configured before I can use the static Metrics methods?
With Spring you should not use the static Metrics methods. You need to inject an instance of a `MeterRegistry` whenever you want it. This happens during context startup, so you can use Micrometer before the context creation finishes if you want.

**Comment by izeye** [comment]
`Metrics` should work in a Spring Boot application by default, so I'm not sure why it's not the case here.

See https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#application-properties.actuator.management.metrics.use-global-registry
