### ISSUE TITLE
Monitored Cache is not elligible for garbage collection

### ISSUE THREAD

**Issue by slovdahl** [micrometer-metrics/micrometer#2642]
The[ `io.micrometer.core.instrument.binder.cache.CaffeineCacheMetrics`](https://github.com/micrometer-metrics/micrometer/blob/258a2f8ad2342244d950ba48d45792f2c373d8b8/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache/CaffeineCacheMetrics.java) class keeps a strong reference to the `com.github.benmanes.caffeine.cache.Cache` instance that `CaffeineCacheMetrics` was created with. The `CacheMeterBinder` super-class on the other hand has a reference wrapped in `WeakReference`. Is it intentional that `CaffeineCacheMetrics` keeps a strong reference?

Combining this with the fact that the gauges created in `CacheMeterBinder.bindTo` reference the `size()`, `missCount()`, `hitCount()`, `putCount()` and `evictionCount()` methods in `CacheMeterBinder`, as far as I can tell, it means that monitored `Cache` instances are never eligible for garbage collection.

**Comment by slovdahl** [comment]
To me, it feels like an anti-pattern to use anything else than parameter provided by the `ToDoubleFunction<T>` in `Gauge.builder(String, T, ToDoubleFunction<T>)`, because it means that the lambda captures the enclosing instance and keeps a strong reference to it forever.

Replacing

```java
private final Cache<?, ?> cache; 
```

with

```java
private final WeakReference<Cache<?, ?>> cache;
```

feels like a reasonable way to fix this.

**Comment by slovdahl** [comment]
Maybe the ideal situation would be to not retain any references at all to `CacheMeterBinder` or its subclasses, but that's a larger change that probably requires changing the signature of the abstract methods in `CacheMeterBinder`.

**Comment by shakuzen** [comment]
It's probably not intentional that it prevents the cache from being garbage collected. In general, we try to not prevent things from being garbage collected just because they are instrumented. It may be the case we didn't realize that the current setup does prevent garbage collection. Let's see what we can do about this. It looks like this affects all the implementations of CacheMeterBinder.

If this were updated so the underlying cache could be garbage collected, the cache metrics would all still be registered. It would end up with meters having nonsense values reported for a cache that's no longer there.

**Comment by slovdahl** [comment]
> It looks like this affects all the implementations of CacheMeterBinder.

Yep, I noticed this as well. I quickly checked the other implementations, and for most of them it seems to be quite straight-forward to fix it in the same way.
