### ISSUE TITLE
Add counter on throwable on Logging metrics

### ISSUE THREAD

**Issue by H3llK33p3r** [micrometer-metrics/micrometer#2697]
**Please describe the feature request.**

It will be great to have a metrics that expose the number of logging message that have an exeption attached. 

**Rationale**

For monitoring purpose and to quickly check that an application is clean, have a quick access on the number of exception logged can be a good thing.

**Comment by jonatan-ivanov** [comment]
@H3llK33p3r I'm trying to understand your use case. Right now you can filter the count of the log events by level so you can see how many `ERROR` events were emitted. This should give you the ability to check is the application is "clean" or not, or is there something I'm missing?

**Comment by H3llK33p3r** [comment]
Hi, sure that's we can do for now. But error message can also be printed without exception just meaning a non expected issue occured but managed by the application. I can understand that my request is specific and not useful for everybody I let you decide if you want to close this issue without adding the feature.

**Comment by jonatan-ivanov** [comment]
>But error message can also be printed without exception just meaning a non expected issue occured but managed by the application

I agree with the first half of this but calling the logger with the exception does not mean that the application was not able to handle that exception. I can see that attaching a tag with the classname of the exception could be useful but you might already have that functionality: do you happen to use Spring Boot or the `@Timed` annotation? They can give you this functionality by adding an `exception` tag to the timers they create.

If these don't work for you, you can take a look at [LogbackMetrics](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/logging/LogbackMetrics.java) and [TimedAspect](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/aop/TimedAspect.java) to se how does this work today and how to add an exception to a meter; with these, you can implement your own. We can also talk about an opt-in addition to `LogbackMetrics` (doing this can have an impact on performance and amount of data shipped).

@shakuzen Have you seen any similar request to this?
What do you think about tagging the logback counters with the exception's classname like `@Timed`.

**Comment by H3llK33p3r** [comment]
Thank you for the reply. I just opened this tiket wondering if this kind of feature can be useful for others ;) ! But yes I can add something on my side to implement this kind of feature ;) !

**Comment by jonatan-ivanov** [comment]
I can imagine that this is useful (also worried about the performance implications).
I think I would just use `@Timed` and `@Counted` to track these exceptions (they have an error tag), would that work for you in this case?

**Comment by checketts** [comment]
I'm opposed in so far that it makes more meters without a real benefit. 

In my opinion, the usecase stated by the request is invalid. (And I admitit is an opinion) If you have ERROR logs that aren't actionable or true problems, those should be logged at the 'WARN' level.

**Comment by shakuzen** [comment]
I haven't seen requests for this before. We would need to see more users requesting this before doing anything in Micrometer. If we did add anything, it would be as an opt-in feature, I think. That said, I share the concerns expressed.

I think the key problem for me is: exceptions can be logged (potentially by a library you are using rather than in your own application code) that are handled and require no action. Discerning whether the logged exception is actionable or not from the proposed additional log metrics seems more difficult than using the `exception` tag on things timed automatically by frameworks - e.g. HTTP server requests. A handled exception wouldn't show up in these metrics. These metrics more closely approximate impact to users of your application than logged exceptions would. So I'm not sure what is gained by counting exceptions logged if you still don't know whether they were handled (and maybe need to be suppressed) or unhandled and are causing impact (which you should be able to see through other metrics).
