### ISSUE TITLE
CaffeineCache hitRate and missRate stats

### ISSUE THREAD

**Issue by djohs** [micrometer-metrics/micrometer#2716]
**Please describe the feature request.**
More a question than an enhancement request: Is there a reason why some CaffeineCache stats like hitRate and missRate are not bound to the MeterRegistry in CaffeineCacheMetrics?

**Rationale**
We currently bind these two stats to the MeterRegistry by ourself. I then just asked myself why this is not done by default.

**Comment by checketts** [comment]
They aren't bound by default because they aren't as useful for most back ends. For example you can't average your hit and miss rates across several servers. (That is bad math)

Instead if you are trying to find the hit/miss rates you would total your hits across those servers and calculate your miss rate from those counters. At least that is the recommended technique with a backend like Prometheus.

**Comment by djohs** [comment]
makes sense, thanks for clarification :)
