### ISSUE TITLE
statsd : Value of a counter always 1 ( 'one' )

### ISSUE THREAD

**Issue by kemuning** [micrometer-metrics/micrometer#2729]
Hi, I'm using micrometer-registry-statsd and Counters to count how many a business function is called. The process is that every time a business function is called, I increment a counter. But when I run a simple query in influxdb, the value is always 1 ( 'one' ), as shows below after 3 times :

![image](https://user-images.githubusercontent.com/23009699/128477293-74378108-6a82-4014-948f-a1a6f999c3b8.png)

where as the actuator shows correctly the value :

![image](https://user-images.githubusercontent.com/23009699/128416694-df44819b-8373-4b52-bb15-416673a2d3a7.png)

Hence, when I display on grafana, what I got is just a straight horizontal line : 

![image](https://user-images.githubusercontent.com/23009699/128416763-c1e4497b-9a85-4ab5-94ed-6a0aefc3f835.png)
 

My environments on Windows :
* SpringBoot 2.5.3, with micrometer-registry-statsd
* Telegraf 1.19.2, with default value in the telegraf.conf for [[inputs.statsd]]
* InfluxDB 1.8.7-1, with default value in the influxdb.conf except the directory location under [meta] et [data]
* Grafana 8.0.6

The code I am using :

```
@Configuration

public class MetricsConfig {

	private static final Logger LOG = LoggerFactory.getLogger(MetricsConfig.class);
	
	@Bean
	public Counter myCounter(MeterRegistry meterRegistry) {
		return Counter.builder("myCounter").register(meterRegistry);
	}
}
```

```
@RestController
public class MyController {
	@Autowired
	private Counter myCounter;

	@GetMapping("/testcounter")
	public ResponseEntity<String> getTestCounter() {
		myCounter.increment();
		return new ResponseEntity<>("Return getTestCounter", HttpStatus.OK);
	}
}
```

```
management.metrics.export.statsd.enabled=true
management.metrics.export.statsd.flavor=telegraf
management.metrics.export.statsd.port=8125
```

I would expect that at `t2`, the value should be 2, and at `t3` should be 3, so grafana will display the line correctly instead of a straight horizontal line.

Can someone please advise what went wrong with my code / config ?

**Comment by shakuzen** [comment]
If you are using InfluxDB, I would suggest using the InfluxMeterRegistry rather than involving statsd at all. I don't know what aggregation or transformation may be happening in telegraf as statsd data is converted and ingested into InfluxDB, but it's possible that it is a count per interval that it is saving in InfluxDB, which is the same as you would get sending data to InfluxDB directly using the micrometer-registry-influx module. Thus it should be interpreted as a count of 1 for that time interval. If there were 3 time intervals as shown, you get your cumulative count of 3. The value of 1 is a rate of increments per interval. See the [documentation of rate aggregation](https://micrometer.io/docs/concepts#_client_side). For statsd, we send each increment to statsd and aggregation is happening in statsd.

The count in the Actuator endpoint when using the statsd module will be the cumulative count.

Does this help what you're seeing make sense?

**Comment by dlmarion** [comment]
I'm having a similar issue, but I'm not using Telegraf or Influx. I have a test case where I'm using the `StatsdMeterRegistry` with the `StatsdFlavor.DATADOG` flavor. My client is always receiving a `1` but I can see the value being incremented in the logs on the server side. I'm curious if [this](https://github.com/micrometer-metrics/micrometer/blob/main/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdCounter.java#L47) is the issue. It appears to be emitting the amount incremented instead of the current count. So, instead of:

```
            sink.next(lineBuilder.count((long) amount));
```

should it be?

```
            sink.next(lineBuilder.count((long) count()));
```
