### ISSUE TITLE
Ensure Micrometer can be compiled to native image with JDK 17 based GraalVM

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#2777]
This is a follow-up to #2670, since JDK 17 is released now, and a JDK 17 based GraalVM 21.3.0 is planned to be released in October.

**Comment by jonatan-ivanov** [comment]
Compiling with native-image works with Java 17-based Graal (as well as with the 11-based).

The Graal Conditional Configuration for Reflection can only add conditional config based on available classes:
>The only currently supported condition is typeReachable

Theoretically, we can add a check for a class that was [added after Java 13](https://javaalmanac.io/jdk/17/apidiff/13/) e.g.: `java.lang.Record` but that would be a really nasty hack.

Since `getSystemCpuLoad` (deprecated) calls `getCpuLoad`, I think we can leave the reflection config as is for now and let the Graal Team know that supporting additional conditions would be great, e.g.: enums so that we can use `SourceVersion.RELEASE_14`.
