### ISSUE TITLE
'?' in tag causes it not being forwarded to Telegraf via statsd

### ISSUE THREAD

**Issue by mbanaszkiewicz-vonage** [micrometer-metrics/micrometer#2840]
This might be an issue in Telegraf, or perhaps some documentation should mention escaping the question mark is required.

Context & steps to reproduce are available here: https://github.com/spring-projects/spring-boot/issues/28393 - looks like all is good on spring-boot actuator side.

**Comment by mbanaszkiewicz-vonage** [comment]
So the real issue is that telegraf statsd plugin does not accept '?' right? 

An explanation I've got is that we don't need exact request stats, and avg/min/max/stddev calculated by statsd plugin is enough.

**Comment by shakuzen** [comment]
> So the real issue is that telegraf statsd plugin does not accept '?' right?

It accepts it in so much as there is no error. It sanitizes it. You could request they not do that, but that would not be a change in Micrometer.

> An explanation I've got is that we don't need exact request stats, and avg/min/max/stddev calculated by statsd plugin is enough.

I'm assuming this was in response to why you are using statsd protocol instead of influxdb protocol. Micrometer will calculate and publish sum/count/average/max for timers in influxdbd protocol with the InfluxMeterRegistry. The difference between doing it in statsd protocol and doing it in your application with Micrometer is whether you need to ship a statsd line over the network for each measurement or not. What you get in the end is very similar. If you time a million requests in a minute, that's a million statsd lines published versus one influxdb histogram type with 4 fields in that minute.

**Comment by jonatan-ivanov** [comment]
Closing as it seems to be fixed: https://github.com/influxdata/telegraf/issues/10113
