### ISSUE TITLE
Remove suffix _total for counters in PrometheusNamingConvention

### ISSUE THREAD

**Issue by CarlosPanarello** [micrometer-metrics/micrometer#2881]
There is no need of adding _total suffix in counter metric when using prometheus registry in PrometheusNamingConvention class.

Since version 0.10 of prometheus-simpleclient they are adding the suffix _total in counter metrics.
This is done in [Collectors](https://github.com/micrometer-metrics/micrometer/blob/8e7f66670cbf33189f9aa3af99943444c5f2643a/implementations/micrometer-registry-prometheus/src/main/java/io/micrometer/prometheus/PrometheusNamingConvention.java#L65).

**Comment by shakuzen** [comment]
This has a surprisingly high number of upvotes. I must be missing some context. The scrape output would be the same either way, so I'm wondering why users are wanting this change. Could someone shed some light on it for me?

I think it would be more correct for our Prometheus naming convention to return the naming matching what will be in the scrape. This is complicated by the differences between Prometheus scrape format and OpenMetrics scrape format. The first below being Prometheus text format, and the latter being OpenMetrics text format. In Prometheus text format, the name of the counter includes `_total` so I would say that's what our naming convention should return, but OpenMetrics text format uses the name without `_total` and only the time series has `_total`, so I would say in that case it could be reasonable for our naming convention to not append `_total` to counter metrics names.

```
# HELP my_counter_total  
# TYPE my_counter_total counter
my_counter_total 1.0

# TYPE my_counter counter
# HELP my_counter  
my_counter_total 1.0
# EOF
```

**Comment by cyrilou242** [comment]
Hey @shakuzen, 
I'm in favour of appending `_total` to counters, but I have the following use case: 
I am migrating [an app](https://github.com/startreedata/thirdeye/blob/b16e284ec2ace879072b8d9242586f39790eb1a7/thirdeye-server/src/main/java/ai/startree/thirdeye/ThirdEyeServer.java#L151) from dropwizard metrics to micrometer.
This apps was generating prometheus counter metric without respecting the naming convention, because originally it was not even generating for prometheus. So it generates counter metrics  like `myCounterMetric`.
Because `_total` is appended with micrometer I am not able to generate the same metric name.
Not being able to generate the exact same metric name makes the migration more difficult because consumers of the metric could get broken.

**Comment by shakuzen** [comment]
@cyrilou242 you can always configure a custom `NamingConvention` if you need to do something non-standard. Would that not work for you use case?
