### ISSUE TITLE
tomcat_global_request_seconds_count value is always 0

### ISSUE THREAD

**Issue by BQsummer** [micrometer-metrics/micrometer#2906]
**Please describe the feature request.**
![image](https://user-images.githubusercontent.com/7424978/145369550-77d687b8-63ed-4721-a82d-b1d58bfdca83.png)
tomcat_global_request_seconds_count value is always 0, but request is continue, the last value is almost Integer.MAX_VALUE.

I debug in local machine : manual modify requestCount close to Integer.MAX_VALUE in org.apache.coyote.RequestInfo class, then request api, the reqeustCount becomes a negative number; in prometheus endpoint, tomcat_global_request_seconds_count is 0.
![image](https://user-images.githubusercontent.com/7424978/145370721-8447c9cd-14eb-4940-a195-272de8557e55.png)

**Rationale**
it seems that: tomcat use int to count the request, if requestCount is lager  than Integer.MAX_VALUE, it will becomes a negative number; in io.micrometer.core.instrument.cumulative.CumulativeFunctionTimer, when call count(), it select the max of zero and count, so tomcat_global_request_seconds_count value is always 0.
```
    /**
     * The total number of occurrences of the timed event.
     */
    public double count() {
        T obj2 = ref.get();
        return obj2 != null ? (lastCount = Math.max(countFunction.applyAsLong(obj2), 0)) : lastCount;
    }
```
how can I fix this problem?

**Additional context**
sorry for my poor english

**Comment by shakuzen** [comment]
Thank you for the detailed report of the issue. Ideally this would be fixed in Tomcat to use a long to not overflow as quickly. I'm not sure it would be a good idea for us to do something on our end to interpret negative numbers as overflowed integers.

If you are using some web framework for handing requests, you can probably get a request count from those metrics with more detail and avoiding this overflow. Then you wouldn't need to use the Tomcat request count.

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2021. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
