### ISSUE TITLE
StatsdMeterRegistry  TCPClient ConnectionProvider properties are not taking effect 

### ISSUE THREAD

**Issue by shirapur01** [micrometer-metrics/micrometer#2917]
**Describe the bug**
The TCPClient ConnectionProvider properties are not taking effect 

I have cloned the micrometer code locally and updated the connectionProvider properties under.

https://github.com/micrometer-metrics/micrometer/blob/a6fe623aab1e664e261ff2a94daf2e794a8ff728/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdMeterRegistry.java#L256

```java
create(ConnectionProvider.builder("builder")
                .maxConnections(2)
                .pendingAcquireTimeout(Duration.ofSeconds(60))
                .maxIdleTime(Duration.ofSeconds(10))
                .maxLifeTime(Duration.ofSeconds(10))
                .build())
                .host(statsdConfig.host())
                .port(statsdConfig.port())
                .handle((in, out) -> out
                        .sendString(publisher)
                        .neverComplete()
```

But when I run the micrometer code , I see that the above properties are not taking effect. 

**Environment**
Mac local environment and in AWS ec2 instance.
 - Micrometer version  -> 1.8.1
 - Micrometer registry ->  StatsdMeterRegistry
 - OS: macOS
 - Java version: Amazon Corretto 11

**To Reproduce**
1. start the application using micrometer registry 
2. update the connection provider properties 
3. Send the metrics every 30 seconds 

Expectation :
Every 10 second the new connection needs to be crated as the metrics are emitted at every 30 second

Actual:
The new connections are not getting created , the same connection is used until we terminate the application

**Comment by shirapur01** [comment]
Created the following [issue](https://github.com/reactor/reactor-netty/issues/1937) on the reactor netty and below is there response -> 
TcpClient connections are not returned to the pool automatically by Reactor-Netty. This responsability lies with the user/framework because they're the only one to know if the actual protocol is compatible with reusing connections.

**Comment by jonatan-ivanov** [comment]
Since we don't support customizing the TcpClient, I assume you implemented your own StatsdMeterRegistry. Given this, I'm not sure if this is a Micrometer bug: since you can't modify those parameters, and using the same connection as long as we can is the intended behavior, I'm not sure what needs to be fixed.

Please check the comments from Violeta and Simon on the linked issues, it seems you need to implement this behavior if you want to change it (their comments and the HttpClient can help).
Please let us know if I misunderstand something and we should reopen this issue.
