### ISSUE TITLE
"Direct to Datadog API Approach" resolves apiKey to null

### ISSUE THREAD

**Issue by ovk-hbomax** [micrometer-metrics/micrometer#2995]
**Describe the bug**
For spring boot `2.7.0-M1` and micrometer-datadog: `implementation 'io.micrometer:micrometer-registry-statsd:latest.release'`, spring is not able to resolve dd api key provided in `application.yml`.

**Environment**
 - Micrometer version: [2.0.0-M1]
 - Micrometer registry: [datadog]
 - OS: [e.g. macOS]
 - Java version: 11

**To Reproduce**
How to reproduce the bug:
Add this to `application.yaml`:
```
management:
  info:
    git:
      mode: full
  metrics:
    distribution:
      percentiles:
        http:
          server:
            requests: 0.5, 0.95, 0.99
      percentiles-histogram:
        http:
          server:
            requests: true
      sla:
        http:
          server:
            requests: 200ms, 400ms, 600ms
    export:
      datadog:
        step: 30s
        enabled: true
        api-key: xxxx # add your api key
    tags:
      application: ${spring.application.name}
      env: ${spring.profiles}
```
Set following dependencies in build.gradle:
```
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.cloud:spring-cloud-starter-config'
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    compileOnly 'org.projectlombok:lombok'
    implementation 'org.springframework.cloud:spring-cloud-starter-bootstrap'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    implementation 'io.micrometer:micrometer-registry-datadog:latest.release'
    datadogagent("com.datadoghq:dd-java-agent:$datadoghq_dd_version")
//	implementation("io.opentracing:opentracing-api:${opentracing_version}")
//	implementation("io.opentracing:opentracing-util:${opentracing_version}")
    implementation("com.datadoghq:dd-trace-api:${datadoghq_dd_version}")
```
**Expected behavior**
Spring boot should start as expected.

**Additional context**
I tried using 1.2 approach mentioned here: https://micrometer.io/docs/registry/datadog and it seems to work. Not sure why first approach is not working. Also developers of micrometer, can you elaborate more on why approach 1 is better?

**Comment by ovk-hbomax** [comment]
Added a SO question: https://stackoverflow.com/questions/70997020/datadog-apikey-was-null-but-it-is-required

**Comment by shakuzen** [comment]
I've answered your StackOverflow question over there.
> can you elaborate more on why approach 1 is better?
Direct to Datadog using the API is more efficient and scales better than statsd because statsd requires shipping one metric line per recording of a measurement. The direct approach instead only publishes once per interval. If you have a Timer with the default configuration, it will produce 4 time series (sum, count, average, max) per step interval with the direct approach, regardless of how many recordings are made on that Timer. With the statsd approach, one statsd line needs to be published for each recording. If you are recording metrics many times per second, this may be of concern for you. By shipping more metrics lines more often, the statsd approach generates more garbage that needs to be collected and more network traffic. For example, if you record timing for one thing 100 times per second, that will be 6000 statsd lines per minute versus 4 time series per minute for the default configuration with the direct to datadog approach.
