### ISSUE TITLE
Failed to bind as io.opentracing.contrib.concurrent.TracedScheduledExecutorService is unsupported.

### ISSUE THREAD

**Issue by deadpoet037** [micrometer-metrics/micrometer#3006]
I am seeing a lot of:
"Failed to bind as io.opentracing.contrib.concurrent.TracedScheduledExecutorService is unsupported."

This started happening with the spring boot version update to 2.6.3. Find the following dependency from pom.xml
```xml
        <dependency>
            <groupId>io.opentracing.contrib</groupId>
            <artifactId>opentracing-grpc</artifactId>
            <version>0.2.3</version>
        </dependency>
        <dependency>
            <groupId>io.opentracing.contrib</groupId>
            <artifactId>opentracing-spring-jaeger-cloud-starter</artifactId>
            <version>3.3.1</version>
        </dependency>
```
micrometer version: 1.8.2

Any direction or help will be grateful

**Comment by shakuzen** [comment]
I'm going to take a guess and say that there are`TracedScheduledExecutorService` beans in your application. As mentioned in Spring Boot's 2.6 [release notes](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes#task-execution-and-scheduling):
> Micrometer’s `ExecutorServiceMetrics` are now auto-configured for all `ThreadPoolTaskExecutor` and `ThreadPoolTaskScheduler` beans, as long as the underlying `ThreadPoolExecutor` is available.

That exception happens when we don't know how to unwrap the executor service to get metrics from it.

**Comment by marcingrzejszczak** [comment]
Closing this issue because OpenTracing is a deprecated project.
