### ISSUE TITLE
[Q] Change push interval for AzureMonitorMeterRegistry with spring boot 

### ISSUE THREAD

**Issue by MelleD** [micrometer-metrics/micrometer#3031]
Is it possible to set the Metric push interval for the AzureMonitorMeterRegistry in the application.properties for spring boot?

Tried, but didn't work
`management.metrics.export.azuremonitor.step=30s`

Not sure which projects is the right place see https://github.com/microsoft/ApplicationInsights-Java/discussions/2123

**Comment by shakuzen** [comment]
There's not enough information provided to know how your `AzureMonitorMeterRegistry` is being configured. Spring Boot does not provide auto-configuration for `AzureMonitorMeterRegistry`. There used to be [this azure-spring-boot-metrics-starter](https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-2x-micrometer#using-spring-2x) but it seems to be deprecated now in favor of Application Insights Java. As far as I can tell, that doesn't use the `AzureMonitorMeterRegistry` at all.

If instead of using the Azure Application Insights Java mentioned above you want to configure `AzureMonitorMeterRegistry` in a Spring Boot application yourself, you should provide an `AzureMonitorMeterRegistry` as a bean, and Spring Boot will bind metrics to it. If you want to customize the configuration, like the step interval, you can do that in the `AzureMonitorConfig` you use when constructing the `AzureMonitorMeterRegistry` bean.
