### ISSUE TITLE
Micrometer Metrics with high cardinality tags resulting in OOM issue (Java heap space)

### ISSUE THREAD

**Issue by dineshv1234567** [micrometer-metrics/micrometer#3038]
**OutOfMemory Issue found with Micrometer counter metrics**
I have implemented Micrometer counters in my Spring Boot application. They have tag value that is unique for every request. So, with every request, new metrics are created. Let's say, it is server_request metrics. When the application is running for a longer time, the heap space gets consumed with new metrics and eventually resulting in the OutOfMempory issue and pod restarts. Looks like, these are not garbage collected.
From the resources present online, others are also facing a similar issue and they have suggested some workaround to resolve this as of now:
1. Use `MeterFilter#maximumAllowableTags`, when the tag is reached max, the new tag will be discarded and garbage collected. Basically ignoring the metrics coming after max numbers.
_Disadvantage_: It will create metrics with fixed numbers only. What if I want to create metrics that are huge in numbers.
_Link_: https://github.com/micrometer-metrics/micrometer/issues/1830
3. To normalize or remove the high cardinality tags.
 _Ask_: Then is there anyway apart from the counter, where I can generate a unique value associated with tag with Micrometer object
_Link_: https://stackoverflow.com/questions/69217202/micro-meter-high-memory-usage

As one bug is already opened and still not resolved. Is this bug is in processing? Or is there any way to resolve this issue

**Environment**
 - Micrometer registry: `'io.micrometer:micrometer-registry-prometheus:1.8.0'`
 - Spring Boot version: 2.6.2
 - Java version: 17

**Comment by checketts** [comment]
I'm not sure what the bug is here. High cardinality tags will take up memory, there are features to limit that (like `MeterFilter#maximumAllowableTags`) if the code isn't trying to address it.

Metrics are intended to be aggregate, not debugging individual requests.

Can you help us understand your usecase for needing the high cardinality tags and perhaps the queries you intend to use with them?

Request details would belong in a log message, and the metrics would indicate an outlier or need to check the logs.

**Comment by checketts** [comment]
Yeah. I think you shouldn't do that.  ;) You'll run out of memory. (But you already knew that)

**Comment by jonatan-ivanov** [comment]
>I want to register Metrics counter for each HTTP server request with its tag as a unique identifier which will be unique for each request.

Please think about this as trying to store "infinite" amount of data in a non-infinite space. Also, let's pretend for a moment that you have "infinite" RAM or Micrometer does some magic and it can store "infinite" amount of data. In this case you will have the same problem on your metrics backend: it needs to store the data somehow and if that data is "infinite", it will be in trouble.

You can use high cardinality data in other systems like in your logs or you can also take a look at [distributed tracing](https://docs.spring.io/spring-cloud-sleuth/docs/3.0.x/reference/htmlsingle/#getting-started-introducing-spring-cloud-sleuth). They can handle high cardinality tags since they are not storing and aggregating them (they don't need to).

Micrometer can protect you and your app's memory consumption against accidentally creating high-cardinality tags `MeterFilter::maximumAllowableTags` but it can't really help you if you are willingly doing it.

Please let us know if I misunderstood something and we can reopen this issue.
