### ISSUE TITLE
version 1.0.3 risk of memory leak in monitor on RestTemplate

### ISSUE THREAD

**Issue by JonathanJohonson** [micrometer-metrics/micrometer#3086]
A default meter filter in created In the method below may cause memory leak if you call RestTemplate.exchangewith a queryString on url string or URI object in your program. 
io.micrometer.core.instrument.config.MeterFilter#maximumAllowableTags
The reason is that the observedTagValues in the MeterFilter is not size-limited and the action of ADD is executed before a size checking.
A memory leak may happen if you use queryString to carry param like sign or requestId.
It seens that this problem is resolved In the newest version. If you still using the old ver, a simple resolve way is creating a bean of RestTemplateExchangeTagsProvider, overwriting the way of getting uri tag.

**Comment by jonatan-ivanov** [comment]
I'm not 100% sure I understand this but:
- 1.0.3 is not supported anymore, the current version is 1.8.4 and 1.9.0 is coming soon
- If you add tags like `requestId`, you already have a memory leak potential since the tag is likely to have high cardinality

I'm closing this issue, please let me know if I misunderstood something and we can reopen.
