### ISSUE TITLE
adding some more attributes with dynamic values in LoggingMeterRegistry

### ISSUE THREAD

**Issue by habeep** [micrometer-metrics/micrometer#3089]
I am using @Timed annotation to measure the performance metrics and using logback. If you look at my below log, some of the attributes values (correlationId, requestId, traceId) are coming as empty but values are available in MDC. I want to inject those values dynamically from/through LoggingMeterRegistry.

{"ts":"2022-03-21T16:51:05.159+0000","level":"INFO","type":"Business","application":"my-web-service","operation":"","suboperation":"","correlationid":"","requestid":"","traceid":"","spanid":"","parentid":"","sessionid":"","customer":"","userid":"","auditid":"","httpmethod":"","url":"","requestparams":"","remoteip":"","port":"","channel":"API","mccustomer":"","mcproduct":"","mcrequestdomicile":"","responsetime":"","thread":"logging-metrics-publisher","logger":"i.m.c.i.logging.LoggingMeterRegistry","message":"DSE-WS{class=com.habeep.service.impl.ControlPersistenceServiceImpl,exception=none,method=saveRequests} throughput=0.016667/s mean=0.2750926s max=0.2750926s"}

Spring boot version: 2.3.10.RELEASE
Java version: 11

Can you please help me to add those attributes with dynamic values which I can get it from MDC.

MetricConfig.java

@Configuration
@RequiredArgsConstructor
@EnableAspectJAutoProxy
public class MetricConfig {

    private final Clock micrometerClock;

    @Bean
    TimedAspect timedAspect(MeterRegistry registry) {
        return new TimedAspect(registry);
    }

    @Bean
    public LoggingMeterRegistry loggingMeterRegistry() {
        LoggingMeterRegistry loggingMeterRegistry = new LoggingMeterRegistry(LoggingRegistryConfig.DEFAULT, micrometerClock);

        loggingMeterRegistry.config().meterFilter(new MeterFilter() {

            @Override
            public DistributionStatisticConfig configure(Meter.Id id, DistributionStatisticConfig config) {
                return DistributionStatisticConfig.builder().expiry(Duration.ofHours(1)).build().merge(config);
            }
        });

        return loggingMeterRegistry;
    }

}

**Comment by habeep** [comment]
@jchambers @shakuzen can you please help on this?

**Comment by jonatan-ivanov** [comment]
I'm not sure Micrometer is the right tool for what you want.
`LoggingMeterRegistry` publishes the **aggregated** data at every minute (by default). For this, it is using a separate thread pool (check `PushMeterRegistry`).
Because of this, the following questions could be interesting:
1. What exactly do you want to be logged out for request-scoped fields (like `requestId`) when you have an aggregated log event for every minute (assuming you have more than one request per minute)?
2. A lot of the fields above (like `requestId`) has high cardinality data which is not very suitable for metric libraries or metric backends
3. MDC is a `ThreadLocal`; since `LoggingMeterRegistry` is logging from a thread pool, you will not see things that you put into the MDC from other threads, you need to propagate the MDC
