### ISSUE TITLE
Performance of Timer with publishPercentiles

### ISSUE THREAD

**Issue by asurovenko-zeta** [micrometer-metrics/micrometer#3101]
Hello
I have the service for measure the time for my pipeline's steps.
Here is my code:
```
Map<String, Timer> timerCacheMap = new ConcurrentHashMap<>();
        .......
        timerCacheMap.computeIfAbsent(stepName, c -> Timer.builder("STEP_TIME")
                        .publishPercentiles(0.5, 0.75, 0.95, 0.99, 0.999)
                        .tag("STEP", c)
                        .minimumExpectedValue(MIN_EXPECTED)
                        .register(getRegistry()))
                .record(time, TimeUnit.NANOSECONDS);
```
_timerCacheMap_ just for cache Timer's object

I need just chart with percentiles of my steps time.

And **JavaFlightRecorder** said that **.record(..,..)** takes many recourses.
Maybe there's better way to do that?

<img width="627" alt="Screenshot" src="https://user-images.githubusercontent.com/80847074/160633759-f342c94a-abb3-4a9c-b40b-8d8a3b1cddd5.png">

**Comment by jonatan-ivanov** [comment]
I'm not sure what you are referring to, I don't see recursive calls in this stacktrace.
Could you please be more specific and show us where the issue is? If you have any proposed fixes, hat would be even better.

There are two more things I would like to note:
1. We usually recommend using `publishPercentileHistogram`, see the [docs](https://micrometer.io/docs/concepts#_histograms_and_percentiles) and calculating the percentiles on the backend-side.
2. You don't need to cache `Timer`s, the registry does this for you, when you build a new Timer, it will only create a new `Timer` instance when one does not already exists. If there is an existing one, it will use that.

**Comment by shakuzen** [comment]
Closing due to lack of feedback. If we get more details, we can take a closer look at things.
