### ISSUE TITLE
Broken support for the Datadog "host" tag

### ISSUE THREAD

**Issue by sambishop** [micrometer-metrics/micrometer#3130]
**Describe the bug**
The `String` returned from the `hostTag` method of the `DatadogConfig` interface is not included in the JSON published to the Datadog ingestion servers.

**Environment**
 - Micrometer version: 1.8.4
 - Micrometer registry: micrometer-registry-datadog

**To Reproduce**
Provide a host name by implementing the `DatadogConfig` interface or assigning `management.metrics.export.datadog.host-tag` a value in your Spring Boot `application.properties` file.

**Expected behavior**
The code should publish JSON to Datadog.  Borrowing from a comment in the code, the JSON should look similar to this:
```
{
    "series": [{
        "metric": "test.metric",
        "points": [[$currenttime, 20]],
        "host": "test.example.com",  <-- This attribute is left out, even if the host name has been set.
        "type": "count",
        "unit": "millisecond",
        "tags": "environment:test"
    }]
}
```

**Additional context**
There appears to be a bug in the `DatadogMeterRegistry::writeMetric()` method.  Assuming that a meter-specific `host` tag should take priority over the `hostTag` `DatadogConfig` value, we modified the code in this way:

```
        // Create host attribute
        String hostname = stream(tags.spliterator(), false)
                .filter(t -> "host".equals(t.getKey()))
                .findAny()
                .map(Tag::getValue)
                .orElse(config.hostTag());
        String host = hostname == null ? "" : ",\"host\":\"" + hostname + "\"";
```

The above replaces existing code in that method which is also prefixed with a `// Create host attribute` comment.

**Workaround**
Set the host name in one of the ways described above.  Then, when you create your meters, add a tag where both the name and value is the host name.  Depending on the meter type, it would look something like this:
```
Metrics.timer("<timer name>", "<host name>", "<host name>");
```

**Comment by shakuzen** [comment]
It sounds like we could do better describing the behavior of the `hostTag` configuration option. The configuration option doesn't set the `host` tag value published to Datadog. It specifies which tag key from which to get the value. The intention is that this makes things more portable across metrics backends. The host is set as a tag on your metrics regardless of the metrics system you are using, and you specify which tag key to map from for Datadog's special `host` key.

Do you have any suggestions for how we could make this more clear to avoid confusion?

The JavaDoc for it currently is:

> The tag that will be mapped to "host" when shipping metrics to datadog.

And in the reference docs, its behavior is described towards the end of [this section](https://micrometer.io/docs/registry/datadog#_direct_to_datadog_api_approach).

> `DatadogConfig.hostTag()` specifies a tag key that is mapped to [the host field](https://docs.datadoghq.com/api/v1/metrics/#submit-metrics) when shipping metrics to Datadog. For example, if `DatadogConfig.hostTag()` returns `host`, the tag having `host` as its key is used. You can set the tag by using common tags, as follows:
> ```java
> registry.config().commonTags("host", "my-host");
> ```

**Comment by sambishop** [comment]
Ah, I see.  Thank you for your patience, and for explaining this to me.

I didn't know that documentation existed.  I had only found the documentation at https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator.metrics.export.datadog, which doesn't mention `host-tag`.  (I am working with a Spring Boot app.)  I got as far as I did by reading the code for the registry.  Do you have the ability to suggest changes to the Spring documentation?  What is currently there seems insufficient.

My only suggestion regarding the Micrometer documentation would be to include `management.metrics.tags.host` in the example Spring Boot configuration.  That seems like a better default approach than using `registry.config().commonTags()`, for a Spring Boot app.  (I didn't mention `management.metrics.tags.host` in my "workaround" above because I only just learned about it.  But it seems like the better way to go.)

**Comment by shakuzen** [comment]
I can't speak for the Spring Boot team, but I think their intention is to not duplicate documentation and defer to the underlying project to have the canonical documentation. They are mentioning required configuration properties in their documentation because a Spring Boot application will not startup without configuring that when that auto-configuration is enabled. They do link to the Micrometer docs for the Datadog registry in that section, though. And `host-tag` is mentioned in [the appendix](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#application-properties.actuator.management.metrics.export.datadog.host-tag), though I can understand how that gets missed from the linked datadog section of the docs. Perhaps the link to Micrometer docs could be more directly called out as such. What do you think?

On the other side, in Micrometer documentation, we are trying to be generic. Our documentation does mention Spring Boot configuration properties as an example, but Micrometer does not depend on Spring, which is why the documentation refers to the `hostTag()` method and to `registry.config().commonTags("host", "my-host")` which is available to all Micrometer users, regardless of whether they are using Spring Boot or not. It does so happen that if you are using Spring Boot, you probably will prefer `management.metrics.tags` for setting common tags.

So it is a challenge to strike a balance of having the documentation discoverable to a user without duplicating documentation in multiple places, which leads to drift and maintenance problems, while also keeping the appropriate level of detail according to the context.
