### ISSUE TITLE
OTLP resource service name is always unknown

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#3146]
We should provide a way for the `service.name` to be configured. The simplest way would be a configuration option that passes through as is. There is a preference to aim for something more portable, though, since other registries may not have an explicit concept of `service.name` but would benefit from one being configured and consistent with the `service.name` publish in OTLP format.

_Originally posted by @shakuzen in https://github.com/micrometer-metrics/micrometer/pull/3129#discussion_r850723274_

**Comment by jonatan-ivanov** [comment]
Since it's very close to this, I'm wondering if we should do something with the `language` too.
Right now `"java"` is hardcoded but I'm not sure what should be there if the app was written in Groovy (or it is polyglot, e.g.: Java + Groovy). I think we should probably keep it as `"java"` since it runs on the JVM (Graal/SubstrateVM?).
