### ISSUE TITLE
CPU load increased 10x between 1.7.0 and 1.7.2 in native mode (Quarkus)

### ISSUE THREAD

**Issue by ebullient** [micrometer-metrics/micrometer#3170]
Details and reproducers are here in https://github.com/quarkusio/quarkus/issues/19359, the issue is summarized in this comment: https://github.com/quarkusio/quarkus/issues/19359#issuecomment-1092779086

> I did some more testing in the past few days. CPU allocation graphs did not show anything obvious but I found out that the cpu spikes are related to a change in [micrometers reflection-config.json](https://github.com/micrometer-metrics/micrometer/blob/v1.7.2/micrometer-core/src/main/resources/META-INF/native-image/io.micrometer/micrometer-core/reflect-config.json). This file was not present before 1.7.2 (or maybe 1.7.1) and building my application with the latest micrometer version (1.8.x) but without this file also solved the cpu spikes for me.

**Comment by shakuzen** [comment]
If I'm reading and understanding all the comments in the other thread, it's an issue with the file descriptor metrics in native mode but only on AWS. That's interestingly specific.

**Comment by shakuzen** [comment]
Thanks for letting us know about this. Hopefully this issue will help other Micrometer users affected by this with the answers in https://github.com/quarkusio/quarkus/issues/19359. Ultimately, I don't know of anything we can do in Micrometer itself to mitigate this. If users are fine without file descriptor metrics, they can use a `MeterFilter` to disable them until they can upgrade to GraalVM 22.2. Similar to https://github.com/micrometer-metrics/micrometer/issues/3121, this will be fixed by https://github.com/oracle/graal/pull/4383 in GraalVM. It could be worth seeing if the GraalVM team will consider a patch fix to 22.1, but I think a patch release containing a fix would be released at the same time as 22.2.0

I'm closing the issue due to no changes to be made in Micrometer. If someone has an idea of a change we could make to help with this, we can reconsider.
