### ISSUE TITLE
Adding metrics for request and response byte size in GRPC client interceptors

### ISSUE THREAD

**Issue by debraj-manna** [micrometer-metrics/micrometer#3180]
**Please describe the feature request.**
Add new metrics for request and response byte size in GRPC client interceptors

**Rationale**
Add new metrics to get wire format byte size of request and response as described [here](https://stackoverflow.com/questions/59245890/how-to-measure-the-size-of-grpc-response).

**Comment by marcingrzejszczak** [comment]
Thank you for filing the issue. Do you happen to know how to retrieve these metrics in Java?

**Comment by debraj-manna** [comment]
No I am not sure about the correct implementation for this in Java,

**Comment by marcingrzejszczak** [comment]
@ttddyy any idea?

**Comment by ttddyy** [comment]
I looked into the grpc java code, and it seems determining the message size is transport implementation dependent.
For example, in-memory transport, [this](https://github.com/grpc/grpc-java/blob/master/inprocess/src/main/java/io/grpc/inprocess/InProcessTransport.java#L236-L249) is the place for checking the size. [Here](https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/MessageDeframer.java#L387-L393) is for netty.


I don't think it is feasible for micrometer to obtain the raw message size unless gRPC provide a way to reliably provide the message size to the interceptor since micrometer instrumentation is implemented by the interceptor.

**Comment by marcingrzejszczak** [comment]
Ok let's close it then since it seems it's not possible to be done at this point. If it becomes possible we can come back to this, WDYT?
