### ISSUE TITLE
Idea: Provide Possibility to extract timers and counters from tracing seperately

### ISSUE THREAD

**Issue by JotBePunkt** [micrometer-metrics/micrometer#3192]
With the new observation API, you can now extract timers from observations (see here: https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/observation/TimerObservationHandler.java). I would like to be able to extract timers and counters with different tag sets. The idea would be to define tag set or tag filters for counters and timers seperately so that you can have a small amount of timers and more detailed counters, maybe have a function that calculates the tag value (e.g. to get an abstraction of the tag values).

An API could look like that: 
```
var observationHandler = MeterObservationHandler.builder().
                                              meterRegistry(meterRegistry)
                                              counterTags("tenant", "messageType").
                                              timerTags(); // no tags at all for the timer                                        
```

**Rationale**
We have microservices processing messages of different type and for different tenants. In the beginning when we instrumented our code, we used to add timers with tags for both message type and tenant. In the meantime we know that this was a bad decission. A) By multiplying out the tenants, message type, le, pod, ... one single component produces that many bucket counters, that the performance of Prometheus calculating the `percentile()` function got really bad ending up in timeouts or even crashes (due to too much memory usage for these query) . B) We noticed, that for the operation it is not relevant how fast a specific message for a specific type is. In many cases, all messages are treated the same way, therefore the performance is the same over all tenants and message types, so a single timer over all is enough  while a counter with tags for tenants and message types makes sense (e.g. to answer the question how much traffic does a specific tenant cause).  

In rare cases some message types are processed differently and therefore have different processing times. Example: when processing message type A and B we store something in the database while for message type C and D we just send another message and message type E and F are ignored. In that case a timer over everyhing would not give that much sense because it might range from a few nanoseconds (for the ignored message types) to several seconds (in the worst case for storing something in the database). I that case it would make sense to distinguish between theses abstract message types (`stored`, `ignored` and `normal`) while having timers for every single message type whould be potentially too much (in cases when you not only have 6 message types like in this example but in the range between 10-100.

**Comment by shakuzen** [comment]
Thank you for checking out the new features in milestone releases and providing feedback. That's really valuable for us to verify the direction we're going makes sense for real use cases. Thank you for all the details too.

For your use case, you could achieve that with two separate observation handlers. One to make Timers without the tenant/type tag, one to make the counters with all the tags. That may not feel as nice as the API you proposed, but in general, we discourage making a counter and timer for the same instrumentation. We write in [the documentation](https://micrometer.io/docs/concepts#_counters):

> Never count something you can time with a `Timer` or summarize with a `DistributionSummary`! Both `Timer` and `DistributionSummary` always publish a count of events in addition to other measurements.

In your use case, it sounds like following that advice leads to performance issues at query time. Is this a problem even when aggregating without the labels you don't care about for percentiles? Also perhaps worth considering: is there a natural upper bound on the latency being measured on messages like a processing timeout? Setting the max expected could reduce the number of buckets to alleviate the performance issues. Otherwise, it sounds like perhaps the characteristics of your use case may be unique enough to go against the general advice.
What do you think?

**Comment by jonatan-ivanov** [comment]
Somewhat related: https://github.com/micrometer-metrics/micrometer/issues/3100
