### ISSUE TITLE
TimeWindowMax#record causes allocation

### ISSUE THREAD

**Issue by agusevas** [micrometer-metrics/micrometer#3193]
Some methods in `TimeWindowMax` class produce garbage because of usage of capturing lambdas. For example:

```
    public void record(double sample, TimeUnit timeUnit) {
        record(() -> (long) TimeUtils.convert(sample, timeUnit, TimeUnit.NANOSECONDS));
    }

    private void record(LongSupplier sampleSupplier) {
        rotate();
        long sample = sampleSupplier.getAsLong();
        for (AtomicLong max : ringBuffer) {
            updateMax(max, sample);
        }
    }
```

Every time the `record(double sample, TimeUnit timeUnit)` is called, a new lambda instance will be created. See example memory allocation profiler stack trace: 
<img width="703" alt="CleanShot 2022-05-24 at 09 08 01@2x" src="https://user-images.githubusercontent.com/3429466/169970138-c2acbf0b-724f-453b-9c50-8f27a97678dc.png">

**Environment**
 - Micrometer version: 1.8.5
 - Micrometer registry: prometheus
 - OS: macOS
 - Java version: 17

**To Reproduce**
How to reproduce the bug:
```
import java.util.concurrent.TimeUnit;

import org.junit.jupiter.api.Test;

import io.micrometer.core.instrument.Timer;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;

public class TimeWindowMaxMemoryAllocation {

	@Test
	void timeWindowMax() {
		SimpleMeterRegistry meterRegistry = new SimpleMeterRegistry();
		Timer timer = Timer.builder("timer").register(meterRegistry);
		for (int i = 0; i < 1_000_000; i++) {
			timer.record(1, TimeUnit.MILLISECONDS);
		}
	}
}
```

Run the test using memory allocation profiler. Sample result:
<img width="940" alt="CleanShot 2022-05-24 at 09 28 49@2x" src="https://user-images.githubusercontent.com/3429466/169973991-ee583412-c6e2-456e-b2f5-419559fe47bb.png">

**Expected behavior**
Garbage creation is reduced in `TimeWindowMax` class.

**Additional context**
See https://www.infoq.com/articles/Java-8-Lambdas-A-Peek-Under-the-Hood/ for more information about the capturing lambdas.

**Comment by shakuzen** [comment]
I did quite a bit of investigation for this. It's a bit difficult to be certain about things because behavior can vary depending on the compiler and other factors. I do not see any garbage from the lambda in a heapdump, but I do see the same allocation you are seeing with the profiler. I think it's likely the allocation is happening on the stack due to escape analysis. If I add a breakpoint on the lambda and pause execution in it, then I can see garbage in a heapdump for the lambda instance. Since we don't need to use a capturing lambda here, and this is the hot path for recording, we should avoid the allocation.
As a separate issue, it would be nice if we can add tests and assertions about allocations to avoid this kind of problem.

**Comment by shakuzen** [comment]
@agusevas Thank you for reporting the issue. The fix is available in snapshots now (1.8.7-SNAPSHOT, 1.9.1-SNAPSHOT). I did not see the allocation in the memory profiler with these changes. Let us know if you still see allocation happening.

**Comment by x-ags** [comment]
@shakuzen Thank you for the fix. I have tested the `1.8.7-SNAPSHOT` version locally. The allocation issue is fixed now.

**Comment by agusevas** [comment]
@shakuzen Thank you for the fix. I have tested the 1.8.7-SNAPSHOT version locally. The allocation issue is fixed now.
