### ISSUE TITLE
Support graceful shutdown for the Executor returned from ExecutorServiceMetrics 

### ISSUE THREAD

**Issue by hugogu** [micrometer-metrics/micrometer#3250]
When `ExecutorServiceMetrics` is used to monitor a [ThreadPoolTaskExecutor](https://github.com/spring-projects/spring-framework/blob/main/spring-context/src/main/java/org/springframework/scheduling/concurrent/ThreadPoolTaskExecutor.java), it will be wrapped into the `TimedScheduledExecutorService` and lost the ability to handle the graceful shutdown that `ThreadPoolTaskExecutor` supports.

**Rationale**
As we know, `ExecutorServiceMetrics` is designed for JVM-based Executor and ExecutorService and may not be the desired scope to support a Spring specific `TaskExecutor` and its feature - graceful shutdown. 

But the lack of supporting graceful shutdown makes people have to make an exclusive choice between graceful shutdown provided by spring boot and metrics provided by micrometer. Regardless of what people choice, they are on their own to implement the part not chosen. And in most cases, the graceful shutdown would be considered a must-have for mature production-ready products, and this leaves `ExecutorServiceMetrics` in an awkward situation - it is super useful, but can't be used in production directly :-(. (Just like JVM itself, not many live with bare JDK these days.)

One possible way of monitoring Executor without wrapping it into a proxy class, `TimedScheduledExecutorService` in this case, is to proxy the target class itself by introducing some AOP framework. 

The only concern is, micrometer itself is clean, being independent against as few other frameworks as possible. Making it start depending on any specific injection framework or AOP framework may not be acceptable. 

Another possible way is, introducing a Spring specific standalone project/module to provide a Spring-based `TaskExecutorMetricBinder`. And this stand-alone project can help more than just generate metrics for TaskExecutor (with graceful shutdown retained), but also for a lot of other Spring specific staff, such as Cache and ScheduledJobs, etc. 

**Additional context**
This feature is quite useful in Spring-Boot-based application where the built in TaskExecutor supports lifecycle handling via [org.springframework.scheduling.concurrent.ExecutorConfigurationSupport](https://github.com/spring-projects/spring-framework/blob/main/spring-context/src/main/java/org/springframework/scheduling/concurrent/ExecutorConfigurationSupport.java). 

The spring community is also struggling with a similar problem (they don't use the value returned by ExecutorServiceMetrics at all because it is no longer a ThreadPoolTaskExecutor) and trying to find out a solution there. Please refer to https://github.com/spring-projects/spring-boot/issues/27041

**Comment by marcingrzejszczak** [comment]
@hugogu thank you for filing the issue. @bclozel do you have an idea how we could try to address this? The problem is about proper instrumentation option of `ThreadPoolTaskExecutor`. In fact we can't simply wrap the object without losing some of its benefits (I had the same problem with Spring Cloud Sleuth, were the least problematic option turned out to be creation of CGLIB proxies, however that was still buggy cause some of the methods were final).

**Comment by dmittriy13** [comment]
@marcingrzejszczak Hi, is there any news regarding this issue?

**Comment by marcingrzejszczak** [comment]
Let me page @bclozel again on this topic

**Comment by bclozel** [comment]
I'm not sure I'm getting the full picture here.
To collect metrics on `ThreadPoolTaskExecutor`, Micrometer provides a `TimedScheduledExecutorService` that delegates to a `ScheduledExecutorService`. Metrics works, but since it is a `ScheduledExecutorService`, the Spring-specific contract is gone once wrapper and users cannot access all features on the `ThreadPoolTaskExecutor` type.

> (I had the same problem with Spring Cloud Sleuth, were the least problematic option turned out to be creation of CGLIB proxies, however that was still buggy cause some of the methods were final).

I could not find any `final` method in the entire `ThreadPoolTaskExecutor` hierarchy, am I missing something?

In any case, it would be interesting to provide such an instrumentation in Spring Framework. Given the expected features and the fact that `ThreadPoolTaskExecutor` lives in the spring-context module, I don't think it would be wise to introduce a mandatory dependency on the metrics or observation API with a direct instrumentation. Instead, maybe Spring Framework could provide a dedicated wrapper or a JDK proxy (like Micrometer does for `JmsInstrumentation`) for this? What do you think @marcingrzejszczak ?

**Comment by marcingrzejszczak** [comment]
In Sleuth we were instrumenting all possible executors but with problematic outcome but that's because we couldn't handle types like `TPTE`. Why can't we add an optional depedency (if we don't do that already) and instrument TPTE natively with some checks if micrometer is on the classpath? If that's not an option then a wrapper or any sort of hook from within Spring Framework would be helpful

**Comment by bclozel** [comment]
After implementing a prototype, I'm not seeing much to be done on the Spring Framework side. See [this comment](https://github.com/spring-projects/spring-framework/issues/33021#issuecomment-2356419363).

I think this issue should be reopened to consider separating the binding of metrics on the executors from the wrapping of the executor to time tasks. With that change, developers could do the following:

```java
ThreadPoolTaskExecutor taskExecutor = //...
new ExecutorServiceMetrics(taskExecutor).bindTo(meterRegistry); // metrics are bound in the "monitor" methods

// then we can create custom observations timing specific tasks
MailMessage message = //...
Observation observation = Observation.createNotStarted("mail.send", observationRegistry);
observation.lowCardinalityKeyValue("mail.purpose", "order confirmation");
observation.highCardinalityKeyValue("mail.to", message.getTo());
taskExecutor.submit(observation.wrap(() -> sendMail(message)));
```

**Comment by hugogu** [comment]
@shakuzen The problem is about that `monitor` methods return a customized ExecutorService and lost graceful shutdown capability.  You are right that user can do something to get rid of this issue by implementing another ExecutorService that support graceful shutdown and metrics collection.

**Comment by shakuzen** [comment]
@hugogu But the code @bclozel shared works as is today without any change in Micrometer. It doesn't use the `monitor` methods. So I'm missing what the requested change is in Micrometer.
