### ISSUE TITLE
Bump prometheus client to 1.6.0

### ISSUE THREAD

**Issue by neiser** [micrometer-metrics/micrometer#3322]
Prometheus client is [released as version 0.16.0](https://github.com/prometheus/client_java/releases/tag/parent-0.16.0), including quite useful enhancements regarding exemplars:  Release happened on June 16, 2022.

I wonder why this wasn't included in Micrometer release 1.9.2 from 18 days ago (July 11, 2022). I couldn't find where this version is set, only [here it says `latest.release`](https://github.com/micrometer-metrics/micrometer/blob/main/dependencies.gradle#L38) For example, [here you can see that Micrometer 1.9.2 still uses prometheus client 0.15.0](https://mvnrepository.com/artifact/io.micrometer/micrometer-registry-prometheus/1.9.2).

Will it be included in 1.9.3 then?

**Comment by shakuzen** [comment]
> Will it be included in 1.9.3 then?

No. As a general rule, we do not upgrade to new minor versions of dependencies in a patch release. We would only upgrade to a new patch release in the same minor version. Our next minor version will pick up the latest minor version of the prometheus client at the time of its release.

The 1.10.0 development is already building against the prometheus client 0.16.0. You can try out pre-release milestones of that now until a GA version is released.

If you want to use version 0.16.0 of the prometheus client in your application, you can manage the version of it for your application, rather than use the version we declare. If there are breaking changes in the API we compile against, this won't work, but otherwise you should be able to use a different version than we declare.

**Comment by neiser** [comment]
@shakuzen Thanks for clarification. Will wait until 1.10.0 then!
