### ISSUE TITLE
Failed to create ObservationRegistry in Spring Boot

### ISSUE THREAD

**Issue by pirgeo** [micrometer-metrics/micrometer#3342]
**Describe the bug**
When running Micrometer in Spring Boot, I get an error when the Spring Boot app starts up, since the `TimerObservationHandler` seems to be missing from the classpath.
Error: 
```
Error creating bean with name 'observationRegistry' defined in class path resource [org/springframework/boot/actuate/autoconfigure/observation/ObservationAutoConfiguration.class]: io/micrometer/core/instrument/observation/TimerObservationHandler
```

See also https://github.com/pirgeo/micrometer-springboot-failing-example/blob/main/README.md for the stack trace.

**Environment**
 - Micrometer version: 1.10.0-M4
 - Spring Boot 3.0.0-SNAPSHOT, but also reproducible with 3.0.0-M4. Seems to work with 2.7.2
 - Micrometer registry: no registry, just Micrometer core
 - OS: tested on Win & Linux
 - Java version: 17

**To Reproduce**
How to reproduce the bug:
There is a complete sample here: https://github.com/pirgeo/micrometer-springboot-failing-example

Note that the Spring Boot and Micrometer versions are fixed.

**Expected behavior**
I expected the Spring Boot app to start without crashing, just as it did when running Micrometer `1.10.0-M3`

**Additional context**
I am not sure if this is a Micrometer or Spring Boot issue, but since it started when I updated the Micrometer registry and did not touch the Spring Boot version, I assume it needs to be fixed here (unless its expected, and will only work with the next Spring Boot version)

Potentially related: https://github.com/spring-projects/spring-boot/issues/31580

**Comment by jonatan-ivanov** [comment]
Thank you for the report and double thanks for the reproducer.
There are at least two issues here. One is visible if you run `./gradlew dependencies`:
```
+--- io.micrometer:micrometer-core:{strictly 1.10.0-M4} -> 1.10.0-M4
|    +--- io.micrometer:micrometer-commons:1.10.0-M4 -> 1.10.0-M3
|    +--- io.micrometer:micrometer-observation:1.10.0-M4 -> 1.10.0-M3
|    |    \--- io.micrometer:micrometer-commons:1.10.0-M3
```
As you can see, you get mixed versions because the Boot BOM wants to use M3 so you need to force them all:
```
implementation('io.micrometer:micrometer-core') { version { strictly '1.10.0-M3' } }
implementation('io.micrometer:micrometer-commons') { version { strictly '1.10.0-M3' } }
implementation('io.micrometer:micrometer-observation') { version { strictly '1.10.0-M3' } }
```
But if you do this, you will get a similar issue:
```
Caused by: java.lang.ClassNotFoundException: io.micrometer.observation.Observation$GlobalKeyValuesProvider
```
This happens because of a breaking change in M4 and since M4 was released yesterday, Boot still depends on M3. If you look into [`ObservationAutoConfiguration`](https://github.com/spring-projects/spring-boot/blob/41334223ffcc6d595807eec452a0387ab344e34b/spring-boot-project/spring-boot-actuator-autoconfigure/src/main/java/org/springframework/boot/actuate/autoconfigure/observation/ObservationAutoConfiguration.java) with your IDE, `GlobalKeyValuesProvider` should be missing and you should se an error (was removed in M4).

The fastest way to fix this is turning auto-config off for this class and doing this part "manually" but I think there isn't really any conditional that you can use for this in this particular case.
So I think the only option to try out M4 with the latest Boot snapshot right now is fixing the issue locally and building Boot on your own. I will ask the Boot Team about updating to M4 so that M4 should work with the latest Boot snapshot.

**Comment by pirgeo** [comment]
Thanks - I don't depend on it, just wanted to make sure this doesn't slip through the cracks 😄
