### ISSUE TITLE
Value discordance in summaries with concurrent record execution

### ISSUE THREAD

**Issue by ceremo** [micrometer-metrics/micrometer#3346]
**Please describe the feature request.**
We are facing sometimes (not frequently) a discordance in the reported summaries values (`max`, `counter`, `total`), the problem is the `record` of the `StepDistributionSummary` does not update their fields atomically ([record method](https://github.com/micrometer-metrics/micrometer/blob/fcb005d934fd5790df67c94178f933b76e7495c3/micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepDistributionSummary.java#L62)), so if you check the value of the metric while there is an execution of the summary record, it could give inconsistent values (only detected with `max` field).

**Rationale**
The execution of the `max.record(amount);` is quite logic heavier than the execution of the `count.add(1);` and `total.add(amount);`, so to try to minimize this behaviour, I'd move the `max.record(amount);` to execute firstly and the `count.add(1);` and `total.add(amount);` at the end.

**Comment by shakuzen** [comment]
Thanks for opening the issue. Indeed things are not updated atomically. However, with a `StepDistributionSummary`, the count and totalTime (and mean) returned will be for the previous step interval. So reading should not be racy except around step boundaries perhaps. Max is different because it doesn't align with the count/total/mean step interval - see https://github.com/micrometer-metrics/micrometer/issues/1993. So without any racy writing and reading, it is expected that the max may return a value from a step interval older than the interval used for count/total/mean.

Does that explain what you are seeing or do you think it's something else? Which registry are you using and how are you seeing the values that aren't what you expect?

**Comment by ceremo** [comment]
Thanks for your time @shakuzen, but I don't really understand why the `max` value does not use the same step interval than the `count` and `total`, it seems to me a bug. We are using a `StepMeterRegistry`, and I can see that the `max` value normally reports a value that matches with the same `count` and `total` step interval, but only if the `record` has executed in the step boundaries the `max` value is not consistent, and is reported in the next step interval.

**Comment by marcingrzejszczak** [comment]
@ceremo do you have a reproducer for this or a test that can replicate this problem?
