### ISSUE TITLE
 Micrometer compatibility with Tomcat 10

### ISSUE THREAD

**Issue by mamba4lifek** [micrometer-metrics/micrometer#3617]
**Please describe the feature request.**
A clear and concise description of what you would like to be able to do with Micrometer and cannot currently.

**Rationale**
Please help us understand the rationale (why) behind the enhancement request.

**Additional context**
Add any other context about the feature request here, e.g. related issues, prior art.

**Comment by shakuzen** [comment]
Please take the time to provide enough information for us to help you. What specifically are you requesting?

**Comment by mamba4lifek** [comment]
Javax is deleted in tomcat10. Need to upgrade to Jakarta EE9/10.

**Comment by mamba4lifek** [comment]
> Please take the time to provide enough information for us to help you. What specifically are you requesting?
Javax is deleted in tomcat10. Need to upgrade to Jakarta EE9/10

**Comment by jonatan-ivanov** [comment]
@mamba4lifek I'm not sure I get if this is a question or you want us to change something.

If the question is: Does Micrometer work with Tomcat 10 that uses Jakarta EE?
Yes, since Micrometer does not instrument Tomcat using Jakarta EE APIs see [`TomcatMetrics`](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/tomcat/TomcatMetrics.java).
Please notice that Micrometer does not instrument the Servlet API or any HTTP endpoints for Tomcat but web frameworks use Micrometer to instrument them.

If you want us to make changes to support Tomcat 10, it is not needed, we already support that, see above.

Hope this helped. Let me close the issue with this, let us know if I misunderstood something and you want us to reopen this issue.
