### ISSUE TITLE
OkHttpMetricsEventListener does not allow user to define timer percentiles

### ISSUE THREAD

**Issue by jasonfagerberg-toast** [micrometer-metrics/micrometer#3620]
**Please describe the feature request.**

The OkHttpMetricsEventListener does not allow users to define what percentiles they would like to measure for latency.
It always defaults to null and therefore only 0.95 by default

**Rationale**

I would like to measure 0.99 and 0.9 percentiles respectively

**Additional context**

PR: https://github.com/micrometer-metrics/micrometer/pull/3619

**Comment by jonatan-ivanov** [comment]
None of the instrumentation does, this is because you can always define this outside of the instrumentation, please see the docs: https://micrometer.io/docs/concepts#_histograms_and_percentiles

```java
registry.config().meterFilter(
    new MeterFilter() {
        @Override
        public DistributionStatisticConfig configure(Meter.Id id, DistributionStatisticConfig config) {
            if(id.getName().startsWith("myservice")) {
                return DistributionStatisticConfig.builder()
                    .percentiles(0.95)
                    .build()
                    .merge(config);
            }
            return config;
        }
    });
```

With this, I'm closing this issue and the PR, please let us know if I missed something and you want us to reopen.
