### ISSUE TITLE
Question: How to reset the counter, after exporting the current snapshot of particular counter.

### ISSUE THREAD

**Issue by suyambuganesh** [micrometer-metrics/micrometer#364]
I would like to know how to reset an counter after the count is exported to external system.

**Comment by jkschneider** [comment]
If you need a value to go up and down, use a `Gauge`.

`Counter`s are by definition monotonically increasing. We purposefully don't support resetting them. The most common "reset" use case is to plot additions to the counter in some specific interval. All monitoring systems that I know of support some sort of rate function that gives you this information. Some monitoring systems (Atlas comes to mind) _only_ publish rate information to the backend because viewing the total value over all time isn't super useful. To the extent that we do ship cumulative values to a particular implementation (like Prometheus), it is because that system's query language is designed to perform such rate normalization over an arbitrary time window (bounded of course by the scrape/publish interval).
