### ISSUE TITLE
Use of Micrometer with Prometheus PushGateway

### ISSUE THREAD

**Issue by Fabian-K** [micrometer-metrics/micrometer#3661]
Hi,

I am collecting metrics using micrometer. This is working fine using the default "scrape" approach. For some parts, I want to switch that to a push approach.

I currently have an instance of `PrometheusMeterRegistry` and run a web server basically exposing `registry.scrape()`. Unfortunately, I only seem to find spring-boot related samples, my project however is not based on spring boot.

Is the recommended approach to keep using `PrometheusMeterRegistry`, add an additional dependency to `io.prometheus:simpleclient_pushgateway`, create an instance of `io.prometheus.client.exporter.PushGateway` and call the `push` method passing `registry.getPrometheusRegistry()` to it?

I also found abstract `PushMeterRegistry`. Should this be used instead? If yes, is there a ready-to-use implementation available? Is a dependency to `io.prometheus:simpleclient_pushgateway` always required or is something similar already included in micrometer?

Thanks, Fabian

**Comment by jonatan-ivanov** [comment]
Hi,

Thanks for creating the issue, let me try to answer your questions:

>Is the recommended approach...

Yes, and as far as I know it is the only approach. Micrometer uses the Prometheus Java client under the hood so if you want to configure something specific to it, you need to 

>I also found abstract PushMeterRegistry. Should this be used instead?

No, `PrometheusMeterRegistry` is not a `PushMeterRegistry` and we only have one registry for Prometheus.

>Is a dependency to io.prometheus:simpleclient_pushgateway always required or is something similar already included in micrometer?

If you want to use `PushGateway`, you will need to get this dependency, it is not included out of the box (if you don't want to use `PushGateway`, you don't need to do anything).

These are the sources that you can use to see how to configure `PushGateway`:
- [Prometheus Java Client Docs](https://github.com/prometheus/client_java#exporting-to-a-pushgateway)
- [Javadoc in Micrometer Samples](https://github.com/micrometer-metrics/micrometer/blob/0bfac45fc7f8a387e303e3f45f89bfdaf81a0895/samples/micrometer-samples-core/src/main/java/io/micrometer/core/samples/utils/SampleRegistries.java#L96-L100)
- [Since you found Spring Boot, you can always check what it does](https://github.com/spring-projects/spring-boot/blob/cf3f25d688ffc9fd28c534acea766f915c371180/spring-boot-project/spring-boot-actuator/src/main/java/org/springframework/boot/actuate/metrics/export/prometheus/PrometheusPushGatewayManager.java)

I think this would be nice to be documented in https://micrometer.io/docs/registry/prometheus (although it is not a Micrometer but a Prometheus Client feature, it can help the users to discover this configuration option in an easier way). I created an issue for this, are you interested in filing a PR? https://github.com/micrometer-metrics/micrometer-docs/issues/291
