### ISSUE TITLE
vmrange format is locale-dependant

### ISSUE THREAD

**Issue by flipp5b** [micrometer-metrics/micrometer#3676]
This issue is specific to VictoriaMetrics histograms. According to this code, `vmrange` format depends on a default locale:

https://github.com/micrometer-metrics/micrometer/blob/ad2d83cb93115cc5b1855dd332118e7b333812a9/micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/FixedBoundaryVictoriaMetricsHistogram.java#L69

Different locales use different chars as a decimal separators. For example, for `ru_RU`, the resulting `vmrange` value looks like `0...1,0e-9`. Wouldn't it be better to explicitly pass `Locale.US` to `String.format` here?

**Comment by jonatan-ivanov** [comment]
Thank you for reporting it. Are you up for filing a PR to fix it?

**Comment by flipp5b** [comment]
Sure. But I'm on the road this week so it will take some time.

**Comment by shakuzen** [comment]
Thank you for catching this and offering to contribute a fix. Since we've got releases coming up on Monday, I wanted to make sure we fixed this for that round of patch releases. I've committed a fix, which should be available in snapshots and in the upcoming releases. Let us know if there are any remaining issues after the fix.

**Comment by flipp5b** [comment]
@jonatan-ivanov, @shakuzen, thank you for the prompt feedback and bug fix!
