### ISSUE TITLE
@counted not recording @valid error in metrics

### ISSUE THREAD

**Issue by sudhan2k14** [micrometer-metrics/micrometer#3677]
When `@Counted` is used at method level, it is not recording the errors happened by `@valid` annotations on method paramethers

ex
```java
public class Myclass{
 
 @Counted
 public ResponseType doWork(@valid Request request){
}}
```

**Comment by jonatan-ivanov** [comment]
I have a feeling that this is because of the order of aop proxies.
If it looks like `counted(valid(doWork()))` it should work but if it is like `valid(counted(doWork()))` then counted will not see errors thrown by valid.

I think the fastest way to test this is doing something like:
```java
public class Myclass{
    @Counted
    public ResponseType doWork(Request request){
        return this.doWorkInternal(request);
    }

    ResponseType doWorkInternal(@Valid Request request){
        ...
    }
}
```

But you can also try `@Ordered`. I'm not sure there is much we can do from Micrometer side.

**Comment by shakuzen** [comment]
Closing due to lack of feedback. Can you control the order in which the annotations are run? It doesn't seem like there is something we can do in Micrometer about this, but if we get feedback there is a change we should make, we can reopen the issue.
