### ISSUE TITLE
Strong References for Numbers in Gauge 

### ISSUE THREAD

**Issue by yonatang** [micrometer-metrics/micrometer#3694]
**Please describe the feature request.**
Currently, the `MeterRegistry.gauge(name, Number)` method in the MicroMeter library holds a weak reference to the `Number` object, which can result in `NaN` metrics being reported after a garbage collection cycle if the `Number` object was collected. To prevent this issue, I suggest modifying the method to keep a strong reference to the object, in case it is a `Number`.

**Rationale**

[According to the documentation](https://github.com/micrometer-metrics/micrometer-docs/blob/main/src/docs/concepts/gauges.adoc#why-is-my-gauge-reporting-nan-or-disappearing), the `Gauge` state object must be strongly referenced, because MicroMeter will only hold a weak reference by default, to prevent memory leaks - which is important for objects that can consume a significant amount of memory, or having other side effects. However, for immutable objects like `Number`, memory leaks are not a concern. Therefore, it makes sense to keep a strong reference to `Number` objects to prevent `NaN` metrics from being reported.

Currently, developers can work around this issue by using the builder and setting the strong reference flag, but this requires an understanding of the MicroMeter internals that many developers may not have. By modifying the gauge method to keep a strong reference to `Number` objects, this issue can be addressed without requiring developers to have an in-depth knowledge of MicroMeter.

I have included a code snippet that demonstrates the issue and believe that most Java developers would find it difficult to understand the problem.

If this enhancement request makes sense, I would be happy to provide a pull request. However, I would like to start a discussion first to see if the maintainers agree with the idea.

**Additional context**

Here is a code snippet that demonstrates the issue:

```java
SimpleMeterRegistry registry=new SimpleMeterRegistry();
registry.gauge("refresh_time", System.currentTimeMillis());
System.gc();
Thread.yield();
System.out.println(registry.getMetersAsString());
```

**Comment by jonatan-ivanov** [comment]
>To prevent this issue, I suggest modifying the method to keep a strong reference to the object, in case it is a Number.

As you found it in the docs, this is by design, I would not call it an issue, I think this was designed like this because @jkschneider was following the the Netflix experience that strong-reference gauges more often led to memory leaks than weak-reference gauges led to accidentally dropped metrics (or at least the effect is more troublesome in the former).

>However, for immutable objects like Number, memory leaks are not a concern.

`Number` is not immutable, e.g.: `AtomicInteger`. Also, using immutable state objects kind of defeats the purpose of using a `Gauge` since if it cannot change, why would you want to track its changes , there won't be any. :) And if you have many gauges this can be a concern.

>Therefore, it makes sense to keep a strong reference to Number objects to prevent NaN metrics from being reported.

Because of the above I don't think it does. Also, the `Gauge` does not really care about it's state object, it can be anything, you don't really know it.

>Currently, developers can work around this issue by using the builder and setting the strong reference flag, but this requires an understanding of the MicroMeter internals that many developers may not have. By modifying the gauge method to keep a strong reference to Number objects, this issue can be addressed without requiring developers to have an in-depth knowledge of MicroMeter.

I would say this is also kind of "by design". Because of the above, we would like users to use the Gauge as it is intended. If they know what they are doing, they can use the strong reference but it is intentionally not advertised very well. :) After all, I don't really find this tedious or hard:
```java
// maintain a reference to myGauge
AtomicInteger myGauge = registry.gauge("myGauge", new AtomicInteger(0));
```

>If this enhancement request makes sense

Even if it would, I think this would be a breaking change.

One of the issues with your code snippet that the value will never be updated, what's the point of using a `Gauge` in this case?
This is what you should do instead:
```java
Gauge.builder("refresh_time", System::currentTimeMillis).register(registry);
```

**Comment by yonatang** [comment]
Thanks for the elaborated answer! Also learned that `AtomicInteger` etc are `Number`. Thanks.

Let me present my use case, which might shade some light on the motivation behind my suggestion: I have a credentials provider that have a background thread to poll and cache a secret store for changes. I want to track the last update timestamp, so I could monitor for any instances lagging behind, or other polling related issues. 
Setting a gauge on the last update timestamp seems a reasonable choice for that purpose - if I take the Prometheus way of doing it, I would create a gauge and every time I see a change, I would use the `gauge.set()` method to update for the current timestamp; that what I was trying to do with the MM gauge, which apparently goes again the MM gauge concept. But in order to properly do that with MM, I need to set a field in the provider object to store the latest update timestamp just to satisfy the MM requirements, which is slightly inconvenient. Alternatively, I can wrap the Long timestamp in a supplier and replace the supplier object on every change event - again, not ideal.
Is there a better way to create a gauge for time stamps (or similar) without having to artificially store it on the monitored object, potentially making a stateless object stateful just for that? The Prometheus approach for that use case seems the most straightforward to me.

**Comment by jonatan-ivanov** [comment]
So if I understand your use-case correctly, you need a strong reference in case of Prometheus, too, something like this:
```java
public class GaugeDemo {
    static Gauge gauge = Gauge.build() // Prometheus Gauge
        .name("test")
        .help("test")
        .register();
    
    public static void main(String[] args) {
        gauge.set(System.currentTimeMillis());
    }
}
```
In order to do the same with Micrometer:
```java
public class GaugeDemo {
    static MeterRegistry registry = new PrometheusMeterRegistry(PrometheusConfig.DEFAULT);
    static AtomicLong gauge = registry.gauge("test", new AtomicLong());

    public static void main(String[] args) {
        gauge.set(System.currentTimeMillis());
    }
}
```
I'm not sure I see much of a difference, except the second one is more flexible since you can use whatever object you want. If you have a lot of these, you can try a MutiGauge: https://micrometer.io/docs/concepts#_multi_gauge

Please let me know if this fulfills your use-case. If not, could you please show me an example with Prometheus and Micrometer?

**Comment by yonatang** [comment]
Perfect, thanks! I guess what baffled me is that with other metrics, such as Timer or Counter, the metric object is holding the state and the registry method just update it, while for Gauge you need to bring your own state object and the registry method just “attaching” to it. 
A good reminder to read the documentation more carefully next time.

**Comment by yonatang** [comment]
Tried that approach, and now I have a Kotlin related comment/question - the `meterRegistry.gauge(String, Number)` is marked as `@Nullable`. I see the general purpose state object can be null, and therefore the result might be also be null, but it make little sense for the `Number` related methods. 
In Kotlin, `@Nullable <T extends Number>` methods are converted into a `<T:Number?>` return type, which requires additional (and unnecessary) null checks. Do you think it is safe to remove the `@Nullable` from the methods handling `Number` state objects? API that makes me use `!!` feels a bit dodgy.

**Comment by jonatan-ivanov** [comment]
I think `Number` can still be `null` there (e.g.: returned by a method) but could you please create a new issue for this and I will take a deeper look next week.
