### ISSUE TITLE
Migrate from Application Insights instrumentation keys to connection strings

### ISSUE THREAD

**Issue by cbismuth** [micrometer-metrics/micrometer#3710]
> On 31 March 2025, technical support for instrumentation key–based global ingestion in the Application Insights feature of Azure Monitor will end.

How can we use connection strings with Micrometer?

https://github.com/micrometer-metrics/micrometer/blob/a350afa3cff4e6df1a68f394250affc39620a4e7/implementations/micrometer-registry-azure-monitor/src/main/java/io/micrometer/azuremonitor/AzureMonitorConfig.java#L42-L44

https://azure.microsoft.com/en-us/updates/technical-support-for-instrumentation-key-based-global-ingestion-in-application-insights-will-end-on-31-march-2025/

Thanks,
Christophe

**Comment by jonatan-ivanov** [comment]
Connected issue: https://github.com/micrometer-metrics/micrometer/issues/3420

Right now you need to override the `AzureMonitorMeterRegistry` but since the connection string is available in the Azure SDK (2.x), I think adding this should not be too complicated.
I think we can add a new config method for `connectionString`, if its value present, we can set it as-is; if its value is not present, we can create a connection string from the `instrumentationKey` (no endpoint override in that case). What do you think?
Would you be interested in creating a PR?

**Comment by cbismuth** [comment]
Yes @jonatan-ivanov, I'll have a look and let you know, thank you.

**Comment by cbismuth** [comment]
Hi, here is a first PR draft below, feel free to comment, thanks!

https://github.com/micrometer-metrics/micrometer/pull/3715
