### ISSUE TITLE
[question] Duplicated http.client.requests metric with Observation API

### ISSUE THREAD

**Issue by ferblaca** [micrometer-metrics/micrometer#3721]
Derived from this other [issue](https://github.com/spring-projects/spring-framework/issues/30205), where in a Spring Boot project using a restTemplate/webClient duplicate metrics (some with the suffix `.active`) are recorded for a single request, it is observed that the `io.micrometer.core.instrument.observation.DefaultMeterObservationHandler` in its [onStart](https://github.com/micrometer-metrics/micrometer/blob/55f61bda320443f40ecbea90076752d0731a264f/micrometer-core/src/main/java/io/micrometer/core/instrument/observation/DefaultMeterObservationHandler.java#L51) method method is the one that is registering the metric.
Thus, a metric with incorrect values is registered in the `onStart`.

What would be the reason to register the metric in the `onStart` and not only in the `onStop` when the timer ends?

Thank you.

**Comment by jonatan-ivanov** [comment]
The `Meter` that I think you are talking about is a `LongTaskTimer` which is different than `Timer`, see the docs: https://micrometer.io/docs/concepts#_long_task_timers

`LongTaskTimer` lets you measure the time while the operation being measured is still running/active. A normal Timer only records the duration after the operation is complete. Saying it differently: `Timer` lets you look into the past but `LongTaskTimer` lets you look into the present.

In order to measure the active operation, `LongTaskTimer` needs to be registered on `start` otherwise it can't report measurements (the present) after `start` but before `stop`. `Timer` on the other hand must be registered after `stop` report past measurements.

There are two big use cases behind `LongTaskTimer`:
1. Let's say you have a task that usually takes 10 minutes (but any arbitrary number works) and you want to alert after 12 minutes. If the task somehow will take 30 minutes this fact will be recorder after 30 minutes and you will get an alert after 30m. With `LongTaskTimer` you get continuous (the present) feedback about your task
2. You can observe the concurrent tasks that are active in a given moment

**Comment by jonatan-ivanov** [comment]
Oh, I forgot to add hints in case you don't need them and you want to eliminate `.active` metrics:
1. You can override `DefaultMeterObservationHandler` and register your own (this is harder since you need to be careful with the order of the handlers and it is more code)
2. You can use a `MeterFilter` (see docs) and `deny` the metrics you don't want.
