### ISSUE TITLE
How to log request and responses with corresponding payloads 

### ISSUE THREAD

**Issue by goodidea-kp** [micrometer-metrics/micrometer#3724]
**Please describe the feature request.**
Need working example to log response body and request payload with Springboot 3.0.x

**Rationale**
To triage issues with clients we need to log all incoming and outgoing data

**Additional context**
Java 17, Springboot 3, non-reactive Rest apis

**Comment by jonatan-ivanov** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](https://stackoverflow.com/). We prefer to use GitHub issues for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that
other people can find it) or add some more details if you feel this is a genuine bug.
