### ISSUE TITLE
Backport fix for partial step values on closing publish

### ISSUE THREAD

**Issue by shakuzen** [micrometer-metrics/micrometer#3759]
Consider backporting https://github.com/micrometer-metrics/micrometer/issues/1882 once we have got feedback on the solution released in milestones and are confident to release it as GA.

**Comment by jonatan-ivanov** [comment]
I back-ported this to `1.9.x`, here are the are the changes I applied (in this order): [`tree/backport-fix-for-partial-step-values`](https://github.com/micrometer-metrics/micrometer/tree/backport-fix-for-partial-step-values)

1. #3681 (1390610fc777521d655bc53fa4efc0e7dda69b9c)
2. #3704 (dfa43efdd8c94887b76b8bc177a1901514556121)
3. #3714 (fddaf1222b7ba07dd5b7fda85a7bb91d23944ada)
4. #3730 (4e64b29bc00b020ef51cab9d59ccc8df9dcf5c6b)
5. #3733 (fe07e980e96e80bb667f4f588f81aa7483be4c53)
6. #3737 (f82cdbc8afcb5382c814d14620965ceef206c913)
7. Fix `@Nullable` import (bbea7b69a1f7f03e15583eae8e0115b32107720a): this was needed because we renamed the package of `@Nullable` in `1.10.0` and deprecated the old one

While I was discovering what changes are related (file history) I found #3750 and #3793 but we should not include them.
