### ISSUE TITLE
Provide a machanism to make sure a remote address can be retrieved from SenderContext or ReceiverContext

### ISSUE THREAD

**Issue by wapkch** [micrometer-metrics/micrometer#3847]
**Please describe the feature request.**
The remoteServiceName and remoteServiceAddress are all Nullable in `SenderContext` and `ReceiverContext`, so remote address can not be easily found directly from `SenderContext` or `ReceiverContext`.

**Rationale**
When using Skywalking with Micrometer Observation, a peer need to be retrieved from `SenderContext` or `ReceiverContext`, and a peer should be IP and port only according to [STAM](https://skywalking.apache.org/docs/main/next/en/papers/stam/). For example, when using feign-micrometer, the remoteServiceName and remoteServiceAddress in FeignContext are all null, so we cannot retrieve a peer directly from SenderContext, and even cannot customize the FeignContext before observation start. 

It will be convenient if remoteServiceName or remoteServiceAddress is not null. Or can we provide a machanism to modify ObservationContext before before observation start?

**Additional context**
https://github.com/OpenFeign/feign/issues/2040, https://github.com/jdbc-observations/datasource-micrometer/issues/20.

**Comment by marcingrzejszczak** [comment]
Hmm you have a getter that you can use can't you?

**Comment by wapkch** [comment]
> Hmm you have a getter that you can use don't you?

So, if i want to get the remoteAddress from FeignContext, i have to getCarrier,  and cast to feign.Request, then get remoteAddress from feign.Request. And there are multiple SenderContext implementations, i have to cast them all in skywalking.

**Comment by jonatan-ivanov** [comment]
>It will be convenient if remoteServiceName or remoteServiceAddress is not null.

That's on the instrumentation to set not Micrometer. If you don't see them you need to open an issue for the component that does the instrumentation to set this.

>Or can we provide a machanism to modify ObservationContext before before observation start?

There are is a mechanism for this: when the instrumentation creates the context, it can set whatever fields it wants on it before start. Also, there is an `ObservationConvention` that you should be able to override (if used) to provide some data.

`getCarrier` has a type parameter, if that is used right (e.g.: not `Object`), you only need to cast the context (depending on where you are, sometimes you don't need to cast the context at all, e.g.: in a handler). See [here](https://github.com/jonatan-ivanov/teahouse/blob/a4e27451998d05480f236d93d49842cac750ecc1/core/src/main/java/org/example/teahouse/core/actuator/config/CommonActuatorConfig.java#L45-L54), `getCarrier` returns `feign.Request` because that's how `FeignContext` is defined:
```
class FeignContext extends RequestReplySenderContext<Request, Response>
```

I think if you want data that is not there right now, you should have the instrumentation modified since it is not Micrometer that provides the data. What do you think?

**Comment by wapkch** [comment]
> I think if you want data that is not there right now, you should have the instrumentation modified since it is not Micrometer that provides the data. What do you think?

Thanks. I understand it is not Micrometer provides the data, but the situation is that most instrumentations(feign, apache http client, resttemplate...) did not set the remoteServiceName or remoteServiceAddress which is needed in skywalking, so i wonder is there a possibility to make remoteServiceName or remoteServiceAddress not null?

**Comment by marcingrzejszczak** [comment]
We currently are not thinking of not making this return `null`. AFAIR I've created custom observation handlers for Skywalking instrumentations. You already have hooks there to do stuff before an observation gets started. That means you can set remote service name and address if they are `null`.
