### ISSUE TITLE
Context does not have an entry for key [class io.micrometer.tracing.handler.TracingObservationHandler$TracingContext]

### ISSUE THREAD

**Issue by desertTown** [micrometer-metrics/micrometer#3901]
**Describe the bug**
Context does not have an entry for key [class io.micrometer.tracing.handler.TracingObservationHandler$TracingContext]

once I set **management.tracing.enable: false**
it will throw bean of Tracer not found  once management.tracing.enable is false.
After I add the Dummy bean of Tracer,  project can startup success, but after access the API, it throw Exception:
**Context does not have an entry for key [class io.micrometer.tracing.handler.TracingObservationHandler$TracingContext]**

Dummy bean of Tracer:
```java
@Configuration(proxyBeanMethods = false)
@ConditionalOnProperty(value = "management.tracing.enabled", havingValue = "false")
class CustomerConfig {
    @Bean
    @ConditionalOnMissingBean(io.micrometer.tracing.Tracer.class)
    Tracer dummyTracer() {
        ThreadLocalCurrentTraceContext braveCurrentTraceContext = ThreadLocalCurrentTraceContext.newBuilder()
                .addScopeDecorator(MDCScopeDecorator.get()) // Example of Brave's
                // automatic MDC setup
                .build();
        CurrentTraceContext bridgeContext = new BraveCurrentTraceContext(braveCurrentTraceContext);
        Tracing tracing = Tracing.newBuilder()
                .currentTraceContext(braveCurrentTraceContext)
                .supportsJoin(false)
                .traceId128Bit(true)
                // For Baggage to work you need to provide a list of fields to propagate
                .propagationFactory(BaggagePropagation.newFactoryBuilder(B3Propagation.FACTORY)
                        .add(BaggagePropagationConfig.SingleBaggageField.remote(BaggageField.create("from_span_in_scope 1")))
                        .add(BaggagePropagationConfig.SingleBaggageField.remote(BaggageField.create("from_span_in_scope 2")))
                        .add(BaggagePropagationConfig.SingleBaggageField.remote(BaggageField.create("from_span")))
                        .build())
                .sampler(Sampler.ALWAYS_SAMPLE)
                .build();
        // [Brave component] Tracer is a component that handles the life-cycle of a span
        brave.Tracer braveTracer = tracing.tracer();

// [Micrometer Tracing component] A Micrometer Tracing wrapper for Brave's Tracer
        Tracer tracer = new BraveTracer(braveTracer, bridgeContext, new BraveBaggageManager());
        return tracer;
    }

}
```

**Environment**
 - io.micrometer:micrometer-tracing:1.1.1
 - SpringBoot -> 3.1.0
 - OS: Win11
 - Java version: JDK17

**To Reproduce**
[MicrometerDemo.zip](https://github.com/micrometer-metrics/micrometer/files/11717266/MicrometerDemo.zip)
unzip MicrometerDemo.zip

  cd producer 
  mvn compile
   mvn spring-boot:run

 cd receiver
  mvn compile
   mvn spring-boot:run

access API
curl --location 'http://localhost:8081/produce'

**Expected behavior**
no any exception occur after set management.tracing.enable: false

**Additional context**
Add any other context about the problem here, e.g. related issues.

**Comment by jonatan-ivanov** [comment]
I took a look, here's my thoughts:
- I've edited your comment to improve the formatting. You might want to check out this [Mastering Markdown guide](https://guides.github.com/features/mastering-markdown/) for future reference.
- I don't think Micrometer has anything to do with this issue, I think you should have opened it for [Spring Boot](https://github.com/spring-projects/spring-boot)
- Attaching maven `target` folder, IntelliJ IDEA-, and Mac OS (`.DS_Store`) files are making things harder for people who wants to look into your reproducer since they need to clean them up.
- Instead of `logging.level.com.springframework.web: Debug`, you might want to do `logging.level.org.springframework.web.servlet.DispatcherServlet: DEBUG` (`org` vs. `com` is a big difference)
- `ReceiverConfiguration` is redundant
- `management.zipkin.tracing.endpoint` is redundant
- There other custom properties that are not needed
- `ProducerController` has a hard dependency on `Tracer` and you are saying in the properties that tracing should be disabled so you don't want a `Tracer`. I don't know what you really want to do in `CustomerConfig` but you need to decide if a `Tracer` is optional or mandatory for your app. If you want to disable it, it's optional, so make an optional dependency for your components, e.g.:

```java
@RestController
public class ProducerController {
    private final RestTemplate restTemplate;
    private final Tracer tracer;

	public ProducerController(RestTemplate restTemplate, ObjectProvider<Tracer> tracer) {
		this.restTemplate = restTemplate;
		this.tracer = tracer.getIfAvailable();
	}

	@GetMapping("/produce")
	public String produce() {
		if (tracer != null) {
			System.out.println(tracer.nextSpan().context().traceId());
		}
		return restTemplate.getForEntity("http://localhost:8082" + "/receiver", String.class).getBody();
    }
}
```
