### ISSUE TITLE
Using a metric annotation with dynamic tags (@Timed and @Counter)

### ISSUE THREAD

**Issue by afishler** [micrometer-metrics/micrometer#3910]
When creating metrics via annotations like @Timed and @Counter it is possible to inject static common tags.

However, there doesn't seem to be a way to add tags upon method execution as tags can be dynamic and change from request to request.

Or maybe there is one and I am missing it?

ability to add the tags seems to be in code - but not through the annotations.

**Comment by afishler** [comment]
Is this solved by https://github.com/micrometer-metrics/micrometer/issues/1732?

**Comment by borisstarik** [comment]
Hi Jonatan . This issue was opens for our use case. We are want to use micrometer in our product. And we are have some limitation.  Because we are working in multi tenancy model , some of tags will be dynamically assigned per request( for example taenant_id) In lot of cases we are want to use @Timed and @Counted annotation .
And we are was think about the possibility to obtaining some of tags dynamically
For example 

@Tymed(value="someVlue",description = "someDescription",extraTagsKeys = {"tenant_id","execution_id"},tagsValueResolver=MyClassResolver.class)
public void myMethod{} 
Also for @Counted

BTW, I was implemented it for my test and it's works , but the problem is - I was override  the original annotation and aspect code and we are thinking it's will be problematic when we will  need  to upgrade the library  to the next version.
As I see in the questions , I think this feature will be very useful for  all community which works with micrometer library.

**Comment by shakuzen** [comment]
Could you please explain more specifically why you can't use the feature delivered in #1732 for your use case?

**Comment by borisstarik** [comment]
Hi ! Thanks for quick  response. 
I am familiar with solution of [#1732 ] it's @MetricTag annotation. This annotation working on method parameter. 
I was implemented it into my POC its may works but I am using it only for interrupt  the previous annotation and assume dynamic tags values into timer. I am not looking the tag values or  tag  names in method parameters.
This is the first part of the problem.
The second part that it's not implemented for @Counter.
And I want to take to developers possibility in minimum code and minimum human errors implement  @Timed and @Counter in our application.
Thanks !

**Comment by shakuzen** [comment]
> This annotation working on method parameter.

Do you mean you are getting tag values from somewhere other than method parameters? If so, where are the values coming from?

**Comment by jonatan-ivanov** [comment]
We don't have that functionality right now, could you please take a look at this and check if this could work work for you? https://github.com/micrometer-metrics/micrometer/issues/1586

**Comment by borisstarik** [comment]
Thanks for response. I was checked  #1586. It's partially works only for @Timed

**Comment by msewerniak** [comment]
Is anyone working on making @MetricTag working for @Counted ?

**Comment by izeye** [comment]
@msewerniak If you meant to ask about `@MeterTag`, see https://github.com/micrometer-metrics/micrometer/issues/4725 and https://github.com/micrometer-metrics/micrometer/pull/4958.
