### ISSUE TITLE
Standardize basic cache metrics

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#393]
You should be able to dimensionally slice fundamental aspects of cache performance across caches with different backing implementations. For example, perhaps I want to reason about hit ratio across two caches, one of which is a Caffeine cache and the other is an Ehcache cache.

Another benefit to standardizing basic metrics is to decouple monitoring of a cache from its implementation, so that the application can swap cache implementations without requiring changes to basic dashboards/alarms.

**Comment by jkschneider** [comment]
![image](https://user-images.githubusercontent.com/1697736/35759397-fe4f88da-083e-11e8-916d-641feb2e4fb6.png)

**Comment by ben-manes** [comment]
Please make sure to calculate your own roll-ups if possible. One of the above vendors redefined their hit rate to `hits / misses` (rather than `hits / (hits + misses)`) in response to being informed that their hit rate was very low due to a bug in their LRU rewrite. It was a year later that they quietly fixed the bug and then the statistics, only due to numerous user complaints. Most often these are honest mistakes, but sadly not always.
