### ISSUE TITLE
HdrHistogram virtual threads friendly

### ISSUE THREAD

**Issue by estigma88** [micrometer-metrics/micrometer#3973]
**Please describe the feature request.**
We would like to use virtual threads with micrometer, but we found some platform threads pinned on our tests, throwing the following warning:

```
org.HdrHistogram.DoubleRecorder.reset([DoubleRecorder.java:265](http://doublerecorder.java:265/)) <== monitors:1
io.micrometer.core.instrument.distribution.AbstractTimeWindowHistogram.rotate([AbstractTimeWindowHistogram.java:268](http://abstracttimewindowhistogram.java:268/)) <== monitors:1
```

Inspecting the code, there are several usages of _synchronized_ keyword, which is not virtual threads friendly:
- https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/AbstractTimeWindowHistogram.java#L234
- https://github.com/HdrHistogram/HdrHistogram/blob/master/src/main/java/org/HdrHistogram/DoubleRecorder.java#L194

Ideally, we should use _ReentrantLock_ instead of _synchronized_ as _ReentrantLock_ is virtual threads friendly.

**Rationale**
As we require high throughput, virtual threads are a pretty good fit for the task

**Additional context**
We are using Spring Boot 3.0.5, Micrometer 1.10.5.

**Comment by jonatan-ivanov** [comment]
We should look into this (right now I'm not sure about the consequences) but [JEP 444](https://openjdk.org/jeps/444) says:
>There is no need to replace synchronized blocks and methods that are used infrequently (e.g., only performed at startup) or that guard in-memory operations. As always, strive to keep locking policies simple and clear.

**Comment by shakuzen** [comment]
Thank you for bringing this to our attention. We need to figure out the extent of the issue.

We would need to be very careful about changing synchronization, and we can't do anything about HdrHistogram's implementation; it is a separate library. If you are not using client-side percentiles, HdrHistogram will not be used. Without client-side percentiles, `FixedBoundaryHistogram` (used by `TimeWindowFixedBoundaryHistogram`) will be used, and the `reset` method there [is not synchronized](https://github.com/micrometer-metrics/micrometer/blob/11a9f8dc068e9daa4aeef008b3b0e2abc4460c30/micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/FixedBoundaryHistogram.java#L43-L47).

And in the first place, the synchronized block in `AbstractTimeWindowHistogram`'s `rotate` should not be called very frequently.

> we found some platform threads pinned on our tests

Pinned for how long? If this is a warning for any length of pinning, I don't think we're going to easily remove all pinning caused by synchronized blocks, and the JEP indicates we shouldn't have to, as @jonatan-ivanov shared.

**Comment by Holmesus** [comment]
> Thank you for bringing this to our attention. We need to figure out the extent of the issue.
> 
> We would need to be very careful about changing synchronization, and we can't do anything about HdrHistogram's implementation; it is a separate library. If you are not using client-side percentiles, HdrHistogram will not be used. Without client-side percentiles, `FixedBoundaryHistogram` (used by `TimeWindowFixedBoundaryHistogram`) will be used, and the `reset` method there [is not synchronized](https://github.com/micrometer-metrics/micrometer/blob/11a9f8dc068e9daa4aeef008b3b0e2abc4460c30/micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/FixedBoundaryHistogram.java#L43-L47).
> 
> And in the first place, the synchronized block in `AbstractTimeWindowHistogram`'s `rotate` should not be called very frequently.
> 
> > we found some platform threads pinned on our tests
> 
> Pinned for how long? If this is a warning for any length of pinning, I don't think we're going to easily remove all pinning caused by synchronized blocks, and the JEP indicates we shouldn't have to, as @jonatan-ivanov shared.

well,not only memory operation, method 'Thread.sleep()' appeared in the full stacktrace

**Comment by michaldo** [comment]
In my case virtual thread is pinned once per 20 seconds (io.micrometer.prometheus.PrometheusConfig#step default is 1 minute divided later by 3)
Thread is pinned for 0.5 millisecond
```
recordingPhaser.flipPhase(500000L /* yield in 0.5 msec units if needed */);
