### ISSUE TITLE
Does micrometer support OpenTelemetry client API/SDK?

### ISSUE THREAD

**Issue by fengli79** [micrometer-metrics/micrometer#3984]
Does micrometer support OpenTelemetry client API/SDK? It looks like micrometer implements the OTLP protocol without depending on the OpenTelemetry SDK.
As a library provider, what's the right approach to be a good residence with other Spring libraries when our library supports OpenTelemetry?

For example:
- My library uses OpenTelemetry API/SDK, our customer can use OpenTelemetry config (via environment variables, etc)
- Other libraries may use micrometer (especially when they are majorly used by Spring), if they just use OTLP protocol, how can we make we have a consistent config story?

**Comment by jonatan-ivanov** [comment]
>Does micrometer support OpenTelemetry client API/SDK? It looks like micrometer implements the OTLP protocol without depending on the OpenTelemetry SDK.

For metrics, instead of depending on the SDK, Micrometer Metrics supports the protocol that you can use with the Micrometer API. For Tracing Micrometer Tracing can use the OTel SDK.

>As a library provider, what's the right approach to be a good residence with other Spring libraries when our library supports OpenTelemetry?

Spring projects are instrumenting themselves with Micrometer (fyi: Quarkus and Micronaut too). Most of the instrumentation in Spring is done via Micrometer's Observation API. It's a simple API that lets you instrument your components once and get multiple benefits out of this instrumentation, e.g.: metrics, tracing, logging, audit events, etc. users can decide what they can do with this data. So if you want metrics and tracing you don't need to instrument your code twice just once. If you want to add a third signal on top you don't need to instrument everything the third time, you can use the single existing instrumentation.

In terms of metrics, you can decide which Micrometer registry (or registries) you want to use ([there are many](https://github.com/micrometer-metrics/micrometer/tree/main/implementations)). As far as I remember this is not the case with the OTel SDK, if your backend does not support Prometheus or OTLP, you need to use a collector to transform the data.
In terms of tracing, you can decide which tracing library you want to use, right now we support Brave (more stable and performant according to our tests) and the OTel SDK.
With this setup, you can always move between metric backends and also tracing backends and libraries.

As a library author, you might want to consider one more aspect: Otel is not stable yet. If you use OTel Semantic Conventions, your library will be broken and users will be broken too since Semantic Conventions will have breaking changes in the future.

Because of these, we recommend using Micrometer (and also its Observation API). You can get a little more details from this talk I gave earlier this year at Devnexus, check the metrics, tracing and observation API sections: https://www.youtube.com/watch?v=HQHuFnKvk_U&t=666s

>My library uses OpenTelemetry API/SDK, our customer can use OpenTelemetry config (via environment variables, etc)
Other libraries may use micrometer (especially when they are majorly used by Spring), if they just use OTLP protocol, how can we make we have a consistent config story?

Micrometer Metrics' OTLP registry supports the OTel SDK environment variables that are applicable. Micrometer Tracing's OTel bridge supports all of them (I guess) since it depends on the OTel SDK.
If you are using Spring, I would highly recommend using the configuration mechanism of Spring instead of the config mechanisms that every library you use provide.
