### ISSUE TITLE
Recursive MpscLinkedQueue instances found in heap dump

### ISSUE THREAD

**Issue by wansadi** [micrometer-metrics/micrometer#3997]
My application used to die out caused by long duration of garbage collection. 
So I dumped the heap memory to see what's going on.
The heap analyser showed that over 70% of heap memory is occupied by io.micrometer.shaded.reactor.core.publisher.UnicastProcessor

So I dig into the object and here what I found:
A Queue is filled with linkedNode of (io.micrometer.shaded.reactor.util.concurrent.MpscLinkedQueue$LinkedQueueNode);
and each LinkedQueueNode's 'next' linked to another LinkedQueueNode, and the whole link is too long for me to reach the end.
![image](https://github.com/micrometer-metrics/micrometer/assets/22144525/3071438a-d839-4217-a208-3668813aa468)
Can I have some suggestions to continue my investigation on this?

**Comment by shakuzen** [comment]
Please let us know what version of Micrometer you're using and more information on when this happens. Is it happening consistently in your application? Does it happen in a minimal sample application? What do you need to do to reproduce it?

**Comment by wansadi** [comment]
> Please let us know what version of Micrometer you're using and more information on when this happens. Is it happening consistently in your application? Does it happen in a minimal sample application? What do you need to do to reproduce it?

Hardest part is to steadily reproduce it. It does happen from couple of times a day to once every 2 or 3 days. It's happening on production . What we know so far is that when there's a long pause of garbage collection, That LinkedNode is always what eat up most of the heap, since I've dumped couple of heap memory.

Version we're using is 1.0.4

**Comment by shakuzen** [comment]
Micrometer 1.0.4 is very old and the 1.0.x line is [no longer supported](https://micrometer.io/docs/support). We can't help track down issues in unsupported versions. Please upgrade to a supported version (preferably the latest version: 1.11.2 as of the time of this comment) to see if the issue is present in a supported version. I remember we had issues like the one described here before, but I believe they have been fixed.

**Comment by wansadi** [comment]
> 

Thanks very much. I'll try upgrade

**Comment by wansadi** [comment]
> 

I found that 1.0.4 dependency was introduced by spring-boot2.0.2 in our application. I can't upgrade springboot to a later version which may involves too much code change. So is there a way to upgrade micrometer version without having to upgrade spring-boot?  May I know the latest micrometer version that's compatible with springboot 2.0.2?

**Comment by shakuzen** [comment]
I would expect the latest patch version of Micrometer 1.0.x to work, if not even later minor versions. You can try and test. Spring Boot 2.0.x is also [out of support](https://spring.io/projects/spring-boot#support), but I would suggest upgrading to at least the latest patch version of Spring Boot 2.0.x which should also upgrade to the latest Micrometer 1.0.x release (1.0.11) and probably doesn't require any code changes since it should only be maintenance releases that are backward compatible.
