### ISSUE TITLE
Memory leak in MpscLinkedQueue?

### ISSUE THREAD

**Issue by linbo21** [micrometer-metrics/micrometer#4008]
**Describe the bug**
We think there may be a memory leak in MpscLinkedQueue. However, please let us know if we are simply missing a configuration.

**Environment**
 

 - Micrometer version [e.g. 1.7.1] 1.11.2
 - Micrometer registry [e.g. prometheus] datadog
 - OS: [e.g. macOS] macOS
 - Java version: [e.g. output of `java -version`]
 openjdk version "11.0.18" 2023-01-17 LTS
OpenJDK Runtime Environment Corretto-11.0.18.10.1 (build 11.0.18+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.18.10.1 (build 11.0.18+10-LTS, mixed mode)

**To Reproduce**
How to reproduce the bug:

We see the same

 One instance of` "io.micrometer.shaded.reactor.util.concurrent.MpscLinkedQueue" loaded by "org.springframework.boot.loader.LaunchedURLClassLoader `

problem suspect. Even when we let the heap grow close to 4GB and analyzed the heap dump we saw the same with that instance retaining  3.35GB (Almost 90%) of the memory. Here's the report 
<img width="1339" alt="Screenshot 2023-08-02 at 4 28 36 PM" src="https://github.com/micrometer-metrics/micrometer/assets/121314581/e4cec521-e723-400c-878a-19ab499c3ac0">
<img width="1456" alt="Screenshot 2023-08-02 at 4 29 09 PM" src="https://github.com/micrometer-metrics/micrometer/assets/121314581/f1bb1366-20de-4802-827a-d674d064b5b9">

**Expected behavior**
Service should run without a memory leak. Usable memory should stabilize ~2 GB from 6 GB total 

**Additional context**
Add any other context about the problem here, e.g. related issues.

We did memory profiling, and we also took the heap dump and analyzed it a few times, it all points to a memory leak on the micrometer dependency. Looks like it's due to the way the service is publishing metrics? Here's the report

**Comment by linbo21** [comment]
We did consider updating our spring boot version, but unfortunately there are internal platform blockers that prevent us from doing that at this time

**Comment by wakingrufus** [comment]
This seems similar to #3997

**Comment by wakingrufus** [comment]
also similar to #1172

**Comment by shakuzen** [comment]
Just to confirm: you are using Micrometer version 1.11.2 for all Micrometer dependencies? Are you able to easily reproduce this running an application locally, or does it only happen in production? It would help investigate if we had a minimal sample we could run and debug.

**Comment by wakingrufus** [comment]
> Hi, thanks for the response. Yes, I ran a gradle dependency tree and can confirm Micrometer version 1.11.2 is being used for all Micrometer dependencies.
> 
> This only happens in an actual preprod/production environment, and I am not able to reproduce locally because the volume of traffic locally is not sufficient.
> 
> Unfortunately, it appears to be caused by how our internal platform is interacting with this library, based on the memory profile and the fact that there minimal usages of it in the application itself. I can ask our platform team what code snipper we might able to provide

As one of the primary devs of this internal platform, i can provide some more context:
we have about 170 services, and this is the only one that seems to have this problem. It is entirely possible that there is something specific about this service that is causing this, but at this point, we are at a loss of where to look. 

We are hoping that someone could maybe point us in the right direction, like has happened with some similar issues int he past.

By the way, we are emitting metrics via StatsdMeterRegistry from micrometer-registry-statsd with a custom netty-based lineSink.

**Comment by jonatan-ivanov** [comment]
Do you have the same issue with that particular server if you use the default LineSink provided by Micrometer?

**Comment by linbo21** [comment]
> Do you have the same issue with that particular server if you use the default LineSink provided by Micrometer?

yes, we tried disabling our custom LinkSink and still got a memory leak

**Comment by jonatan-ivanov** [comment]
Based on the screenshot, it seems `LinkedQueueNode` is what occupies the space.
Could you please check what is there if you go down that path for a while? Is it an "infinite" number of connected nodes?

Could you please check it the app is able to send the data or the nodes are accumulating because of a connection issue?

Based on the description (OS: macOS), I assume you can reproduce this locally. Could you please check what happens if you do this:
1. Start the service, connect to it with visualvm (or something else that lets you see the heap size graph and trigger full GC).
2. Generate a bit of traffic and watch the heap growing (you don't need too much traffic just a little to trigger object creations).
3. Trigger full GC and watch the heap shrinking, the used heap after GC will be our baseline.
4. Generate some traffic and watch the heap is growing again, please try to generate a lot more traffic in this step, try to push the heap utilization pretty high.
5. Trigger full GC and watch the heap shrinking again.
6. Take a screenshot.
Right after `#5`, the used heap should be higher than the baseline (right after `#3`), you might need to iterate over `#4-5` to make this more apparent. If this is not happening, this is probably not a memory leak but your GC thinks it can let the heap grow pretty high before collecting objects. If it is happening, there's probably a leak somewhere. We might need a simple java reproducer to investigate this.
