### ISSUE TITLE
StatsdGauge not sending updates if there's no change

### ISSUE THREAD

**Issue by bob983** [micrometer-metrics/micrometer#403]
Hello!

I used Micrometer if one of our projects and I'm very happy with the library. I however stumbled over one issue with `StatsdGauge`: the `poll` method checks old and new value and only sends the metric to StatsD server if the value changed. This doesn't work well with infrequent changes and `deleteIdleStats` StatsD configuration option. This option removes metric if it hasn't been updated in a 10s interval. If the gauge value doesn't change locally in Micrometer in 10 seconds, `statsd` simply deletes the metric.

The `deleteIdleStats` option is important, because it prevents false positives - without it the last value is reported even if the app crashes for example and it's not sending values anymore. 

```java
    @Override
    public void poll() {
        double val = value();
        if(lastValue.getAndSet(val) != val) {
            publisher.onNext(lineBuilder.gauge(val));
        }
    }
```

https://github.com/micrometer-metrics/micrometer/blob/388fc3ea5b00905e48868defc4e8ec065b22b5f0/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdGauge.java#L51-L57

---

Could this check for last value be optional/configurable? I'm happy to contribute with a PR if you kick me into the right direction :-)

**Comment by jkschneider** [comment]
Thanks @bob983. The design isn't intentional - just wasn't aware of `deleteIdleStats`. Is a configuration option that always ships gauges regardless of whether the value has changed sufficient? 

If you are willing to contribute a PR: let's add a `publishUnchangedMeters` (or better name if you can think of one) option to `StatsdConfig`. Then conditionalize the logic there in `StatsdGauge` and similarly in `StatsdLongTaskTimer`.

Based on recent feedback it seems like dogstatsd also stops shipping gauges when they stop being updated, so I think we should default `publishUnchangedMeters` to `true`.

**Comment by bob983** [comment]
Thanks for the answer, @jkschneider. Yes, `publishUnchangedMeters` config option is a good idea IMO. Let me take a stab at it :-)
