### ISSUE TITLE
Add a timestamp to Event in Observation

### ISSUE THREAD

**Issue by marcingrzejszczak** [micrometer-metrics/micrometer#4032]
sometimes we want to pass a timestamp when an event happened. Currently we don't allow that. Example - https://github.com/line/armeria/pull/4980#discussion_r1252703954

**Comment by jonatan-ivanov** [comment]
Is the use-case getting to know about an event that happened in the past and you know when did the event happen?
Right now we only know the timestamp of current events in the present (when `onEvent` is called; similarly to `onStart`/`onStop`).

I think getting to know about past event can be a fair use-case, my two cents:
- Back in the day, the first  PoC of the ~~Recording~~ Observation API had non-instantaneous (`Observation` as of today) and instantaneous (`Event` as of today) events, both of them hold the timestamp to tell when they happened (was "more stateful" compared to what we have today), I think this is the same what this issue is for
- We removed this capability and made it "less stateful" so that it can be more lightweight but one of the the trade-offs was this
- I think it can be ok to introduce a timestamp on `Event` if there's need for it but if we do it, it will be a little different than `Observation` since that one does not have a timestamp and both suppose to record that something happened
- Also the timestamp will be there even if it is not needed
- As an alternative, I'm also thinking about introducing an `Event` implementation that can have a timestamp (`PastEvent`, `EventWithTimeStamp` ? :|) but adding a timestamp to the event can be also ok

**Comment by marcingrzejszczak** [comment]
The example is available here https://github.com/line/armeria/pull/4980#discussion_r1252703954 . So in Armeria they are gathering timing information about certain events happening in the system. Then they can pass it to annotate e.g. the spans. In case of an observation api we can't really use that information because the event ignores it (and spans ignore it too)
