### ISSUE TITLE
Add Prefix Support for Metric Names in CacheMeterBinder

### ISSUE THREAD

**Issue by fartzy** [micrometer-metrics/micrometer#4047]
**Please describe the feature request.**
I would like to modify the [CacheMeterBinder](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache/CacheMeterBinder.java) abstract class to support prefixing metric names. As of now, the metric names are [hard coded ](https://github.com/micrometer-metrics/micrometer/blob/a56b968ba5b3db9b5e4a4feac813080783a16f5f/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache/CacheMeterBinder.java#L78) when the metrics are created in the `public final void bindTo(MeterRegistry registry)` method and then registered. Specifically, I propose adding a method `getMetricNamePrefix()` which returns a prefix string that can be added to the front of all metric names in - which will be in modifying the `bindTo()` method. This allows for better customization and adaptability in various system settings. 

**Rationale**
Without the proposed feature, it is impossible to rename metrics without deleting the existing cache metrics in the `bindImplementationSpecificMetrics()` method and re-registering them with new, prefixed names. This capability is particularly useful for specialized systems like [ActiveMQ-Artemis](https://issues.apache.org/jira/projects/ARTEMIS/issues/ARTEMIS-4306), which adhere to unique metric naming conventions. For instance, these cache metrics could be applied to the [authorization and authentication caches](https://issues.apache.org/jira/projects/ARTEMIS/issues/ARTEMIS-4306) utilized for access control within the message broker. Deleting, recreating, and re-registering metrics is an inefficient way to align metric names. As such, the ability to add prefixes to metrics is essential for the seamless integration of Micrometer's cache metrics with ActiveMQ-Artemis or any other systems that prefer strict naming conventions for metrics. This feature would eliminate the need to delete and re-register cache metrics, thereby simplifying cache metric management.

**Additional context**
**Backwards Compatibility:** This change is backward compatible because the default prefix is an empty string. This ensures that, by default, the existing metric names will not change, effectively appending an empty string to the current metric name.
**Test Coverage:** I have also added a `CacheMetricsBehaviorTest` class  to verify this new functionality.
**Customization:** This feature enhances Micrometer's flexibility by allowing users to define custom metric name prefixes for cache metrics which can be particularly useful in enterprise or specialized settings.

**Comment by jonatan-ivanov** [comment]
Hey @fartzy,
Have you considered using a `MeterFilter` and changing the names of the meters you want to?

**Comment by shakuzen** [comment]
I think this is similar to the issue we had with `ExecutorServiceMetrics` (https://github.com/micrometer-metrics/micrometer/issues/1919) and Prometheus users where multiple instances of the binder (CacheMeterBinder in this case) will exist but there may be some extra tags that differ. If there's no way to change the name, they'll run into #877. Outside of the Prometheus registry, that shouldn't be an issue, since `CacheMeterBinder` takes a `cacheName` that is supposed to uniquely identify the cache, allowing multiple caches to be monitored with the same meter names.

That would still leave the strict naming convention concern. I'm not familiar with this in Artemis so I can't speak to it specifically. I understand the desire for say Artemis metrics to come under an `artemis.` prefix, but in the case of these generic metrics for things like caches or http, there is power that will be lost in them diverging from the common name chosen. With the common name, dashboards and queries can be used for any implementation because the meter names are known up front, and the `cacheName` tag can be used to identify and filter by specific caches. If the same metrics were renamed with an artemis prefix, then dashboards and metrics queries need to be written specifically for artemis separately from the generic cache metrics.

On the suggestion for `MeterFilter`, end users can configure a `MeterFilter`, but it would be odd and unexpected I think for a library (like Artemis) to register a `MeterFilter`. At least I don't think I anticipate such usage or know of it anywhere else currently.

So I think that leaves us with: Artemis (or other libraries in their position) should copy CacheMeterBinder code to change the meter names used, or we should allow a prefix to be specified as suggested. If we resolved #877, that would take away significant reason to go with the prefix option. In the absence of resolution on #877, it feels more necessary we allow prefixing.

**Comment by fartzy** [comment]
I am going to try to checkout MeterFilter and see if it can be used. I'm not sure just by reading the code if it will be work properly for what is being done with Artemis though
