### ISSUE TITLE
Some metrics from aws lambda are not published

### ISSUE THREAD

**Issue by supriya-albal-polestar** [micrometer-metrics/micrometer#4060]
I have written AWS lambda with java. I am using micrometer cloudwatch library.
I have created CloudWatchMeterRegistry as -

    @Provides
    @Singleton
    public CloudWatchAsyncClient cloudWatchAsyncClient() {
        return CloudWatchAsyncClient.builder().region(Region.of("us-east-1")).build();
    }

    @Provides
    @Singleton
    public MeterRegistry getMeterRegistry(CloudWatchAsyncClient cloudWatchAsyncClient) {
        CloudWatchConfig cloudWatchConfig = setupCloudWatchConfig();
        return new CloudWatchMeterRegistry(cloudWatchConfig, Clock.SYSTEM, cloudWatchAsyncClient);
    }

    private CloudWatchConfig setupCloudWatchConfig() {
        return new CloudWatchConfig() {

            private final Map<String, String> configuration =
                    Map.of(
                            "cloudwatch.namespace",
                            "random-service",
                            "cloudwatch.step",
                            Duration.ofSeconds(1).toString());

            @Override
            public String get(String key) {
                return configuration.get(key);
            }
        };
    }

I am using micrometer for publishing counters. Wherever needed, I increment counters as -

> meterRegistry.counter(counter).increment();

Initially I had setup step function time to publish metrics to be 1 min. However my lambda was running just for 15 seconds, as a result, I was not able to find any metrics getting published.
When I changed the frequency to 1 second, I started seeing some metrics. However there is one metric I publish right before exit of lambda, I did not see it getting published.
My guess is that, some ms data before lambda exit is lost, as step of 1 second is not complete.

**Environment**

 - Micrometer version - 1.11.3
 - Micrometer registry - Cloudwatch
 - AWS lambda
 - Java version: 17

**To Reproduce**
How to reproduce the bug:

Take lambda code, keep step frequency to a higher value than lambda execution time.

**Expected behavior**
I am looking for a on demand publish method using which I can publish metric before lambda exits.

Note:- I tried with shutdown hook, but no luck. I did not see metrics getting logged.

**Additional context**
Add any other context about the problem here, e.g. related issues.

**Comment by ppawlowski15** [comment]
Hey @supriya-albal-polestar, You've asked for tip to solve problem with metrics using AWS Lambda. There U go:
 
 0. In my case I was connecting to ElasticSearch using ElasticMeterRegistry.class. I didn't try this solution on different Registires but I think it should be analogous
 
 1. I've created my own CustomSimpleMeterRegistry which extended SimpleMeterRegistry class
 1.1 I've created my own abstract method 'forcePublish()' in it, which will be usable in next steps 
 1.2 I've override 'close' method to call 'forcePublish()' before calling super.close() / before real closing registry
 ```
 public abstract class CustomSimpleMeterRegistry extends SimpleMeterRegistry {
    protected CustomSimpleMeterRegistry() {
        super(SimpleConfig.DEFAULT, Clock.SYSTEM);
    }

    protected abstract void forcePublish();

    @Override
    public void close() {
        forcePublish();
        super.close();
    }
}
```



2. I've created my own CustomElasticMeterRegistry just by copy content of Micrometer ElasticMeterRegistry from github
https://github.com/micrometer-metrics/micrometer/blob/main/implementations/micrometer-registry-elastic/src/main/java/io/micrometer/elastic/ElasticMeterRegistry.java
2.1 Next my CustomElasticMeterRegistry needs to extends CustomSimpleMeterRegistry class created in step 1 instead of StepMeterRegistry.class
2.2. In CustomElasticMeterRegistry class I've renamed 'publish()' method to 'forcePublish()' - its actually creating an implementation of absttract method from step 1.1 

```
public class CustomElasticMeterRegistry extends CustomSimpleMeterRegistry {
	//start of original ElasticMeterRegistry

    @Override
    public void forcePublish() { //instead of public void public() {
	 createIndexTemplateIfNeeded();
	 ...
	//continuation of original ElasticMeterRegistry
	
```


3. Now u can use CustomElasticMeterRegistry as original ElasticMeterRegistry. Only diference is you need to call 'forcePublish()' on your CustomElasticMeterRegistry instance before Lambda exit. Pseudocode example:


```
public class LambdaConsumer implements RequestHandler<KinesisEvent, Void> {
    private static final ElasticConfig config = null;
    private static final CustomElasticMeterRegistry metricsRegistry = new CustomElasticMeterRegistry(config);

    public LambdaConsumer() {
    }

    @Override
    public Void handleRequest(KinesisEvent event, Context context) {
        try {
            doYourJob(event);
            metricsRegistry.counter("test").increment();
            metricsRegistry.forcePublish();
        } catch (Exception ex) {
            log.error("ERROR", ex.getMessage(), ex);
        }
        return null;
    }
}
```

Maybe this solution is not elegant and comfy (because of copying original class) but I lost a lot of time to figure it out so i choose the easiest way. Maybe U will show me better approach base on it.

Feel free to ask questions, and let us know about results

**Comment by supriya-albal-polestar** [comment]
@shakuzen is it recommended to use elastic meter registry intended for use with elastic search in lambda handler?
Cant forcePublish method be supported in CloudWatchMeterRegistry?

**Comment by marcingrzejszczak** [comment]
Sorry for asking obvious questions... In your shutdown hook, have you tried calling `close()` on the `CloudWatchMeterRegistry` ? It should call `stop()` and should try to send data for the last step. AFAIR the hook should be allowed to be ran till the end. The only potential problem I see is that that publishing is also asynchronous so that might mean that your lambda will finish before your data is getting sent.
