### ISSUE TITLE
Increasing memory usage for DefaultLongTaskTimer due to increasing number of active tasks stored

### ISSUE THREAD

**Issue by pengxo** [micrometer-metrics/micrometer#4221]
**Describe the bug**
The `DefaultLongTaskTimer`  (or rather `OtlpCumulativeLongTaskTimer`/`CumulativeHistogramLongTaskTimer`) has increasing memory usage due to increased number of active tasks stored in the `activeTasks`(`ConcurrentLinkedDeque`). It seems that the tasks are added(started) but not removed (stopped) for some reason. After the heapdump analysis of a component in our environment, there are more than 8 million active tasks(It is not possible to have so many tasks at the same time in our environment) stored and thus consumes a lot of memory.

With so many active tasks, it would also be time-consuming for remove operation in a linked list when the task is finished,

**Environment**

 - Micrometer version 1.11.4
 - Micrometer registry prometheus/otlp
 - OS: Linux
 - Java version: 17

**To Reproduce**
It is difficult to reproduce it locally. The point is that when prometheus/otlp registry is used and the traffic is large (e.g. thousands of concurrent requests), the memory usage originating from the Timer could possibly increase dramatically.

**Expected behavior**
The number of active tasks should be small and the finished tasks should be removed from the `ConcurrentLinkedDeque`.

**Additional context**
We use otlp in our Spring Boot application including also Spring Cloud Gateway.  Also I think `ConcurrentHashMap` would be better for performance (O(1)) compared with `ConcurrentLinkedDeque`. Besides, it would be good to have size limitation to avoid possible memory leak. Furthermore, it happens only for some specific metric which is a `DefaultLongTaskTimer`

**Comment by jonatan-ivanov** [comment]
Thank you for the issue!
Are you creating the `LongTaskTimer`s on your own or are you using the Observation API or some other abstraction?
`OtlpCumulativeLongTaskTimer`/`CumulativeHistogramLongTaskTimer` should not have too much to do from your perspective, they don't really handle the list of active tasks.

From your description:
>It seems that the tasks are added(started) but not removed (stopped) for some reason.

and from the fact that `stop` removes the sample from `activeTasks`:
https://github.com/micrometer-metrics/micrometer/blob/3f23cdded2de3271f1c449e7a5e9280a158398b4/micrometer-core/src/main/java/io/micrometer/core/instrument/internal/DefaultLongTaskTimer.java#L228-L234

I would be suspicious that the task is not stopped. Could you please check if the code you use ensures that (i.e.: call stop from a finally block)?

Based on the memory footprint I would say that using [high cardinality tags](https://develotters.com/posts/high-cardinality/) is also possible but I think that would not bump up the active tasks, you would just have a lot of timers.

**Comment by pengxo** [comment]
Hi @jonatan-ivanov , thanks for your reply.  We don't create `LongTaskTimer` on our own. We don't use the Observation API directly, either. We just integrate the otlp registry `micrometer-registry-otlp` in our Spring Boot Application. With AutoConfiguration in Spring Boot the otlp metrics are active and the default metrics will be created. One type of the metric is `LongTaskTimer` and there are multiple metrics of this type by default. In our environment only the metric with name `spring.security.filterchains.active` has increasing number of active tasks stored in the `ConcurrentLinkedDeque`. This metric comes out of the box in the integration with Spring Boot. There are also other `DefaultLongTaskTimer`s which don't have this issue, e.g. `http.server.requests.active`.  I also did some analysis and could not find out why the active tasks in the metric with name `spring.security.filterchains.active` are not removed in the `stop()` method, as you mentioned above. 

As you said, I also don't think that it relates to high cardinality tags because with that there will be a lot of metrics stored in the `meterMap` (`ConcurrentHashMap`) in the `MeterRegistry`. But here it is only related to once instance of `Timer` metric which contains a lot of active tasks.

**Comment by jonatan-ivanov** [comment]
We are getting closer. :)

Could you please tell us more about your environment?
- What is your Spring Boot version?
- Are you using mvc or webflux?
- Are you overriding any versions in your build.gradle/pom.xml files (any spring modules, micrometer, reactor, etc.)?

To me the fact that `spring.security.filterchains.active` has this issue but `http.server.requests.active` does not tells me that **maybe** there is a bug in the instrumentation in Spring Security and the code somehow goes to a path when the `stop` method is not called.

In order to verify this, could you please check a few more things?
1. Is it only `spring.security.filterchains.active` or do you see any Spring Security metrics that are involved (there should be a bunch of metrics created by security)?
2. Both metrics above should have a "version" that does not contain the word active, these also should produce a counter, look for something like `http.server.requests.count` and `spring.security.filterchains.cont` if you sum them separately, are those two sums the same?

In order to mitigate this issue until we fix it (probably in Spring Security so I might ask you to open an issue there depending on the answers above), you can try to disable the instrumentation of Security:

```java
@Bean
ObservationPredicate noSecurityObservationPredicate() {
    return (name, context) -> !name.startsWith("spring.security.");
}
```
See the [docs](https://docs.spring.io/spring-security/reference/servlet/integrations/observability.html#observability-tracing-disable).

**Comment by pengxo** [comment]
Hi @jonatan-ivanov, the Spring Boot version is 3.1.4 with Webflux. We do not override the module versions in our application.  I did local analysis before and there are other spring security metrics such as `spring.security.authorization`, but only `spring.security.filterchains.active` has memory issue. For the sum of `http.server.requests.count` and `spring.security.filterchains.count` respectively, I need to check the heapdump or check it locally. I will come back to you in the next week.

We disable the metric `spring.security.filterchains.active` through a custom-defined `MeterFilter`. Could it be a valid option compared with the solution you provided? Thanks for your support.

**Comment by jonatan-ivanov** [comment]
>For the sum of http.server.requests.count and spring.security.filterchains.count respectively, I need to check the heapdump or check it locally as the otel metrics are not exposed to the visualization platform currently in our environment.

You can also check the Prometheus endpoint or the `/actuator/metrics` endpoint, all should have the same data.

>We disable the metric spring.security.filterchains.active through a custom-defined MeterFilter. Could it be a valid option compared with the solution you provided? Thanks for your support.

Yes if you only have metrics and you don't have tracing or any other custom `ObservationHandler` you register. Background: Spring Security is instrumented with the Observation API. This API will create metrics if they are configured (start/stop timers) and create spans if those are configured (start/stop them) and can create custom things that you define. It seems the observation is not stopped so your timers are not stopped either but if you have other things (tracing, custom handlers), those are not either which might cause other issues. If you only have metrics, then a `MeterFilter` is totally ok, otherwise I would recommend using an `ObservationPredicate`.

**Comment by pengxo** [comment]
Hi @jonatan-ivanov , I checked the endpoint for the prometheus and I have the following result:
```
spring_security_filterchains_seconds_count: 3562811
http_server_requests_seconds_count: 3547958
```
Both of them should represent the total number of requests for the two metrics. Apparently the sum are different. 

Thanks for your insights about the Observation API. We need both of traces and metrics. So I will follow your suggestions to customize the `ObservationPredicate`.

**Comment by jonatan-ivanov** [comment]
As I was reading this, I realized that these numbers will be different anyways if not all of your endpoints are secured and go through the security filterchain. Iff all goes through security, they must be the same.

Could you please open a new issue for Spring Security (they might need a reproducer), it seems the instrumentation does not always close the Observation.
