### ISSUE TITLE
Enhance Timer.Builder to set custom baseUnit

### ISSUE THREAD

**Issue by iamgollapalli** [micrometer-metrics/micrometer#4322]
**Please describe the feature request.**
As of now Timer metric is giving always seconds value, there is no option of measuring in milliseconds/nano etc.

**Rationale**
the requirement is to capture the timer metric in milliseconds, When we leverage Timer.record(long, TimeUnit). still the metric is shown as seconds format.

for example : 

Timer timer = meterRegistery.timer("latency.capture"); **//there is no specific method to pass the BaseUnit**

long startTime = System.currentTimeInMillis();
// some logic goes here
long endTime = system.currentTimeInMillis();

timer.capture(endTime-startTime, TimeUnit.MILLISECONDS);

for the above code the value is being captured but the baseunit shown as seconds.

sample response of spring boot /actuator/metric/latency.capture is shown as follows.

{
	"name": "latency.capture",
	**"baseUnit": "seconds"**
	"measurements": [
		{
			"statistic": "COUNT",
			"value": 100
		},
		{
			"statistic": "TOTAL_TIME",
			"value": 5000
		},
		{
			"statistic": "MAX",
			"value": 50 **//this value correct as per millis, but the baseUnit stil shown as seconds**
		}
	]
}

**Additional context**
Add any other context about the feature request here, e.g. related issues, prior art.

**Comment by jonatan-ivanov** [comment]
>As of now Timer metric is giving always seconds value

Timer will publish a unit what your registry needs, this is not necessarily seconds, please check your registry.

>there is no option of measuring in milliseconds/nano etc.

`Timer` measures everything in nanos.

>the requirement is to capture the timer metric in milliseconds, When we leverage Timer.record(long, TimeUnit). still the metric is shown as seconds format.
for example :

Please never measure elapsed time like that, here's why: https://develotters.com/posts/how-not-to-measure-elapsed-time/
This is what you should do instead: https://micrometer.io/docs/concepts#_storing_start_state_in_timer_sample

>for the above code the value is being captured but the baseunit shown as seconds.
sample response of spring boot /actuator/metric/latency.capture is shown as follows.

The value stored in nanos then converted to seconds because that's the default unit used in `SimpleMeterRegistry`: https://github.com/micrometer-metrics/micrometer/blob/214f038e45645b69bf1609cb5a486716c3238863/micrometer-core/src/main/java/io/micrometer/core/instrument/simple/SimpleMeterRegistry.java#L160-L163
You can change this by extending the registry and overriding this method.


Fyi: the SI unit of time is also seconds and the registry is capable to show you elapsed time with high precision (way more precise than milliseconds).
