### ISSUE TITLE
Enhance Timer.Sample to accept start timestamp so that I can measure Time from a custom timestamp to till now.

### ISSUE THREAD

**Issue by iamgollapalli** [micrometer-metrics/micrometer#4494]
**Please describe the feature request.**
I want to expose the time gap between a custom past timestamp and current time as a Timer metric.

**Rationale**
My request is originated long back, and through multiples flows request reached to current microservice (but i can get the origination timestamp) and now I want to report the time gap between the origination and current timestamp as Timer metric.

**Additional context**
As of now If I use Timer.Sample timer = Timer.start(); the clock start ticks from the current time but I want the clock should have been started from custom timestamp, so that when I stop the timer we can get the exact time.

**Comment by jonatan-ivanov** [comment]
The rationale behind `Timer.Sample` is that you don't need to deal with timestamps.
If you want to deal with them, you can do this:
```java
long start = System.nanoTime();
// ...
timer.record(System.nanoTime() - start, TimeUnit.NANOSECONDS);
```

I think doing this would defeat the purpose since you will not get the convenience that `Timer.Sample` and it also creates an extra instance of it:
```java
Timer.Sample sample = Timer.start(System.nanoTime());
// ...
sample.stop(timer);
```

Also, you might want to read this: https://develotters.com/posts/how-not-to-measure-elapsed-time/
