### ISSUE TITLE
Mismatch values for jvm memory metrics between actuator values and influxdb exported values

### ISSUE THREAD

**Issue by lzago** [micrometer-metrics/micrometer#4563]
**Describe the bug**
I have a Camel application running on Spring Boot 3, exporting the metrics on HTTP using actuator and on InfluxDB
what i see on `actuator/metrics/jvm.memory.commited?tag=area:heap`  is similar to what i read on the JConsole,
on the contrary it's different from what i read on influxDB with a query:

`SELECT last("value") AS "last_value" FROM "mydb"."autogen"."jvm_memory_commited" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND "area"='heap' GROUP BY time(1s) FILL(null)`

from influx: 67108864
from Jconsole: 125829152 
from micrometer http (actuator): 125829120

i configured micrometer to export to influx every second so:
`management.influx.metrics.export.step=1s`

**Environment**
 - Micrometer version: 1.12.0
 - Micrometer registry io.micrometer:micrometer-registry-influx:jar:1.12.0
 - OS: Ubuntu Linux
 - Java version: openjdk version "17.0.9" 2023-10-17

**To Reproduce**
How to reproduce the bug: 
enable the export of jvm metrics by web and by influx and compare the last values.

**Expected behavior**
the values should be comparable. 

**Additional context**

**Comment by jonatan-ivanov** [comment]
`jvm.memory.committed` has two tags: `area` and `id`. On the actuator endpoint you are only querying the `area`. Same with influx, you are querying the `area` which lets say results in these three time series:
```
jvm_memory_committed_bytes{area="heap",id="G1 Survivor Space"} 1.6777216E7
jvm_memory_committed_bytes{area="heap",id="G1 Old Gen"} 8.8080384E7
jvm_memory_committed_bytes{area="heap",id="G1 Eden Space"} 9.2274688E7
```
Which one will be the last? :)
You can query both `area` and `id` and they should match or you can sum them together (there is no sum in the actuator endpoint since it is only there for you to be able to troubleshoot your metrics).

Also, I don't recommend setting the step size to 1s, the default is 1m, I would use that.

With this, let me close the issue. Please let us know if I misunderstood something and we can reopen.
