### ISSUE TITLE
Remove LongtaskTimer.Sample in DefaultMeterObservationHandler (for the purpose of prevent memory leak and lower CPU consuming)

### ISSUE THREAD

**Issue by HashZhang** [micrometer-metrics/micrometer#4596]
with `LongtaskTimer.Smaple` added in `DefaultMeterObservationHandler`, there are two problems:
 - If `Observation.start()` is called but `Observation.stop()` is not called before `Observation` is Garbage Collected, there would be memory leak in `DefaultLongTaskTimer`'s `activeTasks`;
 - when there are many threads or task running, there would be large amount of Observation started, and cause too many `LongtaskTimer.Smaple` in the queue, and `Observation.stop()` would consume too much CPU.

**Comment by HashZhang** [comment]
<img width="1445" alt="image" src="https://github.com/micrometer-metrics/micrometer/assets/15627489/a558d4b1-903e-4111-9914-6eb7782bc6c8">
<img width="1391" alt="image" src="https://github.com/micrometer-metrics/micrometer/assets/15627489/15e9cbcf-c444-439e-971b-ab5214ecf469">

**Comment by jonatan-ivanov** [comment]
>If Observation.start() is called but Observation.stop() is not called before Observation is Garbage Collected, there would be memory leak

Could you please elaborate on this one?
How would the `Observation` be collected if you keep a reference to it (I assume you call `stop`)?

The second issue you mentioned is already captured in a different issue: https://github.com/micrometer-metrics/micrometer/issues/3993

**Comment by HashZhang** [comment]
> > If Observation.start() is called but Observation.stop() is not called before Observation is Garbage Collected, there would be memory leak
> 
> Could you please elaborate on this one? How would the `Observation` be collected if you keep a reference to it (I assume you call `stop`)?
> 
> The second issue you mentioned is already captured in a different issue: #3993

sorry for misleading, I mean if you never call stop() after you call start(), there would be memory leak only because of LongtaskTimer.Smaple

**Comment by HashZhang** [comment]
I think a potential memory leak of one in depth object (LongTimeTask$Sample) because misuse of another object (Observation), for default behavior, is bad

**Comment by jonatan-ivanov** [comment]
>sorry for misleading, I mean if you never call stop() after you call start(), there would be memory leak only because of LongtaskTimer.Smaple
>I think a potential memory leak of one in depth object (LongTimeTask$Sample) because misuse of another object (Observation), for default behavior, is bad

I think the same thing happens if you never stop a `LongtaskTimer` or if you forget closing certain streams or if you keep adding items to an `ArrayList`.

Not calling stop is misusing the API. I'm not sure it really matters how much components are used during this. If we would inline the code of the `LongtaskTimer`, things would not be better. Even if the `LongtaskTimer` would not be there, not calling stop could cause issues elsewhere.

Let me close this issue and track the issues you mentioned in two separate ones:
- https://github.com/micrometer-metrics/micrometer/issues/3993
- https://github.com/micrometer-metrics/micrometer/issues/4604
