### ISSUE TITLE
Document out-of-the-box meter descriptions

### ISSUE THREAD

**Issue by izeye** [micrometer-metrics/micrometer#4626]
There's no description in the reference manual for out-of-the-box meters. We can find their descriptions in the source files and some monitoring systems like Datadog but it would be nice to have them documented in the reference manual.

**Comment by shakuzen** [comment]
A couple updates around this. We now have versioned docs with the source in each repository. @marcingrzejszczak has also done work to document instrumentations we have that were missing from the documentation. At the time of this comment, you'll have to look at snapshot versions of the docs, e.g. https://docs.micrometer.io/micrometer/reference/1.12-SNAPSHOT/reference.html, until we release 1.12.3.

I still don't know a good solution for automated documentation, but at least we can use snippets from compiled code in docs we produce now so we know it compiles for the version of the project the documentation is for.

@lenin-jaganathan we'd certainly consider a PR for this. I think the challenge is how do we make sure the documentation doesn't get out-of-sync with the code as changes are made. Also what you pointed out about JVM metrics depending on the version of the JVM you're running on and its configuration.

The scope of this issue is pretty wide and we've made a lot of progress on closing the gap between instrumentation we have vs what is documented. Would it be more productive to close this and open issues for any remaining missing documentation specifically?
