### ISSUE TITLE
Atlas PercentileTimers/PercentileDistributionSummary are not configured with a range causing excessive memory usage

### ISSUE THREAD

**Issue by DanielThomas** [micrometer-metrics/micrometer#4747]
While the `DistributionStatisticConfig` supports both minimum and maximum expected values, these aren't propagated to to the `PercentileTimer`:

https://github.com/micrometer-metrics/micrometer/blob/c69180d6819b1fdd278807e87eccdc9c0e16d333/implementations/micrometer-registry-atlas/src/main/java/io/micrometer/atlas/AtlasMeterRegistry.java#L136-L140

This leads the class to choose the worst case multiple of `276`, causing significant overhead, approximately 52K per timer:

<img width="851" alt="Screenshot 2024-02-13 at 8 12 22 pm" src="https://github.com/micrometer-metrics/micrometer/assets/1479220/3754640e-48e4-4c6b-a0c3-d5d0a0031c01">

When using the builder, by default Spectator chooses a default range to keep this in check:

https://github.com/Netflix/spectator/blob/030f5bd3202fdb30ec4a34e5e816591590a03d87/spectator-api/src/main/java/com/netflix/spectator/api/histogram/PercentileTimer.java#L48-L50

Even with the appropriate static helper/builder being called, Micrometer's `DistributionStatisticConfig` defaults don't provide any bound. Perhaps Spectator percentiles should use their default builder behaviour unless values other than these defaults are provided, if it's unsuitable to change these defaults:

https://github.com/micrometer-metrics/micrometer/blob/c69180d6819b1fdd278807e87eccdc9c0e16d333/micrometer-core/src/main/java/io/micrometer/core/instrument/distribution/DistributionStatisticConfig.java#L42-L43

**Environment**
Current Micrometer main.

**To Reproduce**
Create a Atlas timer with percentiles enabled. Note that it's unbounded.

**Expected behavior**
Atlas `PercentileTimers` are appropriately bounded to avoid excessive heap overhead.

**Additional context**
When accidentally combined with tags with high dimensionality, and the lack of expiry when using Spectator via Micrometer (https://github.com/micrometer-metrics/micrometer/issues/1114) this can lead to significant memory overhead and an exhaustion of available heap:

<img width="918" alt="Screenshot 2024-02-13 at 8 23 38 pm" src="https://github.com/micrometer-metrics/micrometer/assets/1479220/44c47670-ea44-4a33-9b69-bc806b81f9b1">

**Comment by shakuzen** [comment]
> Micrometer's `DistributionStatisticConfig` defaults don't provide any bound.

This is true for `DistributionStatisticConfig` itself which is used by both `Timer` and `DistributionSummary`, but when it comes to Timers, the `AbstractTimerBuilder` does default to using a min of 1ms and max of 30s.

https://github.com/micrometer-metrics/micrometer/blob/6f6187484833300e26839fb10aa5ea529b39a7a4/micrometer-core/src/main/java/io/micrometer/core/instrument/AbstractTimerBuilder.java#L47-L51

We can certainly pass the expected min/max when making the `PercentileTimer` in `AtlasMeterRegistry`; it was probably just an oversight this wasn't done originally. Unfortunately I couldn't come up with any way to test the outcome of this since it has to do with the internals of Spectator.
I did notice, though, that the percentile histogram counters array will always have a length of 276, even with a min/max. The counters themselves will be lazily instantiated and only within the range of [min,max].

**Comment by shakuzen** [comment]
> I did notice, though, that the percentile histogram counters array will always have a length of 276, even with a min/max. The counters themselves will be lazily instantiated and only within the range of [min,max].

As far as I can tell, this means that passing the min/max would only save memory in the case values are being recorded outside of the [min,max] range. If they are not, I'm not sure it saves any memory to pass them.

**Comment by DanielThomas** [comment]
If I'm reading `PercentileBuckets` correctly, Micrometer's defaults would use buckets 86 through 152, which is only another 8 more buckets than Spectator's default and in this concrete example, would have avoided the 44 lowest buckets (1021 nanos is bucket 42) for a saving of 38,270 bytes in this worst case we saw.

**Comment by shakuzen** [comment]
The key thing I was pointing out is that because the counters are created lazily, if a value less than 1ms or greater than 30s is never recorded on the timer, the bucket counters outside that range will never be created, regardless of a min/max being set. It still doesn't hurt to pass the min/max as that is the correct behavior and it will help in cases when values outside of the expected range are recorded. I'll work on that now.
