### ISSUE TITLE
customObservationConvention is not respected for MicrometerHttpClient

### ISSUE THREAD

**Issue by provataros** [micrometer-metrics/micrometer#4749]
**Describe the bug**
Even though you can provide a customObservationConvention when building the MicrometerHttpClient, on observationStop, it still uses the DefaultHttpClientObservationConvention.getName() to get the convention name, completely disregarding possible overrides on the customObservationConvention ( MicrometerHttpClient#236)

**Environment**
All environments, master branch

**Expected behavior**
Use customObservationConvention .getName() instead

**Additional context**
Add any other context about the problem here, e.g. related issues.

**Comment by jonatan-ivanov** [comment]
I think you are using the instrumentation with its `Timer` flavor and it only creates a `Timer` not an `Observation`. If you want to utilize the `Observation.Convention` you should use the instrumentation in a way that it creates an instrumentation otherwise you can override the name of the `Timer` using a `MeterFilter`.

/cc @shakuzen

**Comment by provataros** [comment]
I eventually patched this, and added the additional tags on the observationConvention, on my 
company's branch. Once I make sure this works as expected, I will open a proper PR

**Comment by jonatan-ivanov** [comment]
Didn't you already open #4751?

**Comment by provataros** [comment]
I mean, i will include additional improvements that are related to this one. Or should i open a different issue for those?

**Comment by shakuzen** [comment]
As Jonatan pointed out, the part you are changing in the pull request is for the `Timer`-based instrumentation (when an `ObservationRegistry` isn't configured). Please write a unit test that demonstrates what is not working as expected. I think it will be more clear then and we'll be able to make sure it stays fixed in the future. It may not have been clear before how to setup this instrumentation. Just yesterday I added documentation about it; see [the documentation](https://docs.micrometer.io/micrometer/reference/1.13-SNAPSHOT/reference/java-httpclient.html). If you are not passing an `ObservationRegistry`, then the Observation-related things like a custom `ObservationConvention` will not be used.
