### ISSUE TITLE
Make OkHttp observation better match Spring clients' observations.

### ISSUE THREAD

**Issue by efemoney** [micrometer-metrics/micrometer#4766]
**Please describe the feature request.**
This maybe more of a question but why is the OkHttpConvention (so) different from the Spring's DefaultClientConvention? Would it be possible to align on what (key/)values are observed in both?

**Rationale**
We have multiple services that generate metrics & tracing via micrometer. We also have common tooling implemented that reads these and drive our monitoring & tracing tools. Services that use OkHttp as client, however, have different values for reported client metrics and is causing discrepancies with those tools and also does not help with having a common, shared, knowledge-base for our tools. I mean its not the biggest issue but annoying enough to have prompted me to open an issue 😅. 

**Additional context**

**Comment by shakuzen** [comment]
The basic reason is backward compatibility. We try to take care to not break users by changing the instrumentation output in a breaking way. That unfortunately means sometimes maintaining differences between instrumentation that if it were made today would be more aligned. As for why it was made in a way that was not aligned to begin with, I think we did not properly consider the alignment among the different HTTP client instrumentations enough. It would be nice to align them going forward, but we need to take care of how we do this so we do not break existing usage.

As for Spring's instrumentation, they did a major version update which provided an opportunity to make breaking changes like changing tag names.

With the introduction of `ObservationConvention`, it should be fairly straightforward for you to customize the tags as you would like. I appreciate that doing this across many apps requires introducing a shared library or copying code and so it would be nice for it to be the default, but as explained, changing the default would break users relying on the existing output.

Does that answer the question? I would be keen to improve the alignment as much as possible, but how can we do that in the least disruptive way? I suppose one option might be to introduce another implementation of `OkHttpObservationConvention` (in addition to the existing `DefaultOkHttpObservationConvention`) so that users can configure using the other one without the need for a third-party library to provide it. It would still require some configuration in each app to use the new convention.
