### ISSUE TITLE
Graphite prefixes are skipped

### ISSUE THREAD

**Issue by urgelacko** [micrometer-metrics/micrometer#477]
I am using GraphiteMeterRegistry and provide `tagsAsPrefix` in `GraphiteConfig` but the graphite prefixes are not set.
This is caused by not mapping all configuration keys into the buildier. 
https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-graphite/src/main/java/io/micrometer/graphite/GraphiteMeterRegistry.java#L71

**Comment by jkschneider** [comment]
@urgelacko The intention behind `tagsAsPrefix` is to apply the tag value of a set of common tags as a prefix. The feature is working as intended as is shown by [this test](https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-graphite/src/test/java/io/micrometer/graphite/GraphiteMeterRegistryTest.java#L102). Note how `tagsAsPrefix` is defined to contain "application" here and the timer is tagged with "application=APPNAME", yielding a name like "APPNAME.myTimer".

Generally, when you use `tagsAsPrefix`, you'd add a common tag to the registry so that the tag is present on all meters belonging to that registry:

```java
@Bean
public MeterRegistryCustomizer<MeterRegistry> commonTags() {
   return r -> r.config().commonTags("application", "APPNAME");
}
```

**Comment by urgelacko** [comment]
@jkschneider Thank you for the explanation I think I was missing the "dimensional monitoring system" intent here and I found odd that the application metrics are going directly to the root of Graphite without grouping them with `prefixedWith()` method of `GraphiteReporter `.
Another thing I was missing was the filtering. I am using Spring cloud stream with Spring Boot 2.0 and the `StreamListener` bindings always created a metric with different name on application startup which flooded graphite quite quick. So I needed to filter some metrics out for reporting.
Anyway the option of using that additional constructor solves all my problems so thank you for your answer again.

**Comment by mle-enso** [comment]
May be one last question from me, because I ran into the same "problem".

For now I am really happy with the MeterRegistryCustomizer solution, mentioned some comments above, but we have three tags as prefixes and rely on there order (application.stage.host).
```
@Bean
public MeterRegistryCustomizer<MeterRegistry> commonTags() {
   return r -> r.config().commonTags("application", "APPNAME", "stage", "STAGENAME", "host", "HOSTNAME");
}
```
Unfortunately the common tags above appear in Graphite as application.host.stage – alphabetically sorted because of sorting in ```io.micrometer.core.instrument.Meter.Id.Id(String, Iterable<Tag>, String, String, Type)```.
For now we work around this issue by renaming the tags-as-prefix to match our intended ordering, but may be their order should be fixed like configured in the MeterRegistryCustomizer callback.

**Comment by jkschneider** [comment]
@mle-enso Interesting problem again. We do have a habit of sorting tags for performance and consistency reasons, and I see how this could make the feature less useful.

I suppose fully customizing the reporter is another option:

```
@Bean
public MeterRegistry graphiteRegistsry(GraphiteConfig config, Clock clock) {
   MetricRegistry graphiteInternal = new MetricRegistry();
   GraphiteReporter reporter = GraphiteReporter.forRegistry(graphiteInternal)
            .convertRatesTo(config.rateUnits())
            .convertDurationsTo(config.durationUnits())
            .prefixedWith("YOURPREFIXHERE")
            .build(new Graphite(new InetSocketAddress(config.host(), config.port())));
   return new GraphiteMeterRegistry(config, clock, HierarchicalNameMapper.DEFAULT, graphiteInternal, reporter);
}
```

**Comment by mle-enso** [comment]
Ah thanks for this alternative. I'll figure out which way is the least painful for us for now. Any update on your thoughts about
> and I see how this could make the feature less useful.

is always appreciated.

**Comment by jkschneider** [comment]
@mle-enso Here's another, perhaps even simpler approach:

```java
GraphiteMeterRegistry r = new GraphiteMeterRegistry(
            GraphiteConfig.DEFAULT,
            (id, convention) -> "prefix." + HierarchicalNameMapper.DEFAULT.toHierarchicalName(id, convention),
            Clock.SYSTEM);
```

I can't think of a way to deal with common tag ordering for this feature. Common tags are a general-purpose feature and tag ordering is I think an important performance optimization.

**Comment by mle-enso** [comment]
Thank you again, that looks yet smarter! I'll give it a try Monday morning!
May be you could at a little hint somewhere in the Graphite-part of your documentation, which explicitly informs about the sorting of all keys, especially those which we Graphiters use for hierarchical structuring.

**Comment by jkschneider** [comment]
Added a [doc section](http://micrometer.io/docs/registry/graphite#_prefixing_your_metrics) yesterday because of our discussion :)

**Comment by mle-enso** [comment]
Really awesome! Have a nice weekend!
