### ISSUE TITLE
Add response message to the GrpcClientObservationContext

### ISSUE THREAD

**Issue by brumarqu-te** [micrometer-metrics/micrometer#4774]
**Please describe the feature request.**
Currently in the `GrpcClientObservationContext`/`RequestReplySenderContext` there is a method for storing the `response` but that isn't being set in the `ObservationGrpcClientCallListener`
```java
    @Override
    public void onMessage(RespT message) {
        this.observation.event(GrpcClientEvents.MESSAGE_RECEIVED);
        super.onMessage(message);
    }
```
The request is to set the response message in the observation context so that we can then later use it in a custom ObservationConvention (extending `DefaultGrpcClientObservationConvention`)

**Rationale**
We are calling a legacy grpc service that always returns grpc status code 0 even when it fails and then returns the status code inside the response message.

**Comment by ttddyy** [comment]
The challenge in storing the response object in the observation context is that, at the framework level, it cannot know whether the result is one or many.
Obviously, we don't want to store a potentially infinite stream of response objects in the context, which could lead to OOM.

However, since you know how many responses your request will return in your application, you can add an additional interceptor that could add some information to the context to workaround the case.

For instance, you might implement it something like this:

```java
public class MyInterceptor implements ClientInterceptor {

	private final ObservationRegistry observationRegistry;

	public MyInterceptor(ObservationRegistry observationRegistry) {
		this.observationRegistry = observationRegistry;
	}

	@Override
	public <ReqT, RespT> ClientCall<ReqT, RespT> interceptCall(MethodDescriptor<ReqT, RespT> method,
			CallOptions callOptions, Channel next) {
		ClientCall<ReqT, RespT> call = next.newCall(method, callOptions);
		return new SimpleForwardingClientCall<>(call) {

			@Override
			public void start(ClientCall.Listener<RespT> responseListener, Metadata headers) {

				Observation observation = MyInterceptor.this.observationRegistry.getCurrentObservation();

				super.start(new SimpleForwardingClientCallListener<>(responseListener) {

					@Override
					public void onMessage(RespT message) {
						// HERE: populate context based on the message
						super.onMessage(message);
					}
				}, headers);
			}
		};
	}
}
```

Note that the order of registering the interceptor is important because this workaround interceptor needs to grab the observation object generated by `ObservationGrpcClientInterceptor`.

**Comment by shakuzen** [comment]
@brumarqu-te does the above workaround work for you? I think for the reason mentioned by @ttddyy we can't do this by default in our instrumentation. If you think we still can and should, please let us know what you'd propose that avoids the issue @ttddyy mentioned.

**Comment by brumarqu-te** [comment]
Makes sense the multiple messages challenge and yes the workaround works like a charm, thanks for the help!
