### ISSUE TITLE
Expose procfs metrics when on a nix system

### ISSUE THREAD

**Issue by jkschneider** [micrometer-metrics/micrometer#478]
See https://github.com/eiiches/java-procfs-mbeans-agent

@eiiches Would love to incorporate your work here for exposition to a bunch of different monitoring systems, including Influx which I see you are using :). Let me know if that interests you!

**Comment by mweirauch** [comment]
Would like to throw in https://github.com/mweirauch/micrometer-jvm-extras when we are talking `procfs`. Perhaps some synergy effects can be reached. :)

**Comment by jkschneider** [comment]
Ah, of course! Sorry @mweirauch. Want to pull that over into core?

**Comment by jkschneider** [comment]
Especially considering your Grafana dash based in part on `micrometer-jvm-extras` graces the Prometheus doc page now ;)

**Comment by mweirauch** [comment]
In case we'd like to read `procfs` on *nix systems, sure, why not. The title is a bit bold. Perhaps we could work out what metrics to expose.

**Comment by jkschneider** [comment]
@kohlmu-pivotal Has an apparent need for /proc/meminfo. I see you've added a few that were evidently useful to you. Perhaps we just start there?

**Comment by kohlmu-pivotal** [comment]
I could quickly add `/proc/loadavg` as a meter. I think this might supercede or supplement ProcessorMetrics from the MBean?
Also, `/proc/net/dev` maybe another interesting metric.
What about `/proc/diskstats`?
Or should we convert @eiiches into Micrometer Meters?

**Comment by eiiches** [comment]
Hi! Thanks for mentioning.

Well, perhaps it's better to implement a universal way to import MBeans as Micrometer Gauges
rather than to convert/rewrite `java-procfs-metrics-agent` using Micrometer Gauges.

I mean, JMX is a standard way to expose metrics and is already used by many software:

 * JVM itself exposes MBeans,
 * Apache Tomcat exposes MBeans,
 * Many libraries (Commons Pools, HikariCP, ...) expose MBeans, etc.

isn't it cumbersome to convert every MBeans into Micrometer Meters?

If necessary, I can do some changes to `java-procfs-metrics-agent`, such as converting it to a multi-module project separating javaagent part and the rest, so that it can be used as a library, etc.

(Note that `java-procfs-mbeans-agent` is keeping /procfs metrics in raw and unmodified form as possible, for traceability reasons. Some (most?) of the values are cumulative which have to be converted to rate for any meaningful insights.)

**Comment by marcingrzejszczak** [comment]
There was no interest in the issue since 2018. We’ll close it for now, and if there still will be any interest, please comment on this issue and we’ll consider re-opening it.
