### ISSUE TITLE
Is there a way to override the url being recorded in micrometer (spring-boot)

### ISSUE THREAD

**Issue by KKghub** [micrometer-metrics/micrometer#4781]
I have a controller in spring boot defined as:
```java
@RequestMapping(value = "/api/**"......)
```

If I call `/api/random`, In spring boot `/actuator/metrics/http.server.requests` actuator endpoint, the API is recorded and its `uri` tag contains: `/api/**`.

Is it possible to override this behavior and allow recording the exact API which is invoked i.e `/api/random`?

Sorry I am new to micrometer, and let me know if this is not the correct place to ask this question. Thank you!

**Comment by shakuzen** [comment]
See the corresponding Spring Boot [documentation](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#actuator.metrics.supported.spring-mvc). You can provide a `@Bean` of type `ServerRequestObservationConvention` to customize the tagging. However, note that it is intentional that metrics are not tagged with high cardinality URIs when a pattern is available. Depending on how your system is setup, you would be exposing your application and your metrics backend to a denial of service attack if you tag arbitrary URIs that untrusted users can send in requests.
