### ISSUE TITLE
HTTP Response Delay From TimeDecayingMax.rotate()

### ISSUE THREAD

**Issue by JosephBateh** [micrometer-metrics/micrometer#485]
## Expected Behavior

HTTP requests should return with minimal latency added by Micrometer metrics.

## Current Behavior

HTTP request logic finishes in resonable amount of time, but response is held up in TimeDecayingMax.rotate() method for an extended period of time (ranging from a couple hundred ms to multiple seconds). Unfortunately this behavior is not consistent and does not happen with each request.

This [image](https://imgur.com/a/PH73D) shows an example of rotate taking over 1000ms. This was gathered using Dynatrace.

## Possible Solution

It seems likely that the excessive amount of time spent in rotate is due to this code block.

```
try {
    synchronized (this) {
        do {
            ringBuffer[currentBucket].set(0);
            if (++currentBucket >= ringBuffer.length) {
                currentBucket = 0;
            }
            timeSinceLastRotateMillis -= durationBetweenRotatesMillis;
            lastRotateTimestampMillis += durationBetweenRotatesMillis;
        } while (timeSinceLastRotateMillis >= durationBetweenRotatesMillis);
    }
} finally {
    rotating = 0;
}
```

## Context (Environment)

The service uses Micrometer version 1.0.1 but also had the same issue on version 1.0.0-RC6. The service uses Spring Boot 1.5.9.

**Comment by jkschneider** [comment]
Thanks @JosephBateh. We had a similar bug once in the similar histogram structure, and it was due to us not initializing `lastRotateTimestampMillis`. So in effect, it looped once per interval from the unix epoch to current time (read a LOT of loops), but only on the first rotation. That would explain the intermittent nature of it. 

It does appear that it is is being initialized correctly now though, so I'm not certain what the problem is, but probably something similar.

**Comment by yuniorb** [comment]
I am seeing the same issue. +1

**Comment by jkschneider** [comment]
I could reproduce this simulating long delays between samples on a particular timer. The fix should place a low upper bound on the amount of time that could be spent in this loop.
