### ISSUE TITLE
Configurable headers for All PushMeterRegistry

### ISSUE THREAD

**Issue by arukiidou** [micrometer-metrics/micrometer#4858]
**Please describe the feature request.**
- Support configurable headers for All PushMeterRegistry
- Currently, only some registries allow customization of the header

**Rationale**
Most PushMeterRegistry actually requires an API key. 
It means that adding headers is commonly.

**Additional context**

- generalized #3600

**Comment by shakuzen** [comment]
I don't think this would make sense to support at the PushMeterRegistry level. There are many implementations of PushMeterRegistry that deal in some way with an API key already without this. Adding it would make things more confusing for those - do you specify an API key in the generic headers or in the specific API key config? What happens if you do it in both places? Where an API key is a specific concept to the specific implementation of PushMeterRegistry, it would make sense for that concept to exist specifically for that implementation.

Could we take a step back and discuss what the problem is? Are you using some implementation of PushMeterRegistry that doesn't allow customizing headers and you need to do that for some reason?

**Comment by arukiidou** [comment]
I reconsidered. You are right.

I thought that adding a header is common to most PushMeterRegistry, 
but it was not so generalized.
