### ISSUE TITLE
How much memory is it use per one cardinality of meter?

### ISSUE THREAD

**Issue by jaehleeee** [micrometer-metrics/micrometer#4873]
OutOfMemory Issue found with Micrometer counter metrics

I have implemented Micrometer counters in my Spring Boot application. I suffered OOM issue due to high cardinality.
So I'm going to ask you a question to improve the high cardinality.

 * How much memory is it use per one cardinality?
 * (or) May I know how many cardinalities are acceptable for 100MB of memory?

The reason for asking these questions is to get a sense of the level to which cardinality should be reduced. 
This is because I can reduce the number of meter TAG  to 100 digits, or 10 digits.

**Comment by jonatan-ivanov** [comment]
I guess you meant to ask per `Meter`? If so, which `Meter`? The documentation contains memory footprint estimation, you can take a look at it, for example for `Timer`: [Timer memory footprint estimation](https://docs.micrometer.io/micrometer/reference/concepts/timers.html#_memory_footprint_estimation). But instead of guessing, you can measure this. Create X amount of Meters and check your heap size before/after taking GC into consideration:
1. Start your app, warm it up with some "traffic"
2. Force full GC and make sure GC was triggered (e.g.: using GC logs)
3. Record heap size (this will be your baseline)
4. Create X amount of Meters
5. Force full GC and make sure GC was triggered (e.g.: using GC logs)
6. Record heap size

The diff between the two heap size recordings is roughly the memory consumption of X amount of Meters.

You can also check these:
- An article I wrote about high cardinality and what you can do with it: https://develotters.com/posts/high-cardinality/
- [`HighCardinalityTagsDetector`](https://github.com/micrometer-metrics/micrometer/blob/c81da3b9c72b8fe5a652ed5420c725a7f509be09/micrometer-core/src/main/java/io/micrometer/core/instrument/HighCardinalityTagsDetector.java) to detect which tag(s) has(have) high cardinality.
- I made some measurements here: https://github.com/micrometer-metrics/micrometer/pull/3047
Please notice that these measurements happened on my machine (architecture and OS), using my JVM (vendor and version) using my approximation methods and it might not be applicable to you.
- I also have a project called [Resourceater](https://github.com/jonatan-ivanov/resourceater/blob/main/src/main/java/resourceater) that is a web application that is capable of creating resources (including Micrometer [Meter](https://github.com/jonatan-ivanov/resourceater/blob/ca3d8449b6e1f1677e0ff2867db6e3afac049320/src/main/java/resourceater/controller/MeterResourceController.java)s) on demand.

**Comment by jaehleeee** [comment]
@jonatan-ivanov 
I already read other issues about OOM by high cardinality (including https://develotters.com/posts/high-cardinality/)
I want to solve high cardinality of my application so I ask about how much memory use.

I mean Counter Meter and I want to know there are documents that already estimated about it.
(Before I start to measure this.)
