### ISSUE TITLE
Update netty to fix a vulnerability

### ISSUE THREAD

**Issue by marcioesposito** [micrometer-metrics/micrometer#4876]
**VULNDB-353737**
**Vulnerability Name:** Netty contains a flaw in the HttpPostRequestDecoder interface that is triggered as rate limiting or throttling mechanisms are not properly implemented for the number of fields and accumulated bytes a form can possess. This may allow a remote attacker to exhaust available memory resources and cause a denial of service.
**Severity:** High
**Resource Type:** java
**Resource Name:** netty
**Installed Version:** netty-4.1.107.Final
**Fix Version:** 4.1.108.Final

I am receiving this vulnerability alert when I use the `micrometer-bom` artifact version `1.12.4`. I've tried to update the `netty` version, but as `micrometer-registry-statsd` incorporates the `netty` classes into its jar file (shade), there is no way to update it.

BTW: Why are you incorporate the `netty` classes into the `micrometer-registry-statsd` jar file instead of just use it as a compile dependency?

**Comment by shakuzen** [comment]
> Netty contains a flaw in the HttpPostRequestDecoder interface

There is no HTTP usage in `micrometer-registry-statsd` and we make sure to exclude any Netty HTTP-related dependencies to avoid false positives which it sounds like this vulnerability is for us. Perhaps the vulnerability scanner you are using is not specific enough about which netty classes it is looking for. You can see the contents of the `micrometer-registry-statsd` JAR and that `HttpPostRequestDecoder` is not there.

> BTW: Why are you incorporate the `netty` classes into the `micrometer-registry-statsd` jar file instead of just use it as a compile dependency?

Because publishing metrics to statsd with netty is an implementation detail of the library and we would not want the library to put constraints on your application about the version of netty to use and likewise we would not like the version of netty your application uses (if any) to have an effect on whether publishing metrics with our module works. Other libraries you use may have their own opinion on the version of netty to use, and it may be impossible to make everything work with one version of netty. Shading the dependency removes the need to worry about figuring out which version works for everything in your application.

Given the above, particularly that this sounds like a false positive, I will close this issue and we will upgrade the shaded version of netty as part of our normal dependency upgrade process we do before releases.
