### ISSUE TITLE
Using Spring SPEL in the `@Observed` annotation to allow dynamic low and high cardinality values

### ISSUE THREAD

**Issue by mloayzagahona** [micrometer-metrics/micrometer#4919]
**Please describe the feature request.**
Using Spring SPEL in the `@Observation` annotation to allow dynamic low and high cardinality values

**Rationale**
Use Spel expression in the `@Observed` annotation to allow dynamic values for the low cardinality

```java
@Observed(
      name = "observed-feature",
      contextualName = "context-one",
      lowCardinalityKeyValues = {"action", **"#method1"**})
public ResponseEntity<Object> doPost(String method1, HttpHeaders header)
```

**Additional context**
When using low cardinality in the observation, it adds to the metric as tag, and I'm looking to add tags dynamically to the underlying  created metric for this observation.

**Comment by shakuzen** [comment]
Micrometer does not depend on Spring and we cannot (it would create a circular dependency because Spring in turn depends on Micrometer). For that reason, we cannot directly support Spring Expression Language. We do however have [`@MeterTag`](https://docs.micrometer.io/micrometer/reference/concepts/timers.html#_metertag_on_method_parameters) which can be configured to use a `ValueExpressionResolver` implementation that understands SpEL. That won't currently work with the `@Observed` annotation, though. I thought we had another issue for that, but I couldn't find one when searching now. We can change this issue to be an enhancement request for that, however, if it sounds like it would allow what you want.

**Comment by adamalexandru4** [comment]
> Micrometer does not depend on Spring and we cannot (it would create a circular dependency because Spring in turn depends on Micrometer). For that reason, we cannot directly support Spring Expression Language. We do however have [`@MeterTag`](https://docs.micrometer.io/micrometer/reference/concepts/timers.html#_metertag_on_method_parameters) which can be configured to use a `ValueExpressionResolver` implementation that understands SpEL. That won't currently work with the `@Observed` annotation, though. I thought we had another issue for that, but I couldn't find one when searching now. We can change this issue to be an enhancement request for that, however, if it sounds like it would allow what you want.

@shakuzen

I understand the issue with circular dependencies. However, this ultimately leads to copying and pasting code from documentation just to tag a simple method parameter in the Spring ecosystem in order to implement the ValueExpressionResolver. Maybe I'm wrong, but how should we use @MeterTag on methods for numbers, strings, and other simple parameter object?

**Comment by shakuzen** [comment]
> Maybe I'm wrong, but how should we use @MeterTag on methods for numbers, strings, and other simple parameter object?

Perhaps [the documentation](https://docs.micrometer.io/micrometer/reference/concepts/timers.html#_metertag_on_method_parameters) could be improved but see the example there where the default is using the `toString` of the parameter type.

```java
interface MeterTagClassInterface {

    @Timed
    void getAnnotationForArgumentToString(@MeterTag("test") Long param);

}
```

```java
// Example for returning <toString()> on the parameter
service.getAnnotationForArgumentToString(15L);

assertThat(registry.get("method.timed").tag("test", "15").timer().count()).isEqualTo(1);
```
