### ISSUE TITLE
Add gRPC support for OTLP in addition to HTTP

### ISSUE THREAD

**Issue by gayanper** [micrometer-metrics/micrometer#5040]
**Please describe the feature request.**
Add support for grpc transport protocol for OTLP implementation for metrics.

**Rationale**
Some of the tools such as Microsoft .NET Aspire Dashboard which can be used as a developer testing tool to run locally for verification of metrics and traces can only be used if all three traces, metrics and logs are transported using grpc protocol. So it would be nice to implement the support for transporting metrics using grpc in addition to http as well.

**Additional context**
https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/overview

**Comment by gayanper** [comment]
If this is something that it acceptable to be added, I would very much like to contribute with the implementation.

**Comment by jonatan-ivanov** [comment]
As far as I remember (according to the specs and the OTel maintainers), collector implementation must support all three transports (http/json, http/protobuf, grpc) so that they can talk to any clients. It's not the client (Micrometer) who should support all of them but the server. For example the OTel SDK only supports two out of three. I would try to open an issue to the Aspire Dashboard to support all the transport protocols.

**Comment by hackery** [comment]
@jonatan-ivanov any chance you could unearth a reference for this "must support all three transports"? Would be useful to give weight to requests against other projects to round out their implementations.

**Comment by jonatan-ivanov** [comment]
I think so, but now that I just did, I think the current situation might be slightly different but it should not affect this issue.

First see the [OTel SDK specs](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#specify-protocol):
>SDKs SHOULD support both `grpc` and `http/protobuf` transports and MUST support at least one of them. If they support only one, it SHOULD be `http/protobuf`. They also MAY support `http/json`.

I also [asked OTel maintainers](https://cloud-native.slack.com/archives/C014L2KCTE3/p1677784529226719?thread_ts=1677780415.787389&cid=C014L2KCTE3):
>Jonatan Ivanov Mar 2nd, 2023 at 11:15 AM
>Thank you!
>This means that every collector implementation should support both HTTP/JSON and HTTP/protobuf since there can be clients that are only supporting one of them I guess.
>
>Jack Berg Mar 2nd, 2023 at 11:53 AM
>Correct.

I did not find if this is specified for the server but based on the SDK specs servers must support both `grpc` and `http/protobuf` since SDKs only need to support one of those (it seems servers can get away by not supporting `http/json`).
Another interesting detail that this is an SDK spec not a client spec. I did not find any specs for non-SDK clients and what protocols they must support but I would assume, it's the same (`grpc` or `http/protobuf`).
