### ISSUE TITLE
Breaking Change in 1.13.0

### ISSUE THREAD

**Issue by TheSench** [micrometer-metrics/micrometer#5093]
**Describe the bug**
Version 1.13.0 moved `PrometheusMeterRegistry`, resulting in `NoClassDefFoundError` in code referencing the class in its old location in 1.12.5.

**Environment**

 - Micrometer version: `1.13.0`
 - Micrometer registry: `prometheus`
 - OS: `N/A`
 - Java version: `openjdk 17.0.9 2023-10-17`

**Expected behavior**
A new major version, due to the breaking changes to the API surface (e.g. package of various classes).

**Additional context**
This class appears to have been moved to a new package [here](https://github.com/micrometer-metrics/micrometer/commit/d651867b9f19b859534816dea413945562a4c53b) (along with many others).

**Comment by jonatan-ivanov** [comment]
Please take a look at the [Release Notes](https://github.com/micrometer-metrics/micrometer/releases/tag/v1.13.0) and the [1.13 Migration Guide](https://github.com/micrometer-metrics/micrometer/wiki/1.13-Migration-Guide).

Here's some background:
- After 9 years of being on 0.x, Prometheus release 1.x with breaking changes
- `micrometer-registry-prometheus` was migrated to the new 1.x client
- At the same time the original bits `micrometer-registry-prometheus` (Prometheus 0.x) were moved to `micrometer-registry-prometheus-simpleclient`

The decision we needed to make: move to 1.x and offer a way go back to 0.x or stick with 0.x and let users opt-in to the upgrade. We decided to migrate `micrometer-registry-prometheus` to 1.x and also offer `micrometer-registry-prometheus-simpleclient` which is the exact copy of `micrometer-registry-prometheus` before the migration.

The decision you need to make: migrate to 1.x (use `micrometer-registry-prometheus`) or stay on 0.x (use `micrometer-registry-prometheus-simpleclient`).

If you want to migrate to the new client, this is the change you should make:
```
- implementation 'io.micrometer:micrometer-registry-prometheus:1.12.6'
+ implementation 'io.micrometer:micrometer-registry-prometheus:1.13.0'
```

If you do not want to migrate to the new client, this is the change you should make:
```
- implementation 'io.micrometer:micrometer-registry-prometheus:1.12.6'
+ implementation 'io.micrometer:micrometer-registry-prometheus-simpleclient:1.13.0'
```
(Please notice that you need to change the version number and the name of the artifact in this case.)

If you use a framework that auto-configures things for you, like Spring Boot, I think the change should be transparent to you since Boot auto-configures the new client for you. Excluding some cases for example using the Prometheus API directly or the old `PrometheusMeterRegistry`. In that case instead of depending on `PrometheusMeterRegistry`, you should depend on `PrometheusMeterRegistry`.

**Comment by TheSench** [comment]
@jonatan-ivanov Our challenge was that we were receiving this dependency transiently and the dependency that pulled it in was pulling it in via `latest.release` (yes, I agree that this is not a great idea), which forced it to use `1.13.0`.  We did not choose to migrate to `1.13.0`, but we started encountering unexpected build failures as soon as this version was released.

I'm not well-versed enough in my Gradle dependency management to know when it automatically pulls in a higher minor version outside of `latest.release` (my assumption is that it typically doesn't).

That said, 0.x Prometheus may have made a major version change to 1.x, but this specific library had breaking changes in a minor version bump, which feels incorrect.  In these cases, I would usually expect a 2.x release of `micrometer-registry-prometheus`.

**Comment by TheSench** [comment]
Thank you for the extra added context, and for drawing out the key part of the migration guide that we can use `io.micrometer:micrometer-registry-prometheus-simpleclient` in place of `io.micrometer:micrometer-registry-prometheus`.  This is helpful for others that may be running into unexpected build failures after the recent release.

**Comment by jonatan-ivanov** [comment]
>Our challenge was that we were receiving this dependency transiently and the dependency that pulled it in was pulling it in via latest.release (yes, I agree that this is not a great idea), which forced it to use 1.13.0. We did not choose to migrate to 1.13.0, but we started encountering unexpected build failures as soon as this version was released.

From `latest.release` perspective you were broken if this would have happened in a major release, i.e.: Micrometer 2.0.0. How the component that brings this in transiently not broken, did they migrate? (Btw migration should be simple, most of the time is a package name change but please check the migration guide.) Can you ask them to bring in `micrometer-registry-prometheus-simpleclient` instead?

With `latest.release` you are sitting on multiple ticking bombs. (I also recommend using dependency lock files.)

>I'm not well-versed enough in my Gradle dependency management to know when it automatically pulls in a higher minor version outside of latest.release (my assumption is that it typically doesn't).

`latest.release` always pulls in the latest (hence the name), if someone releases a new major version and breaks everything, it pulls that in. `major.+` (`1.+`) is usually a safer bet.
In Gradle, you can exclude `micrometer-registry-prometheus` and pull in `micrometer-registry-prometheus-simpleclient`, you have control over what is transitively pulled in/not pulled in.

>That said, 0.x Prometheus may have made a major version change to 1.x, but this specific library had breaking changes in a minor version bump, which feels incorrect. In these cases, I would usually expect a 2.x release of micrometer-registry-prometheus.

Last time we tried to do 2.x, we were not able to because of users/other libraries who did not want to migrate and breaking changes. :) I explained above what were our two options (2.0 is not really right now I think) and we are trying our best not to break people but is this change really that breaking when the fix is updating the name with the version? You don't need to change your code, but the dependency what you also do with the version.

**Comment by TheSench** [comment]
RE: `latest.release`, [Micrometer's own documentation suggests using this](https://docs.micrometer.io/micrometer/reference/implementations/prometheus.html):

https://github.com/micrometer-metrics/micrometer/blob/b410174db680401423659955581bd03009113908/docs/modules/ROOT/pages/installing.adoc?plain=1#L9-L14

Can we get that documentation updated so something that won't cause breakages to users down the road?

**Comment by TheSench** [comment]
@jonatan-ivanov 

RE: `latest.release`, [Micrometer's own documentation suggests using this](https://docs.micrometer.io/micrometer/reference/implementations/prometheus.html):

https://github.com/micrometer-metrics/micrometer/blob/b410174db680401423659955581bd03009113908/docs/modules/ROOT/pages/installing.adoc?plain=1#L9-L14

Can we get that documentation updated so something that won't cause breakages to users down the road?

**Comment by jonatan-ivanov** [comment]
I think the docs uses `latest.release` as a simple example (we don't need to update the docs for each release). I think this is the simplest way to get the users started, maybe it is not the best for everyone since it will bring in new major versions too but on the other hand, I guess that's the goal for new users who wants to try things out and the docs doesn't assume what versioning strategy you want to follow, maybe you want `latest.release` since you want to migrate or you want your framework's BOM managing the versions for you so you will remove the version part.

I don't think there are many users who use (or should use) any version there in apps that go to prod, they should use the BOM of their framework (or the Micrometer BOM as the last resort) and define the dependency this way:
```groovy
implementation 'io.micrometer:micrometer-registry-prometheus'
```

I don't think discussing versioning strategies, framework BOMs, dependency locking and/or version catalogs is something we should do in the Micrometer docs but I think we can do this as an alternative:
```groovy
implementation 'io.micrometer:micrometer-registry-prometheus:<micrometer.version>'
```
Though this needs an extra step to enter the version if you just want to try things out so I think we should keep using `latest.release` in the docs but we are always open for suggestions.
Could you please open a new issue/PR for this if you would like to propose changes to the docs?

**Comment by izeye** [comment]
Now that Micrometer reference docs are versioned, I think we can use the reference docs' version like [Spring Boot does](https://docs.spring.io/spring-boot/gradle-plugin/getting-started.html).

I created https://github.com/micrometer-metrics/micrometer/pull/5652 to try to resolve it.
