### ISSUE TITLE
[question] about prometheus client 1.x doc 

### ISSUE THREAD

**Issue by shalk** [micrometer-metrics/micrometer#5135]
https://docs.micrometer.io/micrometer/reference/implementations/prometheus.html

> If you use the "new" client (micrometer-registry-prometheus), you can alternatively use io.prometheus.metrics.exporter.httpserver.HTTPServer, which you can find in io.prometheus:prometheus-metrics-exporter-httpserver:

But I found  micrometer-registry-prometheus is not include   io.prometheus:prometheus-metrics-exporter-httpserver.

So I have to write pom.xml like this.

```
    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-registry-prometheus</artifactId>
      <version>1.13.0</version>
    </dependency>
    <dependency>
      <groupId>io.prometheus</groupId>
      <artifactId>prometheus-metrics-exporter-httpserver</artifactId>
      <version>1.2.1</version>
    </dependency>
```

So the doc could be

> If you use the "new" client (micrometer-registry-prometheus), you can alternatively use io.prometheus.metrics.exporter.httpserver.HTTPServer, which you can add dependency io.prometheus:prometheus-metrics-exporter-httpserver:

Meanwhile  I found i have to align the version bewteen  micrometer-registry-prometheus and prometheus-metrics-exporter-httpserver.

**Comment by jonatan-ivanov** [comment]
Thanks for the issue.

>But I found micrometer-registry-prometheus is not include io.prometheus:prometheus-metrics-exporter-httpserver.

This is why the docs says exactly which dependency and class you need.
Micrometer does not depend on `io.prometheus:prometheus-metrics-exporter-httpserver` because users can make the Prometheus output public in various ways. They probably use a framework which takes care about this concern. People who still need that dependency, can add it.

>So the doc could be

I think I would phrase this as "which you can find in `io.prometheus:prometheus-metrics-exporter-httpserver` (you need to add it as a dependency if you want to use it)...".
Do you want to open a PR? You can find the file here: [`prometheus.adoc`](https://github.com/micrometer-metrics/micrometer/blob/1.13.x/docs/modules/ROOT/pages/implementations/prometheus.adoc). If so, please open it against the `1.13.x` branch.

>Meanwhile I found i have to align the version bewteen micrometer-registry-prometheus and prometheus-metrics-exporter-httpserver.

This is something that we can fix on the Prometheus Client side. If the Prometheus Client could publish a BOM, Micrometer could use that so when you bring in a Prometheus dependency, you don't need to define it's version since it is already defined in the BOM.
(You can open an issue [here](https://github.com/prometheus/client_java/issues/new) if you want.)

**Comment by izeye** [comment]
> If the Prometheus Client could publish a BOM, Micrometer could use that so when you bring in a Prometheus dependency, you don't need to define it's version since it is already defined in the BOM.

Prometheus has BOMs, so I created https://github.com/micrometer-metrics/micrometer/pull/5468 to use them.

It doesn't seem to be helpful for end users as it's only for Micrometer project itself.
