### ISSUE TITLE
what difference of v1.0.0-rc.3 and v1.0.0-rc.2

### ISSUE THREAD

**Issue by vinkdong** [micrometer-metrics/micrometer#521]
Hi,
today I had a test to upgrade micrometer from v1.0.0-rc.2 to v1.0.0-rc.3 but there is no prometheus 
metrics anymore.
my dependency like:

```xml
                 <dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-spring-legacy</artifactId>
			<version>1.0.0-rc.3</version>
		</dependency>
		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-registry-prometheus</artifactId>
			<version>1.0.0-rc.3</version>
		</dependency>
```

**Comment by shakuzen** [comment]
Rather than upgrading from one RC to another at this point, it would be advisable to upgrade to the latest GA version - currently 1.0.2, soon to be 1.0.3.

If you want to see the difference between any version, you can always check [the release notes](https://github.com/micrometer-metrics/micrometer/releases) or a [diff in GitHub](https://github.com/micrometer-metrics/micrometer/compare/v1.0.0-rc.2...v1.0.0-rc.3).

**Comment by liuhaipen9** [comment]
哈哈

**Comment by liuhaipen9** [comment]
牛逼呀，666
