### ISSUE TITLE
Performance Issue: Heap is getting full slowly as using unique tag for each new entry of the. Looks like objects are not garbage collected.

### ISSUE THREAD

**Issue by viandervi** [micrometer-metrics/micrometer#5232]
**Describe the bug**
Using micrometer in the code having version 1.6.x for pegging the metrics mainly using gauge and facing heap memory issue, as heap is slowly getting full. Checked the heap dump objects related to micrometer is continuously increasing.
Even tried with latest version of micrometer-core 1.13.1, results were little better but not satisfactory.

<img width="809" alt="Screenshot 2024-06-25 at 12 00 26 PM" src="https://github.com/micrometer-metrics/micrometer/assets/16507896/c91ea29c-8c19-4882-ba7d-ee6801cf0b59">

**Environment**

 - Micrometer version --> 1.6.x , 1.8.3 and 1.13.1
 - Micrometer registry --> prometheus
 - OS: macos(sonoma 14.5) and linux
 - Java version: 17.0.0
**To Reproduce**
How to reproduce the bug:
Peg metrics with unique tag each time continuously.

**Expected behavior**
Objects related to micrometer which are not referenced should be garbage collected.

**Comment by shakuzen** [comment]
Thanks for reporting the issue. It's not entirely clear to me the situation being described. If you keep registering more meters with unique tags, that's a high cardinality scenario and the memory will continually increase. There is no expiry for meters currently so unless they are removed from the registry, they will remain registered and take up memory.

Gauge meters take a backing object and by default Micrometer maintains a weak reference to it so Micrometer does not prevent the backing object from being garbage collected when it is no longer strongly referenced. The gauge itself will still remain registered, however.

One of the purposes of Micrometer's MeterRegistry is to maintain references to meters to be looked up. Micrometer does not require users maintain references to a Meter registered with a MeterRegistry. Are you expecting that Gauges will be removed from the MeterRegistry when the backing object is garbage collected? Or am I otherwise missing something?
