### ISSUE TITLE
Dynamic MeterFilter results in wrong Meter being reused

### ISSUE THREAD

**Issue by NiFNi** [micrometer-metrics/micrometer#5233]
**Describe the bug**
When using a MeterFilter which dynamically adjusts the tags of a meter the MeterRegistry reuses previously created Meters even though the MeterFilter would change the tags to something that does not equal the first used tags.

An example spring boot project can be found here: https://github.com/NiFNi/micrometer-dynamic-tag-example

I have defined a MeterFilter like this so that it it adds a dynamic tag containing a random uuid:
```
    @Bean
    public MeterFilter meterFilter() {
        return new MeterFilter() {
            @Override
            public Meter.Id map(Meter.Id id) {
                var tags = Tags.concat(id.getTagsAsIterable(), Tags.of("DYNAMIC_FILTER_TAG", UUID.randomUUID().toString()));
                return id.withTags(tags);
            }
        };
    }
```

Then I have a Counted Get endpoint:
```
    @GetMapping
    @Counted(value = "foo.bar")
    public void get() {
    }
```

When calling the endpoint multiple times the counter with the first created UUID is increased instead of creating a new counter for each request.

**Environment**
 - Micrometer version: 1.13.1
 - Micrometer registry: prometheus
 - OS: any
 - Java version: any

When using micrometer-core version 1.12.x the issue is not present and each request creates its own counter.

**To Reproduce**
How to reproduce the bug:
See example above. To test for yourself run the spring boot application from the repo and check http://localhost:8080/actuator/prometheus after calling GET http://localhost:8080 multiple times.

**Expected behavior**
Each call should create its own counter as it is doing with previous micrometer versions.

**Additional context**
When searching through things I found this pull request: https://github.com/micrometer-metrics/micrometer/pull/4857 which seems to have introduced some caching of meters which does not seem to take dynamic MeterFilters into account as the MeterFilter is executed only when the cached Meter is not valid anymore or no cached Meter is found. 

We need this feature for a multi tenancy system where each request can be in a different tenant context. The tenant should be added to all metrics to allow filtering metrics by specific tenants. If MeterFilters are not intended to be used like this and there is a better way to implement this apart from using a MeterFilter which dynamically adds this tag I would also be open for that.

**Comment by jonatan-ivanov** [comment]
Thanks for the issue!
As it is right now, I would not consider your example as a valid one since it is introducing high-cardinality tags ([see more about it here](https://develotters.com/posts/high-cardinality/)). You should not create a new `Counter` every time you have an incoming HTTP request, if you want to record high-cardinality data, I would recommend using distributed tracing or logging instead.

**Comment by NiFNi** [comment]
@jonatan-ivanov thanks for the reply!

The example given is just an example to easily reproduce the issue. The actual use case is using a limited set of say 10 different values that a tag might have which I would not call high cardinality. 
We are using Spring Boot and I checked out both ObservationConvention and ObservationFilter:
Both seem to be executed before the SecurityFilterChain. The value we want to set is available only after the SecurityFilters ahve run through. 

Maybe some more background on the use case:

1. the value of the tag is extracted from a bearer token in the SecurityFilters
2. the value should be available in all metrics that are created after the SecurityFilterChain
3. We are currently using a mix of methods annotated with `Counted`, manually created Counters and default metrics provided by Spring Boot (for example `http_server_requests_seconds_count`) which all have the dynamic tag added by just creating a MeterFilter Bean which takes care of this. Some metrics are created before the security filters are applied. For those we do not need and have the additional tag.

For manually created counters we can just add the tag manually. For Counted annotations this is not possible. We could workaround this by not utilizing the annotation which would be uncomfortable but not impossible. The problem would be the metrics created by something inside Spring where we could not do that. 

I really think that the caching in the MeterRegistry introduced in #4857 should be reevaluated if this could take MeterFilter tag modifications into account. 
From what I understood the MeterFilter can be used to dynamically modify/add/remove Tags of a filter. This seems to not be supported anymore as the same incoming tags will always result in the same Meter even if there are MeterFilters which would modify the Tags.

**Comment by lenin-jaganathan** [comment]
I too think that when you are extracting something from context, Observations are a good thing to start with. You can add filters that add lowCardinality information to the Observation. Since, Observation has support for context, It would be a good option for your use-case.

> The value we want to set is available only after the SecurityFilters ahve run through.

Can you not get the Observation that is in scope and add this information to it?

>  MeterFilter can be used to dynamically modify/add/remove Tags of a filter.

It is true that `MeterFilter` can be used to modify the tags. But, I might not agree with the dynamic part of it. It brings in an inconsistency and more-over extracting some sort of context in a MeterFilter doesn't seem like a good option.

**Comment by NiFNi** [comment]
Thanks for your reply @lenin-jaganathan!

> Can you not get the Observation that is in scope and add this information to it?

I am not quite sure what exactly you mean by this. I tried the following:
```
            var observation = observationRegistry.getCurrentObservation();
            if (tenant != null && observation != null) {
                observation.getContext().addLowCardinalityKeyValue(KeyValue.of("tenant", tenant));
                observation.lowCardinalityKeyValue("tenant", tenant);
            }
```
to add it to the current observation and the context. Both do not seem to have any effect. No metric contains a tenant tag even though the part is executed in a OncePerRequestFilter and `tenant` and `observation` are not null.

> It is true that MeterFilter can be used to modify the tags. But, I might not agree with the dynamic part of it. 

So this would mean a MeterFilter should be idempotent. I think this really limits the usefulness of a MeterFilter. The only usecase I can see is to add an additional static tag which does not seem to be that helpful.

**Comment by jonatan-ivanov** [comment]
You might want to take another look at the `ObservationFilter` use-case since other users are doing exactly what you are trying to do (attaching dynamic data to existing Observations runtime).

Also, there can be many different Observations, since Spring Security is instrumented there will be multiple Observations during the lifetime of the security context some of them might contain the exact information you want to attach to the `Observation` in the `Observation.Context`.

Here is an example (the code you attached is not a filter):
```java
@Bean
ObservationFilter example() {
    return context -> {
        if (context instanceof DataSourceBaseContext dataSourceContext) {
            context.addHighCardinalityKeyValue(KeyValue.of("db.name", dataSourceContext.getRemoteServiceName()));
        }
        return context;
    };
}
```

Also, try to write an `ObservationFilter` that does this to see what is available for you right now:
```java
@Bean
ObservationFilter example() {
    return context -> {
        System.out.println(context.getClass().getSimpleName() + ": " + context);
        return context;
    };
}
```

The `MeterFilter` should really be used for static (common) tags. It limits its use-cases a bit but users can gain performance in exchange.

**Comment by NiFNi** [comment]
Alright did some more investigations and want to write down a few things if other people stumble upon this:

1. ObservationFilter do apply for Counted annotations or manual meter creations (For example with `Counter.builder()` which makes sense as observations seem to be an abstraction above metrics.
2. ObservationFilter do apply for metrics created by Spring Boot (i.e. http_server_requests_seconds)

So in the end to solve our problems we have to do the following to replace the functionality of the MeterFilter:

1. Instead of a MeterFilter create an ObservationFilter which adds the dynamic tags.
2. Explicitly add the tenant tag to all metrics created through `Counted` annotations or `Counter.builder()`

Some more comments on MeterFilters:

From how I understood it in https://github.com/micrometer-metrics/micrometer/pull/4857 some kind of caching was done which uses the `Meter.Id` as key for already existing Meter instances that are then reused. I do not see how it has any kind of relevant performance impact to run this on the `Id` before checking the cache:
```
    public MeterFilter meterFilter() {
        return new MeterFilter() {
            @Override
            public Meter.Id map(Meter.Id id) {
                var tags = Tags.concat(id.getTagsAsIterable(), Tags.of("some_dynamic_tag", getDynamicTagValue()));
                return id.withTags(tags);
            }
        };
    }
```

Maybe I am missing something here but for me it would make more sense to run the MeterFilter before checking the cached Meters in `MeterRegistry#getOrCreateMeter` as I don't think stuff like this is relevant for performance. 

And even if it is I still think it is a valid use case to have some global dynamic metrics for which I am fine to spare some CPU cycles. So maybe splitting `MeterFilter` in `StaticMeterFilter` and `DynamicMeterFilter` would be a solution to let the developer explicitly decide on how this is handled. 

If you don't agree feel free to close the issue as we have a workaround. If you like any of the described solutions to still support global dynamic tags I would be open to do some work on that but I would like to clarify the details on how this should look before implementing anything.

Anyway, thanks for the support already!

**Comment by jonatan-ivanov** [comment]
>ObservationFilter do apply for Counted annotations or manual meter creations (For example with Counter.builder() which makes sense as observations seem to be an abstraction above metrics.

I might misunderstand this but this might not be the case. `ObservationFilter` modifies `Observation`s. Metrics like `Counter` or `Timer` can be created from these `Observation`s (see: `DefaultMeterObservationHandler`) but if you create a Counter somewhere manually, `ObservationFilter` should have no effect on it. Since Spring MVC and Spring Security are both instrumented `Timer`s and `Counter`s in them are created through `Observation`s (by `DefaultMeterObservationHandler`). If you apply an `ObservationFilter` on these `Observation`s, the metrics created from them will have that modification too (i.e.: adding low cardinality key-values).

>ObservationFilter do apply for metrics created by Spring Boot (i.e. http_server_requests_seconds)

Exactly, because of the above.

>Instead of a MeterFilter create an ObservationFilter which adds the dynamic tags.

Yes.

>Explicitly add the tenant tag to all metrics created through Counted annotations or Counter.builder()

I don't think this will work, you can add the tenant tag to `Observation`s using an `ObservationFilter` so only those `Counter`s will have this data that are created from the `Observation`. `Counter`s created by `@Counted` are not like this. Though you can create custom `Counter`s by implementing an `ObservationHandler` or I guess you can also call `observationRegistry.currentObservation()`, get the data from it and create your `Counter` but that sounds like a hack and since you should be able to get the tenant at that point it also seems unnecessary.

>I do not see how it has any kind of relevant performance impact to run this on the Id before checking the cache.

The performance in https://github.com/micrometer-metrics/micrometer/pull/4857 is coming form the fact that we can do more aggressive caching and not running every MeterFilter all the time, you can see performance tests in that PR that can prove the impact but @lenin-jaganathan might be also able to share some data from production.

The static/dynamic filter concept could do the trick, though it will need some investigation, we need to be really careful with it and it increases complexity. `MeterFilter`s meant to add static data, the use-cases where you can even get dynamic data in a `MeterFilter` is very narrow. On the other hand, `Observation`s are meant for this use-case.

**Comment by NiFNi** [comment]
> I might misunderstand this but this might not be the case.

I am just missing a "not". Meant to write "ObservationFilter do **not** apply for Counted annotations or manual meter". Sorry for the confusion. I fixed it in the comment above.

> Explicitly add the tenant tag to all metrics created through Counted annotations or Counter.builder()

What I meant by this is to manually add it. Nothing from Observations or similar. Just call our tenantProvider function and set an additional tag in the Counter.

> the use-cases where you can even get dynamic data in a MeterFilter is very narrow

I guess if this is true it makes sense to just leave the current implementation in place. I would have guessed that that would be the main usecase for MeterFilters. But maybe we can just wait if more people come in here with problems. So I'll close the issue for now. 

Thanks for the support!

**Comment by BertOnline** [comment]
@NiFNi Since upgrading to springboot 3.3.0, I have encountered the same issue, which has forced me to clean up the cache after each visit. Writing code in this way is not elegant, and the effectiveness of MeterFilter is greatly reduced.
```java
    public void removePreFilterIdToMeterMap() throws NoSuchFieldException, IllegalAccessException {
        Field field = MeterRegistry.class.getDeclaredField("preFilterIdToMeterMap");
        field.setAccessible(true);
        Object target = field.get(meterRegistry);
        if (Objects.nonNull(target) && target instanceof Map<?, ?> map) {
            Map<Meter.Id, Meter> preFilterIdToMeterMap = (Map<Meter.Id, Meter>) map;
            preFilterIdToMeterMap.entrySet().removeIf(entry -> entry.getKey().getName().equals("http.server.requests"));
        }
    }
```

**Comment by NiFNi** [comment]
@BertOnline I think for that metric you should be able to use an ObservationFilter as mentioned above. Something like this:
```
    @Bean
    public ObservationFilter observationFilter() {
        return context -> {
            var dynamicTag = getDynamicTag();
            context.addLowCardinalityKeyValue(KeyValue.of("dynamicTagName", dynamicTag));
            return context;
        };
    }
```

**Comment by BertOnline** [comment]
@NiFNi Thank you, the issue has been resolved using the method you provided.
```java
    @Override
    public Observation.Context map(Observation.Context context) {
        if (!StringUtils.equalsIgnoreCase(context.getName(), "http.server.requests")) {
            return context;
        }
        String productType = (String) OdinContextHolder.get(PRODUCT_TYPE);
        String sceneId = (String) OdinContextHolder.get(SCENE_ID);
        ProductTypeEnum productTypeEnum = ProductTypeEnum.getProductTypeByCode(productType);
        if (productTypeEnum == CHANNEL) {
            if (X_CHANNEL_PRODUCT_ID_LIST.contains(sceneId) && SpringProfileUtil.enableCollectSceneMeter()) {
                context.addLowCardinalityKeyValues(KeyValues.
                        of(KeyValue.of(SCENE_ID, sceneId), KeyValue.of(PRODUCT_TYPE, productType)));
                return context;
            }
            context.addLowCardinalityKeyValues(KeyValues.
                    of(KeyValue.of(SCENE_ID, NULL.NULL.name()), KeyValue.of(PRODUCT_TYPE, productType)));
            return context;
        } else if (productTypeEnum == TOPIC) {
            context.addLowCardinalityKeyValues(KeyValues.
                    of(KeyValue.of(SCENE_ID, NULL.NULL.name()), KeyValue.of(PRODUCT_TYPE, productType)));
            return context;
        } else {
            context.addLowCardinalityKeyValues(KeyValues.
                    of(KeyValue.of(SCENE_ID, NULL.NULL.name()), KeyValue.of(PRODUCT_TYPE, NULL.NULL.name())));
            return context;
        }
    }
```

**Comment by shakuzen** [comment]
If it's the Spring Framework instrumentation that you're looking to customize, perhaps this section of the documentation helps explain how that's expected to be done: https://docs.spring.io/spring-framework/reference/integration/observability.html#observability.config.conventions

MeterFilter is not intended to be used for customizing instrumentation with dynamic tags.
