### ISSUE TITLE
Backport fix AspectJ pointcut syntax

### ISSUE THREAD

**Issue by jonatan-ivanov** [micrometer-metrics/micrometer#5285]
https://github.com/micrometer-metrics/micrometer/pull/5058 fixed the AspectJ pointcut syntax but that change should have been introduced in `1.13.x`, this issue is for back-porting it to `1.13.x`.

**Comment by mihalyr** [comment]
@jonatan-ivanov #5058 has been reverted for a reason, I fixed all of that in https://github.com/micrometer-metrics/micrometer/pull/5064 that got merged into Marcin's PR. Without the fix the implementation is broken. Plus consider adding the tests from there too.

**Comment by mihalyr** [comment]
@jonatan-ivanov I can't see the PR for this issue, but the linked commit is wrong https://github.com/micrometer-metrics/micrometer/commit/b1dd400e8fca52488e5943b287cba3777dde5455

You should not merge that one because you will face the problems I described in https://github.com/micrometer-metrics/micrometer/pull/5058#issuecomment-2103276853 and https://github.com/micrometer-metrics/micrometer/pull/5058#issuecomment-2103313929

Please extract the pointcut fixes from https://github.com/micrometer-metrics/micrometer/pull/5064 instead and consider adding at least the load-time weaving fixes to avoid the bugs

**Comment by jonatan-ivanov** [comment]
Oops, sorry, I jumped too quickly, I reverted the commit in https://github.com/micrometer-metrics/micrometer/commit/faeebde9c2aa5103bc9facbaa984d3126118ea63 `13.x` has the original pointcuts.
