### ISSUE TITLE
Allow custom bucket configuration for DistributionSummary and Timer

### ISSUE THREAD

**Issue by yarosla** [micrometer-metrics/micrometer#530]
Micrometer 1.0.2

Over 270 buckets are hardcoded in `io.micrometer.core.instrument.distribution.PercentileHistogramBuckets.buckets()`.

I do not usually need that many buckets.

## Proposal

I'd like to specify exact bucket values and do not have any extra ones. Something like this:

```java
DistributionSummary summary = DistributionSummary.builder('my.summary')
                .publishPercentileHistogram()
                .buckets(1, 25, 1000)
                .register(prometheusRegistry)
```

This should create 4 buckets only.

Same for `Timer`.

**Comment by jkschneider** [comment]
@yarosla This is essentially the purpose of the `sla` function:

```java
DistributionSummary summary = DistributionSummary.builder('my.summary')
                .sla(1, 25, 1000)
                .register(prometheusRegistry)
```

For Prometheus, these buckets are formatted in the same way as other histogram buckets, so the `histogram_quantile` function can't tell the difference. It does highlight very intentionally how the buckets you select may not be suitable for percentile approximations, but can still be useful for other things, like determining how many times you have violated a certain SLA boundary.

Also, if you configure your distribution summary with a minimum/maximum expected value then the number of buckets shipped in percentile histograms goes down substantially (as 270 buckets are coating the whole positive real line).

```java
DistributionSummary summary = DistributionSummary.builder('my.summary')
                .publishPercentileHistogram()
                .minimumExpectedValue(1)
                .maximumExpectedValue(1000)
                .sla(1, 25, 1000) // <1>
                .register(prometheusRegistry)
```

Note that you can mix and match percentile histograms and SLA buckets. In this case, the SLA boundaries are simply _additional_ buckets shipped alongside the predetermined buckets for the expected range.

Experience has shown that developers are not good at selecting buckets that yield reasonable error bounds on percentile approximations when given a set of linear/exponential generators. Since the error bound on their approximation is indeterminable from the perspective of the monitoring system, this can lead to wildly inaccurate results and no consciousness of it. That's why we've settled on this design.

Hopefully that makes sense?

**Comment by yarosla** [comment]
Option to disable those auto-generated buckets would be very nice to have. So the only used boundaries are those added via `sla()` and min/max expected values.

Same for timer. two minutes scale might not suit every timing goal. It would be better to be able to fully customize that as well.

I think it is good that you have some pre-defined bucket sets, but there should also be a way to **fully** customize it.

**Comment by jkschneider** [comment]
You can "disable" the auto-generated buckets simply by not including `publishPercentileHistogram`. If you prefer to use _only_ your own bucket boundaries for percentile approximtions, just use SLA. We don't recommend this in general, as those boundaries won't be tested for error bound.

**Comment by yarosla** [comment]
Looks like exactly what I wanted (except for missing `+Inf` bucket bug #529).

Though it is hard to guess from documentation. I thought without `publishPercentileHistogram()` it won't publish histogram data at all.

> `publishPercentileHistogram` - This is used to publish a histogram suitable for computing aggregable (across dimension) percentile approximations in Prometheus using histogram_quantile and Atlas using :percentile.

**Comment by DanielYWoo** [comment]
> Looks like exactly what I wanted (except for missing `+Inf` bucket bug #529).
> 
> Though it is hard to guess from documentation. I thought without `publishPercentileHistogram()` it won't publish histogram data at all.
> 
> > `publishPercentileHistogram` - This is used to publish a histogram suitable for computing aggregable (across dimension) percentile approximations in Prometheus using histogram_quantile and Atlas using :percentile.

so, I either use the buckets auto-generated, or not publish buckets at all, right?

**Comment by jonatan-ivanov** [comment]
@DanielYWoo You can also define SLOs (as mentioned [here](https://github.com/micrometer-metrics/micrometer/issues/530#issuecomment-377803350)) which will result in extra buckets. If you only define SLOs, you basically defined your buckets. But we are recomending using the built-in bucketing strategy.

e.g.: if you do this:
```java
PrometheusMeterRegistry registry = new PrometheusMeterRegistry(PrometheusConfig.DEFAULT);
Timer.builder("test")
    .serviceLevelObjectives(
        Duration.ofMillis(1),
        Duration.ofMillis(10),
        Duration.ofMillis(100),
        Duration.ofMillis(1000)
    )
    .register(registry)
    .record(Duration.ofMillis(111));

System.out.println(registry.scrape());
```
you will get this:
```
test_seconds_bucket{le="0.001",} 0.0
test_seconds_bucket{le="0.01",} 0.0
test_seconds_bucket{le="0.1",} 0.0
test_seconds_bucket{le="1.0",} 1.0
test_seconds_bucket{le="+Inf",} 1.0
test_seconds_count 1.0
test_seconds_sum 0.111
```

**Comment by DanielYWoo** [comment]
@jonatan-ivanov  it works with `Timer`, it solves my problem perfectly, thank you! @yarosla mentioned that "Same for Timer", this is not true ;-)

One more question, why can't `DistributionSummary` do this? I have thought it's more general than `Timer`.

**Comment by yarosla** [comment]
This issue is 5 years old. I am out of context at the moment. Cannot comment.
