### ISSUE TITLE
Sample on error - change sampling decision during the flow

### ISSUE THREAD

**Issue by kfirs** [micrometer-metrics/micrometer#5319]
I know, everywhere is written that changing the sampling decision is not feasible.
BUT, if I created a span, until it is not finished, the export decision in the `SpanProcessor` is not yet happened.
So, the question is why I can't change the sampled decision for this span as long it is not ended?
I can see 2 options - first is directly in the `SpanContext` to be able to set the sampled value. For this, it would require enhancement.
The other option, which is less preferred, is to extend the `SpanProcessor` implementation and change the `onEnd()` method to add additional parameter for the decision if to export or not the Span, and by this, to workaround the sampled decision.
for example
```
public void onEnd(ReadableSpan span) {
    boolean forcedSampling = samplingProvider.get()
    if (span != null && (span.getSpanContext().isSampled() || forcedSampling ) {
        this.worker.addSpan(span);
    }
}
```
BTW, by that I'm getting only the child-parent relationship spans to be forced sampling. For me, this is exactly what is needed.
So, the questions are 
1. why it was decided not to enable the change of `SpanContext.sampled`? 
2. Why not to do what I'm suggesting here and override the sampling decision? 
3. Can it be considered as an enhancement?

**Comment by jonatan-ivanov** [comment]
>So, the question is why I can't change the sampled decision for this span as long it is not ended?

Because of the distributed nature of Distributed Tracing (there are more than one apps) and because the sampling decision needs to be propagated (either the whole trace is sampled or not). Let's say you have two apps: A and B. A calls B sequentially, it waits for B to respond then continues with its job. In this scenario:
- A makes the sampling decision, let's say it's `false` (no sampling)
- A calls B and propagates the sampling decision (no sampling)
- B respects this decision, do its job and drops its spans (no sampling)
- A gets the response from B finishes it's job and at this point it decides to change the sampling decision

How exactly would B know about this? How would it know which spans need to be changed? How would it publish spans that were already dropped?
It's even worse when B calls another app C and so on.
I hope this answers the question why you can't change the sampled decision on the app side (head sampling). On the other hand you can change the sampling decision once you collected these spans on the tracing store/collector/backend (tail sampling).

>why it was decided not to enable the change of SpanContext.sampled?
>Why not to do what I'm suggesting here and override the sampling decision?
>Can it be considered as an enhancement?

I hope the above answers these questions too, if the sampling decision that happens upfront on the app side (head sampling) is not working for you, you should consider doing tail sampling.

With this, let me close this issue, please let us know if I misunderstood something and we can reopen as needed.
