### ISSUE TITLE
Possibility to have non shadowed netty and reuse the dependency

### ISSUE THREAD

**Issue by mesteves1234** [micrometer-metrics/micrometer#5392]
**Please describe the feature request.**
Would like to have access to a version of micrometer that has a not shadowed netty.

**Rationale**
JVM applications when they start have a lot of work to do to with the JIT compiler.
Having netty shadowed incurs in more compilations causing more cpu usage during the startup.

**Comment by jonatan-ivanov** [comment]
I'm assuming you are talking about the StatsD registry.

Are you saying that you can measure the difference? If so, could you please provide a sample project that can show this? I checked this with a [very simple application](https://github.com/jonatan-ivanov/ecoli): web, actuator, micrometer with statsd, micrometer tracing with brave and zipkin. No DB, no extra HTTP client, or libraries, you can see [the dependencies of the project in the repo](https://github.com/jonatan-ivanov/ecoli/blob/12a9947db9c06385d291ea14b08a0a9721a0c3b4/build.gradle#L23-L28) (I added the statsd registry).

If I build and run the app (with Java 22) like this to print out the JIT logs:
```sh
./gradlew assemble
java -Xlog:jit+compilation=debug:compilation.log:time,uptime,level,tags -jar build/libs/ecoli-0.0.1-SNAPSHOT.jar
```

If I start the app like this and then stop it (optionally I can hit it with a request), I can see that there were around 7000 methods compiled and only 17 of them were from the shaded Netty. I think this ratio is lower (more non-netty methods compiled) in real-world applications where you have much more dependencies and the app does more at startup. Are you sure this is something that needs to be fixed?

Please also notice the followings:
- Netty is an implementation detail of the StatsD registry
- It is shaded so that it will not interfere with what the user has (no version conflict)
- StatsD is a `StepMeterRegistry` which means it publishes on a schedule, by default the first publish is around a minute after the app starts so not a lot of shaded Netty code is used for a while
- Maintaining two versions of the StatsD registry (a shaded and a non-shaded one) would mean significantly more maintenance efforts for seemingly not a lot of value

Please let us know if I missed something and please provide a minimal sample project that reproduces the issue.

**Comment by mesteves1234** [comment]
Hello Jonatan, thanks for the quick reply. This comes from analyzing a prodution service with with latency during the startup which are mostly solved by -XX:TieredStopAtLevel=1 and by giving the service more cpu during the startup. I will try to make a separated example given that I cannot share company details. Bu anyways, to note that level 3 and 4 compilations happen after more invocations to the methods, only one invocation probably wont trigger it.

To give more details on how I detected, I used the following flags:
-XX:+PrintFlagsFinal
-XX:+PrintCodeCache
-XX:+PrintCompilation

And then analyzed the result with: https://github.com/martin0esteves/demo-jit?tab=readme-ov-file. If you go throw the readme you will find a google sheet, ignore it because it is an example for an spring application. I will make a copy of the one for my company project without internal details and reply again here.

**Comment by jonatan-ivanov** [comment]
>But anyways, note that level 3 and 4 compilations happen after more invocations to the methods, only one invocation probably won't trigger it.

As far as I remember C2 starts working after 10000-15000 invocations in most HotSpot JVMs, I think this does not fall under the category of startup that you are talking about.
I checked, my JVM (`-XX:+PrintFlagsFinal`), this is what I have:
```
intx CompileThreshold                         = 10000
intx Tier3CompileThreshold                    = 2000
intx Tier4CompileThreshold                    = 15000
```
Also, Micrometer uses Netty to publish the data, which is infrequent and does not happen at startup.

>To give more details on how I detected the issue, I used the following flags: [...]

I'm not sure what you use `-XX:+PrintFlagsFinal` and `-XX:+PrintCodeCache` for here but `-XX:+PrintCompilation` is the "old" way of doing what I did above with `-Xlog`, they are essentially the same, see [JEP-158](https://openjdk.org/jeps/158), I would encourage you to use `-Xlog`, since you have control over the format and the output. Just to make sure, I double checked and got very similar results in my example app with `-XX:+PrintCompilation`: ~7000 vs. ~20.
