### ISSUE TITLE
Question about integration with org.springframework.kafka spring-kafka

### ISSUE THREAD

**Issue by NomedXD** [micrometer-metrics/micrometer#5397]
**Describe the bug**
As i found there is no(hopefully not yet) direct support for org.springframework.kafka spring-kafka as in Kafka-Streams with Sleuth. So, we need to pass traceId and spanId into the Kafka message header. And how we need to set up retrieved traceid and spanId to Tracer context?

In my mind, it should be something like this:
`@Component
@RequiredArgsConstructor
public class MicrometerKafkaConsumerInterceptorConfig implements RecordInterceptor<String, Object> {
    private final Tracer tracer;

    @Override
    public ConsumerRecord<String, Object> intercept(@Nonnull ConsumerRecord<String, Object> record, @Nonnull Consumer<String, Object> consumer) {
        String traceId = record.headers().lastHeader("traceId") != null ? new String(record.headers().lastHeader("traceId").value()) : null;
        String spanId = record.headers().lastHeader("spanId") != null ? new String(record.headers().lastHeader("spanId").value()) : null;
        if (traceId != null && spanId != null) {
            TraceContext customContext = TraceContext.Builder.NOOP.traceId(traceId).spanId(spanId).build();
            // Setting up the context
        }
        return null;
    }
}`
But i did not find any ability to set new gloabal context to tracer(only scoped context in this interceptor method).

It would be great if you provide some example or example link.

**Comment by jonatan-ivanov** [comment]
Thanks for getting in touch, but it feels like this is a question that would be better suited to [Stack Overflow](http://stackoverflow.com/). As mentioned in [the support guidelines](https://github.com/micrometer-metrics/micrometer/blob/main/SUPPORT.adoc), we prefer to use GitHub issues for bugs and enhancements. Feel free to update this issue with a link to the re-posted question (so that other people can find it) or add some more details if you feel this is a genuine bug.

Also, this might be the wrong repo, [Micrometer Tracing](https://github.com/micrometer-metrics/tracing) contains the tracing bits but I think this question would be better suited to Spring Kafka where instrumentation actually lives for Kafka. I don't get what you mean by global context but for context-propagation, you might want to check the classes in the [`io.micrometer.observation.transport`](https://github.com/micrometer-metrics/micrometer/tree/main/micrometer-observation/src/main/java/io/micrometer/observation/transport) package, they can set/extract tracing data for messages. Here is the docs about how to instrument things: https://docs.micrometer.io/micrometer/reference/observation/instrumenting.html
