### ISSUE TITLE
[observation] Support Gauge registration at micromter-observation api

### ISSUE THREAD

**Issue by JordiMartinezVicent** [micrometer-metrics/micrometer#5477]
**Please describe the feature request.**
Create a generic api at micrometer-observation for registering Gauges

**Rationale**

We are developing a set of libraries on top of Spring Boot which use micrometer to create metrics and traces. As Spring Boot did, we load metrics and tracing auto-configurations or not depending if metrics and traces are at classpath. Now we are refactoring our libraries to use micrometer-observation generic api to unify both and get rid of these conditionals. 

Having said that, we use at several points Gauge metrics, so the suggestion would be to have a generic api at micrometer-observation which would register a gauge. (Although I am not sure if it would have sense for tracing.

**Comment by jonatan-ivanov** [comment]
This is an interesting question that we considered since the beginning even before the Observation API was just a proof of concept. Let me put a brain-dump here about the problem space, please bear with me. :)

The initial goal of the Observation API was not only unifying Metrics and Tracing APIs (though I think it can do that pretty well except the `Gauge`) but rather to give you a set of tools to instrument ("observe") that something happened in your application and runtime you can decide what you want to do with the data: record metrics, spans, logs, send http requests, write to a DB, emit sounds (I'm only [halfway-joking](https://www.youtube.com/watch?v=Qyku6cR6ADY#t=35m5s)), etc. The "something happened" part is crucial here, the Observation API is for events that are either instantaneous (or you don't care about their duration) or not and has a duration (that you care about). You can translate these pretty well to metrics (timer, counter), tracing (span, annotation), and other signals as well (see above) but the `Gauge` is a bit of an outlier form this perspective because nothing happens there, it is just a value that is changing without your interaction/knowledge and sometimes you look at the value and record it.
For example, you can "observe" things like an error or processing an http request using the Observation API but there is no event to observe for the CPU temperature being 42°C (`Gauge`).

Also, I feel like Micrometer already has a generic API for gauge-like values, it's the `Gauge` since Micrometer's `Gauge` API is independent from the configured metrics backend and I'm not sure gauge-like values have a use-case other than metrics.

That being said, you are not the first one who asked this question, and I came up with a simple proof of concept for such a component: [`ObservedValue`](https://github.com/micrometer-metrics/micrometer/compare/main...jonatan-ivanov:micrometer:observed-values), the problem with it that without having a use-case other than metrics, this is just copying and renaming the `MeterBinder` interface.

Please let us know if you have a use-case for gauge-like values other than recording metrics, in the meantime, I think these are your options:
1. Use `MeterBinder` and `Gauge`, you can hide/abstract away `Gauge` registrations and you can also register other data pollers if any (or do some actions when the `Gauge` is pulled).
2. You can reuse the code above, and create your own abstraction in your library but again without having another `ObservedValueRegistrar`, this is just copying and renaming the `MeterBinder`.
3. You can also simplify the approach above with a single `valueRegistrar(String name, Supplier<Double> valueSupplier, KeyValues lowCardinalityKeyValues)` method somewhere that registers the `Gauge` but this is also another form of the `MeterBinder`.

What do you think?
Also, please let us know if you have a use-case for gauge-like values other than recording metrics.

**Comment by JordiMartinezVicent** [comment]
I was thinking something like "give me the state of the application". But I guess it is the aim of the Gauge itself, and it does not occur to me any other "real world" example that would fit to it a part from metrics.

Thank you for the time spent!

**Comment by jonatan-ivanov** [comment]
I feel this might be also connected: https://github.com/micrometer-metrics/micrometer/issues/5112

You can use it for things like [`JvmInfoMetrics`](https://github.com/micrometer-metrics/micrometer/blob/main/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jvm/JvmInfoMetrics.java), where the value is always constant (`1`) but the tags are different. Once implemented not just `MeterBinder` can reuse it to register `Meter`s (`Gauge`s) but for example like Spring Boot's `/info` endpoint as well that provides the same info but it ~duplicates the implementation.

**Comment by fmbenhassine** [comment]
> we use at several points Gauge metrics, so the suggestion would be to have a generic api at micrometer-observation which would register a gauge

We have this requirement in Spring Batch as well. Our use case requires a Gauge to monitor the size of the job launcher's queue. We also need a Gauge to monitor the number of currently active workers in a partitioned step. What we are looking for is a way of being able to adapt the batch infrastructure based on the Gauge value (for example if the size of job launch requests queue exceeds a given threshold, we would add more workers dynamically).

> the Gauge is a bit of an outlier form this perspective because nothing happens there, it is just a value that is changing without your interaction/knowledge and sometimes you look at the value and record it. For example, you can "observe" things like an error or processing an http request using the Observation API but there is no event to observe for the CPU temperature being 42°C (Gauge).

> I came up with a simple proof of concept for such a component: ObservedValue, the problem with it that without having a use-case other than metrics, this is just copying and renaming the MeterBinder interface.

I think a Gauge has use cases other than metrics, the use case from the Batch perspective above is one example. Another example based on the temperature use case you gave would be for instance activating/deactivating the A/C if the temperature's value exceeds a threshold.

Now while Micrometer provides the `Gauge` concept, the question in this issue is, as users of Micrometer, we need to use two "sets" of APIs to register metrics: the Observation API with an `ObservationRegistry` for counters, timers and the Gauge API with a `MeterRegistry` for gauges.

**Comment by jonatan-ivanov** [comment]
>What we are looking for is a way of being able to adapt the batch infrastructure based on the Gauge value (for example if the size of job launch requests queue exceeds a given threshold, we would add more workers dynamically).

Could you please check if the [ObservedValue sample](https://github.com/micrometer-metrics/micrometer/compare/main...jonatan-ivanov:micrometer:observed-values) above would work for you? You basically need a component that has a scheduled job in it and periodically checks the `value` of the `ObservedValue` (you should also be able to "register" the `ObservedValue::value` method to this job somehow). My question is, isn't doing this through the `ObservedValue` and the `ObservedValueRegistrar` is more complicated than "just" passing the same (for example) `AtomicLong` instance to a `Gauge` and to the component that watches the queue size?
I'm asking this since the component that watches the queue size only needs the value and it does not care about the other details that would justify using `ObservedValue` (name, description, tags, unit, etc.)

>I think a Gauge has use cases other than metrics, the use case from the Batch perspective above is one example. Another example based on the temperature use case you gave would be for instance activating/deactivating the A/C if the temperature's value exceeds a threshold.

I think I can see the batch use-case (please see the above about using the value directly though) and I can also see the theoretical use-case of controlling the A/C (and more) but we would need something that somebody would do in prod (e.g.: what you described with Batch).

>Now while Micrometer provides the Gauge concept, the question in this issue is, as users of Micrometer, we need to use two "sets" of APIs to register metrics: the Observation API with an ObservationRegistry for counters, timers and the Gauge API with a MeterRegistry for gauges.

The Observation API does not necessarily eliminate the need for the Metrics API, there are still use-cases where you want to register a `Counter`(or a `FunctionCounter`) without an `Observation`, or a `Distributionsummary`, or a `Gauge` (or `MultiGauge`, `TimeGauge`), etc. where it probably does not make sense to have any other output other than the `Meter`(s).

**Comment by ArtyomGabeev** [comment]
Hi there.

One of the use case - to be able to use observation documentation for value based metrics, eg gauges. 

Im not sure provided example for ObservedValue will work with observation documentation.

Is there other way to manage documentation and conventions via observations for gauges as well?

Or plz confirm, that observation api has been designed mostly for context propagation, and in case of pure metrics without distributed tracing we still need to use micrometer api.

Thanks

**Comment by jonatan-ivanov** [comment]
>One of the use case - to be able to use observation documentation for value based metrics, eg gauges.

There is `MeterDocumentation` for that purpose.

>Im not sure provided example for ObservedValue will work with observation documentation.

I think it won't, that's just a proof of concept I put together that you might be able to reuse if you want to but since it is not in Micrometer, Docs-gen has no support for it either.

>Is there other way to manage documentation and conventions via observations for gauges as well?

You can use `MeterDocumentation` for `Gauge`s that you created using the Metrics API (the Observation API does not create `Gauge`s out of the box).

>Or plz confirm, that observation api has been designed mostly for context propagation, and in case of pure metrics without distributed tracing we still need to use micrometer api.

Please read this: https://github.com/micrometer-metrics/micrometer/issues/5477#issuecomment-2354071039, it should give you the necessary details. Please notice that the Observation API does not obviate the Metrics API, there is nothing wrong using it and sometimes you should useit instead (e.g.: registering `Gauge`s).
