### ISSUE TITLE
Add 'description' to Observations

### ISSUE THREAD

**Issue by JordiMartinezVicent** [micrometer-metrics/micrometer#5478]
**Please describe the feature request.**
Add a description to the observation convention. 

**Rationale**
We are developing a set of libraries on top of Spring Boot which use micrometer to create metrics and traces. As Spring Boot did, we load metrics and tracing auto-configurations or not depending if metrics and traces are at classpath. Now we are refactoring our libraries to use micrometer-observation generic api to unify both and get rid of these conditionals.

The metrics api allows to add a description field, but we notices that it is not allowed to add it through the observation api.  It would be nice to have the possibility to add the description through the observation api.

**Comment by jonatan-ivanov** [comment]
The Observation API does not have this capability right now, I remember we discussed this before but I don't remember why we did not add it. Probably because it is only used for metrics, no one asked it before and even for metrics there are not a lot of backends that support it.

What is your concrete use-case, where would you use the desciption?

I think we can add it (it's an extra reference in the `Observation`), let me discuss it with the team. Right now you might be able to work this around using a `MeterFilter` or extending the `DefaultMeterObservationHandler`, in both cases you need to maintain a name -> description mapping that you add on-the-fly.

**Comment by marcingrzejszczak** [comment]
Why not add it as an entry in the map? I mean you can put arbitrary data into an observation and then the handler can retrieve it and do whatever you want.

**Comment by JordiMartinezVicent** [comment]
> What is your concrete use-case, where would you use the desciption?

My use case is for inform the field for metrics. 

I will try to do what you mentioned above. 

Thank you!

**Comment by jonatan-ivanov** [comment]
For the solution that Marcin mentioned, you also need to override and register your own [`DefaultMeterObservationHandler`](https://github.com/micrometer-metrics/micrometer/blob/b410174db680401423659955581bd03009113908/micrometer-core/src/main/java/io/micrometer/core/instrument/observation/DefaultMeterObservationHandler.java) and add the description to the `Timer`, `LongTaskTimer` and `Counter` that are created.

Let us know if you need help.
