### ISSUE TITLE
How to name properly timers to be exported to Prometheus

### ISSUE THREAD

**Issue by blacar** [micrometer-metrics/micrometer#548]
Following guidelines exposed in docs I wan to name Timers in a good way using names + tags to they are exported to Prometheus in a way that:

- I have a single unique name ... as "http_requests_seconds"
- Inside that timeseries I have different data from different endpoints so I can aggregate between them

In order to do so the approach is to create Timers in different endpoints with the same name but different tags?

**Comment by jkschneider** [comment]
> In order to do so the approach is to create Timers in different endpoints with the same name but different tags?

That's correct. In fact, this is what Spring Boot does for you for HTTP request endpoints. The timers have a default name of `http.server.requests` in Micrometer (which appears as `http_server_requests_seconds` after passing through the Prometheus naming convention). They have a tag that represents the parameterized uri, response code, HTTP method, and exception name (if any).

I highly suggest you use the built-in request instrumentation rather than trying to reinvent this, as a lot of work has gone into dealing with maintaining a low-cardinality tag set by using parameterized URIs, dealing with manually recording 500 statuses, dealing with async requests, etc.

**Comment by blacar** [comment]
@jkschneider Thank you very much.

I will really like to use the built-in request instrumentation but I am out of spring-boot si I think that is not possible. I am integrating micrometer into spring framework application (no boot).

**Comment by jkschneider** [comment]
@blacar Feel free to lift this class and use it: https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-spring-legacy/src/main/java/io/micrometer/spring/web/servlet/WebMvcMetricsFilter.java
