### ISSUE TITLE
Prometheus  pushgateway dependecy

### ISSUE THREAD

**Issue by jvmlet** [micrometer-metrics/micrometer#550]
Hello
`io.micrometer:micrometer-registry-prometheus:latest.release` doesn't add transitive dependency on `io.prometheus:simpleclient_pushgateway:0.3.0`. 
Is it by desing ?
If yes, would be greate to have dependcy management gradle/maven plugin to pull without the version :
`compile  'io.prometheus:simpleclient_pushgateway'`

**Comment by mweirauch** [comment]
Yes, that is intentional because `micrometer-registry-prometheus` doesn't need it at all. It's the auto-configuration of `micromter-spring-legacy` which optionally configures the pushgateway only if classes from `simpleclient_pushgateway` are present. If you don't need Pushgateway functionality one doesn't attract it and it's not configured. Just having the dependency always around doesn't make sense as the pull-model is preferred for a Prometheus setup.

Regarding dependency-management, that would require a BOM IMHO. Tracked within #469
