### ISSUE TITLE
Add support for Jetty QueuedThreadPool 

### ISSUE THREAD

**Issue by cemo** [micrometer-metrics/micrometer#557]
Please add support for QueuedThreadPool. We have upgraded to our applications to Boot v2 and noticed that micrometer's Jetty's QueuedThreadPool is missing.

**Comment by cemo** [comment]
I come up with a preliminary implementation like this:

https://gist.github.com/cemo/69589936c1de1e0e6ad56dec6ae15f5a

**Comment by jkschneider** [comment]
Would you like to open that as a PR? 

My only suggestion is to not use underscore in the metric name in OOTB binders, as this isn't seen by naming conventions and could be destructive to some monitoring system with that is particular about its characters. Something like:

`jetty.queued.thread_pool.threads` -> `jetty.queued.threads`
`jetty.queued.threads_pool.threads_idle` -> `jetty.queued.threads.idle`

Haven't look at the Jetty javadocs, but if it is possible to derive one of these from the other, e.g. `max - threads = idle`, then we can reduce the set of metrics to those necessary to perform those derivations. Otherwise, looks great!

**Comment by checketts** [comment]
Sorry for the accidental close. 😨

**Comment by izeye** [comment]
This looks resolved mostly via #914 except queue size metric. I created #920 to add it.

**Comment by jkschneider** [comment]
Thanks @izeye, I thought this looked familiar ;)
