### ISSUE TITLE
Update prometheus to 1.3.2

### ISSUE THREAD

**Issue by robert-gdv** [micrometer-metrics/micrometer#5639]
https://github.com/micrometer-metrics/micrometer/blob/602f6f3acff3f3f193f344ec2be624e194530a7d/gradle/libs.versions.toml#L71

Prometheus https://github.com/prometheus/client_java/releases/tag/v1.3.2 shipped a fix for CVE-2024-7254 (see https://github.com/prometheus/client_java/issues/1086 )
It would be nice if this can be propagated downstream.

**Comment by jonatan-ivanov** [comment]
Superseded by https://github.com/micrometer-metrics/micrometer/pull/5633

**Comment by jonatan-ivanov** [comment]
I don't think Micrometer is affected since it seems [CVE-2024-7254](https://github.com/protocolbuffers/protobuf/security/advisories/GHSA-735f-pc8j-v9w8)  is about parsing unknown fields. Neither Micrometer nor the Prometheus Java Client in Micrometer's use-case parse any protobuf payload (deserializing), it does the opposite: it produces a protobuf payload (serializing).

Other than the question of being affected or not, users should be able to upgrade `io.prometheus:prometheus-metrics-exposition-formats` any time they want to.

We are planning to merge in the version upgrade PR and release Micrometer on Monday.
