### ISSUE TITLE
ObservationFilter does not have an effect on DefaultMeterHandler creating long task timers

### ISSUE THREAD

**Issue by jensbaitingerbosch** [micrometer-metrics/micrometer#5729]
**Describe the bug**
Due to a [bug in Spring AMQP](https://github.com/spring-projects/spring-amqp/issues/2914), where a high cardinality value was put into the low cardinality values, I wanted to remove the high cardinality value via an `ObservationFilter`, though even the filter works correctly, a tag is still created for that high cardinality value. 

**Environment**

 - Micrometer version: 1.13.8
 - Micrometer registry prometheus
 - OS: macOS (though should not be dependent on the OS)
 - Java version: openjdk version "21.0.5" 2024-10-15 LTS

**To Reproduce**
How to reproduce the bug:
```
 var registry = ObservationRegistry.create();
    var meterRegistry = new SimpleMeterRegistry();

    registry.observationConfig()
        .observationHandler(new DefaultMeterObservationHandler(meterRegistry));

    registry.observationConfig().observationFilter((context) -> {
      context.removeLowCardinalityKeyValue("test");
      return context;
    });

    registry.observationConfig().observationConvention(new GlobalObservationConvention<Observation.Context>() {
      @Override
      public boolean supportsContext(Observation.Context context) {
        return true;
      }

      @NotNull
      @Override
      public KeyValues getLowCardinalityKeyValues(Observation.Context context) {
        return KeyValues.of("test", Double.toString(Math.random())); //this should be filtered out
      }
    });

    for (int i = 0; i < 10; i++) {
      Observation.start("test", registry).stop();
    }

    assert meterRegistry.find("test.active").timers().size() == 1;
```

**Expected behavior**
There should be only one long task timer

**Comment by jonatan-ivanov** [comment]
This is a limitation of the `ObservationFilter`; they run when the observation is stopped: https://github.com/micrometer-metrics/micrometer/blob/4f4cbe2b20cf94024bd5de1a479b98665a51c5f4/micrometer-observation/src/main/java/io/micrometer/observation/SimpleObservation.java#L184-L186

This means that if you do something before the observation is stopped you will see the state of the `Observation` before the filters were executed. Since `LongTaskTimer` needs to be created when the `Observation` starts, you can bump into this limitation.
Here are a few ways to fix it:
1. Override the convention so that it will add the right keyvalues
2. Create a `MeterFilter` to remove the high cardinality tags
3. In Micrometer we could add better docs for this behavior
4. I guess running the filters twice (once in start and once in stop) might be also possible though this one is a bit risky and has a potential to break existing filters.

**Comment by jensbaitingerbosch** [comment]
I agree, it is more a conceptual issue that the `LongTaskTimer` are created while starting the `Observation` and the `MeterFilter` being only applied during stopping. 

Maybe as an idea, the `MeterFilter` interface can be extended: there are two methods mapOnStart and mapOnStop, that are called in the corresponding phases of the livecycle of the Observation. Both methods behave the same as the old behavious, for a new version, the `map()` method can be removed. 

```
public interface ObservationFilter {

  default Observation.Context mapOnStart(Observation.Context context) {
    return context; // NOOP
  }

  default Observation.Context mapOnStop(Observation.Context context) {
    return map(context); // for backward compatibility
  }

  @Deprecated
  Observation.Context map(Observation.Context context);
}

// for convinience
abstract class DefaultObservationFilter implements ObservationFilter{

  // to force to implement this method
 abstract Observation.Context mapOnStop(Observation.Context context);

 public final Observation.Context map(Observation.Context context) {
    throw new IllegalStateException("deprecated")
 }
}
```

**Comment by jonatan-ivanov** [comment]
I think where you wrote `MeterFilter`, you actually meant `ObservationFilter`, they are two different things. This is not true for `MeterFilter` but it is true for `ObservationFilter`:
>`MeterFilter` being only applied during stopping.

Likewise:
>the `MeterFilter` interface can be extended: there are two methods `mapOnStart` and `mapOnStop`, that are called in the corresponding phases of the livecycle of the `Observation`. Both methods behave the same as the old behavious, for a new version, the `map()` method can be removed.

I think the change you are proposing is something we should consider (except removing `map`, we cannot do that since it is a breaking change but we can deprecate it).

Please check if you can use a `MeterFilter` to remove the cardinality tags, that one should not be affected by the Observation lifecycle (unlike `ObservationFilter`).
