### ISSUE TITLE
Create abstraction for recording "events"

### ISSUE THREAD

**Issue by mveitas** [micrometer-metrics/micrometer#581]
It would be nice to be able to abstract the details of publishing an "event" to a monitoring system. There are a number of monitoring systems (SignalFx, DataDog) that support the notion of publishing "events".

**Comment by jkschneider** [comment]
New Relic, Azure App Insights, probably others do as well.

**Comment by checketts** [comment]
This will also be a good fit with grafana annotations

**Comment by OleksiiBondar** [comment]
Very similar to what asked in https://github.com/micrometer-metrics/micrometer/issues/1097
where ExceptionMetrics is more granular implementation of EventMetrics

**Comment by msassak** [comment]
Want to add my $0.02 that this would be useful. I believe I'll end up using both Micrometer for metrics in some Spring Boot apps and the official java-dogstatsd-client to send events to DataDog, but I'd gladly use only Micrometer if/when it is supported.

**Comment by jonatan-ivanov** [comment]
Fyi: depending on your needs, some things are possible with the Observation API (since 1.10.0).
You can record `Observation`s that are events with duration and during these observations you can also record `Observation.Event`s that are events without duration. Reporting these events need to be implemented by the end user right now via `ObservationHandler`s.

**Comment by marcingrzejszczak** [comment]
Currently we support it via the Observation API. If there will be any additional interest in this, please comment on the issue and we'll consider re-opening it.
