### ISSUE TITLE
Customized Statsd line format is not sent

### ISSUE THREAD

**Issue by itay-keller** [micrometer-metrics/micrometer#582]
We have a customized Statsd line format to fit our graphite needs.
We added a counter to one of our Spring controller's methods.
When the application is running in debug mode, we see that the line building function `public String count(long amount, Statistic stat) ` is called and returning a value.
But when checking with WireShark the packets sent, we can see other Statsd packets sent, but this particular info is not sent.
Here is the code sample of the rest controller:

    @RestController
     public class MyController{
       Function<Meter.Id, StatsdLineBuilder> nameAndUnits = id -> new StatsdLineBuilder() {
        @Override
        public String count(long amount, Statistic stat) {
            return hostName + "." + stat.getTagValueRepresentation() + ":" + amount +"|c";
        }
		// other overidding methods
       };
    MeterRegistry registry = StatsdMeterRegistry.builder(StatsdConfig.DEFAULT)
            .clock(Clock.SYSTEM).lineBuilder(nameAndUnits) .build();
    Counter myCounter = registry.counter("myCounter");
	
	@PostMapping("/myMethod")
    @Transactional
    @Timed
    public ResponseEntity<String> myMethod(@RequestParam("studentName") String studentName) {
        myCounter.increment();
		...
	}
}

What are we missing here? 
Why other Statsd packets are sent, but this one is not? 
Are we missing some code fragment or configuration?

**Comment by jkschneider** [comment]
@itay-keller It looks like in this case there are two `StastdMeterRegistry`'s in play. 

1. One that Spring autoconfigured for you via `StatsdMetricsAutoConfiguration`. Autoconfigured metrics are being sent with this one, without your custom `lineBuilder`.
2. A `MeterRegistry` used locally here in this controller. The line format only applies to that single counter.

You should instead wire your `MeterRegistry` with the custom line builder in a `@Bean` somewhere in a `@Configuration` class in your application. Spring Boot will defer to this one instead of autoconfiguring its own.
