### ISSUE TITLE
Prometheus: Min and Max request time

### ISSUE THREAD

**Issue by eloo** [micrometer-metrics/micrometer#61]
Hi,
is is currently possible to capture the minimum and maximum request time for an endpoint with @Timed?
If not, does it make sense to implement something like this?
Thanks

**Comment by jkschneider** [comment]
For Prometheus, there are aggregation query functions for this that you use on the server-side called `max_over_time(range-vector)` and `min_over_time(range-vector)`. There are others like it as well.

For Atlas there is a `:dist-max` operation. IIRC Netflix stopped collecting min not too long ago because they found it to be largely unused.

Dropwizard timers result in a multitude of time series per timer, two of which are max and min.

**Comment by Eloo** [comment]
Hi,
so far so good. but which metric should i use for the max/min_over_time?
And yes i'm coming from the dropwizard metrics ;) so thats the origin of this question.

Thanks

**Comment by checketts** [comment]
The Dropwizard min/max approach represents the min/max that has ever been seen. It exists to ensure that large values that occur between scrapes get exposed. (I'm sure you knew this just restating to make sure we are on the same page)

I could see it making sense to implement, however in practice the way `Summary`s export the sum/count it doesn't lose the fact that an outlier affected the result and a Histogram would capture the bucket that a min/max occupied.

I haven't used the micrometer annotation yet so I don't have input in that regard. I just wanted to point out that the min/max while serving a specific purpose, can be accounted for in the other underlying metrics.

**Comment by jkschneider** [comment]
@Eloo looking at this a little closer, I think you have a point. Prometheus allows for the determination of things like "max 5m rate over the last 1d" via [`max_over_time` with a recording rule](https://github.com/prometheus/prometheus/issues/2129), but remarkably graphing the max sample seen in an interval doesn't appear to be possible.

I guess this should come as no surprise. Atlas/Spectator ships 4 statistics (time series) per timer sample: count, totalTime, totalOfSquares, and max. Prometheus only ships 2: count and sum.

I guess this meshes philosophically with Prometheus' idea of time being a continuous scale from the perspective of instrumentation and windowing is accomplished with range vectors at query time. In reality, the scrape interval is always apparent if you zoom in far enough:

![image](https://user-images.githubusercontent.com/1697736/28682330-132799cc-72c2-11e7-8353-e593c3ad8a8e.png)

The problem with `max` is it presupposes a time interval. So we could easily add `max` as a separate time series `timer_max` just like Prometheus exposes `timer_count` and `timer_sum`, but every timer would be tied to the state of scrapes (would need to reset their max every time a scrape happens). @checketts: really interested in your thoughts here.

@checketts idea around capturing the max bucket is an interesting workaround if you don't need precision.

**Comment by checketts** [comment]
Max and min can be added without the expectation of time interval. The dropwizard equivalent just compares the value forever from initialization. I think it could be cool to have it reset at intervals, but not as a default and not by scrape since Prometheus encourages multiple scrapers for redundancy. 

I support the `timer_max` idea.

The resetting is the only potential problem. Not ever resetting is an easy/lazy answer, but really reduces the utility of the metric. It keeps parity with dropwizard, but we can do better. 😜

Probably making the reset interval configurable would be sufficient.

**Comment by jkschneider** [comment]
Great insight on the multiple scrapers. I would not have thought of that.

**Comment by jkschneider** [comment]
This involves a new `step` config option on `PrometheusConfig`, requiring a Boot 2 change.

**Comment by jkschneider** [comment]
Max turns out to be really important in Coordinated Omission scenarios even with percentile approximations. See ~38min of https://www.infoq.com/presentations/latency-pitfalls.

**Comment by jkschneider** [comment]
Fixed with 736fd95ca5a9fb9846699489877eb4021882b9df
