### ISSUE TITLE
Unpredictable time unit in measurement when using Prometheus with some other registry.

### ISSUE THREAD

**Issue by anha1** [micrometer-metrics/micrometer#681]
**Steps to reproduce**
1. Enable both Prometheus and and StatsD so meter registry used is CompositeMeterRegistry with PrometheusMeterRegistry and StatsdMeterRegistry.
2. Check /actuator/metrics/process.uptime - uptime is reported in **ms**.
3. Check /actuator/prometheus "process_uptime_seconds" - uptime is reported in **seconds**.
4. Try to read "process.uptime" manually from CompositeMeterRegistry: meterRegistry.get("process.uptime").meter().measure(): **the result is reported either in ms or in seconds in an unpredictable manner** (time unit is determined on application start with ~50% probability).
5. CompositeTimeGauge used as a meter in this case has two child meters, one reports time in ms, other in seconds while "fUnit" property of the composite meter is always "MILLISECONS".
6. Other time values are also affected by this issue.

**Expected result:**

1. When reading "process.uptime" and other time values, the time unit of a measurement is constant and is aligned with "fUnit" property of a CompositeTimeGauge used.

**Comment by jkschneider** [comment]
@anha1 It is by design that each registry implementation reports to its backend a time value in the base unit of time that that backend expects. `fUnit` on `CompositeTimeGauge` is rather the time unit of the input, a declaration of the time scale of the value you are supplying to the gauge.

That said, I understand the confusion about the unit reported in `/actuator/metrics`. I'm not really sure what the right answer is. Perhaps its best if Spring Boot just always reported metrics a certain way in `/actuator/metrics`: a certain structure, a certain time unit scale. My concern is that folks will see a different value reported to their backend then they see in `/actuator/metrics` and the criticism will just shift to that.

When there is a single registry implementation on the classpath, `/actuator/metrics` is aligned to the base unit of time of that implementation. When there are multiple implementations, we just kind of pick one.

Suggestions?

**Comment by mweirauch** [comment]
What about a dedicated `ActuatorMetricsEndpointMeterRegistry` being a child of the composite like any other? This way it would align with the same setup you'd have when e.g. Prometheus is on board. (By default one child below the composite, and an exposed actuator endpoint delivering it's representation of the metrics.)
IIRC it is not the first time a "exposition-unit-confusion" question for the `/metrics` endpoint comes up.
