### ISSUE TITLE
Missing return statement in WebMvcTags

### ISSUE THREAD

**Issue by anchar2k** [micrometer-metrics/micrometer#744]
I suppose that "return pathInfo;" should be after checking pathInfo for empty.

https://github.com/micrometer-metrics/micrometer/blob/930bca61b600633b19a26f143c83de258d1327ac/micrometer-spring-legacy/src/main/java/io/micrometer/spring/web/servlet/WebMvcTags.java#L103

**Comment by izeye** [comment]
@anchar2k Thanks but no, that's intentional to prevent `uri` tag explosion when use of path variable is undetected. See https://github.com/micrometer-metrics/micrometer/issues/639 for background.

And I guess you raised this due to its outdated Javadoc, so I created https://github.com/micrometer-metrics/micrometer/pull/745 to update it.
