### ISSUE TITLE
Autoclosable issue

### ISSUE THREAD

**Issue by ankurbhakta** [micrometer-metrics/micrometer#757]
All meters extend AutoCloseable which  causes code quality  tools to flag all meters as not being closed.
Looks like only timers really need to be AutoCloseable, so can we move the AutoCloseable down to AbstractTimer class only ?

**Comment by jkschneider** [comment]
Interesting feedback, thanks. Does the code quality tool you are referring to look for a `void close()` method or an implementation of `AutoCloseable`? If it is the latter, we can keep the signature and drop the interface extension which doesn't provide any value anyway.

I think we should leave the signature at least on `Meter` though, because while there may not be `close` implementations across the board for different meter types currently, there could be in the future.

**Comment by ankurbhakta** [comment]
Sonar looks at two things, the close statement is called or an AutoClosable resource should be in a try-with-resources statement. This prevents us from reusing the same counter with try-with-resources in other parts of the service. As you see the example below it really doesn't make sense for meters.
eg.

try ( Counter c =Metrics.counter("rest.failed.counter")){
.....
c.increment();
    }
