### ISSUE TITLE
@Timed on a controller being processed twice when using TimedAspect

### ISSUE THREAD

**Issue by izeye** [micrometer-metrics/micrometer#780]
When I was creating [a working sample](https://github.com/izeye/sample-micrometer-spring-boot/tree/timed-annotation) for [an SO question](https://stackoverflow.com/questions/51749391/timed-annotation-in-spring-metrics), I noticed `@Timed` on a controller being processed twice when using `TimedAspect`. One in `TimedAspect` and the other in `WebMvcMetricsFilter`.

See the above working sample for reproducing the issue.

**Comment by mweirauch** [comment]
It's the same when the Jersey instrumentation and the `TimedAspect` are used together.

Additionally, I had `PrometheusMeterRegistry` choke on different tag cardinality on identically named metrics in some constellation which I can't remember offhand.

**Comment by michaelmcfadyen** [comment]
I don't believe this is a bug. The spring boot documentation states that if you want to use `@Timed` you should disable the metrics filter

> Auto-configuration enables the instrumentation of requests handled by Spring MVC. When management.metrics.web.server.auto-time-requests is true, this instrumentation occurs for all requests. Alternatively, when set to false, you can enable instrumentation by adding @Timed to a request-handling method

Source: https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-metrics.html#production-ready-metrics-spring-mvc

**Comment by izeye** [comment]
@michaelmcfadyen I'm not sure how you came to the conclusion but IIUC, the part of the documentation you quoted is just saying that how `@Timed` works with `WebMvcMetricsFilter`. So if you simply set `management.metrics.web.server.auto-time-requests=false`, you just lose `http.server.requests` metrics but `@Timed` will be processed twice. Try the above "a working sample" I linked with the property you mentioned.

**Comment by jkschneider** [comment]
Trying to think of how we could prevent it without having `TimedAspect` and `WebMvcMetricsFilter` have specific knowledge of each other. Seems most likely to me that we will do away with the `TimedAspect` altogether in Spring Boot 2.1 in favor of a non-AOP approach.

**Comment by kwtan** [comment]
We extends TimedAspect to workaround this issue
`
    @Override
    public Object timedMethod(ProceedingJoinPoint pjp) throws Throwable {
        Class targetClass = pjp.getTarget().getClass();
        if (targetClass.isAnnotationPresent(RestController.class) || targetClass.isAnnotationPresent(Controller.class)) {
            return pjp.proceed();
        }

        return super.timedMethod(pjp);
    }`

**Comment by mghildiy** [comment]
I too face this issue. I got it working by removing TimedAspect bean configuration. Any other better way?

**Comment by shakuzen** [comment]
> I got it working by removing TimedAspect bean configuration. Any other better way?

If you don't need the `TimedAspect`, then it's best to not configure it in the first place.

**Comment by jonatan-ivanov** [comment]
My two cents:
I think this has three point of views:
- User's perspective
- Spring Boot's (or any other framework/lib's that instruments code and reuses `@Timed`) perspective
- Micrometer's perspective

I think implementing the workaround ([here](https://github.com/micrometer-metrics/micrometer/issues/780#issuecomment-579917222)) in the `TimedAspect` is not a viable solution. It is great from the user's/library perspective since they don't need to do anything but it will make Micrometer depend on every framework/lib that instruments code and reuses `@Timed`. This can be a circular dependency at the moment in some cases. If the classname is handled as a `String`, Micrometer must know about the instrumenting libraries (that can be closed-source). Also, this might not be even possible, e.g.: the code that is reusing `@Timed` is generated so we might not know the class to filter.

If I understand correctly, from Micrometer's perspective, reusing `@Timed` in the way as Spring Boot does is somewhat misaligned from the original intention of it (again, I'm not 100% sure if my understanding is correct here). On the other hand, this is not really documented and there isn't really an alternative way to customize `Timer` creation that I guess is the goal here.

With this, I have two suggestions:

### New Annotation
In this case, we could introduce a new annotation that can be used by external frameworks and libraries to make their instrumentation customizable. This new annotation would look very similar (if not the same) as `@Timed` today (extends `@Timed`?). The big difference between them would be their usage: `@Timed` would be exclusively used by `TimedAspect` and we would discourage any other usage while the new annotation would be ignored by `TimedAspect` (and any other parts of Micrometer) and would be there only to help/standardize instrumentation customization for external libraries.

This needs "minimal" change in micrometer but libraries and users need to change their code base and use the new annotation instead of `@Timed`. Also, instrumenting code could throw an exception if `@Timed` is found telling the users to either turn off instrumentation (`TimedAspect` or library) or use the right annotation.

### New Field on `@Timed`
In this case, we could introduce a new field/property (and a default value) for `@Timed` (e.g.: `external = false`) that can be used by `TimedAspect` to ignore `@Timed`  annotation in case the user requests that behavior. This is somewhat similar to the previous case (new annotation) except:
- This needs a little bit more code change on Micrometer side (should be a small amount)
- Libraries might not need to change at all (they can throw an exception if the property is not set properly)

From the user's perspective, it is the same, I don't think replacing an annotation or adding a new parameter to an existing one is too big of a difference.

I think I like the second approach (new property) a little more because of the better discoverability, though, a new annotation seems a bit more explicit/intuitive to me. Please let me know what do you think.

**Comment by jonatan-ivanov** [comment]
I talked to @shakuzen, he had an idea about another alternative: we can do something similar to the workaround but in a generalized form by adding a `Predicate<ProceedingJoinPoint>` to the `TimedAspect` that would do no filtering by default but the users can inject their own `Predicate` in the ctor so that they will have the control of what `TimedAspect` should skip.

This means no change on libraries side, minimal change on Micrometer's side and the users only need to change their `TimedAspect` in one place (if they are already using this workaround, it will be even easier).

**Comment by shakuzen** [comment]
While the double instrumentation is not fixed out-of-the-box because it would create cyclic dependencies and we can't know about every framework (including private ones) that exists, there is now a built-in way to avoid it without extending `TimedAspect`. See #2551 and the example provided in the JavaDoc for use with Spring Boot.

```java
@Bean
public TimedAspect timedAspect(MeterRegistry meterRegistry) {
    return new TimedAspect(meterRegistry, this::skipControllers);
}

private boolean skipControllers(ProceedingJoinPoint pjp) {
    Class<?> targetClass = pjp.getTarget().getClass();
    return targetClass.isAnnotationPresent(RestController.class) || targetClass.isAnnotationPresent(Controller.class);
}
```
