### ISSUE TITLE
How to configure dynamic tag value within a multi-thread app

### ISSUE THREAD

**Issue by aminechouicha** [micrometer-metrics/micrometer#798]
I am new to micrometers, graphite and springboot. This is my use case: a springboot app that opens multiple server websocket endpoints, each endpoint is suppose to handle requests from a specific client with a specific client_id. I need to collect metrics (e.g. request latency) per client_id, as specific client might have their own SLA. I have the current graphite common tags (region, env, app_name, instance), I want to add "client" tag which is defaulted at startup to "default", but then when a client initiates a connection and sends a request, I will capture his id (e.g client_x), then I would like to have this tree in graphite under which I will collect metrics: "uswest.production.autocomplete.instance_123.client_x". Is this doable?  I was thinking by leveraging ThreadLocal. Thanks

**Comment by jkschneider** [comment]
This is the canonical use of [Timer.Sample](http://micrometer.io/docs/concepts#_storing_start_state_in_code_timer_sample_code), where the tag is determined as the sample is stopped at the last minute.

**Comment by lukaszkrawiec** [comment]
Any way you could achieve this for @Timed annotation?

**Comment by jkschneider** [comment]
@lukaszkrawiec I think by definition no, this isn't possible. Annotation parameters types are fairly [limited](https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.6.1), and I have little appetite for further reflection or other silliness just to stuff what could be done programmatically in an annotation, especially since such mechanisms are not refactor safe.
