### ISSUE TITLE
HikariCP binder

### ISSUE THREAD

**Issue by tokuhirom** [micrometer-metrics/micrometer#91]
I want to get metrics data from HikariCP using micrometers.

**Comment by jkschneider** [comment]
For implementation, see the hook for adding a Dropwizard registry [here](https://github.com/brettwooldridge/HikariCP/wiki/Dropwizard-Metrics)

**Comment by shakuzen** [comment]
Note: HikariCP has already added some initial support for Micrometer in HikariCP 2.7.0, as can be seen in [this package](https://github.com/brettwooldridge/HikariCP/tree/dev/src/main/java/com/zaxxer/hikari/metrics/micrometer). Does this cover what this issue was looking for?

**Comment by jkschneider** [comment]
Updated API in https://github.com/brettwooldridge/HikariCP/pull/1002.

**Comment by checketts** [comment]
The Hikari PR is merged can we close this @jkschneider ?

**Comment by jkschneider** [comment]
I'm pretty sure we broke it with rc3 because it had references to quantiles. We should eliminate quantiles config in hikari altogether and allow users to configure them after-the-fact with the new meter filter props support.

**Comment by jkschneider** [comment]
Hikari is on rc6 as of right now. After 1.0, we can circle back with a PR that brings Hikari up to 1.0 GA and removes client-side percentiles.

**Comment by snicoll** [comment]
@jkschneider I can see you dropped the 1.0.0 milestone on this one. Does that mean we shouldn't provide auto-config for this? See the PR @shakuzen submitted to Spring Boot.

**Comment by shakuzen** [comment]
From Slack:

> Tommy Ludwig [12:08 PM]
@jon It would be nice to have the HikariCP binder supported and configured in Spring Boot 2 GA. Is that the plan?

> jon [12:08 PM]
i believe it is?
i had a note on issue #91 because we should do a follow-up PR on hikari to remove its specification of client-side percentiles (edited)
ouch, you’re right. it’s not in boot 2 right now
when i do the 1.0 GA release tomorrow i’ll do a quick PR to Hikari and see if we can get a release cut before Boot 2 GA next week

I just tested that the current HikariCP metrics tracker works with the latest snapshots of Micrometer. As far as I understand, @jkschneider just wants to follow up after Micrometer GA is released to bump the version HikariCP depends on and to remove the currently declared client-side percentiles (since now percentiles can be configured via metrics filters in a user's application rather than needing to be predefined in a library like Hikari).

So right now and after, things should work fine as far as configuring the metrics in Boot. A version bump of HikariCP to get the change of client-side percentiles is just icing on the cake, I think. Of course, Jon can give final confirmation.

**Comment by snicoll** [comment]
Thanks for the context @shakuzen that's very helpful

**Comment by snicoll** [comment]
Alright, as of Spring Boot 2.0 RC2 (to be released soon), Hikari datasources are automatically instrumented.

**Comment by jkschneider** [comment]
Percentiles removed in https://github.com/brettwooldridge/HikariCP/pull/1100

**Comment by n0mer** [comment]
@jkschneider @snicoll  in case of DataDog export (micrometer 1.0.1), Hikari metrics are exported with "unknown" service name.

Wondering how to set service name, and where (application.yaml in spring-boot, datadog.yaml for S6, some system property or env var)?

Relevant datadog support case: https://help.datadoghq.com/hc/en-us/requests/132535

**Comment by jkschneider** [comment]
@n0mer Hmm... datadoghq says that support case doesn't exist? Maybe it's private? I'm missing some info on what you mean by service name. Is this some sort of tag? Feel free to hit us up on slack.micrometer.io if you want to resolve more rapidly!

**Comment by n0mer** [comment]
hi @jkschneider , good to know you've got slack channel!

This is privately-opened support case with datadog, it contains some sensitive data thus it's not public.

I'm talking about this: https://docs.datadoghq.com/tracing/languages/java/

Config: service.name
System Property: dd.service.name
Environment Variable:DD_SERVICE_NAME
Default: unnamed-java-app
Description: The name of a set of processes that do the same job. Used for grouping stats for your application.




How to open page from menu:
![image](https://user-images.githubusercontent.com/1862997/36917898-5f33b91c-1e58-11e8-9628-4aea82839c01.png)

How hikaricp-instrumented service looks like in datadog web ui:
![image](https://user-images.githubusercontent.com/1862997/36917931-7a70406a-1e58-11e8-924d-ee308c7ca35e.png)

Here is proof that this is hiraricp-related (thread name is "${spring.datasource.name} connection adder"

![image](https://user-images.githubusercontent.com/1862997/36918110-0c0a2be4-1e59-11e8-84ca-f6f6969c2ad4.png)

**Comment by jkschneider** [comment]
Oh I see. It looks like a proprietary datadog agent is reaching down into Spring apps to trace Hikari. This is not Micrometer related.
