### ISSUE TITLE
Kafka consumer Metrics values are always NaN 

### ISSUE THREAD

**Issue by thirunar** [micrometer-metrics/micrometer#983]
We have upgraded micrometer version to 1.1.0 to get the `KafkaConsumerMetrics` in our spring boot application v2.1.0. 

But apparently, all the kafka consumer metrics are being collected and only has `NaN` as its value. Few people have reported the issue in [StackOverFlow](https://stackoverflow.com/questions/53073328/spring-boot-2-1-micrometer-kafka-consumer-metric-statistic-count-is-nan). 

You can refer to [simple project](https://github.com/j-tim/spring-kafka-micrometer) created by @j-tim. I also have the same issue with my metrics. 

What could be the reason? Could you please help us with the issue? 
Thank you!!

**Comment by jkschneider** [comment]
Thanks, will look into it and release a patch version.

**Comment by rikitikitaco** [comment]
I believe this is due to the MBeans not being found as the clientId is different. Something adds a -0 to the end.

**Comment by jkschneider** [comment]
Related, I think, to #878

**Comment by hgnoyke** [comment]
We are seeing a similar problem when having a consumer linked to a topic where no messages are being recieved (we have a topic on which we send time-travel-events for testing to different apps and sometimes do not use this feature ;-) ).

Here is one of the error messages:
`failed to send metrics to influx: {"error":"partial write: unable to parse 'kafka_consumer_fetch_latency_max,client_id=consumer-1,[our_custom_tags_left_out],metric_type=gauge value=-∞ 1541775345266': invalid number`

Guess we are getting "negative infinity" because no message has been processed yet or this value has to be given to InfluxDB in a different way?
For the time being we have switched off 

Don't know whether this is related to this "NaN" issue or should be handled in a different issue.
Thanks for looking into this!
